### ISSUE TITLE
Vol'jin animation persists if you cancel his battlecry

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#100]
If you cancel Vol'jin's Battlecry in the middle of the animation, the Battlefield will stay darkened until the end of the game or until you use his Battlecry again.
http://us.battle.net/hearthstone/en/forum/topic/18301000990
http://imgur.com/FSqehzd

**Comment by culinko** [comment]
No longer happens in 4.0.0.10833, it's possible this has been already fixed for some time.
