### ISSUE TITLE
Buff triggers on dead minion letting it live

### ISSUE THREAD

**Issue by ruthnaebeck** [HearthSim/hs-bugs#1000]
Opponent played Primordial Drake which hit Acolyte of Pain for lethal damage.
The damage caused the player to draw a card.
The card is Scroll of Wonder which casts Rampage (Give a damaged minion +3/+3).
Rampage buffed the Acolyte which is technically dead (letting it live).

 https://clips.twitch.tv/GlutenFreeCredulousBeefOpieOP

**Comment by PattuX** [comment]
Death Processing in HS isn't immediate but in delayed Death Phases. Those happen in between the outermost phases, in this case after the Battlecry but before After Summon Triggers (Knife Juggler etc) resolve. The Acolyte trigger (and thus also the Scroll) is nested inside the Primordial battlecry and deaths are generally not processed inside of phases.

This is an interaction that has been around forever, probably the best known example is attacking with a Truesilver Champion into an Explosive Trap at 2 HP.
