### ISSUE TITLE
Baku does not upgrade Hero Power if you're playing as Mecha Jaraxxus and have Baku in your opening hand

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#1001]
https://www.youtube.com/watch?v=vSzmvpWboHo&t=1m24s

https://www.youtube.com/watch?v=1O0hR4GQhWk

https://www.youtube.com/watch?v=FD_LtOCD9NY

A user in the forum suggests that also you have to go second:

https://us.battle.net/forums/en/hearthstone/topic/20765726815

**Comment by Jetz72** [comment]
https://www.youtube.com/watch?v=hHcUbMRH5wY

Video a user posted demonstrates that you don't have to go second.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20765726815

**Comment by troggnostupidhs** [comment]
Baku + Mecha Jaraxxus triggers going first and second with and without Baku in your opening hand

![Hearthstone Screenshot 05-04-19 16 44 11](https://user-images.githubusercontent.com/22508641/57184623-2236bc00-6e8c-11e9-9546-f7538eb3a00b.png)

![Hearthstone Screenshot 05-04-19 16 45 53](https://user-images.githubusercontent.com/22508641/57184624-2236bc00-6e8c-11e9-8d0d-cccf49c532a3.png)
