### ISSUE TITLE
Vicious Fledgling triggers after play effects when it adapts.

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1003]
https://us.battle.net/forums/en/hearthstone/topic/20766787368

> My opponent had a Vicious Fledgling on the board. I played Explosive Runes. On his following turn, he attacked with the Fledgling and got Windfury. Before he was able to attack again, the Explosive Runes proc'd and killed the Fledgling.
> Here is a link to the replay (bug on turn 5): https://hsreplay.net/replay/VgaarjGbCyBtcXvBLAxdhQ

Other reports include this happening with Mirror Entity and Armored Berserker:

https://us.battle.net/forums/en/hearthstone/topic/20766757294

https://www.reddit.com/r/hearthstone/comments/9425pw/bug_vicious_fledgeling/

**Comment by troggnostupidhs** [comment]
A bunch of reports

https://www.reddit.com/r/hearthstone/comments/948f1i/bug_explosive_runes_proccing_when_vicious/

https://www.reddit.com/r/hearthstone/comments/947zr3/bug_a_vicious_fledgeling_that_is_already_on_board/

https://www.reddit.com/r/hearthstone/comments/9490cd/knife_juggler_activates_when_vicious_fledgling/

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/94dfbx/vicious_fledgling_hunting_mastiff_zombeast_adds/

seems echo is also triggered

**Comment by Sunchy321** [comment]
after-summon triggers are also triggered...

**Comment by Jetz72** [comment]
This one appears to have been fixed around the same time as #1005. Like that one, it common circumstance that everyone suddenly started reporting when 12.0 landed, then stopped shortly after.
![hearthstone screenshot 01-24-19 23 35 00](https://user-images.githubusercontent.com/8607832/51734776-7e02d500-2053-11e9-9fdc-2856d3fc4efc.png)
![hearthstone screenshot 01-24-19 23 35 15](https://user-images.githubusercontent.com/8607832/51734784-83601f80-2053-11e9-8dc2-ffff669ff86e.png)
