### ISSUE TITLE
Whizbang decks cannot convert between Standard and Wild

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1012]
https://www.reddit.com/r/hearthstone/comments/95melg/bug_whizbang_decks_cannot_convert_between/

> I'm a Free to Play wild player, and was excited to try out standard mode with my golden Whizbang. After I converted my first Whizbang deck to Standard everything looked normal. The vines disappeared and my deck went to the top of the list; however, when I tried to play with my deck, it still put me into a wild game.
> 
> I had to create a new standard deck with Whizbang in order to actually be able to play standard. I'm assuming this is a bug? Not a huge deal, but I was pretty confused for a while!

**Comment by Jetz72** [comment]
I converted a wild Whizbang deck to standard yesterday. Worked fine. Perhaps that poster thought that the game format is determined by the format of the deck you queue in with?

**Comment by troggnostupidhs** [comment]
True, maybe the format wasn't changed. I'll make this invalid.
