### ISSUE TITLE
Innervate + Omega Defender doesn't work properly

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1019]
https://youtu.be/5PYZ5QELCIk?t=177

Unsure if this applies to all Omega cards, or just Omega Defender.

Per #713, All mana crystals should be considered after the cost is paid. If the are temporary or not, it shouldn't matter. The Omega results probably should be consistent with that interaction.

**Comment by Bercon** [comment]
Temporary Mana Crystals aren't counted as proper Mana Crystals. You already had this same interaction with Living Mana. It innervating Living Mana (5) while at 4 mana will give you 4 treants, not 5.

**Comment by 10925** [comment]
I think it's not a bug
But it's really confusing blizzard not use some word to distinguish the different of mana crtstals.
For example, "if you have 10 permanent mana crystals, then"

**Comment by troggnostupidhs** [comment]
@Bercon good call, my memory of it was wrong. It behaves the same. 

As mentioned in the other issue, it seems like it is intentional. The wording is the problem.

https://www.youtube.com/watch?v=0L2NiuVi-VQ&feature=youtu.be&t=3m18s
