### ISSUE TITLE
Effects that ignore 'mortally wounded' (0 or less Health) don't ignore 'pending destroy'

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#102]
A general bug of Hearthstone is that effects which ignore mortally wounded (0 or less Health) minions (such as Freezing Trap, Arcane Missiles and Misdirection) do not also ignore pending destroy (hit by a Destroy effect) minions.

For example, if you play Acidmaw and your opponent plays Arcane Missiles, the Arcane Missiles will not hit any minions reduced to 0 Health, but will continue to hit minions that have become 'pending destroy' due to Acidmaw's effect. This is seemingly inconsistent.

For many more examples:

http://hearthstone.gamepedia.com/Advanced_rulebook#.27Pending_destroy.27_bugs_and_effects

Ben Brode considers this (or at least some instances of this) a bug they want to fix:

https://twitter.com/bdbrode/status/720314443024838658

**Comment by Patashu** [comment]
This is related to Vaporize/Freezing Trap bug: https://github.com/HearthSim/hs-bugs/issues/69

**Comment by Patashu** [comment]
Also happens with Void Crusher http://us.battle.net/hearthstone/en/forum/topic/18596064443

**Comment by Patashu** [comment]
Confirmed in 3.2, Acidmaw vs Bouncing Blade

https://www.youtube.com/watch?v=SE6n-n8_7JU

**Comment by culinko** [comment]
Confirmed in 4.0 with Brann Bronzebeard and Stampeding Kodo not killing 2 minions.
* https://www.reddit.com/r/hearthstone/comments/3thlcv/stampeding_kodo_bugged_with_brann/

**Comment by PattuX** [comment]
Confirmed with Brann + Kodo in 4.1

**Comment by Patashu** [comment]
Probably-confirmed in 4.2, I'll wait until someone tests Brann+Kodo in 4.2 or whatever though

https://www.youtube.com/watch?v=VcG2zz4gXKk&feature=youtu.be&t=649

**Comment by culinko** [comment]
Still happens in 4.2, tested Brann + Kodo.

**Comment by Patashu** [comment]
Confirmed in 4.3 (Brann + Kodo)

http://us.battle.net/hearthstone/en/forum/topic/20743194780

**Comment by Xinhuan** [comment]
This is cited by Ben Brode to be a bug that they plan on fixing - https://twitter.com/bdbrode/status/720314443024838658

**Comment by Patashu** [comment]
Stampeding Kodo’s ability will no longer target the same minion twice if triggered by Brann Bronzebeard.

from the 5.0 patch notes. We need to test if SPECIFICALLY kodo/Brann is fixed or if this bug is fixed in general, though.

**Comment by Patashu** [comment]
I guess they only fixed Kodo.

http://us.battle.net/hearthstone/en/forum/topic/20743434636

Report of Shadowboxer hitting an Imp targeted by Sacrificial Pact (and therefore 'pending destroy').

**Comment by culinko** [comment]
Tested Acidmaw + Madder Bomber, the minions set to pending_destroy by acidmaw were hit only once.

**Comment by Patashu** [comment]
Totally fixed, including C'Thun, Grim Patron, Madder Bomber, Arcane Missiles, Shadowboxer, SAcrificial Pact, Acidmaw, Brann Bronzebeard, Stampeding Kodo.

https://www.youtube.com/watch?v=jcniWFdCBKY&list=PLx2kRadCTuYYrck0V0soHYjBvas9dGDYI&index=1
