### ISSUE TITLE
Playing Demonic Project with Illidan on the board freezes the game

### ISSUE THREAD

**Issue by thoughthouse** [HearthSim/hs-bugs#1022]
https://www.reddit.com/r/hearthstone/comments/97bf0h/bug_when_i_played_demonic_project_with_illidan_my/

https://www.reddit.com/r/hearthstone/comments/9695bi/some_interaction_between_illidan_stormrage/

https://www.reddit.com/r/hearthstone/comments/96s7ga/bug_game_breaks_if_you_play_demonic_proyect_while/

https://www.reddit.com/r/hearthstone/comments/97b2wx/encountered_a_game_breaking_bug/

**Comment by TheManuz** [comment]
Happened to me, too.
Sidenote: When I encountered this bug, Illidan also was created by a Demonic Project, I don't know if this is relevant but I wanted to report it.

**Comment by anthonyjr2** [comment]
Seems fixed as of 13.0.0.28116.
https://streamable.com/xlsfb
