### ISSUE TITLE
Whizbang decks remember the class used to create the deck, and some interface elements refer to it instead of the class chosen by Whizbang

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1023]
In the Icecrown adventure, beating The Lich King with a Whizbang deck shows the victory cutscene for the original class of the deck

https://us.battle.net/forums/en/hearthstone/topic/20767557340

> I created a Whizbang deck with Mage as my base class, then went to fight the Lich King encounter. For the most part, he treated me as like I was a druid (had the treant deck), but at the end I got Jaina's "there must always be a Lich King" victory thing, instead of the druid one.

Additional report of this: https://us.battle.net/forums/en/hearthstone/topic/20767677417

**Comment by troggnostupidhs** [comment]
I wonder how Whizbang counts for Quests

**Comment by troggnostupidhs** [comment]
I have the quest Win 3 games with Paladin or Warrior 

Paladin playing with a Hunter deck and it did not advance the quest when I won

**Comment by troggnostupidhs** [comment]
Hunter win playing a Warrior deck and it did count for the quest.

So for quest, they have it counting as the Hero for the selected deck.

**Comment by Jetz72** [comment]
It appears Whizbang will also show the wrong experience bar after games, as well. There are reports like this which claim Whizbang doesn't level up the class you played as: https://www.reddit.com/r/hearthstone/comments/95n6f7/whizbang_does_not_level_the_class_you_create_the/

However, this poster seems to have explored the issue more thoroughly:
https://www.reddit.com/r/hearthstone/comments/95h7nz/correcting_the_confusion_about_whizbang_and_class/
>Whizbang is actually leveling your classes just like you'd expect. The post-game level display is bugged, causing confusion.
>On the victory/defeat screen, it will show the portrait of the class that Whizbang chose for you, but underneath it will be the level and progress bar of the class that you chose when you made the Whizbang deck. But, since Whizbang is leveling the class he chose, the progress bar for the class you chose will not increase, unless they just happen to be the same class.

Unsure if this should be a separate issue or if it'd be better to consolidate all Whizbang metagame issues.

**Comment by troggnostupidhs** [comment]
I think all the post game Whizbang issues should be tracked here for now

**Comment by Jetz72** [comment]
Alright. Revised the title and original post.

**Comment by troggnostupidhs** [comment]
The experience part is fixed.

**Comment by troggnostupidhs** [comment]
Animation is fixed, but it's arguably worse because the achievement is for the original class.

> csca_xy Today at 6:32 AM
> if your whizbang deck is built using a priest hero and then the game using paladin deck, after beating the lich king, the animation is paladin, but the priest achievement is unlocked.

**Comment by ceceita** [comment]
https://imgur.com/a/jaVmM4K
