### ISSUE TITLE
Following 12.0, many aura update steps appear to be missing from the usual sequences

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1024]
This has yet to be investigated thoroughly, but with all the undocumented behavior changes this causes, it is probably safe to say this isn't intended. Multiple reports detail issues involving effects triggered by attacks being postponed.

Enrage vs Explosive Trap is the most common case: https://us.battle.net/forums/en/hearthstone/topic/20767146523
> Just played a game as a Warrior and was about to counterplay my opponents explosive trap with Grommash Hellscream. But for some reason, when I attacked with my minion, the secret triggered and damaged Grommash but he didn't receive the attack bonus which led me to lose the game. 

Hysteria's Mythbusters 61 demonstrates an anomaly with Supercollider versus an Enrage minion: https://youtube.com/watch&v=KDJxQ9AtWz8&t=1m4s
The Enrage attack buff was not applied between Supercollider damaging the minion and the minion damaging its neighbor.

Not 100% certain this is related (specifically if this effect is aura-related), but I can't think of a better explanation; Razuvious' Giant Runeblade reportedly no longer deals double damage to heroes: https://us.battle.net/forums/en/hearthstone/topic/20767747509
> It seems that there might be a bug with Razuvious. When he uses his massive runeblade it no longer deals double damage when he attacks heroes, only the normal 5. Thought it was a whizbang thing, but after further testing it's the same across the board in all scenarios.

There's also this, a Necromechanic died at the same time as some friendly deathrattle minions, but the deathrattles still triggered twice: https://us.battle.net/forums/en/hearthstone/topic/20767507098

> 1. Opponent plays Mechromancer.
> 2. I lower the Mechromancer's health to 2.
> 2. Opponent plays Boommaster Flark.
> 3. I consecrate.
> 4. Goblin Bombs deal 16 damage instead of 8.

(This runs contrary to what is documented in the wiki page for Rivendare.)

All of these behaviors are unintuitive at best and obviously broken at worst.

**Comment by Kybxd** [comment]
Raid Leader/Stormwind Champion/Leokk + Noble Sacrifice/Wandering Mosters

Videos: https://www.bilibili.com/video/av28709368

(Starting from 7:45) Defender doesn't gains aura when he does damage to enemy, but before death he gains Stormwind's health aura and survives.

**Comment by PattuX** [comment]
I'm kinda curious whether Grom gains attack when attacking into explosive trap if an Imp Gang Boss is hit by the explosive trap at the same time to find out whether there is a conditional aura update or no aura update at all.

**Comment by Jetz72** [comment]
Would probably want to test that with Amani Beserker or Raging Worgen, so you can get it down to two classes. Think the expert innkeeper runs one Explosive Trap, though also Misdirection and a couple others.

The Defender test suggests there's an attack/health aura update between the attack and death phase, while the Necromechanic case above suggests there isn't an update for other auras during that time. Either that, or summoning the Defender triggered the aura update, but it was delayed until after the attack.

**Comment by troggnostupidhs** [comment]
#106 is possibly worth testing

**Comment by Kybxd** [comment]
Here is a video that shows Aura Update (Other) doesn't run after Death Creation. The auras of Rivendare and Auchenai remains to work in the following death phase.

https://www.bilibili.com/video/av29835504 (Starting from 0:45)

**Comment by PattuX** [comment]
The thing above should also work with Mal'Ganis (specifically the immunity part).

If might be interesting to see what happens when you have Mal'Ganis at 2HP and two Abominations at 2HP and 4HP, respectively and cast a two damage AOE. Does your hero take 2 damage?

If it does, the order may just be swapped, i.e., Death Creation happens after Aura Update A/H now (which may then be consistent and fix #106). If you don't take any damage, no Aura Update is running. Then there is no more Aura Update Before Death Phases or they are conditional (again test by adding Imp Gang Boss).

**Comment by Kybxd** [comment]
I retested Auchenai. Healing is still converted to damage when Auchenai and Zombie Chow die in the same phase.

**Comment by Jetz72** [comment]
I tested Auchenai + Zombie Chow/Mistress of Mixtures dying at the same time. The Deathrattles healed the heroes correctly.

![hearthstone screenshot 01-24-19 21 16 53](https://user-images.githubusercontent.com/8607832/51733748-578f6a80-2050-11e9-9bb9-87b410ed5e07.png)
![hearthstone screenshot 01-24-19 21 17 00](https://user-images.githubusercontent.com/8607832/51733752-5cecb500-2050-11e9-974c-64c1445ab62e.png)

Any other cases that should be tested for this bug?

**Comment by Jetz72** [comment]
The lack of an aura update between removing dead minions and deathrattles triggering has returned:
![Hearthstone Screenshot 04-15-19 09 27 50](https://user-images.githubusercontent.com/8607832/56136762-686dbf00-5f61-11e9-981f-5899de1c7619.png)
![Hearthstone Screenshot 04-15-19 09 28 05](https://user-images.githubusercontent.com/8607832/56136771-6ad01900-5f61-11e9-8392-af30d025ca2a.png)
Both Auchenai and Rivendare continued to apply after they were removed from the board. Considering opening a new report for this.

**Comment by Jetz72** [comment]
Gonna consider the issues caused specifically by 12.0 resolved, and the reemergence of one in particular due to a separate cause. Documenting it in #1156, and closing this, as the remaining issue is no longer associated with 12.0 in particular and refactoring this broad report around a singular aspect of it seems like it'd be worse from an archival stance.

**Comment by Jetz72** [comment]
I just realized, in my January 25th test, there was a Violet Wurm that died alongside the others. The bug probably never stopped; it was just the 1/1s being summoned that triggered an aura update early. Whoops.
