### ISSUE TITLE
Razuvious' Giant Runeblade no longer deals double damage to heroes

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#1025]
https://us.battle.net/forums/en/hearthstone/topic/20767747509

Possibly related to #1024

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22546493
> Naxxramas: Instructor Razuvious’ Massive Runeblade weapon now correctly deals double damage to Heroes.
