### ISSUE TITLE
If you merge Zilliax with a deathrattle Mech, its deathrattle doesn't have Lifesteal

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#1028]
https://www.bilibili.com/video/av29634580 (Starting from 5:05)

**Comment by troggnostupidhs** [comment]
https://youtu.be/lCwyi7iViZw?t=80

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22546493
> Lifesteal provided by Zilliax now correctly applies to damage dealt by Deathrattle effects.
