### ISSUE TITLE
Augmented Elekk shuffles extra copies of cards when you play Golden Monkey or Renounce Darkness

### ISSUE THREAD

**Issue by thoughthouse** [HearthSim/hs-bugs#1029]
Also tested with Explore Un'goro, but there was no interaction.
https://imgur.com/a/oWwbFrz

**Comment by troggnostupidhs** [comment]
Could be a related fix?

https://playhearthstone.com/en-us/blog/22788307

> Tracking will no longer sometimes make a card invisible when your hand is full.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22938499/

> Fixed an issue where playing The Golden Monkey with Augmented Elekk on the board would cause extra legendary minions to be shuffled into your deck.

**Comment by Jetz72** [comment]
Renounce Darkness is fixed:
![Hearthstone Screenshot 04-04-19 19 15 30](https://user-images.githubusercontent.com/8607832/55594614-46c53a00-570e-11e9-9fee-2f23f4c418c1.png)
![Hearthstone Screenshot 04-04-19 19 15 40](https://user-images.githubusercontent.com/8607832/55594615-488efd80-570e-11e9-85eb-2c2776eaa48d.png)

Had 4 cards in deck, 2 of them were Warlock ones. No triggers. Seems Renounce now uses the new transformation method for cards in the deck. Ones in the hand are still thrown into the Setaside zone and replaced, oddly enough.
