### ISSUE TITLE
Garrison Commander played into Snipe refreshes your Hero Power

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#103]
If you use your Hero Power, play Garrison Commander, you will see your Hero Power refresh, Snipe trigger and the Garrison Commander die. However, your Hero Power remains available to use still.

In general, your Garrison Commander or Coldarra Drake dying does not exhaust your Hero Power, which might seem unintuitive if you expect it to work like Windfury or like other Auras like Prophet Velen, which turn off when they leave play.

http://us.battle.net/hearthstone/en/forum/topic/18704212831

Ben Brode has clarified that he thinks something about this interaction is a bug:

https://twitter.com/bdbrode/status/634151178717171712

It is not yet clear what part of this interaction is the bug.

**Comment by Xinhuan** [comment]
This tweet from Whirthun suggests it isn't a bug, given that this interaction is known well in advance to them. Ben Brode's word probably trumps Whirthun's though.

https://twitter.com/CM_Whirthun/status/624609914095165440

**Comment by culinko** [comment]
Still happens in 5.0 after the change of mechanics.

**Comment by jleclanche** [comment]
Closing, this is intended.
