### ISSUE TITLE
Unexpected Results is visually buffed by Prophet Velen, but is not actually affected

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1030]
https://us.battle.net/forums/en/hearthstone/topic/20767688418
>Unexpected results says it will summon two *4*- Cost minons, but it summoned two 2 drops instead.
![Image from thread, as described with Velen played first](https://i.imgur.com/tFHL0n6.jpg)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/9cxw5h/i_had_prophet_velen_on_the_board_which_showed_up/

> I had Prophet Velen on the board which showed up on the card to improve Unexpected Result’s minions. However it still summoned two 3 mana minions.

![image](https://user-images.githubusercontent.com/22508641/45065155-9ca50700-b085-11e8-9fb4-38178597122c.png)

**Comment by troggnostupidhs** [comment]
This is arguably a display bug, not a gameplay bug

**Comment by Bloodskys** [comment]
The problem still exists. Just had the same behaviour.
https://hsreplay.net/replay/FVc3tmyz6w4fCxG3S3PouY#turn=9a
Turn 9

**Comment by troggnostupidhs** [comment]
Thanks for the report!

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/velen-unexpected-results/3133

> Summons 2 cost minions instead of 4 cost (despite the text on the card)

**Comment by Bloodskys** [comment]
> https://us.forums.blizzard.com/en/hearthstone/t/velen-unexpected-results/3133
> 
> > Summons 2 cost minions instead of 4 cost (despite the text on the card)

Yeah, I created topic at Blizzard forum too.

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/velen-unexpected-results/3133/24

> That is correct, it was fixed back in 12.2 and we had some extensive rework done since then. I confirmed that Unexpected Results will change its text when Velen is present, the text should only be affect by spell damage and not Velen.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/23076826

> Unexpected Results should no longer display an incorrect bonus from
Prophet Velen.
