### ISSUE TITLE
If Skaterbot (merged with Zilliax) is returned to hand and then merged to another Mech, the Mech gains Zilliax's keywords

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#1032]
https://www.bilibili.com/video/av30142626 (Starting from 3:45)

1) Merge Zilliax with Skaterbot I
2) Skaterbot I is Sapped
3) Merge Skaterbot I with Skaterbot II
4) Skaterbot II becomes 2/2 Taunt, Divine Shield, Lifesteal

**Comment by PattuX** [comment]
Is this Zilliax specific?

Probably the same underlying issue as #1009

**Comment by PattuX** [comment]
This is very likely #1021, see my comment there.
