### ISSUE TITLE
Supercollider shows the "wrong" hammer animation when used by the opponent.

### ISSUE THREAD

**Issue by TheManuz** [HearthSim/hs-bugs#1034]
As described in [this reddit comment](https://www.reddit.com/r/hearthstone/comments/9ajjma/supercollider_interaction_with_enrage_minions_is/e4wxh3k/), when Supercollider is **used by the player**, the hammer animations are correct (the hammer hits accordingly to the minion motion).

When Supercollider is **used by the opponent**, the animations are shown exactly flipped (the hammer hits on the opposite side, contrary to the expected motion).

### Correct behavior (used by the player)
- [Left to right](https://youtu.be/4lKX7VsZg_o?t=3m44s)
- [Right to left](https://youtu.be/4lKX7VsZg_o?t=2m57s)

### Wrong behavior (used by the opponent)
- [Left to right](https://youtu.be/ZXjiWM07OwY?t=11m50s)
- [Right to left](https://youtu.be/ZXjiWM07OwY?t=11m20s)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/9rn5gv/developer_insights_the_art_behind_the_science/e8istvt/?context=3

**Comment by troggnostupidhs** [comment]
https://youtu.be/kUWnouu-Zqs?t=281
