### ISSUE TITLE
Prophet Velen display issue with Unexpected Results

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1039]
https://www.reddit.com/r/hearthstone/comments/9cxw5h/i_had_prophet_velen_on_the_board_which_showed_up/

> I had Prophet Velen on the board which showed up on the card to improve Unexpected Result’s minions. However it still summoned two 3 mana minions.

![image](https://user-images.githubusercontent.com/22508641/45065155-9ca50700-b085-11e8-9fb4-38178597122c.png)

**Comment by Jetz72** [comment]
#1030

**Comment by troggnostupidhs** [comment]
Oops, thanks
