### ISSUE TITLE
Divine Spirit has rounding errors for Health above about 2^24

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#104]
In the process of trying to test the theory that the maximum possible Attack or HP value of a minion is 2^31 - 1 or 2,147,483,647, the procedure to do so is to start with a 1/1 Wisp, and adding 1 HP and doubling its HP alternatingly like this:

1, 2, 3, 6, 7, 14, 15, 30, 31, 62, 63, 126, 127...

so that its HP value is always just 1 or 2 under the next Power of 2. However, when the HP of the wisp reached 33,554,431, the next Divine Spirit doubled its HP to 67,108,863 (odd number). Using more Divine Spirits doubled its HP again to 134,217,727 and then to 268,435,455 and to  536,870,911 and to 1,073,741,823 and finally 2,147,483,647.

This is possibly because when the HP value is doubled, one of the temporary variables used in the process are of type "float" rather than "int", which loses precision after 16,777,216 (or 2^24) as IEEE single precision floats can no longer hold integer values accurately beyond that point.

Sample C++ code that illustrates this problem: http://pastebin.com/E7r8mQtX

Note that Divine Spirit works by increasing Current HP and Maximum HP of a minion by the same amount which is equal to its Current HP. This is done by addition to both properties of the minion and _not_ by multiplication. For example, if you cast Divine Spirit on a 4/3 Injured Blademaster with 7 Maximum HP, it becomes a 4/6 with 10 Maximum HP.

[[Hearthstone Science] Divine Spirit Rounding Bug and Maximum Possible Health ](https://www.youtube.com/watch?v=VwwtzER5ewc)

**Comment by culinko** [comment]
Confirmed in 4.1 with SimFri.

**Comment by PattuX** [comment]
culinko and me tested this with attack buffs. Neither Gahz'rilla nor Blessed Champion had a rounding error in the process.

**Comment by PattuX** [comment]
Dealt one more damage than expected

* https://www.youtube.com/watch?v=LZRg9vtBmds

**Comment by troggnostupidhs** [comment]
I tested this, I believe it is the correct amounts

![hearthstone screenshot 06-03-17 19 01 42](https://cloud.githubusercontent.com/assets/22508641/26757616/e9f4ff7e-488f-11e7-87bf-08ec283fd7f9.png)

![hearthstone screenshot 06-03-17 19 01 54](https://cloud.githubusercontent.com/assets/22508641/26757618/ebce2028-488f-11e7-93cf-4ec5acc4e775.png)

![hearthstone screenshot 06-03-17 19 02 19](https://cloud.githubusercontent.com/assets/22508641/26757619/edba84da-488f-11e7-9f90-2a477e625c27.png)

![hearthstone screenshot 06-03-17 19 02 39](https://cloud.githubusercontent.com/assets/22508641/26757620/efa13fbe-488f-11e7-843a-94f6df35dae5.png)

**Comment by Patashu** [comment]
Looks fixed to me too.
