### ISSUE TITLE
Potion of Polymorph doesn't remove health modifications instantly, causing the Sheep taking more or less damage from the following Explosive Runes

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#1043]
* https://www.bilibili.com/video/av31202254
(Starting from 3:00)

Witchwood Grizzly becomes 3/10 from its battlecry (Health -2). So the Sheep's health is considered to be -1 (1-2), and all 6 damage is dealt to enemy hero.

Twilight Drake becomes 4/4 from its battlecry (Health +3). So the Sheep's health is considered to be 4 (1+3), and only 2 damage is dealt to enemy hero.

Note that this bug was first found in Patch 11.X.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/avj2ko/blizzard_broke_the_potion_of_polymorph_into/

![image](https://user-images.githubusercontent.com/22508641/53536753-8d06f800-3ad5-11e9-905b-e13fdcda66bc.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/wildhearthstone/comments/bd2c3j/4_damage_to_kill_1_hp_sheep_thank_you_blizzard/

> That was on turn 5 , https://hsreplay.net/replay/Hyd87hGLynqFNToxa7ybCN, BTW I lost because of this

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22933721
> Explosive Runes now deals correct damage to minions that transform after they come into play.

**Comment by Kybxd** [comment]
![QQ图片20190515114030](https://user-images.githubusercontent.com/18246091/57747090-91bb6f80-7706-11e9-822b-b51764526196.jpg)
![QQ图片20190515114042](https://user-images.githubusercontent.com/18246091/57747094-93853300-7706-11e9-9841-c2305c5b6072.jpg)
