### ISSUE TITLE
Inconsistencies in the Combat Preparation Phase and Combat Sequence

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#105]
All of the following are discussed in further detail, with video evidence, in the Combat section of the Advanced rulebook:

http://hearthstone.gamepedia.com/Advanced_rulebook#Combat

1) The Queue of the Combat Preparation Phase is Greedy. That is, triggers can be added to the Queue even if they weren't previously eligible. For example, if you attack with an Ogre Brute into an Explosive Trap and it redirects away, Explosive Trap still goes off. Conversely, if you attack with an Ogre Brute onto a minion and it redirects onto the Hero, Explosive Trap still goes off. This can be contrasted to, for example, how if Troggzor the Earthinator summons a Burly Rockjaw Trogg, the Burly Rockjaw Trogg doesn't immediately queue and trigger off of the same spell.

2) The Combat Preparation Phase has not one, but two queues - the High Priority Queue and the Low Priority Queue. (A full list of what is High and what is Low Priority is in the Advanced rulebook). This means that, for example, regardless of order of play, Freezing Trap always goes off before (and prevents) Blessing of Wisdom. In addition, greediness is only within the same Queue. For example, since Ogre Brute's 'Forgetful' is High Priority and Snake Trap is Low Priority, if Ogre Brute redirects onto a minion, then Snake Trap will go off, but if he redirects off of a minion, Snake Trap will not go off, seemingly in contradiction to what we discussed in 1).

3) If one or both heroes die after the Combat Preparation Phase (and all subsequent Death Phases), but before the Combat Phase itself, then the game ends in a win/loss/draw with the proposed attacker still hanging in mid air. This is inconsistent with all other Sequences, such as casting a spell or playing a minion, which will wait until the very end of the Sequence before checking for win/loss/draw. This matters if, for example, you attack with a minion into an Explosive Trap, die, but if the minion attack went off you would have tied instead.

https://www.youtube.com/watch?v=YlaP_kF823k

**Comment by Patashu** [comment]
(I think this is all still true as of 3.0, but not 100% sure, so leaving it at a tentative 2.7)

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3ic916/crazy_interaction_with_cutpurse_and_misdirection/ < Cutpurse + Misdirection gives two coins. Looks like we're going to have to dig into this a lot in 3.0.

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=YlaP_kF823k

Win/loss/draw is still checked before the actual combat occurs in 3.0.

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=KdqR8kwQr-8&t=1m26s

If you attack face but Forgetful redirects off, Secrets like Explosive Trap still trigger, in 3.0.

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=mDaw4ujGw0Y

Cutpurse got changed some patch after 3.0, it's now a Low Priority trigger and can't give two coins with Misdirection anymore.

**Comment by PattuX** [comment]
Isn't this irrelevant with the new model now?

1) We know now that there is no greedy queue but a new queue after target has changed (Orge - Explosive - Noble Sac test)

2) We declared it as 2 Phases now

3) Same reason, death is checked between phases

**Comment by jleclanche** [comment]
Either way we can't really keep this bug open, it's far too unclear what is actually wrong here.
