### ISSUE TITLE
Replaying Myra Rotspring with Anub'arak's deathrattle causes a crash

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1051]
https://www.reddit.com/r/hearthstone/comments/9jrc3h/bug_myra_rotspring_anubarak_deathrattle_that_dies/
https://i.imgur.com/BtRaLXd.mp4

> Steps to reproduce:
> 
>     Play Myra.
> 
>     Choose Anub'arak.
> 
>     Myra dies and returns to hand.
> 
>     Replay Myra.
> 
> Her animation plays but the game hangs and soon disconnects, awarding a loss.
> 
> Video of bug in action.
> 
> Sorry for potato quality, resizing client window and recording does that sometimes.

**Comment by anthonyjr2** [comment]
Seems to have been fixed at some point, from my testing. Sorry for horrific quality I didn't expect the recording to have so few frames.

https://i.imgur.com/DnCdtoS.mp4

**Comment by Jetz72** [comment]
Unclear when it was fixed. Can't find a more recent report of it happening, or any other reports of it at all. Unclear if Reddit OP actually tested it thoroughly - the only video was taken on ladder. They may have just encountered a random disconnect and reported it. Either way, seems like it's no longer an issue.

**Comment by troggnostupidhs** [comment]
Trying to get confirmation on this report

https://www.reddit.com/r/hearthstone/comments/atjagj/forget_about_esports_just_put_basic_things_into/eh3jc1p/

> If [[Myra]] discovers Anub'arak and she dies, the game may glitch out when she's played again. Happened to me last month.

**Comment by Jetz72** [comment]
Tried a bunch of things with Trogg for like an hour and came up with nothing, despite getting several Myra->Anub'araks and eliminating them in various ways,

```
### Myra Test
# Class: Rogue
# Format: Wild
#
# 2x (0) Shadowstep
# 2x (2) Cheap Shot
# 2x (2) Eviscerate
# 2x (2) Gadgetzan Ferryman
# 2x (2) Gang Up
# 2x (2) Lab Recruiter
# 2x (2) Novice Engineer
# 1x (2) Roll the Bones
# 2x (2) Shiv
# 2x (2) Youthful Brewmaster
# 1x (3) Augmented Elekk
# 1x (3) Unearthed Raptor
# 2x (4) Ancient Brewmaster
# 2x (4) Elven Minstrel
# 1x (5) Myra Rotspring
# 1x (6) Emperor Thaurissan
# 1x (6) Vanish
# 1x (9) Valeera the Hollow
# 1x (10) Deathwing
# 
AAEBAYO6AgjEAcIG1hHLFsDMAoDTAp/4AvWAAwu6AZwC7QKfA70EiAeAEvi9AtvjArHuAuD6AgA=
# 
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
```

**Comment by troggnostupidhs** [comment]
Tested for a while with Jetz. I had Anub'arak come up over 6 times and it was never an issue. I even had the same Myra discover Anub'arak two times in a row. We also tried having Myra die on the player's turn and the opponent's turn.
