### ISSUE TITLE
Headless Horseman Rides: The Horseman's Head can be transformed, leaving the brawl unwinnable

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1055]
https://www.reddit.com/r/hearthstone/comments/9r95sb/devolve_off_of_witchs_apprentice_doesnt_work/

> ![Enemy horseman immune, nothing on their battlefield](https://i.redd.it/j6qenf4eabu11.jpg)

Removing the head in this way without killing it leaves the boss permanently Immune. 

It can be argued that this is intended, as the Head's text does say: "**Destroy his head to win the game**, but watch out for fireballs!". However, there are a number of reasons to think it might not be.

- Silencing the head and killing it _does_ win the brawl - https://www.reddit.com/r/hearthstone/comments/797ic4/til_the_headless_horsemans_head_is_unaffected_by/dozw0vl/
- The brawl is heavily flavor-oriented. There are a number of unwritten rules such as the enemy hero being immune, the head being untargetable by spells or hero powers, and the head's text not being written from the user's perspective. The text can not be relied upon to accurately describe the game logic. The body surviving because the head was transformed before it died is a technicality that seems out of place with the rest of the flavor.
- It is possible that the head being transformed was never considered in design. Reviewing all 4 decks, the encounter's card pool seems almost entirely closed. Infest is the only leak that allows access to the full card pool, and only through the small set of beasts with further random generation effects. Gaining access to a card that can transform the head is exceedingly rare, and the possibility may have been an oversight. For comparison, other brawls with Boss minions such as Nefarian Rises have a completely closed card pool, making transformation and other obscure removals impossible.

**Comment by troggnostupidhs** [comment]
Silence is the same in this years brawl (killing the silenced head will end the brawl)

https://www.reddit.com/r/hearthstone/comments/9r0ybg/this_weeks_tavern_brawl_is_the_headless_horseman/e8dzahz/

https://www.reddit.com/r/hearthstone/comments/9r1clk/horseman_brawl_glitch/

**Comment by troggnostupidhs** [comment]
Another unwritten rule, can't attack the Headless Horseman's head with poison

https://www.reddit.com/r/hearthstone/comments/9r1gar/just_trying_to_meme_when_this_appears/

![image](https://user-images.githubusercontent.com/22508641/47520441-2be8c280-d85e-11e8-8000-be43bb417205.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/9rwbz8/ive_made_a_huge_mistake/

![image](https://user-images.githubusercontent.com/22508641/47622260-73c74e00-dad9-11e8-8f15-57638119e8f1.png)

**Comment by Jetz72** [comment]
The head apparently cannot be transformed this time around. Attempting to transform it via Swampqueen's Call had no effect:

![Hearthstone Screenshot 10-11-19 19 46 41](https://user-images.githubusercontent.com/8607832/66706974-ff94b300-ed07-11e9-8871-bdf801b667eb.png)

A log excerpt indicates that it attempted to transform into Archivist Elysiana (52870), but the effect was prevented by a trigger.
```
TAG_CHANGE Entity=[entityName=Headless Horseman's Head id=212 zone=PLAY zonePos=3 cardId=TB_TempleOutrun_HHHead player=1] tag=1069 value=52870 
BLOCK_START BlockType=TRIGGER Entity=[entityName=Headless Horseman's Head id=212 zone=PLAY zonePos=3 cardId=TB_TempleOutrun_HHHead player=1] EffectCardId= EffectIndex=6 Target=0 SubOption=-1 TriggerKeyword=0
    TAG_CHANGE Entity=[entityName=Headless Horseman's Head id=212 zone=PLAY zonePos=3 cardId=TB_TempleOutrun_HHHead player=1] tag=1069 value=0 
BLOCK_END
META_DATA - Meta=TARGET Data=0 InfoCount=1
            Info[0] = [entityName=Headless Horseman's Head id=212 zone=PLAY zonePos=3 cardId=TB_TempleOutrun_HHHead player=1]
TAG_CHANGE Entity=[entityName=Headless Horseman's Head id=212 zone=PLAY zonePos=3 cardId=TB_TempleOutrun_HHHead player=1] tag=DISPLAYED_CREATOR value=225 
```

The immunity also seems to come from controlling the head, as stealing it transfers the effect to you. 

Seems fair to call this fixed.
