### ISSUE TITLE
Raging Worgen keeps Windfury if enraged and copied with specific stats

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1057]
https://us.battle.net/forums/en/hearthstone/topic/20769648262
>When you copy a damaged Raging Worgen with a Mirage Caller / Power Word: Replicate than the copy will retain Windfury.

Tested and confirmed:
![hearthstone screenshot 10-30-18 20 48 31](https://user-images.githubusercontent.com/8607832/47759927-5d132980-dc88-11e8-8312-e3ae161f1559.png)

![hearthstone screenshot 10-30-18 20 51 23](https://user-images.githubusercontent.com/8607832/47759805-b6c72400-dc87-11e8-9cd0-644bba8a14ee.png)

Did not happen when stats on an enraged Worgen were set to 3/3 via Dark Conviction. Also did not extend to Quartz Elemental ("Can't attack while damaged."), which presumably doesn't use the same setup as the old enrage cards.

**Comment by troggnostupidhs** [comment]
https://news.blizzard.com/en-us/hearthstone/22882146/hearthstone-update-february-5

> Fixed an issue that could cause cards that copy and set minion Health to a specific value to incorrectly activate “while damaged” effects.

**Comment by Jetz72** [comment]
Tested, confirmed fixed:
![Hearthstone Screenshot 03-18-19 17 57 33](https://user-images.githubusercontent.com/8607832/54566570-98986100-49a7-11e9-8138-96e6be6bd6ee.png)
