### ISSUE TITLE
Druid of the Flame has its stats reversed on the discover choices

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1063]
https://us.battle.net/forums/en/hearthstone/topic/20763956467#post-8

**Comment by anthonyjr2** [comment]
Not sure what the problem was originally but it seems fine now? Unless I'm missing something.

![hearthstone screenshot 12-12-18 10 22 45](https://user-images.githubusercontent.com/5232548/49879491-13297180-fdf8-11e8-81e6-ad60e9e1d8fa.png)

**Comment by troggnostupidhs** [comment]
Looks good to me.

**Comment by troggnostupidhs** [comment]
Looks good to me. Thanks for testing.
