### ISSUE TITLE
Tracking triggers Augmented Elekk

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1068]
From the report here: https://us.battle.net/forums/en/hearthstone/topic/20769776810

>I found the interaction bug between Tracking and Augmented elekk. When I draw a card with Tracking, Augmented elekk will shuffle a copy of that card into the deck. I think the problem is the way Tracking work. First it remove 3 card from top of your deck and let's you discover one removed cards after that it shuffle the selected card into the top of your deck and draw it the problem is the shuffled card trigger A.E. and miracle happen.

Tested and confirmed:
![hearthstone screenshot 12-01-18 11 58 03](https://user-images.githubusercontent.com/8607832/49331314-ead48400-f568-11e8-94a0-de68740bf757.png)
![hearthstone screenshot 12-01-18 11 58 15](https://user-images.githubusercontent.com/8607832/49331317-f162fb80-f568-11e8-89c3-8c21ebfe524f.png)
![hearthstone screenshot 12-01-18 11 58 22](https://user-images.githubusercontent.com/8607832/49331322-ffb11780-f568-11e8-9e9a-2c07eae42a70.png)
![hearthstone screenshot 12-01-18 11 59 12](https://user-images.githubusercontent.com/8607832/49331325-0770bc00-f569-11e8-8081-febf0bacdb33.png)

Presumably happens for the reason OP guessed. The card is in the setaside zone when making the choice, goes back to the deck triggering Elekk, then drawn to the hand so that on-draw triggers can work.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/a30rjh/a_weird_bug_i_just_encountered_with_elekk_and/

> 
> So I was playing deathrattle hunter and got an Elekk mix (Elekk + Boar). I played the Elekk and then tracking afterwards. The choices were Hunters Mark, Spiderbot and Kathrena. I chose Kathrena and it was added to my hand. Then the Elekk did it’s animation. For the next 2 turns the only card I drew was Kathrena. I had 3 in my hand when my opponent conceded. I’m not sure what happened but I think the Elekk added a 3-6 Kathrena to the deck. Tracking must put the cards back into the deck so Elekk triggered putting extra copies into the deck but the other 2 were discarded so it put a bunch of Kathrena in the deck instead.
> 
> Sorry I didn’t get a picture, my Opponent conceded as I drew the 3rd Kathrena so I didn’t get chance. I’ll try to recreate the bug and post a pic.
>

**Comment by Kybxd** [comment]
> Fixed an issue that could prevent Augmented Elekk form activating.

Possibly the side effect of fixing an previous bug: If you shuffle a card into deck and draw it immediately (for example, Map to the Golden Monkey), Elekk won't shuffle a copy of it. Here is a previous video: (starting from 6:50) https://www.bilibili.com/video/av37117483

**Comment by troggnostupidhs** [comment]
https://news.blizzard.com/en-us/hearthstone/22882146/hearthstone-update-february-5

> Fixed an issue that would cause Augmented Elekk to shuffle a copy of a card drawn by Tracking into the deck.
