### ISSUE TITLE
Jan'alai the Dragonhawk causes an animation hang when its Battlecry is doubled

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1071]
https://www.reddit.com/r/hearthstone/comments/a33zq1/potential_bug_brann_and_janalai_crashed_the_game/
>Happened for a second time: https://clips.twitch.tv/RelentlessWanderingMartenTheTarFu

https://www.reddit.com/r/hearthstone/comments/a34379/brann_janalai_crashes_the_game_in_wild/
>Just was watching Dane's stream playing Odd Mage in wild. 2 games in a row he played a Brann + Jan'Alai combo and both times it crashed his game.

https://clips.twitch.tv/StrongEndearingSeahorseBibleThump

**Comment by troggnostupidhs** [comment]
Spirit of the Shark does not have the same problem.

![hearthstone screenshot 12-04-18 20 07 29](https://user-images.githubusercontent.com/22508641/49483247-7b78c180-f800-11e8-9efe-d4e5a9a3e74d.png)
![hearthstone screenshot 12-04-18 20 07 41](https://user-images.githubusercontent.com/22508641/49483248-7b78c180-f800-11e8-873f-df3f46e8e224.png)

Rogue goal, draw Finley and copy him until get a damage Hero Power. After 8 HP damage, copy Jan'alai and return to hand. Play Jan'alai with Shark.

Mage goal, get Jan'alai. 

Rogue Deck
AAEBAaIHAu0FhBcO+wGcAp8DkwS9BJsFuQaIB4AS+L0C+MECpvAC4PoCtIYDAA==

Mage Deck
AAEBAf0EBP4D7QWohwOthwMNTbMB+wGcArsClgW5BvETt2ziygKm8AKkhwPNiQMA

**Comment by troggnostupidhs** [comment]
Does not happen for me against Innkeeper

![hearthstone screenshot 12-04-18 20 31 18](https://user-images.githubusercontent.com/22508641/49484075-ad3f5780-f803-11e8-8f6e-e1a694966219.png)

Mage Deck
AAEBAf0EBO0Fm9MCqIcDrYcDDU37AbsClgW5BvETiawCo7YCmMQCx8cCpvACpIcDzYkDAA==

**Comment by troggnostupidhs** [comment]
new update
did it in wild
got two rags
but they didn't shoot the fireballs

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/a34vu8/danehs_crashing_hearthstone_with_janalai_the/

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/a33zjd/janalais_battlecry_not_triggering_twice_with_the/

https://clips.twitch.tv/AbstruseToughButterAsianGlow

**Comment by troggnostupidhs** [comment]
Tested Brann in friend challenge and it hangs. So it seems specific to Brann.

**Comment by troggnostupidhs** [comment]
This person reports a crash with Shark

https://www.reddit.com/r/hearthstone/comments/a4gaey/playing_janalai_with_spirit_of_the_shark_on_board/

![image](https://user-images.githubusercontent.com/22508641/49699615-47efbb80-fba1-11e8-8c24-3cec5e9e059a.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/a4e47a/the_brannjanalai_interaction_is_still_crashing/ebeqtyp/

> There is a fix incoming. Unfortunately it's a client side issue so we have to patch instead of hotfixing. I expect it to go out sometime this coming week.

**Comment by troggnostupidhs** [comment]
Should be fixed in latest patch

https://www.reddit.com/r/hearthstone/comments/a5022e/brannjanalai_interaction_finally_fixed/

**Comment by troggnostupidhs** [comment]
I guess Kripp doesn't checkout hs-bugs

https://youtu.be/YpmcD7H6e7A?t=432
