### ISSUE TITLE
The 'summoning catchup step'

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#108]
(This likely exists in order to make Starving Buzzard work with Unleash the Hounds and Druid of the Claw, but has some weirdness and inconsistencies around it nonetheless.)

Conditional on-summon checks (Undertaker, One-eyed Cheat and Starving Buzzard) will fail to trigger during their usual Phase if
* The minion did not satisfy the condition, but after its Battlecry, it transformed itself (Druid of the Fang, Faceless Manipulator, etc), and now it does, or
* The Undertaker/One-eyed Cheat/Starving Buzzard was not in play at the start of the Phase, and wants to trigger to summons that occurred earlier in the same Phase, or
* The minion was summoned, not played (such as via a spell, Battlecry, Deathrattle or Secret)

The "summoning catchup step" allows these minions, per minion summoned then in order of play, to check again for their condition now being satisfied, and to trigger if so. Auras/enchantments also seem to recalculate just before the "summoning catchup step".

Note that Cobalt Guardian and Murloc Tidecaller do not observe the "Summoning catchup step".

This is explored further in

http://hearthstone.gamepedia.com/Advanced_rulebook#Summoning_catchup_step

**Comment by jleclanche** [comment]
Design issue, not our call.
