### ISSUE TITLE
Rumble Run: Bouncing Blade causes an animation hang when doubled by Pirate's Mark

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1085]
https://us.battle.net/forums/en/hearthstone/topic/20770606978
>Bug with (double spell spirit) and bouncing blade
When you have the spirit “play the secret again same target“ and you play bouncing blade and you kill a minion besides your spirit the game bugs out and you can’t do anything anymore the killed minnion remains on the field with 0 health and you can’t do anything.

https://us.battle.net/forums/en/hearthstone/topic/20770697004
>When the card Bouncing Blade is used and kills the Pirate's Mark Shrine with the first spell, the game does not know what to do. The first time it happened the game soft locked without performing the second spell. The second time, it resulted in the Shrine to go to negative health but not dying. It even allowed me to use the second spell and pass the turn. However, the computer does nothing afterwards.
If anyone would like I can provide my screenshots to show what I am talking about.
It's a relatively small bug but it has happened twice so far and ended both runs.

https://us.battle.net/forums/en/hearthstone/topic/20770646973
>Game got stuck when I cast bouncing blade with pirates mark active

>I was just about to post the same: did your bouncing blade kill your shrine?
Also, I can't even concede the game after this!

https://us.battle.net/forums/en/hearthstone/topic/20770616990
>AI casts Bouncing Blade. When it finishes resolving the AI never continues playing or passes the turn.

It's not clear from these reports if any circumstances are needed beyond apparently being doubled by Pirate's Mark. My guess is that the second one is cast while a minion is already mortally wounded and the animation is unprepared to be finished so soon, in which case this could theoretically be replicated outside of Rumble Run with Violet Teacher/Illidan + Knife Juggler.

**Comment by troggnostupidhs** [comment]
https://news.blizzard.com/en-us/hearthstone/22882146/hearthstone-update-february-5

> Fixed an instability issue that could occur when playing Bouncing Blade while the Pirate’s Mark Shrine is in play.
