### ISSUE TITLE
Corrupted Blood is affected by Spell Damage

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1087]
Hakkar the Soul Flayer's Corrupted Blood spell is affected by Spell Damage, unlike all other "Cast when drawn" spells. They're usually tagged ImmuneToSpellpower, but Corrupted Blood is not. This inconsistency is likely an oversight.

https://www.reddit.com/r/hearthstone/comments/a7bvp8/never_even_considered_that_his_spell_damage_would/

>[Corrupted Blood][TRL_541t][50455]
[1 Mana, Spell]
Casts When Drawn
Take 3 damage. After you draw, shuffle two copies of this into your deck.
COST=1, CARD_SET=1129, CLASS=12, CARDTYPE=5, TOPDECK=1

For comparison:
>[Ancient Curse][LOE_110t][9082]
[4 Mana, Spell]
Casts When Drawn
You take 7 damage.
COST=4, CARD_SET=20, CLASS=12, CARDTYPE=5, **ImmuneToSpellpower=1**, TOPDECK=1

**Comment by troggnostupidhs** [comment]
https://news.blizzard.com/en-us/hearthstone/22882146/hearthstone-update-february-5

> Corrupted Blood no longer benefits from Spell Damage.
