### ISSUE TITLE
Beast Within and Mass Hysteria don't consume a minion's attack chance

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#1092]
Here is an example of Mass Hysteria: https://www.bilibili.com/video/av37549380 (7:55 to 8:20)
And if you Beast Within your haven't-attacked Giant Sand Worm to kill an enemy minion, he may attack enemy hero twice .

As for other "Forced Attack" cards, they all consume attack chance.
1. Kobold Barbarian always auto-attacks at the start of turn, and you can never control him to attack unless he is silenced / has windfury.
2. If you attack enemy hero with Supercollider but are misdirected to an haven't-attacked friendly minion (having an adjacent minion), his attack chance is consumed and cannot attack this turn.
3. If you play a minion to trigger Dred and then Shadow Madness Dred. He cannot attack.
(Note: Controller change doesn't reset attack chance. For example if your Wolfrider attacks enemy hero and you Treachery + Mind Control him, he cannot attack again.)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/a0xwcc/new_card_the_beast_within/eal7ukv/

> Peter confirmed on the Omnistone stream that
> 
> * You can use it on a minion you just played
> * It doesn't take away the minions ability to attack that turn if it was able to before. (Doesn't use it's attack)

--- 

> Well that's a pretty big inconsistency with how automatic attacks work in hearthstone (for example Swamp King Dredd when stolen with Potion of Madness or Shadow Madness)

---

> This thread was about something similar
> https://www.reddit.com/r/hearthstone/comments/9oyrn8/learned_of_a_new_interaction/
>

**Comment by troggnostupidhs** [comment]
As far as what is known, I believe these are all intentional. Even though it is all inconsistent.

**Comment by troggnostupidhs** [comment]
Warrior deck
AAEBAQcAD/sBnAK0ApED/weCCLnDAvbPAvHTAqbwApfzApzzArX2AoP7Ao77AgA=

Hunter deck
AAEBAR8C1hGWwwIOjQH7AZwCtAKTBIEFiAW5BpcImA2JwwKm8ALMiQPUiwMA

Priest deck
AAEBAa0GAA+zAfsBnAK0ApME5QSIBbkG8gy3bNHBAuLKAqbwAqH+ApeHAwA=

**Comment by troggnostupidhs** [comment]
All these cards trigger Festeroot Hulk

Mass Hysteria. I didn't time the photo correctly, but the attack did go to 5.
![hearthstone screenshot 01-05-19 16 24 52](https://user-images.githubusercontent.com/22508641/50729386-ad828980-1106-11e9-9d7c-d35febf9697c.png)

Supercollider
![hearthstone screenshot 01-05-19 16 34 23](https://user-images.githubusercontent.com/22508641/50729456-d6efe500-1107-11e9-9df0-b30cd11d792b.png)

The Beast Within
![hearthstone screenshot 01-05-19 16 48 52](https://user-images.githubusercontent.com/22508641/50729548-e2dca680-1109-11e9-9373-8a10f074e1cb.png)

Swamp King Dredd (same Festeroot on board from The Beast Within)
![hearthstone screenshot 01-05-19 16 50 44](https://user-images.githubusercontent.com/22508641/50729567-3cdd6c00-110a-11e9-8f2a-2d1534d097e0.png)

**Comment by troggnostupidhs** [comment]
After a long discussion on Discord, I think that this issue will be closed. The behavior for Beast Within and Mass Hysteria is intended as the new behavior. I don't think there is any official comments on Supercollider and Swamp King Dred, but they worked consistently for the old behavior. The two behaviors are not consistent, but seem to be intended. So, at least for now, this issue will be closed because there is not enough evidence that it is a bug.
