### ISSUE TITLE
If you disenchant Whizbang, you can fill the now invalid deck with normal cards but still keep the Whizbang portrait

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1096]
https://www.reddit.com/r/hearthstone/comments/aeprq1/had_a_regular_whizbang_made_a_deck_using_warrior/

>Had a regular Whizbang, made a deck using Warrior, disenchanted the Whizbang to make a Golden Whizbang (to get Golden Heroes, Cards & Coin, i.e. Cheap Kibler). Turns out my Warrior Whizbang deck can be used to make a regular deck, but the portrait stays as Whizbang and doesn't turn back to Garrosh!

>It's still Whizbang in the Play window where you choose your deck, however Garrosh returns in game.

**Comment by Jetz72** [comment]
Adding Account label (and updating milestone) because:
https://www.reddit.com/r/hearthstone/comments/aeprq1/had_a_regular_whizbang_made_a_deck_using_warrior/edtwror/
>Did it persist when you restarted the game?

>Yes.
>Update: Been over a month. Still Whizbang Warrior.

**Comment by troggnostupidhs** [comment]
Does not occur in the current version.

![Hearthstone Screenshot 03-19-19 20 32 21](https://user-images.githubusercontent.com/22508641/54650769-63167500-4a86-11e9-8fcf-1e53b2ef182e.png)

![Hearthstone Screenshot 03-19-19 20 32 40](https://user-images.githubusercontent.com/22508641/54650776-66a9fc00-4a86-11e9-8d65-88c147b1487d.png)

**Comment by Jetz72** [comment]
The fix for #1176 seems to have caused this for some players. 
https://www.reddit.com/r/hearthstone/comments/bs1j55/i_opened_zayle_shadow_cloak_before_it_was/
>Also I got to keep the unique deck slot image and was able to build a mage deck in it. here is what it looks like
>![](https://i.imgur.com/7lmvS9p.jpg)

Not sure if this should be reopened. The issue can apparently no longer be caused by players but the effects still linger for those who want to keep the deck. We probably won't ever find out if and when that part does get fixed, and we can't test for it.
