### ISSUE TITLE
Mistcaller does not buff cards summoned directly from the deck

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#110]
Screenshot:
https://www.reddit.com/r/hearthstone/comments/3i99ps/the_mistcaller_bug/

Other:

https://www.reddit.com/r/hearthstone/comments/3i9416/cards_pulled_from_deathlord_dont_receive_the/
https://www.reddit.com/r/hearthstone/comments/3i91yk/mistcaller_bug/
https://www.reddit.com/r/hearthstone/comments/3i8qy5/bug_minions_summoned_by_deathlord_do_not_have/
https://www.reddit.com/r/hearthstone/comments/3i9ky3/mistcaller_bug/
https://www.reddit.com/r/hearthstone/comments/3i9lao/bug_or_misleading_text_with_the_mistcaller/
https://www.reddit.com/r/hearthstone/comments/3i9ss2/bug_mistcaller_does_not_buff_minions_summoned_by/
http://us.battle.net/hearthstone/en/forum/topic/18695102316
http://us.battle.net/hearthstone/en/forum/topic/18695102328

(I'd like to see logs of Mistcaller being played and how/where the enchantments are applied. I'd also like to see tested Alarm-o-Bot on a buffed Bolvar Fordragon to see if Bolvar keeps his enchantment.)

-=-

DisguisedToast has made a video that illuminates why this bug might exist. In particular, Mistcaller seems to be coded as "Give all minions in your hand +1/+1. then create an Enchantment attached to your Player that says 'when you draw a minion, give it +1/+1'".

[Hearthstone Experiments - Episode 2 - Mistcaller (Interesting Interactions)](https://www.youtube.com/watch?v=RB85s2S0-lM)

-=-

However, here Rolkyr says the developers are aware and it is working as intended:

http://us.battle.net/hearthstone/en/forum/topic/18704213104?page=1#3

Therefore this is not a bug, but the intended behaviour of Mistcaller.

**Comment by jleclanche** [comment]
Despite Rolkyr's comment, I think this is a bug. I'd wait for a more official word on it.

**Comment by NightKev** [comment]
[He made another post in that thread](http://us.battle.net/hearthstone/en/forum/topic/18704213104?page=1#13):
>Everyone,

>I understand what everyone is saying. I have discussed this with Dev and **currently**, this is not a bug. We are aware the wording can be misleading. I will happily continue to relay concerns over this. As always, I encourage anyone who feels strongly about this to deliver it as feedback in the General Forums so the proper eyes can see the level of concern.

>\- Rolkyr

**Comment by Patashu** [comment]
Since Rolkyr has spoken with a dev and this is considered to not be a bug, I'll close this.

**Comment by Patashu** [comment]
This MIGHT be changed in the future:

**Comment by jleclanche** [comment]
hmrph, reopening then.

**Comment by NightKev** [comment]
Hm, well it's not technically a bug since they implemented it this way on purpose, but they do want to change it... ehhhhh

**Comment by jleclanche** [comment]
It's an acknowledged design bug. good enough imo

**Comment by culinko** [comment]
Same happens with force played minions put into play by Varian Wrynn.

**Comment by Patashu** [comment]
Should also happen with Desert Camel, also being a deck->play force play mechanic.

As well as the Pile On! Hero Power.

**Comment by Patashu** [comment]
Could be related: In the new Tavern Brawl (Decks Assemble!), Mistcaller doesn't work:

https://www.reddit.com/r/hearthstone/comments/3v771y/psa_the_mistcaller_battlecry_has_no_effect_in_the/

**Comment by Patashu** [comment]
Confirmed in 4.1

http://us.battle.net/hearthstone/en/forum/topic/20043055348

**Comment by Patashu** [comment]
Confirmed in 4.2

https://www.reddit.com/r/hearthstone/comments/4akuco/mistcaller_varian_bug/

**Comment by Patashu** [comment]
Oh, I didn't realize this was still tracked. Confirmed in 5.0 by a lot of people

**Comment by Patashu** [comment]
Confirmed in 6.0

https://www.reddit.com/r/hearthstone/comments/51sqgk/til_that_mistcaller_doesnt_boost_the_cards_in/

**Comment by Patashu** [comment]
Apparently fixed now: http://imgur.com/a/ZpD0c

**Comment by NightKev** [comment]
Whoa, that's quite the fix.
