### ISSUE TITLE
iOS: Using the Good Cheer card back on iphone devices can cause instability

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1102]
https://us.battle.net/forums/en/hearthstone/topic/20763956467#post-9

> We’re currently working to resolve an issue where using the Good Cheer card back on iphone devices can cause instability. In the meantime, affected players can switch to a different card back via the desktop app to play.

**Comment by czhihong** [comment]
https://twitter.com/BlizzardCS/status/1094015947516637184

> [#Hearthstone] This issue has been resolved. Thank you for your patience and may the cards be ever in your favor.
