### ISSUE TITLE
Astromancer summons its minion on the far right, instead of adjacent to itself

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1105]
(Astromancer - Battlecry: Summon a random minion with Cost equal to your hand size.)

https://us.battle.net/forums/en/hearthstone/topic/20770847126
>Astromancer doesn't summon the minion right next to it, but on the outer right - other minions that summon, work differently. 

Tested and confirmed:
![hearthstone screenshot 02-13-19 09 31 15](https://user-images.githubusercontent.com/8607832/52719133-00a3f380-2f73-11e9-9c07-3b8c37acc9c5.png)
![hearthstone screenshot 02-13-19 09 31 19](https://user-images.githubusercontent.com/8607832/52719139-039ee400-2f73-11e9-8fc3-d4df5069a4f9.png)

I can't see any reason this would be deliberate.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22911364

> Astromancer now correctly summons a minion immediately next to her instead of the far right of the board.
