### ISSUE TITLE
The Lich King: Lich King no longer emotes correctly

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1106]
https://us.battle.net/forums/en/hearthstone/topic/20771137297

>When I was fighting the lich king as mage and cast counterspell, he did not say what he was support to which was (How did that get past QA?). Also the trapped souls are suppost to say things on his turn, but their not anymore.

> 
> I just confirmed it is also happening on PC as well. We got a bug in for tracking now.
> 
> Thanks for the report!

**Comment by Jetz72** [comment]
This appears to have been fixed for a long time. Can confirm the Trapped Souls emote as usual. Seen a few other card reactions of his too.
