### ISSUE TITLE
Rumble Run: Treasure From Below only steals minions on the turn it resurrects, instead of any card

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1107]
Title updated now that cause is known; original post preserved here:

"Treasure From Below sometimes loses the ability to trigger as it resurrects"

Treasure From Below: "Shrine. At the start of your turn, steal a card from your opponent's deck. It costs (2) less."
This Shrine is unique in having a Start of Turn effect, which is able to trigger the same turn it revives. However, sometimes, this ability does not work, and it simply revives without stealing anything.

https://us.battle.net/forums/en/hearthstone/topic/20771017213
>https://hsreplay.net/replay/dQXceB2KBbJpHgxTz6RDBd#turn=7a

The replay showcases two shrines that stop behaving correctly in the middle of the game.
Turns of note:
- Turn 1: Original Shrine is duplicated by Passive. Before the natural Draw, both the Original Shrine and the Copy Shrine trigger correctly, stealing two cards.
- Turns 2 and 3: Both Shrines trigger correctly.
- Turn 3b: Original Shrine killed.
- Turn 4: Copy Shrine triggers correctly. Is killed by opponent on turn 4b.
- Turn 6: Original Shrine revives and correctly steals a card. Is killed by opponent on turn 6b.
- Turn 7: (linked) Copy Shrine revives. No card is stolen. Opponent still has cards in deck, player has room in hand, no obvious effects to prevent the trigger. Is killed by opponent on turn 7b.
- Turn 9: Original Shrine revives, no card is stolen. It appears to have lost this ability despite working correctly on turn 6. Is killed by opponent on turn 9b.
- Turn 10: Copy revives, no steal, killed on 10b.
- Turn 12: Original revives, no steal.
- Turn 13: Original (not dead this time) steals a card, indicating that it has not completely lost the ability to steal, only the ability to revive and steal together. Copy revives without stealing.
- Nothing remarkable from then on.

Not seeing anything special between turns 6 and 7, where the behavior seemed to start.

Many more reports exist of this bug: 
https://us.battle.net/forums/en/hearthstone/topic/20770697018
https://www.reddit.com/r/hearthstone/comments/a64dz4/bug_treasure_from_below_activation_inconsistency/
https://www.reddit.com/r/hearthstone/comments/a63mst/bug_treasure_from_below_rumble_run/

Some screenshots indicate that the shrine does not need to be copied. Some people report that the issue started after copying it, though that may be coincidental. Many reports tend to take place in the later rounds of the run, suggesting that Passives can cause it, but this may simply be a correlation with the longer and tougher games providing more chances for the bug to occur.

**Comment by Jetz72** [comment]
One theory that just occurred to me: Maybe while the normal "steal" trigger is coded to take any card, the alternate "revive+steal" trigger will only take minions. Fits the replay above, and all the correlations (more shrines to steal more, late run encounters that go on longer, particularly Zul'jin who has few minions).

**Comment by FireSiku** [comment]
Here are some additional replays of mine picked at random that correlates with this theory, on the turn the shrine comes back, it always steals a minion or nothing at all:
https://hsreplay.net/replay/bGqoAEDvv58BeGLbc6D6cb
https://hsreplay.net/replay/hYFam2xsCUjwePBuFmUbT3
https://hsreplay.net/replay/XmfuRWW8VxTdJJ2YEGvKSi

It is particularly obvious in this Zuljin replay thanks to having two shrines: https://hsreplay.net/replay/JeFvydEmV6bTNtc8oahmjc
On Turn 6, enemy deck has 16 spells and 3 minions. Both shrines stole a minion. The odds are pretty slim.
On Turn 9, enemy deck has 13 spells and 1 minion. First shrine steals a minion, second shrine stole nothing.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20771017213#post-10

> Thanks for the report!
> 
> Jetz you are indeed correct. I tested it out myself and confirmed what you are seeing. The shrine revives and does not steal if there are no minions in the deck. This also explains how most of the reports are showing two shrines, having both shrines would quickly remove all of the minion from the deck. The good news is that the turn it revived on, it will start stealing any card from the deck again.
> 
> We'll have our team look into this and hopefully address this in the next update.

**Comment by Jetz72** [comment]
Just observed the Shrine steal a spell (Call of the Void) on the turn it revived, so this is evidently fixed.

https://hsreplay.net/replay/FXTHDhts7zYq6PocxaL2Cf#turn=4a
