### ISSUE TITLE
Sense Demons can draw Demonfuse as one of its two cards

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#111]
https://www.reddit.com/r/hearthstone/comments/3i9261/psa_demonfuse_can_search_sense_demons/
https://www.reddit.com/r/hearthstone/comments/3i946q/demonfuse_just_came_out_of_sense_demons/
https://www.reddit.com/r/hearthstone/comments/3i9t4b/bug_sense_demons_can_draw_demon_cards_too/
This is because Demonfuse erroneously has the Demon racial tag, which is meant to only be on minions (and Lord Jaraxxus the Hero).

https://twitter.com/xhelli0n/status/638133443973521409 Confirmed as a bug that will be fixed by Yong Woo here.

**Comment by jleclanche** [comment]
:beers:

**Comment by NightKev** [comment]
Thanks, Blizzard. Some interesting testing to do: https://www.reddit.com/r/hearthstone/comments/3i9261/psa_demonfuse_can_search_sense_demons/cueu7re

**Comment by jleclanche** [comment]
Voidcaller doesn't summon it.

Bane of Doom would definitely be limited to demons, otherwise it'd summon the Jaraxxus hero (although, it's not collectible...)

**Comment by jleclanche** [comment]
Fixed in 3.1.0.10357
