### ISSUE TITLE
Rumble Run: Pirate's Mark causes each choice of Branching Paths to be cast twice, in addition to the spell itself

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1111]
Pirate's Mark - "Shrine. After you cast a spell, cast it again (on the same target)."

When a choice is made for Branching Paths, the effects of the choice are doubled.

![hearthstone screenshot 02-26-19 18 28 43](https://user-images.githubusercontent.com/8607832/53459321-5793d900-3a07-11e9-84c8-3085bdbf95b2.png)
![hearthstone screenshot 02-26-19 18 28 40](https://user-images.githubusercontent.com/8607832/53459324-595d9c80-3a07-11e9-800e-2be3dfb47086.png)

https://hsreplay.net/replay/woVpVCjn8Jpskg9FP28g3J#turn=8b

These choice cards are generally not considered spells for the purposes of triggered effects.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22911364

> Choices from Branching Paths will no longer trigger twice with Pirate's Mark in play.
