### ISSUE TITLE
General instability with iOS client following 13.4, particularly for those who pre-ordered the expansion

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1115]
https://www.reddit.com/r/hearthstone/comments/b1h8qa/bug_clicking_on_the_card_of_shadows_cardback/
>Clicking on the Card of Shadows cardback consistently crashes HS on ios devices.

>It crashes In ranked at a end of the match, trying to edit or make a deck/change cosmetics, disenchanting cards, entering the solo adventure menu, messaging a friend, all forces the game to crash. 

>The app didn't crash when I clicked on "Card of Shadows" or any other card backs. However, the app crashes when trying to switch from page 2 to 3 in the card back section (happened twice).

>Picking any cardback on iOS crashes the game, creating a deck crashes the game, finishing a match crashes the game. They might of fixed the game for Android users but they made iOS unplayable.

>On my iPad, I can't even get to that page. I get to page 10 of my card back, but when I switch to page 11, the game just crashes.

https://us.forums.blizzard.com/en/hearthstone/t/game-cant-continue-after-each-game-ios-client-crashes-after-prepurchasing-the-new-expansion/1021
>On IOS platforms, my game crashes all the time with my account. My friend’s account worked just fine. I believe there must be some sort of bug for players that prepurchased the packs before the maintenance as I have read several posts on the same issues in technical support.

>My iPad crashes after every game with the new update and I didn’t pre-order anything.

https://www.reddit.com/r/hearthstone/comments/b1evkz/the_new_update_has_broken_hearthstone_on_ios/
>I can’t even make a deck without crashing. I’m crashing after every game. And lag is so bad I’m going to rope just trying to play my cards. 

>Using iPhone X no issues so far

>Works great on iphone 8

>Same issue on my iPad. Try to open a practice game, crash. Playing Witchwood PvE and after win or defeat, crash. [...] did you purchase the pre-release bundle? I did, so in the absence of a definitive issue with the client version or operating system, maybe that is the common thread?

>Adding my experience on iPad mini 2. I deleted and installed the app as I always do for an update. Since then the game has crashed after every game. Also crashed a few times before and mid game.
The collection menu and making a deck feature is very slow. Going into play mode is also much slower. 

>Nothing wrong for me. Using the ipad pro 10.5. No crashes under any circumstances whatsoever.

>Works great on iPhone 6S and iPad 4. No problems whatsoever.

https://www.reddit.com/r/hearthstone/comments/b1dp8w/new_patch_breaks_ios_eu/
>Since downloading the new patch about 15 minutes ago, the HS app on my iPad has crashed 11 times. Thrice it's managed to connect to a game, and then crash out, 'unable to reconnect'; the rest of the time it just crashes immediately upon hitting 'Play'.

https://us.forums.blizzard.com/en/hearthstone/t/game-crashing-on-iphone-and-mac-laptop/1024
>Just bought the new expansion bundle, and now every time I try to play on my iPhone, the game crashes at the title screen. I even re-installed the app, but it’s still crashing. Almost as bad, my game’s been crashing after every match when I play on my [iOS] laptop.

https://us.forums.blizzard.com/en/hearthstone/t/ipad-crashing-a-lot-since-update/1001
>I have an older iPad Air, but it is running the latest version of iOS (12.1.4.) I also just updated the game client from the app store. I am playing some solo adventure content and the game is crashing after I finish each level in the Witchwood’s Monster Hunt. If I go into practice mode, when I select the opponent, the game just crashes. The game freezes for a second, it doesn’t even show the loading bar, and then id suddenly quits back to my homescreen of my iPad.

>Same thing everything just crash tested with IPad mini 2 and iPhone 6.

https://us.forums.blizzard.com/en/hearthstone/t/2-platforms-messed-up-after-3-14-update/1017
>iOS: game just minimizes and restarts upon opening [...] I did pre-order both bundles on launch-before the shop close, maybe it could have affected my account in the overall.

Seems like something with the pre-order is causing issues with the game on iOS. Could be an issue with certain visual effects that the card back also utilizes.

**Comment by troggnostupidhs** [comment]
More info from the reddit post

> Just checked out the Hs Bug report, I havent preorder the upcoming expansion yet (kinda due to the fact I can’t navigate the store without crashing haha) so I don’t think it has anything to do with the preorder.. Maybe they accidentally deleted some assists on accident when they were working on reducing the file size?

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/b1u470/hearthstone_crashing_on_ipad_after_update_more/

> Up until last night I’ve always been able to play hearthstone on my iPad just fine but now I can’t even edit decks without it crashing after I start choosing cards and whenever I’m in a match the game crashes as soon as it’s over with. Like right after the rank symbol goes away. It’s an older iPad but none of the updates ever did this before and I can play it fine on my phone. Is anyone else having an issue like this on a tablet?

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/constant-crashes-on-ios/1079/19

> Hi there friends,
> 
> I am sorry to hear about all the users on iOS devices crashing. We are starting to gather information on this now. I would ask any one who is crashing on an iOS device post back here with the following:
> 
> The Device type / model. ( Phones, iphone 7 )
> If you have tried to reinstall the game.
> If this happens on Mobile, Wifi, or both.
> What iOS version 2 you are on.
> This is not for users who are crashing on multiple devices after a match, this is for users who are crashing on startup or soon after on iOS devices.
> 
> /Nathardrick

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/constant-crashes-on-ios/1079/254

> Hey everyone, thanks for sharing your device information for us to investigate this issue! We’re currently working on a fix for this. We’ll follow up when we have more information about when that will happen.

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/constant-crashes-on-ios/1079/439

> Hey all,
> 
> We pushed a fix for this about 9 days ago and it should be resolved. If you continue to have issues I would recommend reinstalling the game client on your iOS device. Beyond that, you’ll want to create your own thread.

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/constant-crashes-on-ios/1079/450

> 
> Hey, everyone!
> 
> This issue has been resolved weeks ago and was related to crashing. It appears everyone posting after the fix has been disconnecting and not crashing.
> 
> If you happen to have disconnection issues, we would recommend making your own new thread with the details, including your ISP, so we can see if others experiencing the same issue.
> 
> We will be locking this thread as the crashing issue for iOS has been resolved.
> 
> Thanks!
