### ISSUE TITLE
Treant card art is missing on mobile

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1118]
Tested this on PC and it did not happen.

At least one comment mentions it happening on Android.

https://www.reddit.com/r/hearthstone/comments/b1miic/treants_from_landscaping_and_fon_visual_bug/

![image](https://user-images.githubusercontent.com/22508641/54470750-d5840e00-4783-11e9-9a4a-f3a8b3a94b07.png)

https://www.reddit.com/r/hearthstone/comments/b1ihe4/i_love_the_new_treant_art_great_job_from_the_team/

![image](https://user-images.githubusercontent.com/22508641/54470754-dfa60c80-4783-11e9-9dfd-47d9f6133041.png)

https://www.reddit.com/r/hearthstone/comments/b1ipua/light_infused_treants/

![image](https://user-images.githubusercontent.com/22508641/54470761-ea60a180-4783-11e9-9eee-29b2b2696783.png)

https://www.reddit.com/r/hearthstone/comments/b1lk0l/my_treant_sure_looks_cool/

https://www.reddit.com/r/hearthstone/comments/b18pgo/treants_are_broken_again/

https://www.reddit.com/r/hearthstone/comments/b18pgo/treants_are_broken_again/

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/b1sjtq/looks_like_the_treant_has_acended/

https://www.reddit.com/r/hearthstone/comments/b1s67n/bug_treants_from_druids_5mana_spell_force_of/

https://www.reddit.com/r/hearthstone/comments/b1oyid/landscaping_treants_going_full_squidward_mode/

Cool effect on the golden card
https://www.reddit.com/r/hearthstone/comments/b1ptwm/really_like_this_new_golden_treant/

![image](https://user-images.githubusercontent.com/22508641/54478508-545f6200-47e9-11e9-9bf7-3e1acba7dd14.png)

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/known-issues-list-2019-updated-april-3rd/64/6

> Treant minion is missing its portrait art.

**Comment by Jetz72** [comment]
https://www.reddit.com/r/hearthstone/comments/b9fefw/hearthstone_update_april_4/ek4t8jj/?context=1
>We've trained those tricky treants to freeze in their frames, so they should be much less mobile when playing on mobile devices.
In other words: This should be fixed with today's update but unfortunately didn't make it into the patch notes.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/bk38fc/ah_yes_the_invisible_treant/

![image](https://user-images.githubusercontent.com/22508641/57147734-3dbf9b00-6d96-11e9-9a1c-e77646e31274.png)
