### ISSUE TITLE
Mobile spectating - it's possible to spectate 'the other person' and have both hands be hidden from you

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#112]
https://www.reddit.com/r/hearthstone/comments/3i9d22/a_new_bug_i_discovered_for_mobile_spectating/

**Comment by jleclanche** [comment]
Without a way to reproduce this isn't very useful.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3ussaz/question_spectate_bug/ Is this related?

**Comment by jleclanche** [comment]
Closing, no repro in 2 major patches.
