### ISSUE TITLE
Skipping the returning player quest chain prevents daily quests from being distributed

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1120]
https://us.forums.blizzard.com/en/hearthstone/t/no-daily-quests-after-skip-legendary-quest-ready-for-action/1012
>When I login I have first quest “Return of the Hero” - need to win 3 challangers, I am retire this, then game give me second quest “Ready for Action”, this quest I reroll, because it was interesting for me reroll legendary quest and this quest “Ready for Action” dissapear and no quests in my quest log, than I wait next day and still no quest :frowning:
quest log is empty
>https://youtu.be/h6BaL1M09Jc

>I also have the same problem with not receiving the daily quests after skipping this quest.

Daily quests are supposedly disabled while a player has these quests incomplete, but players are reporting that rerolling does not reenable them.

**Comment by troggnostupidhs** [comment]
Here is the statement about the quests that need to be completed

> Can you check your quest log and see if you have any of these three quests? Completing all of them will unlock the daily quest.
> 
> (Returning Players) Return of the Hero, Ready for Action and Back in the Game!

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/no-daily-quests-after-skip-legendary-quest-ready-for-action/1012/7

> Thanks for the report everyone, we are investigating into this issue.

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/no-daily-quests-after-skip-legendary-quest-ready-for-action/1012/14

> The issue should be hotfixed now. For anyone that chose to the abandon the quest, the Ready for Action quest is given back to you.
> 
> If you are still not receiving any daily quest, please confirm that you do not have any of the three quests below first:
> 
>Return of the Hero
>Ready for Action
>Back in the Game!
> 
> Otherwise go ahead and contact our customer support here:
> https://www.battle.net/support/en/help/product/hearthstone/1398/1422/channels
