### ISSUE TITLE
Puzzle Lab: Poisonmaster Pollark has 30 health

### ISSUE THREAD

**Issue by mandaputtra** [HearthSim/hs-bugs#1122]
I think the hero enemy health its too much ! [image](https://ibb.co/PYjnfbh)

![image](https://user-images.githubusercontent.com/22508641/55039193-a4180780-4ff9-11e9-91d4-1f369c5758b5.png)

**Comment by mandaputtra** [comment]
was made

**Comment by bbbbbbbbba** [comment]
It is interesting that apparently this puzzle used to have the enemy hero at 9 or 11 health (https://youtu.be/kCA5skcfZaA?t=125). I think the (slight spoiler) 32 HP solution is obviously the intended one from the beginning...

**Comment by mandaputtra** [comment]
yeah i realy stuck at first try... 😂 damn so im cheating to look at guides
