### ISSUE TITLE
Zerek's and Test Subject's Deathrattles will not trigger on Da Undatakah

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1126]
https://us.forums.blizzard.com/en/hearthstone/t/undatakah-zerek-bug/1944
>If Undatakah grabs Zereks deathrattle, casting a spell on Undatakah does nothing.

>Undatakah only gains zerek. Cast spells on undatakah let it die and it summons nothing.
I cast seance, power word shield, and tons of other spells. Nothing works
Board is not full. I eliminated everything and every test is the same result. Undatakah, even with a buff saying he is storing a zerek does nothing

>Here’s a video of this issue and the test subject one:
clips.twitch.tv/BillowingMildWaspAMPTropPunch

[Clip shows Undatakah being played, gaining the Deathrattles: Test Subject, Zerek, Zerek. A banana is cast on it. The following turn, Shadow Word: Death is cast on it. No spells are returned, nothing is summoned.]

https://us.forums.blizzard.com/en/hearthstone/t/da-undatakah-mastercloner-zerek-interaction
>Since the latest patch Mastercloner Zereks deathrattle will no longer work if he gets copied by Undatakah (obviously with a spell casted on Undatakah). Earlier this interaction did work as intended (at least as far as I can judge)

**Comment by Jetz72** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/undatakah-zerek-bug/1944/6
>FYI - Undatakah Zerek now resummons…Undatakahs instead of how it used to work (resummoned Zerek)
So I guess it’s fixed? The old way was probably not intended.

If true, addresses this and #1073. Would be a good idea to check Test Subject.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/a364i3/weird_interaction_of_da_undatakah_with_zerek/ 

I think I had this in the wrong ticket

**Comment by Jetz72** [comment]
Confirmed fixed:
![Hearthstone Screenshot 04-13-19 22 43 10](https://user-images.githubusercontent.com/8607832/56087707-4a5b6e00-5e3e-11e9-8ef8-e65624f8b3cd.png)
![Hearthstone Screenshot 04-13-19 22 43 37](https://user-images.githubusercontent.com/8607832/56087708-4c253180-5e3e-11e9-905a-5f51090f4562.png)
![Hearthstone Screenshot 04-13-19 22 43 51](https://user-images.githubusercontent.com/8607832/56087744-12085f80-5e3f-11e9-8f0d-fa858807a75c.png)

**Comment by troggnostupidhs** [comment]
Deck
AAEBAaCsAwLL+AKLigMOlwKcAvgC5QS5Bo0PiBSWFNLBAqbwAtD+AvGAA+qMA8+dAwA=
