### ISSUE TITLE
Rumble Run: Freezing Trap can kill a Shrine forever if something else also triggers

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1138]
https://us.forums.blizzard.com/en/hearthstone/t/bug-in-rastackhan-s-dangeon/2539
>Look at the replay on 3rd turn:
https://hsreplay.net/replay/Pehur6GdaH9CSKwttHpDQT
>
>On the third turn i have a freezing trap and a snake trap on my face. Opponent-bot plays cruel taskmaster on the horn of the Akalee and it`s try to hit my trap of Halazee but can’t because of freezing trap. And then horn of Akalee just disappears from board forever. You can see it on the replay next turns.

https://us.forums.blizzard.com/en/hearthstone/t/i-killed-the-enemys-shrine-during-rumble/2451
>His shrine attacked my hero. The freezing trap animation went off and I was terrified that he was about to get a second shrine in his hand while keeping the one on the board because some avatar head popped up on my screen telling me something about how you can’t bounce or otherwise get rid of shrines. Well, I didn’t see a copy go to his hand, but my second trap–explosive trap–went off next and down went his shrine; no placeholder minion portrait, no 3-turn counter, just gone. Simple as that. 

https://us.forums.blizzard.com/en/hearthstone/t/i-permanently-destroyed-war-master-voones-shrine-in-rumble-run/2456
>Playing secret hunter. Unfortunately I did not notice right away and the sequence of events was somewhat confusing. Voone triggered my “when an enemy minion attacks, return it to their hand” secret with his shrine, which should have destroyed it normally. But multiple secrets were triggered at the same time and the board became chaotic. He had some other card in play that summoned a random minion which ended up being The Darkness (unfortunately for him, he did not get the candles so it’s sitting there permanently like a dead shrine itself). His shrine did not come back and I feel bad for him… 

Might be informative to compare a log of this bug to one of a Shrine normally resisting a bounce effect

**Comment by Jetz72** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/shrines-just-disappeared/2674
>So I was running the rumble run. And during the 8th fight against Zul’Jin, my shrines just disappears. >.< You can see what happened in the video.
>https://www.youtube.com/watch?v=TiDMgHY8Cfc

No extra secret triggers, but an Eaglehorn Bow does. Not 100% sure a trigger is required but reports so far seem like they have one.

**Comment by hamidnazari** [comment]
I did too send Krag'wa's Lure to another dimension! Secret triggered, Shrine death animation kicked off, and then the Shrine disappeared and never got replayed by AI.

![2019-04-16 13 44 54](https://user-images.githubusercontent.com/544028/56182100-d7c3db80-6053-11e9-97b2-930a10d407c7.png)
![2019-04-16 13 44 57](https://user-images.githubusercontent.com/544028/56182101-d7c3db80-6053-11e9-9885-e345c9d73343.png)

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22933721
> [Rumble Run] Fixed an issue where Freezing Trap would destroy the enemy's shrine without leaving the dormant shrine.
