### ISSUE TITLE
Witchwood cards that were moved to the Hall of Fame can still be found in Witchwood packs

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1139]
https://www.reddit.com/r/hearthstone/comments/bbari7/half_an_hour_after_expansion_release_i_opened_my/
>![](https://i.redd.it/7n70cvj9x9r21.jpg)

Expansion stamp shows that the card is in the Hall of Fame now. Others have also reported this:
https://www.reddit.com/r/hearthstone/comments/bbar9k/so_i_just_pulled_a_glitter_moth_in_my_free/
>So i just pulled a glitter moth in my free witchwood pack.

https://www.reddit.com/r/hearthstone/comments/bbarq1/play_25_cards_quest_gave_me_a_ww_packcan_we_still/
>![](https://i.redd.it/2j8b5wvcx9r21.jpg)

Classic cards moved to HoF don't show up in packs, so this behavior is inconsistent.

**Comment by Jetz72** [comment]
One report alleges that this can also lead to duplicate copies of Genn and Baku being given out.

https://www.reddit.com/r/hearthstone/comments/bbawa4/bug_received_duplicate_legendary_from_ww_pack/
>As the title implies, I got a second Genn Greymane from the WW pack they gave from the quest. This shouldn't have happened as I don't have all WW legendaries and did not dust my original Genn. Just want to give anyone a heads up if their legendary timer is close, but this may just apply to the HoF cards (Genn and Baku) as their tags might have changed, but am not sure.

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/still-hall-of-fame-cards-in-witchwood-packs/2747/6

> Hey everyone,
> 
> Thanks for the report, we are looking into this one right now.

**Comment by troggnostupidhs** [comment]
Should have been hotfixed

https://us.forums.blizzard.com/en/hearthstone/t/hall-of-fame-cards-in-card-packs/2999

> Upon the launch of Rise of Shadows, an error associated with how our servers processed the change from Year of the Raven to Year of the Dragon resulted in a small number of players receiving cards that had just rotated to the Hall of Fame. We caught this shortly after launch, but there was still an impact to some of our players, so we’d like to share what we’ve done so far and what affected players will see going forward.
> 
> We started tracking the issue on Tuesday morning and gathered a list of accounts that received Hall of Fame cards in their card packs. We also made the decision that these players will receive a full dust refund for any Hall of Fame cards they received after the rotation. We have some work to do to develop the fix, test it, and roll it out, so players won’t see the dust refunds immediately. We’ll share more once we have the fix in place.
