### ISSUE TITLE
Effigy visual effect may remain on wrong side of board permanently

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#114]
PC:
https://www.reddit.com/r/hearthstone/comments/3ibli0/bug_with_effigy/
https://www.reddit.com/r/hearthstone/comments/3id61l/effigy_vfx_bug/
https://www.reddit.com/r/hearthstone/comments/3iucp4/visual_bug_caused_by_effigy/

Mobile:
https://www.reddit.com/r/hearthstone/comments/3icutp/new_bug_witg_effigy/

**Comment by Xinhuan** [comment]
No reports of this bug found since Patch 3.1, closing bug as fixed.
