### ISSUE TITLE
Shudderwock doesn't cast the Battlecry of Drustvar Horror (token from Swampqueen Hagatha)

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1143]
https://www.reddit.com/r/hearthstone/comments/bbofpr/shudderwock_doesnt_recast_the_battlecry_of/

https://old.reddit.com/r/hearthstone/comments/bbuviv/shudderwock_too_horrified_by_drustvar_horrors/

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/horror-shudderwock-not-working/2872/13

> Hey everyone, thanks for the report. We currently investigating into this one and will be addressing it in an upcoming update.

**Comment by troggnostupidhs** [comment]
https://youtu.be/msHYVfnbpc8?t=391

**Comment by czhihong** [comment]
Peter says this should be fixed - https://twitter.com/LegendaryFerret/status/1116954460369014784

> I think this has been fixed.  Let me know if you're still seeing it.

**Comment by troggnostupidhs** [comment]
> Thanks pete, myfriend said it was fixed. U guys are the best!
