### ISSUE TITLE
Recombobulating a minion reduced to 0 Mana by Wilfred Fizzlebang's effect gives another 0 Mana minion

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#115]
https://www.reddit.com/r/hearthstone/comments/3ie1x7/recombobulating_a_minion_drawn_from_wilfred/

The intended behaviour is that all mana cost related enchantments are removed when a minion is played from your hand.

**Comment by jleclanche** [comment]
Closed in 3.1.0.10357
