### ISSUE TITLE
Fel Lord Betrug has misleading text

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1152]
https://youtu.be/msHYVfnbpc8?t=429

> Whenever you draw a minion, summon a copy with Rush that dies at end of turn.

The text implies that they would die at the end of any turn. They only die at the end of your turn. The text should either be "at the end of your turn", or the minions should die at the end of any turn.

**Comment by thoughthouse** [comment]
Looks like they die at the end of any turn now:
https://youtu.be/RcfsMq8ZOQo?t=460
