### ISSUE TITLE
Esc key not working after opening and closing the Quest log

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#116]
Esc key is not working after you open and close your Quest log. It's working again if you go into any sub menu and come back to the main menu. Someone reported this happening before this patch. I reproduced it myself in 3.0.

https://www.reddit.com/r/hearthstone/comments/3hhict/hearthstone_30_unofficial_patch_notes/cu7fd9z

**Comment by ZeroRin** [comment]
tested in 3.1 and it works well for me
