### ISSUE TITLE
Kalecgos' effect is not consumed when the first spell of the turn is countered

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1160]
Original title: Spells inconsistently consume "first/next" effects when countered by Counterspell

---

Spell is not considered as cast:
- Kalecgos's effect is not consumed
  - Your first spell each turn costs (0). Battlecry: Discover a spell.
- Electra Stormsurge's effect is not consumed
  - Battlecry: Your next spell this turn casts twice.
- Celestial Emissary's effect is not consumed
  - Battlecry: Your next spell this turn has Spell Damage +2.
- Text effects like Overload and Twinspell do not occur (fixed in #265)
- "Whenever" effects do not trigger

Spell is considered as cast:
- Kirin Tor Mage's effect is consumed
  - Battlecry: The next Secret you play this turn costs (0).
- Kabal Lackey's effect is consumed
  - Battlecry: The next Secret you play this turn costs (0).
- Duskfallen Aviana's effect is consumed
  - The first card each player plays each turn costs (0).
- Bloodbloom's effect is consumed
  - The next spell you cast this turn costs Health instead of Mana.
- Haunting Visions's effect is consumed
  - The next spell you cast this turn costs 3 less. Discover a spell.
- Preparation's effect is consumed
  - The next spell you cast this turn costs (3) less.
- Inkmaster Solia's effect is consumed
  - Battlecry: If your deck has no duplicates, the next spell you cast this turn costs (0).

Untested:
- Cho'Gall
  - Battlecry: The next spell you cast this turn costs Health instead of Mana.

Decks

Counter Mage
AAEBAf0EBO0F7wjsEcPqAg1x+wGcApYF7AW5BvcN67oCwcECpvACp/cC74ADn5sDAA==

Counter Mage with Solia
AAEBAf0EBO0F7wj9vQLD6gINcfsBnAKWBewFuQb3Deu6AsHBAqbwAqf3Au+AA5+bAwA=

Solia Highlander
AAEBAf0EHk2zAfsBnAK0ArsChQOrBLQElgXtBbkG+AfvCMMTubIC/b0Cl8ECmMQCx8cCmc4Cw+oCpvACp/cCtPwCuf8C74ADpIcDzYkDn5sDAAA=

**Comment by troggnostupidhs** [comment]
The only consistency is that when "cast / play" is _not_ specified, the effect is not consumed.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/bejiyv/if_the_first_spell_you_cast_with_kalecgos_gets/elawn5u

> This is a bug. Kalecgos' effect should be consumed by a spell that gets countered. The fix should go out with the next patch.

**Comment by Jetz72** [comment]
https://www.reddit.com/r/hearthstone/comments/bjiwrx/kalecgos_2x_free_spells_in_one_round/emf9a8i/?context=3
>Your intuition that this feels wrong is correct, this is a bug. Expect a fix for it in the next patch. Even though [[Counterspell]] means you never actually cast the spell, you still took advantage of [[Kalecgos]]' effect, and our intention is that you can only take advantage of the effect once per turn.

>Besides Kalecgos, Electra Stormsurge and Celestial Emissary's effects are [also not consumed](https://github.com/HearthSim/hs-bugs/issues/1160) when the spell is countered. If the pattern is "consume the effect because the caster benefitted from it" rather than "consume the effect because the countered card still counts as the 'first' or 'next' spell", can we take this to mean Electra and Emissary are correct in this behavior?

>Correct.

This means Kalecgos is the only one that's bugged.

**Comment by troggnostupidhs** [comment]
Kalecgos is the only one that is currently bugged. We should keep this rule in mind for any future interactions, "our intention is that you can only take advantage of the effect once per turn".

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22933721
> Kalecgos no longer grants a discount to another spell if the first spell is countered. This is now consistent with other one-time cost reduction effects, such as Inkmaster Solia or Kirin Tor Mage.

**Comment by Kybxd** [comment]
![QQ图片20190515115411](https://user-images.githubusercontent.com/18246091/57747442-312d3200-7708-11e9-8a1a-3770240d0529.png)
