### ISSUE TITLE
Sideshow Spelleater does not work in Tavern Brawl

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#117]
https://www.reddit.com/r/hearthstone/comments/3ih5iv/is_the_sideshow_spelleater_not_working/
https://www.reddit.com/r/hearthstone/comments/3ih87m/sideshow_spelleater_doesnt_work/
http://us.battle.net/hearthstone/en/forum/topic/19136205077
http://us.battle.net/hearthstone/en/forum/topic/18695102741

It works fine in Constructed (and presumably in Arena).

It is currently 'being looked into':

http://us.battle.net/hearthstone/en/forum/topic/18700823257

Video:

* https://www.youtube.com/watch?v=AcYFmin_HXY
* https://www.youtube.com/watch?v=j4bSfC_k7os

**Comment by culinko** [comment]
Happened in Arena, needs to be verified: https://www.reddit.com/r/hearthstone/comments/3jz1lm/why_did_my_opponents_sideshow_spelleater_not_work/

**Comment by beheh** [comment]
Sideshow Spelleater does also not work in `Too many portals!`. You have to rely on RNG a bit, but it doesn't work once you have it.

**Comment by Patashu** [comment]
Right, I edited the topic so it just mentions Tavern Brawl in general.

**Comment by Patashu** [comment]
Confirmed in 3.1:

http://us.battle.net/hearthstone/en/forum/topic/19136205077

**Comment by Patashu** [comment]
Confirmed in 3.2:

https://www.reddit.com/r/hearthstone/comments/3pq4uy/tawern_brawl_heropower_mechanics_get_confusing/

**Comment by Xinhuan** [comment]
Now works in Tavern Brawls.

However, unconfirmed if it can copy non-standard hero powers (eg Ragnaros vs Nefarian).
