### ISSUE TITLE
Loading screen tip will reference “Year of the Raven”

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#1172]
https://us.forums.blizzard.com/en/hearthstone/t/known-issues-list-2019-updated-april-25th/64/6

> Loading screen tip will reference “Year of the Raven”

https://www.reddit.com/r/hearthstone/comments/bi5nwd/ummmm_its_not_year_of_the_raven_anymore/

https://www.reddit.com/r/hearthstone/comments/bk8grl/blizzard_please_ravens_are_so_last_year/

![image](https://user-images.githubusercontent.com/22508641/57179147-66a06880-6e48-11e9-89ce-bae527b4ff39.png)

**Comment by Jetz72** [comment]
Quietly updated in the latest patch:
https://github.com/HearthSim/hsdata/commit/32c8b31a69662efc5984a09f7ba5eaced12ff4c8#diff-9f10bbbad7bf8d1b4f3538e1da25d984R537
>GLUE_TIP_DEFAULT_25	This is the year of the Dragon! (Each year will have a new theme)
