### ISSUE TITLE
Zayle, Shadow Cloak can be found in Rise of Shadows packs

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1176]
https://us.forums.blizzard.com/en/hearthstone/t/got-zayle-from-a-pack/5572
>I just got a Zayle from a pack of the RoS expansion. I think its a bug since its a non craftable card (and also, dusting it is not allowed by the game)

https://www.reddit.com/r/hearthstone/comments/booabg/finished_an_arena_run_and_opened_a_pack_and_got/
>![](https://i.redd.it/8ufvzkc6n8y21.png)

According to this, this shouldn't be possible:
https://www.reddit.com/r/hearthstone/comments/b8i22g/is_it_possible_that_zayle_shadow_cloak_isnt/ejyftmo/
>Zayle will not show up in packs. There are 5 Neutral Legendaries, not including him. You get the golden version in the single player content, but if you want the normal one, you have to craft it.

**Comment by troggnostupidhs** [comment]
Should be fixed Soon™

https://www.reddit.com/r/hearthstone/comments/booabg/finished_an_arena_run_and_opened_a_pack_and_got/enjghvz/

> This was not intended, and we're putting out a hotfix soon to remove Zayle from card packs. Starting Thursday, you'll be able to get Golden Zayle if you own all 5 chapters of The Dalaran Heist! Regular Zayle will be craftable starting Thursday but the golden version is not.

**Comment by Jetz72** [comment]
It appears this has been fixed, and people who acquired the card from a pack have had it replaced with a random Legendary:
https://www.reddit.com/r/hearthstone/comments/brs4ji/for_those_that_unpacked_zayle_early/
>I made a post earlier about being upset that I unpacked Zayle and was 100% on board with buying (either with gold or $) the new SP content. A few days ago I noticed I was gifted Catrina Muerte. I finally put 2 and 2 together and saw my Zayle deck had 0/1 cards in the deck. They took away my Zayle and replaced it with a Legendary not in my collection.

https://www.reddit.com/r/hearthstone/comments/bs1j55/i_opened_zayle_shadow_cloak_before_it_was/
>So I opened Zayle, Shadow Cloak from a pack a week ago when the patch for Dalaran heist dropped. This was caused by a bug. Some days later I got this mail.
>![](https://i.imgur.com/B4WC2y8.jpg)
