### ISSUE TITLE
Dalaran Heist: Duplatransmogrifier sometimes deletes all minions from your Adventure Deck

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1180]
Duplatransmogrifier: "Choose a friendly minion. Replace all minions in your Adventure deck with copies of it."

https://us.forums.blizzard.com/en/hearthstone/t/duplatransmorgifier-bug/5718
>I had the passive treasure that made my minions cost 1 less. I then proceeded to buff a Pyros by +2/+2 in the Tavern. Finally, in the next game, I played Duplatransmorgifier on the Pyros to make all the minions in my deck 1 mana 4/4s. Instead, Duplatransmorgifier cleared all minions from my adventure deck, and I had to stop my run because I pretty much fatigued my next match right away.

>I had the same issue happen to me. I buffed a primalfin totem with +2/+2 and Duplatransmorgified it, had no minions in my deck after that.

https://www.reddit.com/r/hearthstone/comments/bpgwl7/anyone_else_have_experience_with_the/
>I used the Duplatransmogrifier twice in a run, first on a Babbling book made 3/3 by the tavern, then a buffed up dollmaster dorian. Both times I used it, after the game I find that my deck just has no minions. Here is how it looked when it ended. https://puu.sh/DtbwD/62721a62f4.jpg
Anybody else have experience with this card? My theory is that it may have bugged out since they had buffs on them.

Seems to happen primarily with buffed minions. Saw another report that it happened with a Drustvar Horror, but it was [removed](https://www.reddit.com/r/hearthstone/comments/bpgwvz/duplatransmogrifier_bug/) before I could copy it. That behavior would be akin to #1047, another issue in trying to persist a dynamic card beyond the game.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/bpmfs2/bug_used_the_spell_which_replaces_all_minions_in/

https://www.reddit.com/r/hearthstone/comments/bpiyht/bug_duplatransmorgifier_on_a_zombeast_will_just/

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/hotfixes-for-the-dalaran-heist-may-17-2019/5959

> We’ve just released a hotfix to address a few issues with The Dalaran Heist.
> Fixed an issue that caused Duplatransmogrifier to delete all minions in your deck if you select a minion that was buffed by a Friendly Encounter card.
