### ISSUE TITLE
When a secret transformed by Shifting Scroll or Chameleos triggers, the game hangs

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#1183]
https://www.bilibili.com/video/av52735646 (2:50 to 3:33)

Also for Chameleos.

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/shifting-scroll-crashes-dalaran-heist/5773/2

> 
> Howdy!
> 
> We are actively hard at work looking to resolve Chameleos 4 and Shifting Scroll cards freezing the game if shifting into secrets. Hopefully we will see this resolved very soon! Thanks for the workaround!

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22992997

> Triggering a secret that was transformed from Shifting Scroll or Chameleos no longer causes the client to lock up for both players.
