### ISSUE TITLE
Dalaran Heist: Potion of Vitality prevents "next spell" effects like Electra from working

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1185]
https://www.reddit.com/r/hearthstone/comments/bpgc04/the_dalaran_heist_celestial_emissary_bug/
>Take a look at this.
https://imgur.com/a/kwklWAh
As you can see, the only actions I took this turn are: draw 3 cards (from treasure passive effect that draw you 2 extra cards each turn and prevent fatigue damage) -> played Celestial Emissary -> played Arcane Blast. Arcane Blast dealt only 2 damage. The only other passive effect I have is the one that shuffles 2 extra copies of a played minion in your deck.

https://us.forums.blizzard.com/en/hearthstone/t/dalaran-heist-electra-sotrmsurge-didnt-cast-rockbiter-twice/5913
>Playing Shaman against cooking trainer.
Played Electra Stormsurge.
Immediately cast Rockbiter weapon on self
Only received 3 attack.

Blizzard response:
https://us.forums.blizzard.com/en/hearthstone/t/dalaran-heist-electra-sotrmsurge-didnt-cast-rockbiter-twice/5913/3
>We believe this is caused by the Elixir of Vigor treasure preventing “next cast” cards from triggering properly. This includes Electra and Celestial Emissary.

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/hotfixes-for-the-dalaran-heist-may-17-2019/5959

> We’ve just released a hotfix to address a few issues with The Dalaran Heist.
> Fixed an unintended interaction with Elixir of Vigor and the “next” effects caused by cards like Electra Stormsurge.
