### ISSUE TITLE
Dalaran Heist: Frostburn Hero Power not visually affected by Fallen Hero

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1188]
https://us.forums.blizzard.com/en/hearthstone/t/fallen-hero-dalaran-heist/6153
>Fallen Hero does not effect the Frost Burn hero power, the damage remains at 2 not going to 3

Taking an educated guess that this is purely visual.

>[Frostburn][DALA_Mage_HP2][53285]
[2 Mana, Hero_Power]
<b>Hero Power</b>
<b>Freeze</b> a character.
If it's already <b>Frozen</b>, deal 2 damage.
COST=2, CARD_SET=1130, CLASS=4, CARDTYPE=10, HIDE_WATERMARK=1

The '2' in the text lacks the damage modifier character, so the power wouldn't appear to respond to Fallen Hero's presence. It should still deal increased damage, though.

**Comment by Jetz72** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/dalaran-heist-cut-less-not-showing-damage-when-upgraded/6793
>When the rogue hero power Cut-less has upgraded damage with a card such as the Fallen Hero, the additional damage is not shown when you hover over the hero power, although it’s effect seems to be working.

Cut-less seems affected as well.

>[Cut-less][DALA_Rogue_HP2][53293]
[2 Mana, Hero_Power]
<b>Hero Power</b>
Deal 2 damage to an undamaged minion.
COST=2, CARD_SET=1130, CLASS=7, CARDTYPE=10, HIDE_WATERMARK=1

**Comment by troggnostupidhs** [comment]
![image](https://user-images.githubusercontent.com/22508641/64892346-28128a00-d642-11e9-869f-dbadec895cce.png)


![image](https://user-images.githubusercontent.com/22508641/64892387-48424900-d642-11e9-8f8a-5d936161836b.png)

**Comment by troggnostupidhs** [comment]
Pain Split, The Pact, and Invigorating Brew were also updated
