### ISSUE TITLE
King's Elekk doesn't trigger draw-based effects

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#119]
https://www.reddit.com/r/hearthstone/comments/3il1t4/chromaggus_doesnt_work_with_joust_like_kings_elekk/

With Chromaggus on the field, King's Elekk  is played and the Joust is won. The card is drawn, but no copy was put in the hand.

Likely if the winning card is Flame Leviathan or Sea Plunderer, those triggers will also not work, but this remains speculation for now.

**Comment by Patashu** [comment]
Closely related to https://github.com/HearthSim/hs-bugs/issues/28

**Comment by culinko** [comment]
King's Elekk and Shadowfiend interaction: http://us.battle.net/hearthstone/en/forum/topic/19891108954

**Comment by Xinhuan** [comment]
Confirmed to be a bug by Blizzard, and yet to be fixed - https://twitter.com/PlayHearthstone/status/664260742191775744

**Comment by Xinhuan** [comment]
Confirmed for 4.3 - https://www.reddit.com/r/hearthstone/comments/4fjbij/chromaggus_kings_elekk_does_not_provide_two_copies/

**Comment by Patashu** [comment]
Confirmed in 5.0

http://us.battle.net/hearthstone/en/forum/topic/20743666085

**Comment by PattuX** [comment]
https://youtu.be/UKeNoxRiTPI?t=2m34s

It does apply Renounce Darkness buff it seems.

**Comment by Patashu** [comment]
Confirmed in 7.0

https://us.battle.net/forums/en/hearthstone/topic/20752545231

**Comment by Patashu** [comment]
Captain's Parrot now uses the word 'Draw' instead of 'Put'. If it has a non-interaction with Chromaggus, then it should have a bug opened for it:

https://www.reddit.com/r/hearthstone/comments/5wqtea/71_card_consistency_updates/

**Comment by Patashu** [comment]
According to https://www.reddit.com/r/hearthstone/comments/5wqtea/71_card_consistency_updates/decgp98/ and https://www.reddit.com/r/hearthstone/comments/5wqtea/71_card_consistency_updates/dech9ji/ and https://www.reddit.com/r/hearthstone/comments/5wqtea/71_card_consistency_updates/decgswy/ Captain's Parrot works with on-draw triggers.

Time to test King's Elekk and Sense Demons?

**Comment by culinko** [comment]
Chromaggus now triggers after playing both King's Elekk and Sense Demons. Attaching logs below.

King's Elekk: https://gist.github.com/culinko/22ab8a4d2a151bc27a9b28bef556bc25
Sense Demons: https://gist.github.com/culinko/2ff94e2394a64e32a84f067c03058305

**Comment by Patashu** [comment]
Cool!
