### ISSUE TITLE
Dalaran Heist: Hero Power "Refresh" does not interact with Wilfred Fizzlebang

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1190]
https://www.reddit.com/r/hearthstone/comments/bq8kzn/wilfred_fizzlebang_was_in_my_prison_cell_was_sad/
>Wilfred Fizzlebang was in my prison cell. Was sad to discover he does not interact with the Shaman hero power.
> ![](https://i.redd.it/ecd1ts5z61z21.png) 

https://us.forums.blizzard.com/en/hearthstone/t/refresh-does-not-work-with-wilfred-fizzlebang/6330
>When using the solo adventure hero power “Refresh” with Wilfred Fizzlebang on board does not reduce the drawn cards cost to 0 mana.

https://us.forums.blizzard.com/en/hearthstone/t/wilfred-fizzlebang-does-not-interact-with-the-shaman-hero-power-refresh/6067
>Wilfred Fizzlebang reads “Cards you draw from your hero power cost (0)” so this seems like a potential bug.

There are a number of old posts that suggest it works with Brilliance in the Karazhan prologue - [(example)](https://www.reddit.com/r/hearthstone/comments/4zkn9e/wilfred_fizzlebang_works_with_medivhs_hero_power/). Unclear if this is due to hard-coding or something else. Other viable tests: Soul Tap from Mecha Jaraxxus and Nemsy, or giving it to Vaelastrasz or similar via Treachery.

**Comment by Jetz72** [comment]
Acknowledged by Blizzard:
https://us.forums.blizzard.com/en/hearthstone/t/known-issues-list-2019-updated-may-22nd/64/8
>Wilfred Fizzlebang does not apply cost reduction to cards drawn from Hero Power: Refresh.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/23037180/hearthstone-update-july-1-preparing-for-saviors-of-uldum

> Wilfred Fizzlebang's cost reduction now works with all card-drawing hero powers.
