### ISSUE TITLE
Dalaran Heist: Bartender Bob may use a blank emote at the end of a friendly encounter

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1191]
https://us.forums.blizzard.com/en/hearthstone/t/bartender-bob-blank-emote/6237
>After pressing End Turn, having used my coins with Bartender Bob, he literally blanked me. His emote was blank, which I thought was quite rude. 

>![https://imgur.com/WYAd5dn](https://i.imgur.com/WYAd5dnr.jpg)

Included in list of known issues:
https://us.forums.blizzard.com/en/hearthstone/t/hotfixes-for-the-dalaran-heist-may-17-2019/5959
>Bartender Bob may sometimes display an empty dialog bubble when leaving a Friendly Encounter.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22992997

> [Dalaran Heist] Bartender Bob should no longer show an empty speech bubble upon exiting a friendly encounter.
