### ISSUE TITLE
Quests that say "win as [class]" doesn't count wins if played in friendly match when borrowing a deck.

### ISSUE THREAD

**Issue by Adusak90** [HearthSim/hs-bugs#1193]
Just like in the title, I was playing friendly match with my friend, she had a quest to win 2 games as warrior, borrowed my warrior deck and her win didn't count. (She killed me normally so the usual "you need to be at below half of hp for it to count" condition was also met)

Not sure if borrowing of the deck is needed to replicate this or just something is off with winning games in friendly encounter

It may be intended, however I thought that you are able to do any quest that doesn't have specified conditions to complete it like "beat 3 bosses in dungeon run".

**Comment by Jetz72** [comment]
Shouldn't be too tough to test this, unless it's caused by something less straightforward.

**Comment by Adusak90** [comment]
Nevermind, it looks like it was a UI issue that resolved itself the next day, revealing that the warrior quest didn't exist even tho it showed up, and it randomly replaced itself with 3 wins by druid and hunter on it's place

**Comment by troggnostupidhs** [comment]
Could be related to #261
