### ISSUE TITLE
Event quest "Plays of the Frozen Throne" can't be rerolled

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1198]
https://www.reddit.com/r/hearthstone/comments/bc0s13/stuck_with_plays_of_the_frozen_throne/
>I've come back after a long layoff and I have the quest Plays of the Frozen Throne, which requires playing 40 KoTFT cards. Well... I never played that expac so I only have one card, which was a promo from the release. And since that expac is 2+ years old now my one card is only available in Wild. And because I'm a "new" (returning) player, Wild format appears to be locked from me. I can't create a Wild deck in Adventure or Tavern Brawl. And the quest itself can't be abandoned/reset (though of course I want the 300 gold...). So it seems like I am unable to progress the quest or get rid of it. Help?

https://us.forums.blizzard.com/en/hearthstone/t/cant-remove-plays-of-the-frozen-throne-quest/4985
>I’ve had this Knights of the Frozen Throne quest for months now, and I am not able to re-roll it or get rid of it. 

https://us.forums.blizzard.com/en/hearthstone/t/daily-quest-reroll-issue/6432
>I have a problem with daily quest Plays of the Frozen Throne. I can’t reroll it. In addition, i deleted all Frozen Throne expansion cards because they became wild format so i cant accomplish this quest. 

As of 13.4, Legendary Quests should be able to be rerolled. The issue seems to be that "Plays of the Frozen Throne" is not actually a Legendary quest. Images I can find of it don't show the bright background typical of them. Perhaps it used a different flag to make it impossible to reroll. Whether or not that's the case, this consequence of such a distinction doesn't seem deliberate. And since the cards needed to complete it have rotated out, players who dusted their old cards or have been locked out of Wild by the new player experience are now stuck with it being very difficult to complete.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/23076826

> Fixed an issue preventing the Legendary Quests from the Knights of the Frozen Throne from being rerolled.
