### ISSUE TITLE
Hero attack value multiplied during death animation

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#12]
If Sacrificial Pact is used on Jaraxxus, his attack value visually changes from 3 to 9 and then 24 for a brief moment before he dies. If his attack is X, it changes to X\*3 then to X\*8 (tested with Spiteful Smith and Truesilver Champion).
* [Hearthstone Mythbusters Episode 1 (closed beta edition)](https://www.youtube.com/watch?v=gl529WTyJd4&t=1m6s)

The bug can be reproduced by playing Bite or Heroic Strike and then dying:
* [[Hearthstone Visual Bug] Heroic Strike Suicide 28 Attack Bug](https://www.youtube.com/watch?v=692-grgwLP4)

or by equipping a weapon and then attacking into an enemy Zombie Chow:
* [[Hearthstone Visual Bug] Rogue Zombie Chow Suicide 24 Attack Bug](https://www.youtube.com/watch?v=M0EoAnip_Aw)

The interaction seems to be because, whenever Hearthstone updates attacks, the Hero/Minion being in play resets the attack to base value, then every Weapon, Enchantment and Aura affecting the Hero/Minion changes the Attack value. But if the Hero is not in play while the Enchantments affecting it are, Hearthstone erroneously does not reset attack to base value before then applying Enchantment effects. Hearthstone updates Attack many times while it is ending the game, leading to the Attack values climbing indefinitely.

**Comment by theAprel** [comment]
I also saw this happen with a Druid suiciding into a Leper Gnome last night. The Leper Gnome was at 3 attack from a Glavezooka buff and Druid at 1 hp. I think the Druid used Claw, not Hero Power. The weird part of it was that the Druid's attack value didn't bug out until the Leper Gnome's deathrattle. The Druid's attack value jumped to 3 simultaneous with the Leper Gnome's deathrattle sound (the slimy sound). Then the Druid's death explosion animation played as expected.

**Comment by culinko** [comment]
Druid's hero power and/or Claw suiciding into a minion is the same example as Bite or Heroic Strike (second link).

**Comment by theAprel** [comment]
Also here's an example from Kripp's stream. Shaman with Rockbiter into Venture Co. Shaman's attack goes from 3 to 6 right before death animation. Jump to <b>07h19m20s</b>.

http://www.twitch.tv/nl_kripp/v/12491577

**Comment by culinko** [comment]
Thanks for confirming that the bug is still present in 3.0.0.9786. The rockbiter example is also the second case, same with all cards that buff your attack and are not weapons. The damage is multiplied 7 times, I just checked in the log.

**Comment by Xinhuan** [comment]
Still in 4.0.0.10833

Video: https://www.youtube.com/watch?v=079AdKILZM8
Power.Log: https://gist.github.com/Patashu/ae473b3518c18e7ce18f

**Comment by Patashu** [comment]
We talked about this, and jleclanche thinks that the only requirement for the bug is that the active player dies with an attack buff or weapon out. Is there any counter example to this (e.g. someone dying on their turn with a weapon or attack buff and not seeing the visual bug)?

**Comment by Xinhuan** [comment]
> the only requirement for the bug is that the active player dies with an attack buff or weapon out.

I think the bug occurs at all times, but it is simply not visible to the client if the attack value is 0, since 0 attack multiplied by anything is still 0 and would not produce any tag changes that is sent to the client,

**Comment by culinko** [comment]
@Patashu if you have a weapon out, you only see the bug if you attack either into a Zombie Chow (probably more stuff) or use Sacrificial Pact on yourself. Afaik you don't see the bug if you just attack into normal minions.

If you have a buff, you can attack into anything and the bug will show.

**Comment by jleclanche** [comment]
@culinko something to do with health updates post death?

**Comment by theAprel** [comment]
For reference, here's an instance of a Rogue with a Tinker Oil-buffed weapon suiciding into a Captured Jormungar and **not** causing the visual bug (4.0.0.10833).

http://www.twitch.tv/nl_kripp/v/27245619?t=03h13m38s

**Comment by Patashu** [comment]
Looks like it also happens with minions buffed in the deck. We cast Seal of Champions on Malorne, who died and went to deck before the spell text resolved. When we force played him, his attack was briefly 81 and immediately updated to 9.

https://gist.github.com/Patashu/519ce7f78c4906be1fee

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=_zCiqsdP7tE

When Shadowflame could target your Hero, Weapons and Attack buffs would continue to give your Hero additional attack after each outermost Phase.

**Comment by theAprel** [comment]
Still active in 4.2.0.12051

https://www.twitch.tv/nl_kripp/v/57109726?t=2h17m20s

**Comment by Patashu** [comment]
Does Jaraxxus get 27 attack now?

https://www.youtube.com/watch?v=9WA2chxDNro&t=1m00s

**Comment by theAprel** [comment]
Instance in 5.0.0.12574:

https://www.twitch.tv/nl_kripp/v/65201362?t=5h48m

**Comment by Xinhuan** [comment]
Still occurs in 5.0.0.13030.

https://www.youtube.com/watch?v=6ajQF74ZHFw&t=25m48s (Trump's channel)

**Comment by culinko** [comment]
Tested all instances of this bug in 6.0 and it's been fixed now.
