### ISSUE TITLE
Crowd Favorite gets a Powered Up highlight for Choose One minions, despite not being activated by them

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#120]
http://us.battle.net/hearthstone/en/forum/topic/18705073809

Minion that was lit in yellow was Druid of the Claw.

Not being buffed is correct (since the card does not actually use the word Battlecry, see Nerub'ar Weblord), so the glow is wrong.

(Should be tested with Combo minions too.)

**Comment by jleclanche** [comment]
Er, what? Why would crowd favorite be highlighted? It's on the board?

**Comment by jleclanche** [comment]
Marking invalid, the guy probably used druid of the fang and has no idea what's going on. There's nothing in HS that's known to cause a powered up highlight on *other* cards.
