### ISSUE TITLE
Whizbang and Zayle don't update the hero shown on deck selection

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1207]
https://us.forums.blizzard.com/en/hearthstone/t/zayle-the-shadow-cloak/7473
>When I put Zayle in a deck it doesn’t replace the hero neither does it show in the deck cards but I can press done.Also, I can play with one of Zayle’s deck as expected but it shows in my deck collection as a normal deck(ex: A Custom Rogue or Warrior). Also, If I open the deck again from my collection it appears like in the attached screenshot.
Screenshot of the deck: 
>![b394317916077f63e51b2c140380ef1b](https://user-images.githubusercontent.com/8607832/58910268-15072a00-86e3-11e9-93bd-0e04a21d61e0.png)

>Yea, same bug also with whizbang the wonderful

Seems like the inverse outcome of #1096 - a Whizbang deck that looks like a normal deck, instead of a normal deck showing as a Whizbang deck.

Acknowledged by Blizzard:
https://us.forums.blizzard.com/en/hearthstone/t/known-issues-list-2019-updated-june-4th/64/9
>Whizbang the Wonderful and Zayle, Shadow Cloak does not update your deck art.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/23037180/hearthstone-update-july-1-preparing-for-saviors-of-uldum

> Creating Zayle and Whizbang decks should now properly show the card's deck header art instead of the class art.

**Comment by troggnostupidhs** [comment]
fixed again?

https://playhearthstone.com/en-us/blog/23076826

> Fixed issue where
Zayle, Shadow Cloak and
Whizbang the Wonderful would not properly update the player's deck header when being added to a deck.
