### ISSUE TITLE
Summoning Portal has an early priority, inconsistent with Reckless Experimenter

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1214]
It's been known for a long time that Summoning Portal has a priority earlier than most cost modifiers. If you play a Mechwarper then a Portal, a 2-cost Mech still goes down to 0. This was presumed to be intended for a while. 

Reckless Experimenter, however, does not have the same early priority following the addition of a similar clause in its text. Currently, it has a late one, but one of the devs has mentioned that they're looking to move it to an even priority. They describe how this would make Mechwarper+Experimenter affected by order of play:
https://www.reddit.com/r/hearthstone/comments/bwfy7c/reckless_experimenter_does_not_work_in/epxnkrl/

Both the current behavior and described intended behavior for Experimenter is inconsistent with the current behavior for Portal. So either:

* Summoning Portal is not working as intended.
* Summoning Portal is working as intended and the discrepancy is related to the minor wording difference.
* Summoning Portal is working as intended but the inconsistency is an oversight.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/23037180/hearthstone-update-july-1-preparing-for-saviors-of-uldum

> Fixed an issue where Summoning Portal and Reckless Experimenter's effects were being applied at different timings than other similar cost modification effects.
