### ISSUE TITLE
The Storm Bringer sometimes does not update the displayed attack of transformed minions

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1220]
https://us.forums.blizzard.com/en/hearthstone/t/stormbringer-bug-minion-attack-stat-error/7895
>I was playing Shaman, used Stormbringer on my board, whereby Princess Talanji spawned from my Grimscale Oracle on the far right of the board but instead of being a 7/5 minion. It was summoned with 2/5 stats.
Screenshot of the minion, it clearly does not have any debuffs present. 
![https://imgur.com/a/SbGisof](https://i.imgur.com/x2PzKgI.jpg)

>I’m having the same problem. Pretty sure it’s just the interaction between stormbringer and certain murlocs. Doesn’t seem to effect any other minions. When I used bloodlust next turn though, my tirion went from a 1/8 to an 11/8. Lol.

Appears to be entirely visual. Unsure if other transform effects are affected. Seen several reports of this involving Murlocs. Perhaps transforming a minion emitting an aura alongside one being affected by it causes this? E.g. Grimscale Oracle and another Murloc? Perhaps also affected by order of play?

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/23174811/hearthstone-update-october-8-doom-in-the-tomb

> Fixed a bug with The Storm Bringer that would sometimes display incorrect attack or health for the transformed minion.
