### ISSUE TITLE
Hunting Party doubles enchantments when copying minions

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1229]
https://us.forums.blizzard.com/en/hearthstone/t/a-massive-bug-with-hunting-party-card/9271
>I was playing today with Hunter and I found a bug with “Hunting Party”. When the card copy a beast affected by “Dire Frenzy”, the copy regain the +3/+3 buff.
I originally had a copy of “Shimmerfly” that got the “Dire Frenzy” buff and was a 4/4, but the copy created by “Hunting Party” was a 7/7 instead a 4/4, apparently that copy regained the buff of “Dire Frenzy”.

>Works with Emeriss buff, and Zul’jin reapplies the buffs. I had a 3000 damage Stonetusk Boar with this nuttiness. 

Acknowledged by Blizzard:
>Thank you for the report. I was able to reproduce this issue and have sent it for further investigation.

**Comment by Kybxd** [comment]
This has been fixed.

**Comment by Jetz72** [comment]
More specific documentation would be nice but I'll take your word for it since it seems to have stopped getting reports.
