### ISSUE TITLE
Hero power and cards stay green while spectating

### ISSUE THREAD

**Issue by JeremybellEU** [HearthSim/hs-bugs#123]
When you are spectating a game, the player is able to use their hero power, after using all mana or ending the turn without using his hero power, will cause the spectator to remain seeing the green light around the hero power.

**Comment by Patashu** [comment]
I think it happens with the cards as well. When you mouse over the entities or when there's an update from the server (I forget which kind of update it has to be) the green glow finally updates properly. Not sure of all the details but seen this one a lot.

**Comment by jleclanche** [comment]
>  (I forget which kind of update it has to be) 

That'd be the Options packet. At a guess, in spectator mode, the client doesn't clear the options properly on end turn. Could look into it for stove.

**Comment by jleclanche** [comment]
This was fixed in 3.2.
