### ISSUE TITLE
Plot Twist will expose cards which have been known by opponent

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#1242]
https://www.bilibili.com/video/av59921224 (5:25 to 6:15)

**Comment by Jetz72** [comment]
Seen a lot of reports of info leaks regarding previously revealed cards. Is Plot Twist responsible for it happening consistently?

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/23076826

> Fixed an issue where the animation for
Plot Twist would show the front of a card if it was revealed, such as
Aranasi Broodmother.
