### ISSUE TITLE
Gorillabot Battlecry triggers unconditionally

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1244]
https://www.reddit.com/r/hearthstone/comments/cksxcl/can_someone_explain_how_this_happened_how_was_he/
>Can someone explain how this happened? How was he able to discover, without a mech??

(Images show enemy Gorillabot discovered a card. Nothing else on their board besides a 1/1 beast.)

Tested and confirmed; it triggers even if played on an empty board, regardless of what else is in play:
![Hearthstone Screenshot 08-01-19 17 40 48](https://user-images.githubusercontent.com/8607832/62330650-499b2600-b487-11e9-9ca4-2d860694486c.png)

Hand glow behaves as though the card were working correctly: Yellow only if a mech is in play.

**Comment by troggnostupidhs** [comment]
Dendrologist, Primalfin Lookout, Avian Watcher, and Fossilized Devilsaur (with tribe based conditions) were tested and did not trigger on an empty board (which is the correct behavior).

**Comment by troggnostupidhs** [comment]
I think this was hotfixed

![Hearthstone Screenshot 08-02-19 20 38 03](https://user-images.githubusercontent.com/22508641/62404802-7e7daa80-b565-11e9-8a72-c6209c0c78e9.png)
