### ISSUE TITLE
Darnassus Aspirant's Battlecry turns 10/10 Mana into 9/10 Mana

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#126]
For some reason, if you play a 0 cost Darnassus Aspirant at 10/10 Mana, the Battlecry makes you have 9/10 Mana.

https://www.youtube.com/watch?v=u3L50eGC0ug

If you play Darnassus Aspirant at 10/10 Mana but it costs 2 Mana, the behaviour is as expected, you go to, and then stay at, 8/10 Mana: https://www.youtube.com/watch?v=qh97e31rkJM&t=0m50s

**Comment by Patashu** [comment]
I think it also turns 10/8 mana into 9/9. I saw footage of it on DisguisedToast's stream, but he has not posted it anywhere yet.

**Comment by ZeroRin** [comment]
tested in 3.1, fixed
http://tieba.baidu.com/photo/p?kw=%E8%BF%9C%E5%8F%A4%E7%82%8E%E9%BE%99&flux=1&tid=4085781251&pic_id=6b6d221bb051f819eae281e2dcb44aed2c73e7d7&pn=1&fp=2&see_lz=1#!/pid6b6d221bb051f819eae281e2dcb44aed2c73e7d7/pn1

**Comment by culinko** [comment]
Thanks for the find, verified and closing the issue.
