### ISSUE TITLE
Frostmourne and and Soulreaper’s Scythe do not resummon minions

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1264]
https://us.forums.blizzard.com/en/hearthstone/t/frostmourne-doesnt-respawn-reborn-minions-killed-by-weapon/13855
>I was playing highlander control warlock and I got the Frostmourne. Enemy was playing deathrattle N’zoth rogue with Khar’tut Defenders and such. I’ve killed 3 Khar’tut Defenders in their original form (first phase) and I didn’t try the second phase but I’m pretty sure that wouldn’t change anything. After the last strike on a defender, weapon was destroyed but didn’t respawn anything.

https://us.forums.blizzard.com/en/hearthstone/t/frostmourne-bug/13848
>When my opponent’s FrostMourne broke it didn’t summoned the minions that has killed here is the replay of the game
https://hsreplay.net/replay/2BeYrnSyE3p94dvUoG3YKj

Acknowledged by Blizzard:
https://us.forums.blizzard.com/en/hearthstone/t/frostmourne-deathrattle-effect-known-issue-upcoming-hotfix/13895
>We’re aware of an issue introduced with the most recent update causing the Deathrattle effect on the Frostmourne weapon (gained from The Lich King) to fail to summon minions that were killed by the weapon.
>
>Our current plan is to get a hotfix out to address this issue on Monday, September 16. We will update this thread with more information if anything changes.

Unclear if the issue is that killing a minion fails to trigger the sword and create the enchantment, or if the data is correctly stored but the Deathrattle fails to do anything with it.

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/known-issues-list-2019-updated-sept-12th/64/11

> Frostmourne (ICC_314t1) and Soulreaper’s Scythe (DALA_719) deathrattle are not spawning minions.

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/frostmourne-deathrattle-effect-known-issue-upcoming-hotfix/13895/2

> 
> We’re aware of an issue introduced with the most recent update causing the Deathrattle effect on the Frostmourne weapon (gained from The Lich King) to fail to summon minions that were killed by the weapon.
> 
> Our current plan is to get a hotfix out to address this issue on Monday, September 16. We will update this thread with more information if anything changes.
> 
> Thanks for your patience!

**Comment by Jetz72** [comment]
This was hotfixed around that time. No further reports.
