### ISSUE TITLE
Tinyfin Mode: If you queue in with less than 30 cards, the random ones that you're given to fill the remainder can include uncollectibles

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1268]
https://us.forums.blizzard.com/en/hearthstone/t/tavern-brawl-bug/14215
>So i’ve recently been playing the new brawl, when i wanted to clear the deck, hearthstone asked me to autocomplete with 1 card remaining (i had 0/30)
That intrigued me so i tried making a deck with only 1 card in my deck. I was able to search for a match.
Turns out Hearthstone autoincluded cards in my deck, but thats not even the best part. It included cards from the whole pool of HS cards, and not the ones i had in my library.
Even further, it gave me cards that DONT EVEN EXIST IN THE GAME. No voicelines, animations etc. cards that devs use for testing. I managed to get stuff like: pre-nerfed knife juggler, avatar of coin (0 mana 1/1 text: you lost the coin flip, but you gained a friend.), a litterall cardback as a card, heropowers as cards, a fully complete diamond spellstone, gilean royal guard in the 8/3 statline and the priest ‘elixir of shadows’ (its normally called undefined elixir and becomes something random, but it came in the shadow form from the start)

Tested and confirmed:
![Hearthstone Screenshot 09-18-19 17 58 04](https://user-images.githubusercontent.com/8607832/65193129-08b39c80-da48-11e9-8737-17717f4bb58e.png)

![Hearthstone Screenshot 09-18-19 18 11 58](https://user-images.githubusercontent.com/8607832/65193132-0ea97d80-da48-11e9-9bf0-7a23a319e747.png)

![Hearthstone Screenshot 09-18-19 19 00 04](https://user-images.githubusercontent.com/8607832/65193136-12d59b00-da48-11e9-8367-42c4f7258d6f.png)

Drawing a hero power softlocks me when I try it, but others on Reddit have been able to draw them:
https://www.reddit.com/r/hearthstone/comments/d64rk9/i_always_run_extra_hero_powers_in_my_deck/

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/d64w6o/tavern_brawl_game_me_a_hero_power_card/f0t0ibe/

> Aware of this bug, should be fixed now. Let me know if you're still seeing weird cards in the deck backfill.
