### ISSUE TITLE
Tombs of Terror: A tie with a Plague Lord will reset its health

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1269]
https://us.forums.blizzard.com/en/hearthstone/t/2nd-boss-reset-with-sou-expansion/14200/
>2nd boss (last one) reset from 40 hp to full 300. I wa using bulwark (negatives fatal dmg and deal 20 dmg to the boss). My 2nd encounter and boss got 40 hp left. He used cthun on me when he was below 10 hp. Now what happens:
one of Cthuns missiles should kill me, then secret procs and deals 20 dmg to boss what killed him, but then next cthun shot killed me aswell. Game shows that is a lost, but after i could still encounter last boss but he back to full 300 hp.

https://us.forums.blizzard.com/en/hearthstone/t/plague-lord-health-reset/14255
>Just faced against chapter 2 plague lord. With both of us att low HP I used ”Eye for an eye”. He attacked me and we both died resulting in defeat. However I got to immediatly fight him again but at a resetted 300hp. 

Plague Lords are supposed to retain their health between battles and only reset when beaten. There's no obvious answer for what that means in a tie, but losing the progress from previous runs seems wrong. Ideally it should return the boss to the health they had before the match.

**Comment by Jetz72** [comment]
https://www.reddit.com/r/hearthstone/comments/d6bqbl/be_warned_primordial_bulwark_does_not_work_like/f0rovj9/
>Damn that sucks.  Looks like there's a bug with how ties works.  The game should remember the lowest Health you got the Plague Lord to. It should be at 1 health.

**Comment by troggnostupidhs** [comment]
There might be a general boss health issue. I had it also just happen to me where I had the Heroic first wing boss below 100 and now it is at 162.

https://us.forums.blizzard.com/en/hearthstone/t/2nd-tombs-boss-health-went-back-to-285-from-165/14285

https://us.forums.blizzard.com/en/hearthstone/t/second-plague-lord-wont-retain-lost-health/14283

https://us.forums.blizzard.com/en/hearthstone/t/heroic-mode-plague-boss-health-not-lowering/14288

https://us.forums.blizzard.com/en/hearthstone/t/plague-lord-health-reset/14255

https://us.forums.blizzard.com/en/hearthstone/t/2nd-wing-boss-health-stays-at-300/14286

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/d6saai/why_is_krazaths_health_returning_to_300_each_fight/f0w0hh6/

> This definitely shouldn't be happening. We're looking into it right now - will update ASAP!

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/tombs-of-terror-plague-lord-progress-not-saving/14291/19

> Thank you for the reports. We’re aware of an issue with Plague Lord health not saving properly. Thank you for your patience while we work on a resolution!

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/small-client-update-15-2-2/14325

> Please also note that the recently introduced Plague Lord health persistence issue is something we are aware of, but is not contained in this update. We’re working hard on a fix for this and will update as soon as possible.

**Comment by troggnostupidhs** [comment]
Unsure if this impacts the tie issue

https://us.forums.blizzard.com/en/hearthstone/t/small-client-update-15-2-2/14325/4

> Update: We’ve recently implemented a server-side update in all regions to fix the issue causing Plague Lord persistent health to fail to save.
> 
> You may experience some minor unexpected results due to this change, but there shouldn’t be anything gameplay impacting.
> 
> Thanks!

**Comment by troggnostupidhs** [comment]
Original issue with ties may still be a problem. This report also mentions an issue with the player's health.

https://www.reddit.com/r/hearthstone/comments/d9smq2/important_tip_do_not_attempt_a_tie_with_a_plague/

> Made this mistake in my most recent run. I was fighting against Xatma, the previous two attempts I'd managed to do all of 2 and 0 damage to his health before dying. Xatma being Xatma.
> 
> This time around, I actually did well. Well enough in fact that I managed to just barely get him down to 5 HP.
> 
> Trouble was, I had enough toxins in my deck that I'd die next turn, and my only card remaining was one free Ultimate Infestation. Thought "What's the worst that could happen?" and tried using it. I brought him to zero, then drew enough cards to bring me to -17. We both exploded, which left me back on the boss selection screen for Xatma, who was now back to -FULL- health, and me still at -17.
> 
> Loaded into the match, instantly exploded, lost. Guess -that's- the worst that could happen!
> 
> Thus, that now makes 3 attempts on Xatma in which I've technically done 2, 0, and -2 total damage to him. Oof.

**Comment by Jetz72** [comment]
The issue with the player health in that case is probably unrelated. And possibly not even an issue depending on how you look at it.
https://www.reddit.com/r/hearthstone/comments/d9smq2/important_tip_do_not_attempt_a_tie_with_a_plague/f1oi6n2/?context=3
>Were you using the "you don't heal between encounters" anomaly or something?

>Yep, I had the anomaly activated.

**Comment by Jetz72** [comment]
https://www.reddit.com/r/hearthstone/comments/e9wen7/1603_update/
>[Tombs of Terror] Fixed an issue that could cause the Battle Scars anomaly to prevent the player from progressing after ending a plague lord encounter with a tie.

Never ended up documenting it but apparently this was fixed at some point, causing a new issue where a tie with a plague lord while under the "don't heal between encounters" anomaly would create a permanent stalemate. Both heroes would start the game with negative health and die immediately. That was in turn fixed just recently, though the current behavior in this scenario is unclear.
