### ISSUE TITLE
Crush has no animation when played on a silenced minion

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#13]
The Crush animation is not played when used on a Silenced minion.
- https://www.reddit.com/r/hearthstone/comments/2vo6tf/crush_has_a_bug/
- [[Hearthstone Visual Bug] Crush on Silenced Minion](https://www.youtube.com/watch?v=HXirPk9hmOk)

**Comment by troggnostupidhs** [comment]
This still happens

![hearthstone screenshot 12-18-16 13 49 08](https://cloud.githubusercontent.com/assets/22508641/21295724/54925dd0-c529-11e6-8f6c-160723f4bfe1.png)

**Comment by troggnostupidhs** [comment]
I think this is fixed

![hearthstone screenshot 06-03-17 22 19 09](https://cloud.githubusercontent.com/assets/22508641/26758396/da272b6a-48aa-11e7-963e-21c97dc94017.png)
