### ISSUE TITLE
Clever Disguise sometimes gives no cards

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1311]
https://us.forums.blizzard.com/en/hearthstone/t/clever-disguise-non-generation/27166
>Played a game of ranked standard on 3/26/2020. Game ended 13:59 EST.
Clever disguise was generated by ethereal lackey. When played Clever disguise did not generate any cards. Replay seems to have glitched out so cannot link it.
Platform is PC, Windows 10 Pro.
>Edit: Update: Added Clever disguise to main deck and played it twice, both times it generated as it was supposed to.

>It happened to my opponent and in the following game it happened to me. The spell is casted, uses mana but the cards are not generated to your hand nor do they count towards rogue quest completion. 

https://www.reddit.com/r/hearthstone/comments/fpgfai/clever_disguise_is_broken_and_wont_cast/
>Rogue 2 mana spell does nothing when cast. I tried it several times in ranked, does not work.

Mixed reports. Some have said it affects other cards. Some suggest it's already fixed. And some have theorized that it occurs when the card "rolls" Demon Hunter as its chosen class, which makes sense, though the ones claiming it happened several times in a row would be odd.

**Comment by hamidnazari** [comment]
Here's a video of the interaction, or lack there of I should say.
https://www.youtube.com/watch?v=pYhixy7RW5M

**Comment by Jetz72** [comment]
https://twitter.com/Celestalon/status/1243412340713771009
>There's a bug with Clever Disguise right now. 10% of the time, it picks Demon Hunter, but there are no valid Demon Hunter cards yet, so it gives you nothing. :(
>
>Working on a fix.

**Comment by Jetz72** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/170-hotfix-update/27437
>Clever Disguise will now correctly function as intended when played.
