### ISSUE TITLE
Living Roots has Epic rarity

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#1312]
https://www.reddit.com/r/hearthstone/comments/fpfgar/living_roots_is_now_an_epic/
>Living roots is now an Epic?
>![](https://i.redd.it/iexh18f5w1p41.jpg)

It can apparently be disenchanted for a quick 100 dust if you want to cash in on it.

**Comment by riQQ** [comment]
Can confirm that it disenchants for 100 dust

**Comment by Jetz72** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/170-hotfix-update/27437
>Living Root, when disenchanted, now properly gives the amount of dust of a common instead of an epic. However, its gem rarity will not be updated until Monday (3/30).
![Hearthstone Screenshot 03-27-20 20 11 42](https://user-images.githubusercontent.com/8607832/77809720-53e9e000-7067-11ea-87c5-60393d64eb25.png)

**Comment by Jetz72** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/170-hotfix-update/27437
>Living Root’s gem rarity will be corrected from Epic to Common.

Fixed as of the 17.0.0.44582 data patch.
