### ISSUE TITLE
Mind controlling a Coldarra Drake/Garrison Commander does not refresh your Hero Power

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#134]
When a Coldarra Drake/Garrison Commander is played, summoned or transformed into, in the next Summon Resolution Step, it will trigger on its own Summon Event and refresh your Hero Power. In addition, during the Inspire Phase, Coldarra Drake/Garrison Commander queue and trigger to refresh your Hero Power.

https://www.youtube.com/watch?v=htSOCPQleqQ&list=PLx2kRadCTuYawUW_vn3fVLauYYwnilgU5&index=1

As a consequence of the above rules, stealing (using Mind Control or otherwise) a Coldarra Drake/Garrison Commander does not refresh your Hero Power:

https://www.youtube.com/watch?v=ax4U6dDIlws&t=2m42s

**Comment by culinko** [comment]
Just to mention, if you steal them before you use your hero power for the first time, they are working correctly. The bug only happens if you already used your hero power before you decided to steal them.

**Comment by Patashu** [comment]
What happens if you create a Coldarra Drake or Garrison Commander via a transform effect in 5.0? Will your Hero Power immediately refresh? (see http://us.battle.net/hearthstone/en/forum/topic/20743614487 - Special SRS seems to be gone)

Basically, we should test if these cards are still SRS mechanics.

**Comment by culinko** [comment]
Tested in 5.0 and it's fixed.
