### ISSUE TITLE
Skull of guldan bug

### ISSUE THREAD

**Issue by gingamonk86** [HearthSim/hs-bugs#1353]
When I draw a soul fragment with 'skull of guldan' cast with outcast the card after the soul fragment does not have the 3 Mana cost reduction as it's supposed to.

**Comment by Jetz72** [comment]
The Soul Fragment is one of the three cards drawn by the Skull, and so the cost reduction goes to it. The card immediately after the Soul Fragment is not drawn by the Skull, but by a secondary effect of "Casts When Drawn" on Soul Fragment. So it does not get the reduction.

"Casts When Drawn" could theoretically be retooled so the card replaces itself with the drawn one in the eyes of external effects and it'd clear up a lot of confusion. But as it stands, this is the intended behavior.
