### ISSUE TITLE
Sylvanas can steal dying minions

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hs-bugs#137]
From reddit:
https://www.reddit.com/r/hearthstone/comments/30dodu/bug_sylvanas_steals_souls/

> My last minion (antique healbot) killed sylvanas of my opponent. I play Kel'Thuzad after both are dead and end my turn. Result: Minion is not revived.
> My only logical point of view is the order of play. if Sylvanas was played earlier then my minion (which i think it was, but i am not sure). It killed sylvanas, but before the minion was actually dead, the deathrattle of sylvanas played (as this maybe happens before the minions are actually dead) and steals my dead minion, then it dies.

Confirmed as a bug by [/u/CM_Zeriyah](https://www.reddit.com/user/CM_Zeriyah).

**Comment by jleclanche** [comment]
Fixed in Patch 2.4.0.8311.

**Comment by strages** [comment]
ha the reddit post was mine XD
