### ISSUE TITLE
Bear Trap can activate on full board

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hs-bugs#139]
Confirmed as a bug by Ben Brode here:

https://twitter.com/bdbrode/status/641456430248144897

**Comment by culinko** [comment]
Should this be merged into #27 so it would cover all 3 affected secrets?

**Comment by jleclanche** [comment]
They are separate bugs, as they are separate card implementations.

**Comment by Patashu** [comment]
Confirmed in 3.1 by Adys

**Comment by Patashu** [comment]
This needs to be tested in 4.0

**Comment by culinko** [comment]
Tested and Bear Trap no longer triggers with full board.
