### ISSUE TITLE
Transforming Echoing Ooze causes the "goo" effect to persist

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#14]
If you play an Echoing Ooze, then transform it the same turn via effects like Tinkmaster Overspark, Polymorph or Recombobulator, the green semi-transparent goo visual effect does not disappear and permanently remains on the Battlefield in the position of the original Echoing Ooze for the remainder of the match. This is purely a visual bug. This bug was introduced in Patch 2.0.0.7234 (GvG patch).

* [Hearthstone Recombobulator + Echoing Ooze Funny Bug](https://www.youtube.com/watch?v=eZOfMMeA_O4)
* http://us.battle.net/hearthstone/en/forum/topic/16952155520
* https://www.reddit.com/r/hearthstone/comments/3jyilm/interesting_bug_involving_the_ooze_graphic/

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3jyilm/interesting_bug_involving_the_ooze_graphic/ Confirmed in 3.0

**Comment by ZeroRin** [comment]
http://tieba.baidu.com/photo/p?kw=%E8%BF%9C%E5%8F%A4%E7%82%8E%E9%BE%99&flux=1&tid=4084070757&pic_id=1b2b9823dd54564e5ca43c9fb5de9c82d3584fd7&pn=1&fp=2&see_lz=1

fixed in 3.1
