### ISSUE TITLE
Faceless Manipulator on Murloc Tidecaller has bugged animation

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#141]
If you play Faceless Manipulator targetting Murloc Tidecaller, a second Murloc Tidecaller appears, then the Battlecry occurs and the Faceless Manipulator vanishes.

https://www.youtube.com/watch?v=hfoxyv5uLbw

(This interaction likely also exists between Faceless Manipulator and a friendly Cobalt Guardian because they share the Pre-Summon Reaction Bug in common, see http://hearthstone.gamepedia.com/Advanced_rulebook#Cobalt_Guardian.2FMurloc_Tidecaller_Pre-Summon_Reaction_Bug )

**Comment by Patashu** [comment]
Related to https://github.com/HearthSim/hs-bugs/issues/45 and https://github.com/HearthSim/hs-bugs/issues/35

**Comment by jleclanche** [comment]
Labeling gameplay as well because the root cause is due to how early the buff happens.

**Comment by Patashu** [comment]
Will be fixed in 5.0 since Presummon triggers no longer interact with Transforms.
