### ISSUE TITLE
Elemental Destruction deals damage one-by-one instead of all at once

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#143]
Elemental Destruction deals its damage one by one and runs on-damage triggers in between, rather than all at once then run all on-damage triggers.

https://www.youtube.com/watch?v=phurzsurH2k&t=9m55s

Lightning Storm has the same behaviour.

**Comment by jleclanche** [comment]
not sure how easily this can be fixed, due to the random element of it.

**Comment by Patashu** [comment]
"not sure how easily this can be fixed, due to the random element of it."

Pre-calculate all the damage, then create the damage events as an AoE. Briefly, Lightbomb was 'fixed' to do all its damage in a single AoE, but there was a bug with 0 attack minions and spell damage that made them hotfix and revert back to the previous behaviour. So if they can 'fix' Lightbomb they can 'fix' Lightning Storm and Elemental Destruction.

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=KGPH1DpxjPs&t=3m48s Confirmed in 5.0

**Comment by culinko** [comment]
Still happens in 7.0.

**Comment by NightKev** [comment]
```
<+TardisBot> [discord] <culinko> I don't think they should be merged, but Patashu and jleclanche should know more about gameplay issues than I do.
<+TardisBot> [discord] <culinko> So maybe they know better.
<@jleclanche> which ones?
<+TardisBot> [discord] <culinko> 133 and 143
<@jleclanche> oh yeah
<@jleclanche> they're the same
<@jleclanche> i asked Patashu to merge them before
<@jleclanche> it's the same core issue
<@Patashu> I'm fine with merging them
<+TardisBot> [discord] <culinko> Fine here as well
