### ISSUE TITLE
Silencing Lord Jaraxxus the Hero with Light's Champion inconsistencies

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#146]
If you target Lord Jaraxxus the Hero with Light's Champion you can silence off Frozen, Repentance, temporary Attack but not the temporary Immune effect of Ice Block triggering (which is attached to your Hero, therefore should be a silence-able enchantment).

https://www.reddit.com/r/hearthstone/comments/3m3c33/til_lights_champion_can_silence_jaraxxus/

**Comment by Patashu** [comment]
Closed b/c I'm an idiot who didn't realize you can't

1) be Immune due to Ice Block on your own turn

2) so they either tried to silence the secret off (which obviously won't work, since secrets aren't a property of your hero) or popped ice block then tried to target Jaraxxus (which also obviously won't work)

So it is currently unknown if you can silence off the Ice Block Immune effect or not.

**Comment by culinko** [comment]
You could try to play Light's Champion on the opponent's Jaraxxus and have the Illidan+Juggler to kill the Abomination and proc the opponent' Ice Block.

**Comment by Patashu** [comment]
Right, it had to be suggested to me because I'm dumb lol. I'd like footage of this.

**Comment by jleclanche** [comment]
Brilliant @culinko

**Comment by Xinhuan** [comment]
Adding video footage link here for completeness:

* https://www.youtube.com/watch?v=5knLJTwbe4o
* https://www.reddit.com/r/hearthstone/comments/3mbheb/hearthstone_science_silence_ice_block_immunity/

**Comment by jleclanche** [comment]
Repurposed the bug, fixed in 4.0.0.10833

**Comment by Xinhuan** [comment]
Adding context. The 4.0 patch changed it so you can no longer target Jaraxxus with Light's Champion. (Although this introduces a new inconsistency where Sacrificial Pact can still target Jaraxxus.)
