### ISSUE TITLE
Choose One Hero Powers activates Combo

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#147]
Totemic Slam is the upgraded version of the Shaman Hero Power (using Justicar Trueheart).

If you use Totemic Slam, you click a 'choose one' card, which counts to the game as clicking on a card. Then, Combo effects of cards such as Eviscerate are activated this turn.

http://tieba.baidu.com/p/4068015902

Edwin Vancleef correctly gets only +2/+2, not +4/+4, from playing a 'Choose One' card such as Wrath. (Tested by Patashu, video/log available on request)

Totemic Slam may also possibly be bugged to play, not summon, a totem (unknown), or to count as a spell (unknown). (It seems to not do any of these)

https://www.youtube.com/watch?v=1GaQq9vY_KI

**Comment by Xinhuan** [comment]
Now further confirmed with our own video of the bug: https://www.youtube.com/watch?v=cT91Oap6bNk

**Comment by Patashu** [comment]
Confirmed in 3.1 by thevdude and NightKev

**Comment by Patashu** [comment]
Video in 3.1: https://www.youtube.com/watch?v=1GaQq9vY_KI

**Comment by troggnostupidhs** [comment]
This still happens

![hearthstone screenshot 12-17-16 17 52 03](https://cloud.githubusercontent.com/assets/22508641/21290287/a6ed7e9a-c482-11e6-95ef-6b2936a8dba6.png)

**Comment by Kybxd** [comment]
Still happening in the recent patch.
* http://imgur.com/a/NATfe

**Comment by Kybxd** [comment]
DK Druid's Hero Power can activate combo. 

https://www.reddit.com/r/hearthstone/comments/6td0kx/death_knight_druid_hero_power_counts_as_playing_a/

Guess: What about DK Hunter's Hero Power, and is it counted as 2 cards for Edwin Vancleef?

**Comment by troggnostupidhs** [comment]
https://youtu.be/OLLqOIvol1o?t=105

Starts at 1:44

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

>Using certain Hero Powers, such as Totemic Slam and Plague Lord, will no longer activate Combo cards.

**Comment by culinko** [comment]
Can confirm that Totemic Slam has been fixed. Can't test the Plague Lord because I don't have Malfurion the Pestilent.

**Comment by troggnostupidhs** [comment]
Fixed

![img000](https://user-images.githubusercontent.com/22508641/31788152-e20ac8e4-b4db-11e7-9798-0107abd2301d.png)

![img001](https://user-images.githubusercontent.com/22508641/31788153-e2182746-b4db-11e7-8b6b-f9f60615f40a.png)
