### ISSUE TITLE
Wrath's effect order is inconsistent with other Damage spells that Draw a card

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#148]
When you use Wrath (1 damage version) on your own Mech-Bear-Cat, you first draw the card from your deck, then the spare part.

When you do the same with Starfire, you first draw the spare part, then the card from your deck.

**Damage first then, Card Draw (Spart part first)**
- Starfire - https://www.youtube.com/watch?v=F0nBnPY8Sf0
- Hammer of Wrath - https://www.youtube.com/watch?v=9wmZ_lMwwMQ
- Mortal Coil - https://www.youtube.com/watch?v=RWPF-DezC3Y
- Slam - https://www.youtube.com/watch?v=QqIu7K4-Phg
- Shiv - https://www.youtube.com/watch?v=NtZettio-6E
- Quick Shot - https://www.youtube.com/watch?v=c_znpOKir44

**Card draw first, then Damage (Spart Part last)**
- Wrath - https://www.youtube.com/watch?v=8BOz-KJGmiU
- Holy Wrath - Deck first, because the draw has to happen first - https://www.youtube.com/watch?v=VA67jDrXCok

**Additional Notes**
Quick Shot on your own Acolyte of Pain (with Quick Shot being the only card in your hand just before you cast it) draws a total of 1 card, also proving that the Damage occurs first.

**Comment by Patashu** [comment]
Verified only with logs and not with gameplay side-effects, but Life Tap and Fan of Knives are also damage before draw.

**Comment by Patashu** [comment]
Confirmed in 7.0 by https://github.com/HearthSim/hs-bugs/issues/638#issuecomment-265351946

**Comment by troggnostupidhs** [comment]
Potentially fixed.

http://us.battle.net/hearthstone/en/blog/20562933/hearthstone-update-february-28-2-28-2017

> Addressed an issue with the interaction of Wrath’s card draw timing in conjunction with Daring Reporter.

**Comment by culinko** [comment]
I tested the example with Wrath and Mech-Bear-Cat and you get the spare part first now, then you get the card from your deck. I assume the Holy Wrath interaction is correct.

@Xinhuan @Patashu Is there anything else that needs to be tested (e.g. Wrath + Fandral) or some other card drawing effects before we close this?

**Comment by Patashu** [comment]
Double check that Wrath + Fandral hasn't changed and we should be good to close and update the wiki.

**Comment by culinko** [comment]
Wasn't it bugged as well? Anyway, Wrath works the same with Fandral and Mech-Bear-Cat, getting you the Spare Part first before you get the drawn card. Log here: https://gist.github.com/culinko/8d66ef54ace6147dc92a2c827b9a87fb.

**Comment by Patashu** [comment]
Nope, Fandral was working non-bugged (damage then draw) already. Just verifying that there's no regression.
