### ISSUE TITLE
Game hangs in Rangaros (Majordomo Phase 2)/Siege Engine interaction

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#149]
* https://www.reddit.com/r/hearthstone/comments/3mhzc6/we_are_the_hearthsim_community_simulator/cvh5lfb?context=3
* https://youtu.be/XhZusEJswSA?t=442

When Majordomo Executus (Hero in the BRM adventure) is killed and Ragnaros is summoned for the next phase of the fight, if Majordomo controls a Siege Engine, the game hangs.

The player does not see Steam Engine trigger (Ragnaros gains 8 Armor after entering play) until the player restarts Hearthstone and reconnects to the game.

**Comment by PattuX** [comment]
Fixed between Patch 3.1 and 4.1.

https://youtu.be/2o096_Ey0OM
