### ISSUE TITLE
Tinker's Sharpsword Oil has REQ_MINION_TARGET in its requirements

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hs-bugs#150]
Same issue as #131. Tinker's doesn't require a target, but carries REQ_MINION_TARGET.

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=SlDQvJ4jJ60&t=28m18s Proof it doesn't have any targeting requirements

**Comment by troggnostupidhs** [comment]
Fixed?

https://api.hearthstonejson.com/v1/18336/enUS/cards.json

**Comment by troggnostupidhs** [comment]
`{"cardClass":"NEUTRAL","dbfId":2184,"id":"GVG_022b","name":"Tinker's Sharpsword Oil","playerClass":"NEUTRAL","set":"GVG","text":"+3 Attack.","type":"ENCHANTMENT"}`
