### ISSUE TITLE
Arena decks with multiples of a card sometimes use more than one slot to list the card

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#151]
For example if you have 3 Water Elementals it will list 2 Water Elementals, then separately below it a single Water Elemental.

* https://www.reddit.com/r/hearthstone/comments/3mwv1b/is_this_a_new_bug/
* http://us.battle.net/hearthstone/en/forum/topic/19136253660
* https://www.reddit.com/r/hearthstone/comments/3mwysi/well_thats_pretty_weird_is_this_a_bug/
* https://www.reddit.com/r/hearthstone/comments/3mxcb5/interesting_bug_with_my_arena_draft/

**Comment by NightKev** [comment]
It can happen even if you only have two of a minion as well, and it's inconsistent (notice that some of them are grouped correctly but others not).
![hearthstone screenshot 09-30-15 00 14 42](https://cloud.githubusercontent.com/assets/849285/10186757/6706f654-6708-11e5-8dcf-5a18c6d31e8e.png)

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3mxsdz/2_or_3_holy_champion/

Here's an instance where the two slots are 2 and 3 respectively

**Comment by NightKev** [comment]
Seems like it was fixed?
![hearthstone screenshot 10-02-15 01 56 33](https://cloud.githubusercontent.com/assets/849285/10242858/dc835c32-68a8-11e5-90e3-fc8342457b00.png)

**Comment by culinko** [comment]
No reports about this issue since Oct 18 on official forums.

**Comment by jleclanche** [comment]
I think it was hotfixed.
