### ISSUE TITLE
"Rolled" rope is displayed for the remained of the match

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#155]
https://www.reddit.com/r/hearthstone/comments/3myshm/mildly_interesting_how_the_hearthstone_rope_looks/

Not sure if there is anything specific to trigger this bug or if it stays there after the first time some of the players sees the rope animation.

**Comment by NightKev** [comment]
It seems to happen if you end your turn just as the rope is about to finish appearing.

**Comment by culinko** [comment]
Tested it now and it's been fixed.
