### ISSUE TITLE
Replacing your hero resets Fatigue damage to 1

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#156]
New bug in patch 3.1.0.10357, works with both Lord Jaraxxus and Ragnaros (from Majordomo Executus).

* http://us.battle.net/hearthstone/en/forum/topic/19136833743
* https://www.youtube.com/watch?v=umAFwBIgUDU

Fatigue damage should not reset ever:
* https://twitter.com/CM_Zeriyah/status/540580004279484416

**Comment by jleclanche** [comment]
https://twitter.com/ywoo_dev/status/649360054773239808 Confirmed as a bug by ywoo

**Comment by Xinhuan** [comment]
Majordomo (Ragnaros) confirmed by Simfri to also be bugged: https://www.youtube.com/watch?t=3&v=soagSpn0zf8

**Comment by Patashu** [comment]
Confirmed in 3.2

https://www.reddit.com/r/hearthstone/comments/3ppgv5/apparently_once_you_are_jaraxxus_the_damage_you/

**Comment by culinko** [comment]
I can confirm that this bug is fixed in 4.0. Tested with both Jaraxxus and Ragnaros. I will post the log shortly.
