### ISSUE TITLE
Skeleton Knight/Anub'arak with Baron Rivendare and 9 cards in hand causes the repeated Deathrattle to discard itself from hand

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#159]
* http://us.battle.net/hearthstone/en/forum/topic/19136203808
* https://www.youtube.com/watch?v=twZrV3A3TBA (Anub'arak)
* https://www.youtube.com/watch?v=8w4labPSEHk (Skeleton Knight)

**Comment by Xinhuan** [comment]
This is related to this bug: https://www.youtube.com/watch?v=rc7oejbhdUA

A minion that is Shadow Madnessed, then Mind Controlled (via Sylvanas) back to the original controller will die if the player ends turn with that minion on a full board (7 minion) because it tries return itself to a full zone of 7 minions while already being there.

**Comment by Patashu** [comment]
Fixed in 4.0 (tested by ZeroRin)

**Comment by Xinhuan** [comment]
Video showing it is fixed: https://www.youtube.com/watch?v=c6aja40HL9s&t=2910

In this video, a Panda is played from a full hand on a minion while Brann Bronzebeard is in play, the card did not self-discard during the activation of the second Battlecry.
