### ISSUE TITLE
Combat cancelled after death processing causes you to be unable to attack

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#16]
If you begin combat, but triggers on preparing to attack (during the "Combat Preparation Phase") remove your target first, the attack aborts and you are not exhausted or lose durability. This is the normal case, and can be seen here: [2x heals with truesilver champion in one turn](https://www.youtube.com/watch?v=X1MkS7_jj0U)

However, if the target is alive after the "Combat Preparation Phase" BUT the Death Phase following the "Combat Preparation Phase" THEN causes your target to die, a glitch occurs where the attacker is stuck in mid air and cannot be used to attack again. For example, an enemy minion is summoned, triggering an enemy Knife Juggler, mortally wounding an allied Boom Bot. During the subsequent Death Phase the Boom Bot Deathrattle mortally wounds the defender, and THEN it is removed from play, and then combat glitches out. This has happened with both Hero and Minion attackers. The extra Death Phase seems to be the culprit.
- https://www.reddit.com/r/hearthstone/comments/2slubn/funny_weapon_interaction/
- https://www.reddit.com/r/hearthstone/comments/31px6a/bug_noble_sacrifice_knife_juggler_boom_bot/
- http://us.battle.net/hearthstone/en/forum/topic/18194505322
- http://us.battle.net/hearthstone/en/forum/topic/18596063432
- http://us.battle.net/hearthstone/en/forum/topic/18705073817
- http://us.battle.net/hearthstone/en/forum/topic/18700823968
- https://www.reddit.com/r/hearthstone/comments/3jif60/bug_with_snake_trap_knife_juggler/
- https://www.reddit.com/r/hearthstone/comments/3k4bmh/so_a_very_rare_interaction_happened_in_my_game/
- https://www.reddit.com/r/hearthstone/comments/3k4hno/noble_sacrifice_bug/
- http://us.battle.net/hearthstone/en/forum/topic/19136254316 (contains screenshot)
- https://www.reddit.com/r/hearthstone/comments/3nletn/strangest_bug_noble_sac_minion_got_killed/ (contains screenshot)
- http://us.battle.net/hearthstone/en/forum/topic/19136254316#3
- https://www.youtube.com/watch?v=_udMghmZC80

**Comment by Patashu** [comment]
'normal case' (truesilver vs shadowboxer) confirmed in 3.0:

https://www.reddit.com/r/hearthstone/comments/3mp26p/best_rng_ive_ever_had_shadowboxer_truesilver/

**Comment by Patashu** [comment]
Confirmed in 3.1:

http://us.battle.net/hearthstone/en/forum/topic/19136254316

**Comment by Xinhuan** [comment]
Another confirmation in patch 3.1: https://www.reddit.com/r/hearthstone/comments/3ozq2m/a_series_of_somewhat_unlikely_events_leading_up/

**Comment by Patashu** [comment]
Confirmed in 3.2:

http://us.battle.net/hearthstone/en/forum/topic/19136254316#3

**Comment by culinko** [comment]
https://www.youtube.com/watch?v=_udMghmZC80

**Comment by Patashu** [comment]
Confirmed in 4.1:

http://us.battle.net/hearthstone/en/forum/topic/20043026400

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3x3meg/strange_interaction_with_shadowboxer_today/ < report saying that truesilver champion + shadowboxer canceled the attack AND prevented them from attacking again this turn. But they should be able to attack again, so has the behaviour changed or is this a dud?

**Comment by culinko** [comment]
This should be re-tested (might still not be fixed), because in 4.2 you're unable to attack again (tested with Explosive Trap).

**Comment by PattuX** [comment]
In Patch 4.2 the attacker (hero or minion) is visually reset correctly and not stuck mid-air anymore.

**Comment by PattuX** [comment]
Note: There is a second condition that must be True in order to be able to attack again.

Either it is "defender is a minion" or "defender is in graveyard".

With the tests currently done, we can't tell those apart.

A test which would make this clear, is attacking a minion that got returned by Ambusher in Death Phase 1 or a Malorne who died in Death Phase 1. (The latter is little less RNG)
Enemy: KJ (1 HP), Malorne (1 HP), Snake Trap. You: 2-3x KJ, 2x Grim Patron
You have to attack Malorne, Snake trap triggers, enemy KJ triggers Patron, who triggers your KJ, who then kills Malorne.

**Comment by Kybxd** [comment]
It seems that you will always waste this attack chance when the combat is cancelled now. Two examples I've tested:
* I have Blackguard and attack a 2-health enemy minion with Truesilver Champion. I restore 2 health and the target is killed by Blackguard. Durability is not wasted but I cannot attack again.
* I have a 2-health friendly minion and attack enemy hero. First I'm Misdirected to this minion, then it's killed by Explosive Trap. Then I cannot attack again.
