### ISSUE TITLE
Sometimes triggering Counterspell causes you to disconnect

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#161]
When Counterspell is triggered (you can be the owner, triggerer or a spectator of either player), if you click away the big 'Counterspell' card that appears telling you what Secret was triggered, it is very likely that your client will hang and you need to disconnect and reconnect to the game to resume playing.

Post by Yong Woo explaining the workaround:

https://www.reddit.com/r/hearthstone/comments/3pj52o/counter_spell_destroys_hearthstone_client/

Other threads:

* https://www.reddit.com/r/hearthstone/comments/3n9qq1/counterspell_causes_game_to_freeze_research_inside/
* https://www.reddit.com/r/hearthstone/comments/3n5x1d/psa_avoid_counterspell_dc_bug/
* http://us.battle.net/hearthstone/en/forum/topic/19137003736
* http://us.battle.net/hearthstone/en/forum/topic/19135803844
* http://us.battle.net/hearthstone/en/forum/topic/19136833980
* http://us.battle.net/hearthstone/en/forum/topic/19136013944
* https://www.reddit.com/r/hearthstone/comments/3n64jn/counterspell_causing_static_bug/
* https://www.reddit.com/r/hearthstone/comments/3pjsxs/gamebreaking_counter_spell_bug/
* https://www.reddit.com/r/hearthstone/comments/3pk44y/bugcounterspell/

**Comment by Patashu** [comment]
Additional research:

https://www.reddit.com/r/hearthstone/comments/3n9qq1/counterspell_causes_game_to_freeze_research_inside/

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/19136254352

Report of it happening when a player played Counterspell and Gluth triggered it.

**Comment by Patashu** [comment]
ZeroRin claims that the freeze only occurs if Counterspell is the second secret.

**Comment by Patashu** [comment]
Confirmed in 3.2

* https://www.reddit.com/r/hearthstone/comments/3pj52o/counter_spell_destroys_hearthstone_client/
* https://www.reddit.com/r/hearthstone/comments/3pjsxs/gamebreaking_counter_spell_bug/

**Comment by Xinhuan** [comment]
Yong Woo posted here:

https://www.reddit.com/r/hearthstone/comments/3pj52o/counter_spell_destroys_hearthstone_client/

> We unfortunately did not get a fix for this into the 3.2 patch! We will be rolling out a fix for this soon.

> In the mean time, do not click on the Big Card for the spell that is being countered when the animation is happening. That should help with not breaking the client. Worst comes if your client dies, you should be able to reconnect to the game.

> Try this out and let me know if the work around doesn't work for you. Again, sorry about the bug! We are working on it.

> http://i.imgur.com/ZyV40Yv.png[1]

> This shows Counter Spell in "Big Card" view. The work around is to not click on this or the card that is about to get counter spelled. Let the animation play out.

**Comment by Patashu** [comment]
No reports yet, probably fixed in 4.0

**Comment by Patashu** [comment]
No reports yet, so closing.
