### ISSUE TITLE
Using your Hero Power just before your turn ends leads to it remaining visually flipped

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#162]
If you use your Hero Power so late in your turn that it says 'Too late! Your turn is already over.' rather than performing it, then the Hero Power remains flipped, even on your next turn. It will be highlighted in green. It can be clicked on (at least in the Windows PC client).
- https://www.youtube.com/watch?v=C8ReLSxnkEU&t=1m27s
- http://us.battle.net/hearthstone/en/forum/topic/19288928941
- https://www.youtube.com/watch?v=K5fYxmD7Fjo

It seems to last until the next time the Hero Power is used. If you have insufficient mana, the client will erroneously give the error 'Hero powers may only be used once per turn' instead.
- https://youtu.be/ykTMikjlwqk?t=7m50s (Attempt to use is at 10:40)

**Comment by Patashu** [comment]
Confirmed in 3.2, and it apparently can be clicked in the Windows PC client

https://www.youtube.com/watch?v=K5fYxmD7Fjo

**Comment by theAprel** [comment]
Screenshot in of bug in 4.1.0.10956

![hearthstone screenshot 01-01-16 21 53 32](https://cloud.githubusercontent.com/assets/10458225/12073092/ead1b8ee-b0d6-11e5-93a6-f0c8aa7ab30f.png)

**Comment by chrissprague** [comment]
Also affects the OS X client (and clicking works.) v4.1.0.10956

Before:
<img width="1440" alt="osx" src="https://cloud.githubusercontent.com/assets/3145878/12601190/3526a34c-c46d-11e5-986a-a270a9b269f4.png">

After:
<img width="1440" alt="osx2" src="https://cloud.githubusercontent.com/assets/3145878/12601197/44988f66-c46d-11e5-8c62-bad15cd24ce5.png">

**Comment by Patashu** [comment]
Video example in 4.1:

https://www.youtube.com/watch?v=izur1VrPKic&t=25m40s

**Comment by Patashu** [comment]
Confirmed in 5.0? (waiting for video)

http://us.battle.net/hearthstone/en/forum/topic/20743676045

**Comment by Patashu** [comment]
Fixed according to http://us.battle.net/forums/en/hearthstone/topic/20749867298

**Comment by troggnostupidhs** [comment]
This probably should be closed.

**Comment by troggnostupidhs** [comment]
> Non-targeted Hero powers will no longer remain flipped if used just before the rope timer forces the end of turn

As a note, it was specifically non-targeted Hero Powers.

I'm closing this because it should have been fixed and there are no reports that I can find.
