### ISSUE TITLE
The sound of equipping a weapon is much quieter than expected

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#163]
Confirmed for Windows client only, may or may not occur on other clients.

http://us.battle.net/hearthstone/en/forum/topic/19136064192

**Comment by jleclanche** [comment]
So Onyxia really *does* deep breath more.

**Comment by culinko** [comment]
I've seen many reports of incorrect sound effects, so this might be related. Taunt, Truesilver, Consecration sounds playing only in left audio channel (if you use headphones). This reddit thread is full of those, attaching some of them:

https://www.reddit.com/r/hearthstone/comments/3n0hoe/hidden_patch_notes/cvjznr4
https://www.reddit.com/r/hearthstone/comments/3n0hoe/hidden_patch_notes/cvjwvsq
https://www.reddit.com/r/hearthstone/comments/3n0hoe/hidden_patch_notes/cvk3ulb

**Comment by culinko** [comment]
Sounds like this one was already fixed, probably in the same patch that fixed other sound issues like Savage Roar.
