### ISSUE TITLE
Explosive Sheep AoE ignores mortally wounded minions, all other AoE includes them

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#165]
Explosive Sheep ignores (does not continue to damage) mortally wounded (0 or less Health) minions. However, all other AoE damage that has been tested overkills mortally wounded characters, and Healing Totem can heal mortally wounded minions.

* https://www.youtube.com/watch?v=IUMQ7MAilJ0

**Comment by Patashu** [comment]
Current as of 3.2:

https://www.youtube.com/watch?v=TdH8FSs31zA

**Comment by Patashu** [comment]
Current as of 4.0:

https://www.youtube.com/watch?v=IUMQ7MAilJ0

**Comment by Patashu** [comment]
Note to self.

1) Shadowflame ignores mortally wounded, Cone of Cold includes mortally wounded (proven in Djinni of Zephyrs video)

2) Spawn of Shadows ignores mortally wounded, last tested in 3.0

3) When Brann comes out, we can test Dread Infernal, Refreshment Vendor, etc

4) Untested effects: Death's Bite (use Blingtron to equip over both), Wild Pyromancer, Dreadscale, maybe others

**Comment by PattuX** [comment]
Deaths Bite + Blingtron (I knew he was gonna be useful somehow) http://imgur.com/a/oKfov
Wild Pyro http://imgur.com/a/wfhrI (I used Flamewaker instead of 2nd Pyro, effect should be the same)

**Comment by Patashu** [comment]
https://twitter.com/bdbrode/status/670691133807198208

Chillmaw correctly overkills in 4.0 according to this report

**Comment by jleclanche** [comment]
Acked at https://twitter.com/bdbrode/status/670830523946700800

**Comment by Patashu** [comment]
Fixed in 4.2

https://www.youtube.com/watch?v=A0ZDuqp6EOo
