### ISSUE TITLE
Casting Brawl that resolves with 0 minions causes non-ending Brawl animation

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#167]
Casting Brawl that causes a Violet Teacher/Illidan/enemy Troggzor to spawn a minion, that causes a Knife Juggler to throw a knife, that causes the death of Abomination/Explosive Sheeps that clears the entire board of minions, will result in a situation where Brawl resolves with 0 minions on the board.

When this happens, the Brawl animation runs forever, requiring a client restart.

https://www.youtube.com/watch?v=5ItppVLJqko&t=38

**Comment by culinko** [comment]
This does not happen with Enter the Coliseum, i just tested it with a friend. The animation ends properly.

**Comment by culinko** [comment]
Tested in 4.1 with SimFri and it no longer happens. The Brawl animation will end properly.
