### ISSUE TITLE
Divine shield doesn't prevent on-damage triggers from non-combat sources

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#17]
If a minion with a Divine Shield takes damage from a non-combat source, on-damage triggers run. This bug was introduced in Patch 2.7.0.9166 (Tavern Brawl).

* https://www.reddit.com/r/hearthstone/comments/3a3678/takes_damage_with_divine_shield_interaction_rules/
* http://us.battle.net/hearthstone/en/forum/topic/18194590703

**Comment by Patashu** [comment]
Can we please confirm this is fixed in 3.0? Haven't seen anyone report it in weeks.

**Comment by culinko** [comment]
I just tested Acolyte + Divine Shield + Elven Archer/Hammer of Wrath and the Acolyte didn't trigger in either of the cases.
