### ISSUE TITLE
Faceless Manipulator does not copy the temporary Immune of Stablemaster

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#172]
https://www.reddit.com/r/hearthstone/comments/3p3r23/til_if_you_copied_a_beast_which_was_given/cw39v2d

Using Bestial Wrath and than Faceless Manipulator on beast gives immune to both beasts. Stablemaster should works the same as Bestial Wrath.

Bestial Wrath on Savannah Highmane:
* http://i.imgur.com/4nP9aeB.jpg

Stablemaster on King of Beasts:
* http://i.imgur.com/luPe5Xw.png

**Comment by jleclanche** [comment]
The temp immune is a buff, isn't it? How does it look in the logs?

**Comment by culinko** [comment]
Reproduced in 4.1. Attaching logs below.
Bestial Wrath: https://gist.github.com/culinko/e71d40d29fe74595ce7d
Stablemaster: https://gist.github.com/culinko/571cba847fc20b7a0822

**Comment by culinko** [comment]
This bug has been fixed.
