### ISSUE TITLE
Windfury visual effect is left on the battlefield after a Windfury minion is Transformed

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#176]
If you transform a minion that has Windfury, its Windfury visual effect remains on the battlefield until the game ends or you reconnect.

* https://www.reddit.com/r/hearthstone/comments/3pkaxf/found_a_potentially_new_bug_nothing_big_just/

**Comment by Xinhuan** [comment]
I saw this bug in 3.1.0.10357 on my iPad a few days ago. Didn't take a screenshot though.

**Comment by culinko** [comment]
I tested this with SimFri in 4.1 and we couldn't reproduce it with Windfury minion + Recombobulator, so I assume it's fixed.
