### ISSUE TITLE
If you freeze a friendly newly summoned minion, it will unfreeze at the end of your turn

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#18]
This bug only happens with summoned minions, minions played from hand will work correctly. For example playing Animal Companion which summons Leokk and freezing him by Frost Elemental will unfreeze at the end of your turn. This might be related: `tag=JUST_PLAYED value=1` is attached to every card played from hand, but is not copied over to the minions that will get summoned by it.

Log: https://gist.github.com/culinko/2b0690d9769f5f01cc223b71b09dbc4a.

Similar happens to frozen Echoing Ooze or a frozen minion copied by Faceless Manipulator. Herald Volazj presumably has the same bug.
- https://www.reddit.com/r/hearthstone/comments/2blnzm/working_as_intended_the_echoing_ooze/
- https://www.reddit.com/r/hearthstone/comments/4nbld1/bug_ragnaros_the_firelord_unfreezing_himself_on/

---

Video by RevolverHS:
[![Working as intended? ; The Echoing Ooze](https://img.youtube.com/vi/vBno4msYF9Q/0.jpg)](https://www.youtube.com/watch?v=vBno4msYF9Q)

**Comment by PattuX** [comment]
Confirmed in 4.2.

Not sure if someone noted that already, but the spawned Ooze is actually frozen but just until the end of the turn.

* https://youtu.be/LPiN29FNXI0

**Comment by Patashu** [comment]
Copying the freeze but becoming unfrozen is actually weirder than not copying freeze at all.

**Comment by culinko** [comment]
I just confirmed the same behavior by playing a minion, freezing it with Ice Lance and copying the frozen minion by Faceless Manipulator. The copied minion unfroze at the end of my turn.

![hearthstone screenshot 04-01-16 15 15 21](https://cloud.githubusercontent.com/assets/11700272/14207820/b7672060-f81c-11e5-9800-05ad4204b0cf.png)

**Comment by Patashu** [comment]
So the bug is that JUST_PLAYED isn't copied, and the game engine rule for wearing off frozen cares about JUST_PLAYED, right?

And the tag NUM_TURNS_IN_PLAY is used for summoning sickness, and that's assigned correctly. Interesting.

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=Cxrqzwr1K7Y&t=10m29s

Mirror Entity copies the Frozen state of a Frozen Yogg-Saron. So it's Echoing Ooze specific. I'll edit the title.

**Comment by culinko** [comment]
Happens with any summoned minion, not just copied ones: https://www.reddit.com/r/hearthstone/comments/4nbld1/bug_ragnaros_the_firelord_unfreezing_himself_on/

Log (Animal Companion + Ice Lance): https://gist.github.com/culinko/2b0690d9769f5f01cc223b71b09dbc4a

**Comment by Patashu** [comment]
http://imgur.com/a/4hfKi the aberrant berserker is new from atiesh (see trigger in the sidelog) but unfreezes immediately. confirmed in 6.1.14830

**Comment by EDL666** [comment]
Don't know if you need more footage/proof of this, but here is Trump footage with a Menagerie Warden summoning a frozen Stranglethorn Tiger that unfreezes on the same turn:
[https://youtu.be/bbU1ImizJBQ?t=13m30s](url)

**Comment by troggnostupidhs** [comment]
The ooze copy is now also frozen

![hearthstone screenshot 08-09-17 13 01 15](https://user-images.githubusercontent.com/22508641/29133886-e5446530-7d02-11e7-85bf-c69c726e7944.png)

**Comment by troggnostupidhs** [comment]
Repeated the Faceless test, and it seems to be fixed

![hearthstone screenshot 08-09-17 13 17 46](https://user-images.githubusercontent.com/22508641/29134619-3d058fd6-7d05-11e7-909d-742eeb3a0fe6.png)

**Comment by troggnostupidhs** [comment]
Animal Companion also works

![hearthstone screenshot 08-09-17 14 42 30](https://user-images.githubusercontent.com/22508641/29138239-1222f554-7d11-11e7-86bf-11cf5943b6b4.png)

**Comment by troggnostupidhs** [comment]
This is not affected by the dominant player bug.

Ooze Deck
AAEBAf0EAk3tBQ6sAfsBnAK0ArsCqwTmBJYFuQbCDo+aAomsArGwAsfHAgA=
