### ISSUE TITLE
Deck Limit: 2 is sometimes displayed incorrectly for Legendary cards in the Collection Manager while constructing a deck

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#185]
"Deck Limit: 2" is sometimes displayed incorrectly for Legendary cards in the Collection Manager while constructing a deck. It is currently unknown what causes the bug.
- http://us.battle.net/hearthstone/en/forum/topic/12504511312
- http://www.reddit.com/r/hearthstone/comments/3eg3ae/nobody_told_me_they_buffed_malganis/
- https://www.reddit.com/r/hearthstone/comments/3kwr21/time_to_craft_another_alexstrasza/

**Comment by troggnostupidhs** [comment]
This hasn't been reported in a long time. I would argue it can be closed.
