### ISSUE TITLE
Receiving multiple copies of Old Murk-Eye or Captain's Parrot after completing the achievement

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#188]
After you receive Old Murk-Eye or Captain's Parrot as a reward for having all Murlocs/Pirates and go to your collection, they can appear there multiple times. After finishing another game, you will receive the reward pop-up again and the number will increase even more. This is purely a visual bug and can be fixed by restarting the Hearthstone client.
* https://www.reddit.com/r/hearthstone/comments/39yuvz/murloc_bug_or_maybe_a_new_feature/
* https://www.reddit.com/r/hearthstone/comments/3a2z5l/golden_murk_eye_bug/
* https://www.reddit.com/r/hearthstone/comments/3ikhah/possible_bug_just_got_a_second_old_murkeye/
* https://www.reddit.com/r/hearthstone/comments/3tdqmn/i_keep_getting_old_murkeye_as_a_reward/

**Comment by Xinhuan** [comment]
Still occurs in patch 4.0.

http://us.battle.net/hearthstone/en/forum/topic/19877977718

**Comment by Patashu** [comment]
https://t.co/CdEELCxAIE should be impossible to reproduce now as they've left standard
