### ISSUE TITLE
Pandaria: It's possible to move the crops board off-screen

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#189]
You can move the crops on the Pandaria board off-screen with correct timing. Also you can make the top right vegetable appear much bigger.
- https://www.reddit.com/r/hearthstone/comments/3cyk82/i_found_an_interesting_crop_bug/
- https://www.reddit.com/r/hearthstone/comments/3w9pcw/a_little_fun_hearthstone_bug/

**Comment by troggnostupidhs** [comment]
I was trying to reproduce this but I wasn't able to. It's possibly fixed.

**Comment by culinko** [comment]
I couldn't reproduce it either.
