### ISSUE TITLE
UI elements will overlap if you click My Collection, Card back and Hero tab in a quick succession

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#194]
If you click My Collection, Card back tab and Hero tab in a quick succession, some of the UI elements will overlap.
- http://us.battle.net/hearthstone/en/forum/topic/18300091215

![cvrilp1](https://cloud.githubusercontent.com/assets/11700272/12409473/a6946586-be6a-11e5-9a25-0cf17fabf7ea.jpg)

**Comment by culinko** [comment]
Still happens in 5.0: https://www.reddit.com/r/hearthstone/comments/4lok1e/bug_in_my_collection/.

**Comment by troggnostupidhs** [comment]
This seems fine to me.

**Comment by culinko** [comment]
Can't reproduce this anymore. A small delay has been added so you can't press a different button so fast anymore. This issue was probably fixed in the same patch as #181.
