### ISSUE TITLE
Showdown at Blackrock Mountain: Core Hound Pup not reviving enemy Core Hound Pups at the end of the turn

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#196]
Core Hound Pup revives only friendly Core Hound Pups at the end of the turn. This contradicts its card text.
- http://us.battle.net/hearthstone/en/forum/topic/18124236485
- https://www.reddit.com/r/hearthstone/comments/3a6fyv/core_hound_pup_bug/

**Comment by troggnostupidhs** [comment]
I didn't reproduce the same use case (Mind Control + Shadow Flame). I used Mana Bind to copy the spell. When I traded all but one Core Hound Pup, all of them regenerated on my side.

![hearthstone screenshot 07-27-17 23 12 53](https://user-images.githubusercontent.com/22508641/28701086-c04882ce-7321-11e7-9546-ea9686ba26fb.png)

![hearthstone screenshot 07-27-17 23 13 02](https://user-images.githubusercontent.com/22508641/28701088-c221bd68-7321-11e7-9427-a399294a9147.png)

![hearthstone screenshot 07-27-17 23 13 17](https://user-images.githubusercontent.com/22508641/28701090-c3f38ec8-7321-11e7-907d-b9cbc0f694c5.png)

**Comment by troggnostupidhs** [comment]
I think this is good enough to show that they now revive.

**Comment by culinko** [comment]
Your opponent's Core Hound Pups didn't revive though, which is what this bug is about.

**Comment by troggnostupidhs** [comment]
They did revive, on my side.

**Comment by culinko** [comment]
Oh I see. Sorry about the confusion.
