### ISSUE TITLE
Commanding Shout is not applied to transformed or stolen minions

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hs-bugs#2]
Commanding Shout states that your minions can't be reduced below 1 Health this turn. However, it is not applied in several cases:

If you steal a minion, it does not gain the Commanding Shout enchantment.
* https://www.youtube.com/watch?v=QC8_jNOvdEs&t=11m33s
* https://gist.github.com/culinko/26c9af33fe94c451811c

If one of your minions is Transformed with a spell transformer, the post-transformed minion does not have the enchantment.
* https://www.youtube.com/watch?v=QC8_jNOvdEs&12m49s
* https://gist.github.com/culinko/1618777838b560d66b59
* https://www.reddit.com/r/hearthstone/comments/3i0jxz/bug_commanding_shout_doesnt_work_when_using/

If you play Grim Patron, Commanding Shout and Bouncing Blade, it should result in a board full of 3/1 Patrons for the player. However, this is not the case.
* https://twitter.com/bdbrode/status/574250421608259585
* https://www.youtube.com/watch?v=QC8_jNOvdEs&13m10s
* https://www.youtube.com/watch?v=iMb5Vs49oIE

Below are the examples where Commanding Shout works correctly:
If one of your minions gets stolen by Sylvanas Windrunner' Deathrattle, it will keep the enchantment until the end of your turn.
* https://www.youtube.com/watch?v=QC8_jNOvdEs&12m1s

If one of your minions is Transformed with a minion transformer, the post-transformed minion will receive the enchantment.
* https://www.youtube.com/watch?v=QC8_jNOvdEs&12m22s

If you play a self-transformer like a Druid of the Claw, the final minion will also receive the enchantment.
* https://gist.github.com/culinko/415817bf40dafbac641f

**Comment by Patashu** [comment]
Also

1) If you steal a minion, it doesn't gain Commanding Shout buff. https://gist.github.com/culinko/26c9af33fe94c451811c

2) If a minion is stolen from you, it maintains Commanding Shout buff. (no log/video)

3) Playing Druid of the Claw gains Commanding Shout buff, as expected. https://gist.github.com/culinko/415817bf40dafbac641f

4) Commanding Shout is only applied to minions during Aura Update Step between Phases, so stuff like Commanding Shout -> Grim Patron -> Bouncing Blade does not work as expected. https://www.youtube.com/watch?v=iMb5Vs49oIE  (Commanding Shout protects your minions from Snipe, as expected: https://www.youtube.com/watch?v=RTZn5GGncPc )

**Comment by PattuX** [comment]
Probably changed Commanding Shout to not trigger in the Summon Resolution Step:

*http://youtu.be/_XPENLtMLV4?t=26m

When stolen minions are tested as well, this can be closed.

**Comment by Patashu** [comment]
Also from the same video:

https://www.youtube.com/watch?v=_XPENLtMLV4&t=25m30s -> silence no longer removes commanding shout enchantment

**Comment by culinko** [comment]
Tested stealing enemy minion and getting your minion stolen, both fixed in 5.0.

Stealing enemy minion: https://gist.github.com/culinko/d3447e4444c533c4d6c9ffc84d05f25d
![hearthstone screenshot 05-11-16 11 09 07](https://cloud.githubusercontent.com/assets/11700272/15176087/bba70afc-1769-11e6-999b-0a1cece1d16b.png)

Getting your minion stolen: https://gist.github.com/culinko/5732a4f95a2fa7f12e5d0b439941a161
![hearthstone screenshot 05-11-16 11 02 02](https://cloud.githubusercontent.com/assets/11700272/15176084/b96d01f6-1769-11e6-9325-a2e0608c56fe.png)
