### ISSUE TITLE
Attacking into Explosive Trap with Gladiator's Longbow prevents the Hero damage 50% of the time (Dominant Player Bug)

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#20]
**UPDATE:**

Patch 5.0 'fixed' the Gladiator's Longbow vs Explosive Trap interaction by making Gladiator's Longbow a Proposed Attack Event trigger that renders your Hero Immune. Unfortunately, Explosive Trap is also a Proposed Attack Event trigger, meaning the Dominant Player Bug determines which trigger goes first. If Explosive Trap triggers first, the Hunter will take damage.
- https://www.youtube.com/watch?v=Tp-fvE8ODcE

Learn more about the Dominant Player Bug here: http://hearthstone.gamepedia.com/Advanced_rulebook#Dominant_Player_Bug

---

**Previous post:**

You will take damage if you attack with a Gladiator's Longbow into an Explosive Trap. Ben Brode [tweeted](https://twitter.com/bdbrode/status/480033773673668608) on 21 June 2014 that this is likely a bug:

> Q: Gladiator's Longbow. Even though the immune shimmer appears over the hero, they are still damaged by Explosive Trap.
> A: it's a bug. We're looking into it.
> Q: What one is the bug? That we're damaged by Explosive Trap or that the immune shimmer appears?
> A: probably the fact that you're damaged
> Q: Been debating on Hearthpwn. Some folks figure damage shouldn't occur. Some think it should and shimmer is the bug. Clears it up.
> A: I think the text makes you feel like you shouldn't take damage even if there were no effect.

This is in contrast with attacking into a Paladin with an Eye for an Eye secret, where the Hunter will not take any damage from the secret.

Screenshots:
![](https://cloud.githubusercontent.com/assets/235410/9426835/3d5b72a6-495a-11e5-9f4b-b66746bbe723.jpg)
![](https://cloud.githubusercontent.com/assets/235410/9426837/3d5e80fe-495a-11e5-9836-c7fc3e1df51c.jpg)

If a Hunter attacks a Water Elemental with the bow, it will take no damage from the Water Elemental as expected. Since the Water Elemental did not do any damage, it will also not Freeze the Hunter. 

Screenshots:
![](https://cloud.githubusercontent.com/assets/235410/9426836/3d5e6466-495a-11e5-8dff-a7e6e5267c01.jpg)
![](https://cloud.githubusercontent.com/assets/235410/9426838/3d62ddf2-495a-11e5-99d9-ce8efa2c6216.jpg)

Video:
- [Hearthstone Trivia: Do You Really Know the Gladiator's Longbow?](https://www.youtube.com/watch?v=tGgtkUVRsPM)

**Comment by Patashu** [comment]
Reconfirmed by Adys in 3.1

**Comment by Patashu** [comment]
Confirmed in 4.0:

https://www.reddit.com/r/hearthstone/comments/3t9cfl/gladiators_longbow_not_always_immune_while/

(With Noble Sac+KJ but same timing)

**Comment by Patashu** [comment]
Confirmed in 4.2

https://www.reddit.com/r/hearthstone/comments/4dnwlp/explosive_trap_ignores_gladiators_longbow/

**Comment by Patashu** [comment]
Confirmed in 4.3

http://us.battle.net/hearthstone/en/forum/topic/20743264556

**Comment by Patashu** [comment]
This is stated to be fixed in the 5.0 patch notes.

**Comment by culinko** [comment]
The immune visual effect still disappears when Explosive Trap triggers, but you no longer take damage. Does this need to be tested with kj+noble sac as well?

**Comment by Patashu** [comment]
Yes, I think it should be tested with KJ/Noble Sac, just to make sure it's not hardcoded.

**Comment by culinko** [comment]
Attacking with Gladiator's Longbow into Noble Sacrifice with Knife Juggler still damages the attacker.

**Comment by Patashu** [comment]
Ok. I would say that is a bug (both triggers occur in the Combat Preparation Phase, so it is inconsistent that Gladiator's Longbow protects from only one source).

Feel free to re-purpose the bug.

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20743444670 And here's a report of it not being fixed???

**Comment by Patashu** [comment]
Theory: Could be order of play or dominant play related

**Comment by Patashu** [comment]
Not fixed in Patch 5.0. Now it is Dominant Player Bug dependent. https://www.youtube.com/watch?v=Tp-fvE8ODcE

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20745674484 confirmed in 5.0.0.13030

**Comment by troggnostupidhs** [comment]
Potentially fixed.
http://us.battle.net/hearthstone/en/blog/20328179/hearthstone-update-october-20-2016-10-20-2016

**Comment by Patashu** [comment]
It should be tested specifically how it's been fixed, too - if it's still a trigger but now high priority, or if it's some other kind of effect (such as an Aura or game engine rule).

**Comment by Patashu** [comment]
https://gist.github.com/Patashu/c398470ca14896c6b42f15f8e6999722 log of the interaction on current patch

**Comment by troggnostupidhs** [comment]
Tested as id 1 and 2, didn't take damage
