### ISSUE TITLE
Patchwerk ignores Misdirection when attacking with his weapon

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#201]
Patchwerk (Naxxramas boss) ignores Misdirection when attacking with his weapon. However, it is also stated that "The bosses of Naxxramas do not play by the rules. :)" although not specifically directed at this bug since certain cards are banned from use in some Naxxramas boss encounters. There is currently no confirmation from Blizzard that this bug is intended behavior.
* http://us.battle.net/hearthstone/en/forum/topic/13348545343
* http://www.reddit.com/r/hearthstone/comments/2dfjfj/patchwerk_does_not_activate_misdirection_secret/cjpiayu
* http://us.battle.net/hearthstone/en/forum/topic/16716551728 (20 March 2015)

**Comment by jleclanche** [comment]
Cannot reproduce in 4.0.0.10833.

**Comment by culinko** [comment]
This could have been fixed in 3.1, the same patch that fixed Misdirection and Stealth (#121).

**Comment by jleclanche** [comment]
It's likely yeah.
