### ISSUE TITLE
Holy Wrath ignores spell damage if the drawn card is 0-cost

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#21]
When casting Holy Wrath and the drawn card has a casting cost of 0 (such as the Wisp or Target Dummy), the damage done by the spell remains at 0 even if the player has Spell Damage. Using Holy Wrath on a minion with Divine Shield in this situation will not break Divine Shield.

This bug is similar to 2 bugs that has already been fixed, namely using Shield Slam with 0 Armor and using Shadowflame on a 0-attack minion while having Spell Damage used to deal 0 damage incorrectly.

* https://www.youtube.com/watch?v=afl2BgIS9Ms
* https://www.youtube.com/watch?v=FrNis6DEkDQ

**Comment by Patashu** [comment]
This bug has not been verified in a long time, so it may or may not have been fixed in the mean time.

**Comment by jleclanche** [comment]
I believe we verified this in 2.6 or 2.7.

**Comment by Patashu** [comment]
OK, let's say 2.6 then and we'll see if it reproduces.

**Comment by Patashu** [comment]
Proof Shield Slam uses Spell Damage +1 in 3.0:

https://www.reddit.com/r/hearthstone/comments/3ihzt1/tavern_brawl_uhh_mage_with_0_armor_used_shield/

**Comment by Patashu** [comment]
Confirmed in 3.1.

**Comment by culinko** [comment]
This bug has been fixed.
