### ISSUE TITLE
The sandstorm effect is not activated when Nozdormu is brought into play via Deathlord

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#215]
If a Nozdormu is brought into play via the death of Deathlord, the sandstorm effect is not activated. This is purely a visual bug, turns will still last 15 seconds (See Nozdormu timer bug).
- http://www.reddit.com/r/hearthstone/comments/323dcn/possible_nozdormudeathlord_bug/
- http://us.battle.net/hearthstone/en/forum/topic/16859666291

Last confirmed April 2015.

**Comment by culinko** [comment]
Confirmed in 5.0 with Y'Shaarj, Rage Unbound: https://www.reddit.com/r/hearthstone/comments/4kiueg/new_visual_nozdormu_bug/.

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13030 with Y'shaarj

https://www.reddit.com/r/hearthstone/comments/4pm2h7/nozdormu_broken_yet_again/

**Comment by troggnostupidhs** [comment]
Possibly fixed with #214

**Comment by culinko** [comment]
Still happens in 8.0.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20756885897

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6k8ef2/bug_if_madame_goya_brings_nozdormu_from_your_deck/

**Comment by troggnostupidhs** [comment]
Fixed

![img000](https://user-images.githubusercontent.com/22508641/34363886-f483465c-ea4d-11e7-8558-91fbc6c9eb32.png)

**Comment by troggnostupidhs** [comment]
Not sure about Madame Goya.
