### ISSUE TITLE
Thoughtstolen Burrowing Mine explodes when next player draws a card or the original Burrowing Mine is drawn

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#216]
Explodes in hand (if obtained by Thoughtsteal) when next player draws a card, or the original Burrowing Mine is drawn. Unclear what is the triggering condition.
* http://www.reddit.com/r/hearthstone/comments/2ynrs9/if_you_thoughtsteal_a_burrowing_mine_it_explodes/

**Comment by PattuX** [comment]
Might be interesting to know whether HS keeps track of which mine was created from which mine.  Could check this with non-golden Iron Juggernaut, play a golden faceless on it, play Brewmaster on the facelessed and re-play it. Thoughtsteal both mines and see if both trigger when your opponent draws a mine or just the golden/non-golden ones together. Don't have the setup unfortunatelly.

**Comment by culinko** [comment]
I am pretty sure this got fixed in previous patches, but I personally don't have that card so I was not able to test it.

**Comment by culinko** [comment]
Tested in 4.0 and can confirm that it's fixed. If anyone can find out when, you can fill in the milestone.
