### ISSUE TITLE
Minions constantly switching positions on the board

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#217]
In Showdown at Blackrock Mountain, when playing as Ragnaros, if you have Core Hound Pups out on the board, your minions may swap position after you play them. The cause seems to be playing minions fast before or after casting Core Hound Puppies, making the played minion be between the Core Hound Pups on the server but not on the client.
- https://www.youtube.com/watch?v=k-Np0kSJeco
  It appears to also occur with Feral Spirit.
- http://www.reddit.com/r/hearthstone/comments/3a8ui5/the_card_switching_places_bug_is_back_in_tavern/

**Comment by jleclanche** [comment]
Can this be reproduced with Mirror Image?

**Comment by PattuX** [comment]
Happened to ne with Echoing Ooze after attacking.
I'm not sure whether it's the same bug or a different tho.

http://m.imgur.com/a/zoMFP

**Comment by Patashu** [comment]
https://youtu.be/hQ4kOaPLRUA?t=6m30s / https://www.twitch.tv/noxious_hs/v/58578574?t=1h14m48s

This clip is particularly interesting. It shows the swapping minions bug happening during your opponent's turn. I wonder how this is possible...

**Comment by Patashu** [comment]
Report in 5.0

http://us.battle.net/hearthstone/en/forum/topic/20743595400

**Comment by troggnostupidhs** [comment]
I think this has generally been improved, it's not as bad as it was before.
