### ISSUE TITLE
If you use Power Overwhelming on your Echoing Ooze, the newly cloned one will not die at the end of your turn

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#218]
If you use Power Overwhelming on your Echoing Ooze, at the end of your turn, the Ooze clones itself. Then the original Ooze dies horribly, and the clone survives. This 5/6 clone then dies horribly at the end of your opponent's turn. This directly contradicts what Ben Brode said should happen, but is consistent with how triggers are queued in other cases (in particular, if a trigger appears after the queue is finished, it is not added to the queue).
- http://www.youtube.com/watch?v=0NyiP4WINP8
- https://twitter.com/bdbrode/status/491317775387090944

**Comment by VoidMayonnaise** [comment]
https://youtu.be/I11M7KDxHgw
Retest in patch 8.2. Still works. (And I also test it with Brann, the two copies won't die either)

**Comment by troggnostupidhs** [comment]
Still happens.

Deck
AAEBAf0GAu0F7L8CDvsBnAK0ArkGzgbECMwIwg7wEc8WsbAC58sCos0C980CAA==

![hearthstone screenshot 11-10-17 01 19 38](https://user-images.githubusercontent.com/22508641/32645471-6a3f6244-c5b5-11e7-9f3e-fde4c017f537.png)

**Comment by Patashu** [comment]
I think this is now intended, because the second Echoing Ooze isn't around at the start of the 'End of Turn Sequence', meaning its Power Overwhelming isn't expected to trigger as per the new mechanics changes.

Probably long since time to close this one.
