### ISSUE TITLE
Immune characters can be targeted by random effects

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#22]
Random effects can target an Immune character. For example, Avenging Wrath, Ragnaros the Firelord or Ogre Brute can still target an Immune character randomly, but will deal 0 damage. This is cited to be unintended specifically for Avenging Wrath.

https://twitter.com/bdbrode/status/585311581937905664

**Comment by jleclanche** [comment]
I know Brode said it's a bug but I still don't think it is.

**Comment by NightKev** [comment]
Makes sense, though maybe for multi-hit effects like Avenging Wrath they want it to act differently than single-hit effects like Ragnaros.

**Comment by jleclanche** [comment]
Multi-hit effects are just single hit effects that run multiple times. Ragnaros will pick a target and hit it once. Avenging wrath will pick a target and hit it once, and will do that 8 times.

Here's another fun one: What would happen with Cleave? Cleave is playable with 2 enemy minions on the board regardless of their immune state. If you have one immune, one non-immune, the immune one won't get damaged -- but Cleave will still run.
Now consider Deadly Shot. As a Destroy effect, it ignores Immune. If the "random enemy minion" picker wasn't able to pick it, only one of the two minions would get destroyed. And this would be inconsistent with, say, Twisting Nether -- which doesn't pick at all, it just destroys everything.

**Comment by Patashu** [comment]
Notably, Immune is treated as a combination of permanent Stealth and permanent Divine Shield.

This leads to things like:

1) You can have an enemy Taunt Immune minion and bypass it.

2) You can Sacrificial Pact your own Immune Jaraxxus Hero and lose the game.

3) You can attack a Stonetusk Boar with Bestial Wrath into an enemy Vaporize. It dies.

**Comment by culinko** [comment]
I reproduced all of the examples from the initial post in the current patch and here are the logs: https://gist.github.com/culinko/58ce9df8fc3a4d75fc3e

Also, an example with Flamewaker can be seen here: https://www.youtube.com/watch?v=Kri3svWsY7w&t=30s

**Comment by PattuX** [comment]
Confirmed in 4.2

https://youtu.be/kWMj0Lm-qT8?t=9m15s

**Comment by Patashu** [comment]
Confirmed in 5.0

https://www.youtube.com/watch?v=5f1ql_hUiSw&feature=youtu.be

**Comment by troggnostupidhs** [comment]
Why is this labeled 'may be intended'? Didn't Brode confirm it's a bug in the tweet.

This still happens.

![img005](https://user-images.githubusercontent.com/22508641/32863976-6d576e70-ca2b-11e7-84c3-347d71574054.png)

![img007](https://user-images.githubusercontent.com/22508641/32863994-7bdab182-ca2b-11e7-9cad-04c3a4f68ddd.png)


Deck
AAEBAf0EAu0Fl+gCDsAB+wGcArQCqwS0BKAF7AW5BskR9RP0rwLrugLBwQIA

**Comment by troggnostupidhs** [comment]
Not a bug.

![image](https://user-images.githubusercontent.com/22508641/49263156-54447d80-f417-11e8-98b9-d7d248e657e9.png)
