### ISSUE TITLE
After using Tracking, the sidebar will not highlight the picked card and all of the 3 cards will be in different order than presented

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#226]
**Only the player sees the bug.**

After using Tracking, the sidebar will not highlight which card you picked. Also, the cards might be randomly ordered.

Presented cards (picked Tinkertown Technician):

![vmzm2fn](https://cloud.githubusercontent.com/assets/11700272/12883201/ad87b4e6-ce56-11e5-9909-397acf32aac6.jpg)

![fvgc3uy](https://cloud.githubusercontent.com/assets/11700272/12883210/bb9bf952-ce56-11e5-9647-9b94ee146e36.png)

**Comment by troggnostupidhs** [comment]
The order is correct now. It still does not highlight the selected card.

![hearthstone screenshot 12-10-16 09 18 58](https://cloud.githubusercontent.com/assets/22508641/21075135/888092a8-bed8-11e6-90cb-b09b1e5f43a4.png)

![hearthstone screenshot 12-10-16 09 19 11](https://cloud.githubusercontent.com/assets/22508641/21075136/89da5b5c-bed8-11e6-9e9a-c46c572575e0.png)

**Comment by culinko** [comment]
I think the highlighting is not really a bug, just a missing feature I wanted to see :) I think this issue can be closed now.
