### ISSUE TITLE
When a card's state changes while invisible to the opponent, the old state will be displayed to the opponent when played in the sidebar

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#227]
<b>Only the opponent sees the bug.</b>

If your opponent buffs Alarm-o-Bot with a spell such as Blessing of Kings before it swaps for another minion and re-play the bot again, your sidebar will display incorrect stats (4/7 instead of 0/3).
![8thusgr](https://cloud.githubusercontent.com/assets/11700272/11577669/d2c25f7e-9a1f-11e5-8ea7-da8f00f2efa4.png)

Your opponent's sidebar will show the base stats correctly.
![m45svlq](https://cloud.githubusercontent.com/assets/11700272/11577675/da970b64-9a1f-11e5-9bb8-a15add34ffc4.png)

This can also be observed by your opponent playing Entomb on a minion with modified stats.
* https://www.reddit.com/r/hearthstone/comments/3tht9k/fun_observation_about_entomb/

Your sidebar will show the incorrect stats.
![hearthstone screenshot 12-03-15 23 57 56](https://cloud.githubusercontent.com/assets/11700272/11577642/89e7e292-9a1f-11e5-83e3-33c34358adad.png)

Your opponent's sidebar with show the base stats correctly.
![hearthstone screenshot 12-03-15 14 57 37](https://cloud.githubusercontent.com/assets/11700272/11577660/b310bbd0-9a1f-11e5-9992-d4a49fc46640.png)

**Comment by jleclanche** [comment]
It's interesting because I'm not sure how they would fix it. The buff disappears while the card is in the hand and, while the client knows the buff is gone, it doesn't know the state of the card has changed.

I think you'll be able to reproduce the inverse situation with mistcaller: Cards played won't look buffed unless they were revealed prior.

**Comment by jleclanche** [comment]
Delaying the sidebar display until the state update is complete is doable but it's very scary; lots of possible consequences...

**Comment by culinko** [comment]
Observed with Entomb in 4.0:
* https://www.reddit.com/r/hearthstone/comments/3tht9k/fun_observation_about_entomb/

**Comment by culinko** [comment]
Merged into #70.
