### ISSUE TITLE
After your opponent plays Blessing of Wisdom, Power Word:Glory or Corruption on a minion, your sidebar pop-up will show his card back

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#228]
**Only the opponent sees the bug.**

If your opponent plays Blessing of Wisdom, Power Word: Glory or Corruption, your sidebar pop-up will show his card back on hover.

![ijpquta](https://cloud.githubusercontent.com/assets/11700272/12882932/1d361a6e-ce55-11e5-963b-ff9c0261606e.png)

Your opponent's sidebar will show this correctly without a card back.

![xijkkiv](https://cloud.githubusercontent.com/assets/11700272/12882934/25c73e56-ce55-11e5-844f-caa4a466c89d.png)

**Comment by Patashu** [comment]
Confirmed in 4.1

![image](https://cloud.githubusercontent.com/assets/666597/12069925/bd11a222-b0a7-11e5-9965-9c60afb995f7.png)

**Comment by Patashu** [comment]
Confirmed in 5.0 for Corruption

http://us.battle.net/hearthstone/en/forum/topic/20743474636

**Comment by troggnostupidhs** [comment]
Fixed.

Deck
AAEBAaToAgLtBd3CAg6zAfsBnAK0AoUD/gP1BbkG3Qq3bJfBAuLKAqfNApXOAgA=


![img000](https://user-images.githubusercontent.com/22508641/32643560-3b07e98e-c5aa-11e7-8528-e7f601ab09b3.png)

**Comment by troggnostupidhs** [comment]
Fixed

![img000](https://user-images.githubusercontent.com/22508641/32643631-a5a5399a-c5aa-11e7-8d4d-57c4e4f18609.png)
![img001](https://user-images.githubusercontent.com/22508641/32643632-a5b90e3e-c5aa-11e7-9431-ccc0164a87ba.png)
