### ISSUE TITLE
Mad Scientist deathrattle ignores 5 secret limit

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#23]
Normally, there is a limit of 5 secrets that a player may have in play. However, Mad Scientist's Deathrattle ignores this limit. Mad Scientist will correctly not put into play a second copy of currently active secrets, but will put additional different secrets into play if available in the player's deck. This has been shown to allow at least 11 different secrets to be active on a hero at the same time. Secrets beyond the 5 limit will activate and take effect normally, and in the correct order.
- [How did 11 secrets arranged ?｜爐石戰記如何排列11個秘密?](https://www.youtube.com/watch?v=YRIw0nT0vtM)
- https://twitter.com/bdbrode/status/562009044441759744
  ![Tested by User:Taohinton and User:Xinhuan on 2015-02-01](https://cloud.githubusercontent.com/assets/235410/9426775/0eee46f4-4956-11e5-9e11-16c6627822f5.jpg)
  ![Tested by User:Taohinton and User:Xinhuan on 2015-02-01](https://cloud.githubusercontent.com/assets/235410/9426776/0ef0e7d8-4956-11e5-9f3d-b61a56ee4210.jpg)

**Comment by Patashu** [comment]
This has not been confirmed in a very long time.

**Comment by Patashu** [comment]
Confirmed in 3.0 by culinko.

**Comment by Xinhuan** [comment]
Ben Brode states that max secrets in play is 5 yesterday - https://twitter.com/bdbrode/status/691020283113660416 - not new information, but just to put relevant information together in one spot.

**Comment by PattuX** [comment]
Confirmed in 4.2.

**Comment by PattuX** [comment]
Yogg Saron obeys the limit:

* https://www.youtube.com/watch?v=PH-DYhD8A3g

**Comment by troggnostupidhs** [comment]
Mad Scientist still allows more than 5 secrets.

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=lp4X4Fx2J1w&feature=youtu.be&t=7m15s

**Comment by troggnostupidhs** [comment]
This is fixed.

**Comment by troggnostupidhs** [comment]
5 secrets in play

![hearthstone screenshot 08-09-17 12 45 22](https://user-images.githubusercontent.com/22508641/29133302-0245821a-7d01-11e7-873d-885eb1e663a1.png)

Mad Scientist dies, still 5 secrets

![hearthstone screenshot 08-09-17 12 45 34](https://user-images.githubusercontent.com/22508641/29133320-0eedffec-7d01-11e7-85ae-f0400d029be8.png)

Decklist 

```
### Custom Paladin
# Class: Paladin
# Format: Wild
#
# 1x (1) Avenge
# 1x (1) Competitive Spirit
# 1x (1) Eye for an Eye
# 1x (1) Getaway Kodo
# 1x (1) Noble Sacrifice
# 1x (1) Redemption
# 1x (1) Repentance
# 1x (1) Sacred Trial
# 2x (1) Secretkeeper
# 1x (2) Haunted Creeper
# 2x (2) Knife Juggler
# 2x (2) Mad Scientist
# 2x (2) Shielded Minibot
# 1x (3) Coghammer
# 2x (3) Muster for Battle
# 2x (4) Blessing of Kings
# 2x (4) Keeper of Uldaman
# 2x (4) Piloted Shredder
# 2x (5) Sludge Belcher
# 2x (6) Mysterious Challenger
# 
AAEBAYsWCowB6AHOA8gE9Q2MDusP2BTTFou9AgqeAa8HsQj3DYEO6g/tD5AQphXJFgA=
# 
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone

```
