### ISSUE TITLE
Blood Imp's buff trigger is missing in the sidebar

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#233]
**Both player see the bug**

Blood Imp's buff trigger is missing in the sidebar. (Note: Young Priestess has it.)
- http://us.battle.net/hearthstone/en/forum/topic/12675228819

![rptlrcr](https://cloud.githubusercontent.com/assets/11700272/12882631/460ca8b0-ce53-11e5-893d-0bba46441a92.png)

**Comment by troggnostupidhs** [comment]
> Several cards now properly generate a history tile when played.

http://us.battle.net/hearthstone/en/blog/20382066/hearthstone-update-november-29-2016-11-29-2016

This might be fixed.

**Comment by culinko** [comment]
Can confirm this being fixed in the current patch.
