### ISSUE TITLE
If you copy a damaged minion that has less than 50% Health with Faceless Manipulator, the sidebar will show that it died

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#236]
<b>Both players see the bug.</b>

If you copy a damaged minion with Faceless Manipulator, the sidebar will show the amount of damage that is done to the minion.
* http://imgur.com/eawiE3X

However, if you copy a damaged minion that has less than or equal to 50% of its remaining HP, the sidebar will show that it died.
* http://imgur.com/eauV0fV

**Comment by PattuX** [comment]
I just copied a 8/3 Gurubashi Berserker and it was not labeled dead in the sidebar. Also #245 appeared.
(I have the screenshot, but just on iPad, will propably edit it in later)

**Comment by culinko** [comment]
Yep, it seems to be fixed. Nice find.
