### ISSUE TITLE
If you attack with minion buffed with Blessing of Wisdom/Power Word: Glory, the drawn card/healing effect will be missing from the sidebar

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#239]
**Both players see the bug.**

If you attack with minion that has been buffed with Blessing of Wisdom/Power Word: Glory, the drawn card/healing effect will be missing in the sidebar.

**Comment by Patashu** [comment]
Is this related?

http://us.battle.net/hearthstone/en/forum/topic/20419811900

![image](https://cloud.githubusercontent.com/assets/666597/12069925/bd11a222-b0a7-11e5-9965-9c60afb995f7.png)

**Comment by culinko** [comment]
It's #228.

**Comment by culinko** [comment]
Merged into #640.
