### ISSUE TITLE
Misdirection into Noble Sacrifice causes game to hang

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#24]
Noble Sacrifice causes the game server to stop responding if it is triggered at the same time as Misdirection. Noble Sacrifice must be played first then Misdirection so that they trigger in that exact order. The reverse order is not bugged.

----

Video by Bub ChaCha:

[![Bug｜?｜誤導 V.S. 光榮犧牲｜Misdirection V.S. Noble Sacrifice](https://img.youtube.com/vi/lJ0xtvynBVo/0.jpg)](https://www.youtube.com/watch?v=lJ0xtvynBVo)
#### Bug｜?｜誤導 V.S. 光榮犧牲｜Misdirection V.S. Noble Sacrifice

**Comment by Patashu** [comment]
This bug has not been retested in a very long time.

**Comment by culinko** [comment]
The client no longer freezes as of current patch, not sure when precisely was this hang fixed: https://www.youtube.com/watch?v=r66qdxHnAb8&t=1m56s
