### ISSUE TITLE
Death triggers of Corruption/Nightmare/Power Overwhelming are missing from the sidebar

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#240]
**Both players see the bug.**

Corruption/Nightmare/Power Overwhelming death triggers are missing in the sidebar.
- http://www.reddit.com/r/hearthstone/comments/2crv9t/blizzard_please_make_the_deathrattle_effects_to/

![](https://cloud.githubusercontent.com/assets/235410/11100627/086a75d8-88bb-11e5-877e-24fc7a0ac4e3.png)
![](https://cloud.githubusercontent.com/assets/235410/11100626/08575048-88bb-11e5-9304-66629f442b95.jpg)

**Comment by troggnostupidhs** [comment]
Tested Corruption and Power Overwhelming, this is still happening.

**Comment by culinko** [comment]
Merged into #640.
