### ISSUE TITLE
If you obtain Spare Parts from Mech-Bear-Cat, they will have no entry in the sidebar

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#242]
**Both players see the bug.**

If you obtain Spare Parts from Mech-Bear-Cat, they will have no entry in the sidebar.

![hearthstone screenshot 11-12-15 07 38 44](https://cloud.githubusercontent.com/assets/11700272/11112135/7bac714a-8910-11e5-9956-fd488bee5d33.png)

**Comment by jleclanche** [comment]
Confirmed in 4.0

**Comment by culinko** [comment]
Merging into #376.
