### ISSUE TITLE
When you start the game, your gold won't be shown to you until you go to a sub-menu and return back to the main menu

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#243]
I reproduced it myself in the newest patch.

* https://www.reddit.com/r/hearthstone/comments/3sazae/gold_doesnt_show_up_when_you_start_the_game/

**Comment by Xinhuan** [comment]
This bug is now confirmed by Blizzard QA.

http://us.battle.net/hearthstone/en/forum/topic/19741204711

**Comment by culinko** [comment]
Also, your dust will overlap with gold when you enter the play mode for the first time: https://www.reddit.com/r/hearthstone/comments/3seyey/patch_40010833_brings_with_it_a_new_visual_glitch/

**Comment by culinko** [comment]
Fixed in 4.1.
