### ISSUE TITLE
Knife Juggler does not trigger when playing a non-transformation Choose One minion

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#244]
When you have a Knife Juggler on the field and play a Choose One minion that does not transform itself (such as Keeper of the Grove), Knife Juggler will not trigger.

* http://us.battle.net/hearthstone/en/forum/topic/19649066230
* http://us.battle.net/hearthstone/en/forum/topic/19745645170
* https://www.reddit.com/r/hearthstone/comments/3sborw/bug_knife_juggler_doesnt_trigger_after_keeper_of/
* https://www.reddit.com/r/hearthstone/comments/3sbvll/bug_knife_juggler_not_activating/
* https://www.reddit.com/r/hearthstone/comments/3sb5mv/bug_knife_juggler_not_registering/

Sword of Justice also will not trigger, because Sword of Justice is also a trigger in the After Summon Phase.
* https://www.reddit.com/r/hearthstone/comments/3ssqob/knife_juggler_sword_of_justice_bugs/

**Comment by Patashu** [comment]
Yong Woo has acknowledge this bug.

**Comment by jleclanche** [comment]
So they *did* change Choose Ones this patch. I'm starting to really wonder why.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3sjthq/new_angry_chicken_enrage_bug/cwy1huo

May occur for 'Summon 2 Saplings' effect of Living Roots too

**Comment by Patashu** [comment]
Sword of Justice also will not trigger, because Sword of Justice is also a trigger in the After Summon Phase.
* https://www.reddit.com/r/hearthstone/comments/3ssqob/knife_juggler_sword_of_justice_bugs/

**Comment by 10925** [comment]
Should be hot fixed, test Knife Juggler with Grove tender, Robo Cub and keeper of grove.
They all trigger normally.

**Comment by jleclanche** [comment]
Yeah this was in the last hotfix.
