### ISSUE TITLE
Faceless Manipulator does not correctly copy buffs

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#245]
When you target a buffed minion with Faceless Manipulator, not all of the buffs copy. (However, all of the damage copies, meaning the Faceless Manipulator might have 0 or less Health and die.)

* https://imgur.com/a/h3es2
* http://us.battle.net/hearthstone/en/forum/topic/19745185172
* http://us.battle.net/hearthstone/en/forum/topic/19864696351
* https://www.reddit.com/r/hearthstone/comments/3sb4re/unofficial_patch_notes_400/cwwjakn
* https://www.reddit.com/r/hearthstone/comments/3si0f0/is_this_a_bug/
* https://www.reddit.com/r/hearthstone/comments/3sknpm/gruulfaceless_bug_in_loe/

The pattern seems to be that a self-applied buff is copied as though it was only applied once, not the actual number of times it applied. It seems to happen with Mirror Entity as well.

* http://us.battle.net/hearthstone/en/forum/topic/19877517587

Acknowledged by @bdbrode [here](https://twitter.com/bdbrode/status/665375493189795841).

**Comment by PattuX** [comment]
At the moment it only seems to appear on self buffing minions. 
I tried several (Unbound Elemental, Murloc Tidecaller, Gurubashi Berserker, Frostwolf Warlord, Undertaker) once and they mostly worked fine, just Gurubashi was copied 5/3 instead of 8/3 once.
(will edit in Screenshot later)

**Comment by Patashu** [comment]
Yong Woo has acknowledge this bug.

**Comment by Xinhuan** [comment]
More reports:

Kvaldir: http://us.battle.net/hearthstone/en/forum/topic/19864696351 (has SS)
Gruul: http://us.battle.net/hearthstone/en/forum/topic/19864856363 (no SS)

**Comment by culinko** [comment]
Lightwarden: https://www.reddit.com/r/hearthstone/comments/3sb4re/unofficial_patch_notes_400/cwwjakn

**Comment by Patashu** [comment]
Scavenging Hyena:
https://www.reddit.com/r/hearthstone/comments/3si0f0/is_this_a_bug/

**Comment by Patashu** [comment]
I think this may also occur with Mirror Entity.

http://us.battle.net/hearthstone/en/forum/topic/19877517587 Draenei Totemcarver vs Mirror Entity

**Comment by jleclanche** [comment]
Guessing the copy mechanic is borked. Echoing Ooze bugged as well?

**Comment by PattuX** [comment]
Still my theory that this only applies to self-buffing minions seems to be true and until we find any counterexamples I doubt that this also happens with Ooze, as it cant buff itself.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3sknpm/gruulfaceless_bug_in_loe/ Gruul with Screenshot

**Comment by jleclanche** [comment]
Maybe it has to do with buff stacking rather than specifically self-buffs. But I think only self-buffs can stack?

**Comment by Patashu** [comment]
Yeah, that's my gut feeling too. IIRC if an enchantment is applied multiple times with no other enchantments in between, they coalesce into a single Entity. I don't understand all the rules, because until this bug appeared it didn't matter if two enchantments coalesced into one or not.

**Comment by PattuX** [comment]
So if you theory with only copying one itteration of each buff is correct, does that mean Draenai Totemcarver gets buffed by +1/+1 multiple times instead of e.g. +3/+3 at one time?

Btw, what does "enchantments" include? Also Spell or Battlecry buffs?

**Comment by Patashu** [comment]
I think that enchantments that can coalesce have a base version (like +1/+1 for Draenei Totem Carver) and a variable that indicates how many times to repeat it, and that Faceless is forgetting to copy the variable.

Enchantments are all Entities that can be attached to another Entity, including changes in Mana Cost, to Attack, Health, temporary enchantments that will trigger later and do something (Corruption, Nightmare, Power Overwhelming, Shadow Madness, Conceal/Finicky Cloakfield), etc. Turning on logging will help you understand it ( https://github.com/jleclanche/fireplace/wiki/How-to-enable-logging )

**Comment by PattuX** [comment]
Yea, I already thought something like that. At first it seemed strange to me, as it didn't bug with Frostwolf, but I already thought something similar. Draenei might check every single card for the totem tag and get +1/+1 per totem while Frostwold might just request the number of minions and get buffed by +x/+x. 
Also it always annoyed me, that the now affected self-buffing card just say "Increased stats" instead of concrete values... 

I already enabled logging but I prefer playing on iPad ^^

**Comment by jleclanche** [comment]
@Patashu @PattuX Buff stacking is, afaik, a flag on certain buffs which is unfortunately not available in the files or logs :/

**Comment by Xinhuan** [comment]
More data and more minions affected: 
Mana Wyrm, Holy Champion, Scavenging Hyena, Frothing Berserker, Bolvar Fordragon, Kvadir Raider.

https://www.reddit.com/r/hearthstone/comments/3srckh/til_dont_use_facless_manipulator_on_buffed/

The summary is that it (seems that) only 1 stack of any buff is copied if there are multiple stacks of it present..

**Comment by jleclanche** [comment]
@Xinhuan @Patashu Any new reports since? If they died down it's possible this was hotfixed.

**Comment by Patashu** [comment]
(reposting here) Report from 7 hours ago:

http://us.battle.net/hearthstone/en/forum/topic/19974497941

**Comment by Patashu** [comment]
video:

https://youtu.be/rb6AlS2Iicc

**Comment by culinko** [comment]
We tested it in 4.1 and it's fixed.
