### ISSUE TITLE
AI using Removal cards on own minions

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#246]
This happened 2 times to me so far since 4.0, didn't happen before the patch.

First time: AI played Northshire Cleric turn 1, Shadow Word: Pain turn 2.
Second time: My board was: Ancient of Lore, Azure Drake, Druid of the Claw (Charge). AI played Silverback Patriarch and used Shadow Word: Pain (can't remember if it happened in the same turn or not).

So looks like AI is playing spells (in this case Shadow Word: Pain) just because it "can".

**Comment by culinko** [comment]
https://www.reddit.com/r/hearthstone/comments/3sf91w/resolved_various_issues_with_ai_behavior_and/

**Comment by Xinhuan** [comment]
More examples of AI using SW:P on its own minions.

* https://www.reddit.com/r/hearthstone/comments/3swpbu/ladies_and_gentlemen_i_present_to_you_the/cx16mhb
* https://www.reddit.com/r/hearthstone/comments/3swpbu/ladies_and_gentlemen_i_present_to_you_the/cx12a8x

AI casts Rampage on player's minion:
* https://www.reddit.com/r/hearthstone/comments/3swpbu/ladies_and_gentlemen_i_present_to_you_the/cx17nyb

**Comment by culinko** [comment]
Merged into #8.
