### ISSUE TITLE
Sound effects scale with number of actors, making them much louder in some cases

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#247]
This bug was introduced in Patch 4.0. It happens with multiple card effects.

Savage Roar:
* https://www.reddit.com/r/hearthstone/comments/3sb4re/unofficial_patch_notes_400/cwvog6r

Mysterious Challenger (Secrets):
* https://www.reddit.com/r/hearthstone/comments/3seygs/mysterious_challenger_is_too_loud_patch_400/

More cards: Unleash the Hounds, Mukla's Champion, Blizzard.

**Comment by culinko** [comment]
Also the sound of Unleash the Hounds is louder (it sounds like a same sound effect), but my results varied (didn't hear the bug when unleash spawned 3 minions, but did hear it when unleash spawned 6).

**Comment by culinko** [comment]
More loud sound effects. The secrets put into play by Mysterious Challenger have a loud sound effect: https://www.reddit.com/r/hearthstone/comments/3seygs/mysterious_challenger_is_too_loud_patch_400/

**Comment by HearthstoneBugs** [comment]
Doing a search in My Collection also produces a louder sound than usual for the "clonk" that is heard - for example, search for Epic and the "clonk" is too loud compared to the other sounds and compared to the volume that it used to be. This also only started happening in patch 4.0.0.10833

**Comment by culinko** [comment]
I can confirm the sound bug in My Collection. It happens if your filter makes a tab being hidden or shown. For example if I search for "death", the mage tab gets hidden (because I don't have Rhonin).

**Comment by HearthstoneBugs** [comment]
When Mukla's Champion distributes his bananas the sound effect used is also far too loud.

**Comment by jleclanche** [comment]
All sounds that scale with number of actors?

**Comment by culinko** [comment]
It's possible that this is indeed the case for all the sounds that appear during the game that are listed here.

As for the bug in My Collection, I think it only happens with 1 tab, there are different sound effects when hiding and showing multiple tabs at one.

**Comment by jleclanche** [comment]
Looks like they fixed it internally for next patch:

https://twitter.com/bdbrode/status/669569022543851520

**Comment by culinko** [comment]
Verified with Unleash the Hounds and the bug is fixed.
