### ISSUE TITLE
Playing a Spell that has its Mana Cost modified by an aura shows the original mana cost for the opponent

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#250]
When your opponent plays a Spell that had its mana cost modified by an aura, it will display the original mana cost on the card when it enters the play.
- https://www.reddit.com/r/hearthstone/comments/3sdffm/new_bug_after_patch_cards_not_showing_discounted/ (Only the 1st and 3rd paragraph are correct; minions from Unstable Portal are working fine, I tested it.)
- https://www.reddit.com/r/hearthstone/comments/3sb4re/unofficial_patch_notes_400/cwvru0u

![2yjn7sw](https://cloud.githubusercontent.com/assets/11700272/12076980/4cdfd44a-b1c6-11e5-9d61-243f74d2389d.jpg)

This bug only happens with auras (Sorcerer's Apprentice, Loatheb) and not buffs (Emperor Thaurissan). If both an aura and a buff modified the cost of the spell, only the buff modification will be shown. Example: Opponent plays Emperor Thaurissan (1 tick), then you play Loatheb, then they play Frostbolt for 6 mana (it shows 1 mana in green color on the card when it enters the play).

**The same bug happens also in sidebar. Only the opponent sees the bug.**

After your opponent plays a Spell that had its mana cost reduced or increased by auras, such as Sorcerer's Apprentice or Loatheb, your sidebar will display the original cost.

![vqhjmfs](https://cloud.githubusercontent.com/assets/11700272/12076974/22a9430a-b1c6-11e5-9f43-2ba2ae2b7495.png)

Your opponent will see the correct value.

![pbfy9is](https://cloud.githubusercontent.com/assets/11700272/12076976/2d7e5306-b1c6-11e5-8455-89cb720bc667.png)

**Comment by Patashu** [comment]
Confirmed in 4.2?

http://us.battle.net/hearthstone/en/forum/topic/20742945078

**Comment by culinko** [comment]
I tested this in 7.0 and the issue is fixed now.
