### ISSUE TITLE
When Sacrificial Pact is played, one or both players may disconnect

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#253]
When Sacrificial Pact is played, one or both players may disconnect before the Sacrificial Pact's effects have finished. If you disconnect and reconnect immediately, you may resume playing the game.
* http://us.battle.net/hearthstone/en/forum/topic/19865056335
* https://www.reddit.com/r/hearthstone/comments/3sdw0f/dreadsteed_sacrificial_pact_makes_hs_crash_on/

**Comment by Patashu** [comment]
Seems to only happen on iPad/iPhone.

**Comment by Patashu** [comment]
Yong Woo has acknowledged this bug on twitter. It is being investigated.

**Comment by PattuX** [comment]
Fixed according to patchnotes (on my iPad this is 4.0.10833 now, the LoE patch was 4.0.10784)

**Comment by Xinhuan** [comment]
The patch notes on iOS is just 3 lines:

![img_1064](https://cloud.githubusercontent.com/assets/17907/11260302/c0326042-8ea4-11e5-9748-ea938ec39be1.PNG)

> Patch 4.0.10833
BUG FIXES
* Resolved a stability issue involving Sacrificial Pact.
