### ISSUE TITLE
No card shuffling animation when Forgotten Torch is played

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#254]
The created card 'Roaring Torch' is not visibly shuffled into the deck; there is no animation for it, giving the impression that the card is not created.

http://us.battle.net/hearthstone/en/forum/topic/19890708878

Acknowledged by Blizzard QA: http://us.battle.net/hearthstone/en/forum/topic/19891108970

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6silqm/forgotten_torch_after_use_now_shuffles_a_roaring/
