### ISSUE TITLE
Sacred Trial triggers on Lord Jaraxxus the Hero but does nothing

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#255]
When you play Repentance or Snipe and your opponent plays Lord Jaraxxus, these Secrets trigger on Lord Jaraxxus the Hero and have their expected effect.
* https://www.youtube.com/watch?v=n8u2Senk_XU

This is because they are hard-coded to work this way. Normally the Secrets can only trigger on minions.
* https://twitter.com/bdbrode/status/532326185305243649

When you play Sacred Trial and your opponent plays Lord Jaraxxus while having 4 or more minions on the board, Sacred Trial triggers, targets Lord Jaraxxus the Hero but has no effect. To be consistent, it should either trigger and destroy Lord Jaraxxus the Hero or not trigger at all.
* https://www.youtube.com/watch?v=GE8xQJDuodA

**Comment by Patashu** [comment]
Hotfixed:

https://www.reddit.com/r/hearthstone/comments/3tqtby/jaraxxus_and_sacred_trial_have_been_fixed/

**Comment by Xinhuan** [comment]
Videos proving it is hotfixed:

https://www.youtube.com/watch?v=079AdKILZM8 (Paladin viewpoint)
https://www.youtube.com/watch?v=zWPrPJGfDTI (Warlock viewpoint)

Jaraxxus just explodes with no animation from Sacred Trial.

**Comment by culinko** [comment]
@Xinhuan Should we create an issue for the missing animation? (Will probably be fixed in the next patch anyway).

**Comment by jleclanche** [comment]
@culinko No, leave it - the anim couldn't be hotfixed in anyway.

**Comment by culinko** [comment]
Looks like this hotfix got reverted in 4.1.0.10956.

**Comment by Patashu** [comment]
Looks like in 4.2 Sacred Trial kills Lord Jaraxxus again:

http://us.battle.net/hearthstone/en/forum/topic/20742994611

Needs a confirmation, including checking exact number of other friendly minions required for it to go off (as the report indicates it's bugged, but has no proof)

**Comment by 10925** [comment]
Videos of the proof that Sacred Trial vs Lord Jaraxxus in patch 4.2.
https://www.youtube.com/watch?v=PMZPUfQgCIM&feature=youtu.be

**Comment by culinko** [comment]
Closing this as fixed, opened #408 for the current behavior.
