### ISSUE TITLE
Playing Faceless Manipulator on a Battlecry Minion triggers Rumbling Elemental twice

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#257]
If you play Faceless Manipulator targeting a Battlecry Minion, your Rumbling Elementals trigger twice in the After Play Phase, instead of just once.
- https://www.youtube.com/watch?v=ZF_205XWfmo

This was fixed a week later.
- https://www.youtube.com/watch?v=gRWmVzANWD0

As of Patch 5.0, this bug is back. Proof: Faceless Manipulator on a Rumbling Elemental causes both to trigger (expected result: neither should trigger, since the played minion is no longer a Battlecry minion)
- https://youtu.be/yfYlOXFyMao

**Comment by Patashu** [comment]
https://twitter.com/ywoo_dev/status/665704459545108480 Yong Woo says it will be looked into

**Comment by jleclanche** [comment]
This is probably #108.

**Comment by Patashu** [comment]
I disagree.

108 refers to the Summon Resolution Step. Summon Events are put in a Summon Event Queue when created, and resolved each Summon Event Step. In addition, Transform Events (like Faceless Manipulator turning into a Beast) are put in a Transform Event Queue, and the Special Summon Resolution Step (replacing the normal Summon Resolution Step following the After Summon Phase) resolves both these Queues.

An example of a Summon trigger triggering twice on the same played minion is if you play Druid of the Saber against Maloriak - Maloriak triggers in the Summon Resolution Step following the On Play Phase to swap stats, then in the Special Summon Resolution Step following the After Summon Phase to swap stats a second time.

In the case of Rumbling Elemental, if you Faceless a Battlecry Minion, Rumbling Elemental does not trigger before and after the Battlecry, Rumbling Elemental triggers twice in the After Play Phase.

**Comment by PattuX** [comment]
Despite the fact that it is clearly bugged imo, is there any reason I don't see to yet introduce another possible phase to trigger for minions coming into play? 
I mean we got the bugged Pre-summon trigger, On play trigger, Summon Resolution Trigger, After Summon Trigger and now even After Play trigger.
I see the reasoning for On play trigger, as you don't want some cards to trigger on Battlecry/Deathrattle/Secret/Spell summons (e.g. Hobgoblin + Unleash), and for Summon resolution (as you stated in #108), but why do we really need After Summon and After Play triggers? Sure, some interactions would change but nothing seems really problematic...

**Comment by Patashu** [comment]
After Summon Phase exists to prevent Illidan+KJ interactions from becoming too easy. If you could do them with just KJ, everyone would start doing them in ranked matches and it would be a big mess for Blizzard.

After Play Phase exists because Blizzard wants Mirror Entity to copy the post-Battlecry state.

So I feel like those have very strong rationale to exist.

IMO, if anything, I'd like to see all summon resolution step trigger be made either after summon triggers (maloriak, starving, one-eyed cheat, undertaker, knight of the wild) or auras (CS, coldarra, garrison). That would remove a very large part of IMO unneeded complexity from the model.

**Comment by PattuX** [comment]
I don't see what exactly you mean by Illidan + KJ interactions...
But now you mentioned Mirror Entity, KJ triggering after e.g. Razorfen Hunter and killing an Explosive Sheep/Abom would make Mirror Entity not copy the After-battlecry state.
Still I agree, that After Summon and Summon Resolution don't need both to exist as they could be merged into one quite easily.

I saw why Secrets triggered in the After Play Phase, I just wondered why Rumbling, Elemental, too. I guess they didn't want to make him trigger on summon effects, so basically there was only On Play left. The only thought I got is that this would enable Stealing Battlecries much easier with only Elemental and Sheep, so that it might occur even in real games, which is tbh not intuitive at all, so they propably just put him into the Secret triggers.
Making him On Play trigger doesn't change Mirror Image interactions at all.

**Comment by Patashu** [comment]
Fixed a week later in a hotfix:

https://www.youtube.com/watch?v=gRWmVzANWD0

**Comment by Patashu** [comment]
This bug is back.

Hat tip /u/Jess_than_three

https://youtu.be/yfYlOXFyMao

**Comment by Patashu** [comment]
Confirmed in 7.0 - player facelesses an enemy Rumbling Elemental, and the post-transform Rumbling Elemental triggers once (For the faceless)

https://us.battle.net/forums/en/hearthstone/topic/20752565965

**Comment by culinko** [comment]
Tested in 7.0: Using Faceless Manipulator on another battlecry minion of yours will trigger the Rumbling Elemental twice.

However, using Faceless Manipulator on your Rumbling Elemental triggers each Rumbling Elemental just once.  Log of the interaction: https://gist.github.com/culinko/25e1a3ccc618a9bb5b121e4019de75b8.

**Comment by Patashu** [comment]
Yup, that's what I expect to happen in the bugged version.

**Comment by Kybxd** [comment]
Still happening in 8.0(https://youtu.be/QwmOfhaOfho)

Related to #727 ,will Faceless (or other battlecry-transformed minions) trigger Sherazin twice? Will a 1-cost Faceless transfroming into a 1-cost minion trigger Hunter Quest twice?

Besides, I notice the 2/2 Murloc died directly rather than stayed in the battlefield as a 2/0,  indicating a Death Phase is inserted between the 2 hits?

**Comment by Patashu** [comment]
The Death Phase between both Rumbling Elemental triggers is extremely surprising and confusing. There's no existing mechanic that can explain this.

**Comment by troggnostupidhs** [comment]
Faceless targeting a Battlecry minion only triggers Rumbling once

![hearthstone screenshot 06-03-17 14 41 10](https://cloud.githubusercontent.com/assets/22508641/26756224/6c3e6a4e-486b-11e7-80f5-524a4970d98d.png)

![hearthstone screenshot 06-03-17 14 41 14](https://cloud.githubusercontent.com/assets/22508641/26756225/6eee6bf4-486b-11e7-8692-f8b508e6e3d1.png)

----

Faceless targeting Rumbling triggers both Rumblings (see sidebar)

![hearthstone screenshot 06-03-17 14 43 56](https://cloud.githubusercontent.com/assets/22508641/26756232/874d30ea-486b-11e7-8abe-2b2e18c47ea5.png)

**Comment by VoidMayonnaise** [comment]
https://youtu.be/gfdGYntQD88
Rumbling Elemental won't trigger twice now, but there's still inconsistency between Faceless and normal minions with battlecry. KJ will trigger before RE, which is quite strange.

**Comment by Kybxd** [comment]
Further test:
Faceless to a 1-cost minion doesn't count for Hunter Quest.(http://imgur.com/a/XhoUg)
For self-transfrom minions, Sherazin triggers later than KJ, while Hidden Cache doesn't trigger.(http://imgur.com/a/8WyAM)

So I think playing a self-transforming minion should work like this:(starting from Battlecry Phase)
1.Battlecry Phase:
1)Transform
2)After-play events for the post-transform minion, including 5 secrets and Dred
3)After-summon events for the post-transform minion, including all after-summon triggers
2.After Play Phase:
After-play events for the pre-transform minion, including Rumbling, Sherazin, Rogue&Hunter Quest
3.After Summon Phase:
No triggers 

So all after-play events should be divided into 2 timings according as its effect is related to the post-transform minion or not. The only exception(or bug) is Hidden Cache, which doesn't trigger in either timing.

**Comment by troggnostupidhs** [comment]
Starts at 4:32

https://youtu.be/OLLqOIvol1o?t=272

**Comment by troggnostupidhs** [comment]
Fixed

Deck
AAEBAfe5AgLcAu0FDr0B+wGcArQCkwT+BbkG0RPIFvmqAqC2ApvCAofEAtPFAgA=

![img000](https://user-images.githubusercontent.com/22508641/31864261-8f9e453c-b728-11e7-9a00-5b25f2e4e0e9.png)
