### ISSUE TITLE
Djinni of Zephyrs can trigger on a targeted Choose One minion

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#258]
If you play a targeted Choose One minion on a friendly target, such as Keeper of the Grove, any friendly Djinni of Zephyrs will trigger in the After Play Phase.

* https://www.youtube.com/watch?v=djSKr0dO4ds

**Comment by ZeroRin** [comment]
don't think that is a side-effect of this bug. it's only because knife juggler doesn't trigger for keeper of the grove

**Comment by Patashu** [comment]
You're right, I only realized it after I went to bed -.- Sigh lol

**Comment by Patashu** [comment]
Yong Woo says 'a fix is imminent' https://twitter.com/ywoo_dev/status/665704345850134528

**Comment by Patashu** [comment]
Yong Woo says 'a fix is imminent' https://twitter.com/ywoo_dev/status/665704345850134528

**Comment by Patashu** [comment]
If Knife Juggler vs Choose One was hotfixed, it's highly likely this also got hotfixed.

**Comment by 10925** [comment]
Yeah, test with Innkeeper myself.
I test all Keeper of the Grover's 2 effect, and Ancient of Lore's heal.
No one triggers.
It should be fixed.
