### ISSUE TITLE
Savage Roar can't be silenced

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#26]
The effects of Savage Roar cannot be silenced off. The minions retain +2 Attack even after silencing them. This bug does not occur with Bloodlust.

* https://www.reddit.com/r/hearthstone/comments/377qna/you_cant_silence_savage_roars_buff/
* [[Hearthstone Science] Savage Roar Silence Bug](https://www.youtube.com/watch?v=a6sYGOwLnAs)
* https://www.reddit.com/r/hearthstone/comments/22r3eh/savage_roar_immune_to_silence_bug/
* [Hearthstone - Savage Roar immune to Silence? BUG](https://www.youtube.com/watch?v=21Q5PZ41Taw)

**Comment by Patashu** [comment]
This might be fixed in 3.0? Lord Jaraxxus's Savage Roar buff can be silenced off using Light's Champion.

https://www.reddit.com/r/hearthstone/comments/3m3c33/til_lights_champion_can_silence_jaraxxus/

**Comment by Patashu** [comment]
Confirmed fixed in 3.0 by Xinhuan. Tested with Spellbreaker and Wailing Soul.
