### ISSUE TITLE
Heroic Phaerix - the Rod of the Sun does not correctly update its +3/+3 buff

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#262]
In the Heroic Phaerix encounter, the Rod of the Sun has a +3/+3 buff, and the tooltip says that the buff is maintained while Phaerix controls the Rod. However, this is actually an Enchantment on the rod itself. If you steal the Rod (using Shadow Madness or otherwise), the Enchantment maintains. If you Silence the Rod, the Enchantment dissappears. Note that Phaerix correctly loses Immune when the Rod is stolen, for example.

* https://www.youtube.com/watch?v=0uIpspLg_HU

**Comment by jleclanche** [comment]
To be clear, the rod gains the buff when it is created in Phaerix's control. It's a weird way to do it.

**Comment by jleclanche** [comment]
Closing as invalid. Per discussion in the channel, this is likely intended to allow for silence, aldor and similar mechanics.
