### ISSUE TITLE
Some cards incorrectly use 'whenever' instead of 'after' in their description

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#263]
**Fixed in 4.1.0.10956:**

Cards that are written like they trigger in the On Play Phase of playing a spell (e.g. before the spell effects), but actually trigger in the After Spell Phase (e.g. after the spell effects):
* Djinni of Zephyrs (Whenever -> After)

Cards that are written like they are Summon Event triggers (like Starving Buzzard etc) (e.g. before the Battlecry), but actually trigger in the After Summon Phase (e.g. after the Battlecry):
* Sword of Justice (Whenever -> After)
* Ship's Cannon (Whenever -> After)

**Fixed in 4.2.0.12051:**

Cards that are written like they trigger in the On Play Phase of playing a minion (e.g. before the Battlecry), but actually trigger in the After Play Phase (e.g. after the Battlecry):
* Sacred Trial (When -> After)
* Mirror Entity (When -> After)
* Repentance (When -> After)
* Snipe (When -> After)

**Fixed in 5.0.0.12574:**

Cards that are written like they trigger before the Hero Power, but actually trigger after the Hero Power:
* Dart Trap

**Comment by Xinhuan** [comment]
Djinni of Zephyrs, Sword of Justice and Ship's Cannon have their text updated from "Whenever" to "After" in Patch 4.1.0.10956.

**Comment by jleclanche** [comment]
I think the whole secrets timing thing might be worded like this on purpose.

**Comment by Patashu** [comment]
I still think making the secrets say 'after' instead of 'when' will make them much easier to understand.

**Comment by jleclanche** [comment]
I do too, but I'd like to hear a designer's take on it.

**Comment by Patashu** [comment]
Added Dart Trap, since according to http://hearthstone.gamepedia.com/Dart_Trap it triggers after, not before, the Hero Power resolves.

**Comment by Xinhuan** [comment]
Sacred Trial, Mirror Entity, Snipe and Repentence have their text updated from "When" to "After" in Patch 4.2.0.12051.

Dart Trap remains the only one that still uses "When".

**Comment by jleclanche** [comment]
Dart Trap is arguable (there's no "when" for using hero powers right now), so I suggest we close this.

**Comment by Patashu** [comment]
Yay for Mirror Entity et all. being fixed!

Dart Trap definitely needs to be changed still. It triggers after, not whenever (before) your Hero Power resolves and all subsequent death processing.

**Comment by culinko** [comment]
Dart Trap has been fixed in 5.0.0.12574.
