### ISSUE TITLE
A spell countered by Counterspell still overloads you

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#265]
In 4.0, Overload was changed from occurring in the Battlecry/Spell Text Phase to occuring when you play the card from your hand. This means that if you play a spell with Overload but it is countered by Counterspell, you still gain the Overload.
* http://us.battle.net/hearthstone/en/forum/topic/19877077551?page=1#4
* https://www.reddit.com/r/hearthstone/comments/3sinir/bug_with_overload/

Specifically in the case of Spells, this is said to be unintended by Ben Brode.
* https://twitter.com/bdbrode/status/666431386396459008

**Comment by Patashu** [comment]
I thought that this is an intended change when I found out about it, it made sense because it would make it so Brann Bronzebeard doesn't double overloading battlecries (like Fireguard Destroyer). But Ben Brode says it's a bug for spells so it's a bug for spells.

(I'll talk about this in the Brann Bronzebeard video.)

**Comment by Xinhuan** [comment]
Followup tweet from bdbrode (which answered jleclanche)  that agrees that fixing double overload from Battlecry is probably the cause of the bug, but that it is an unintended side effect for spells.

https://twitter.com/bdbrode/status/666459940249178112
