### ISSUE TITLE
Copying multiple deathrattles from Unearthed Raptors with another Unearthed Raptor crashes the game

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#269]
When copying multiple deathrattles from Unearthed Raptors that already copied some Unearthed Raptors with another Unearthed Raptor crashes the game (happens only with Brann Bronzebeard on the board?). Players can't connect back to the game until it times out .
* https://www.youtube.com/watch?v=EC-KXTJAhbE

**Comment by Xinhuan** [comment]
Quite a lot of reports for it.

http://us.battle.net/hearthstone/en/forum/topic/19973037197
http://us.battle.net/hearthstone/en/forum/topic/19975167378

Some players report that their game client crashes to desktop/home screen, while others just get a game hang (infinite duration turn).

It is possible the player playing Unearthed Raptor crashes, while the opponent just hangs, based on what I've been reading.

**Comment by jleclanche** [comment]
This is an animation issue (rooted in the engine), not a simulation issue.

**Comment by PattuX** [comment]
Fixed.
https://www.youtube.com/watch?v=wLhRoK7kBNM
http://us.battle.net/hearthstone/en/forum/topic/19975167581
Capped to 16 Deathrattles now.

**Comment by culinko** [comment]
Hotfixed 2 days after the release of 2nd wing.
