### ISSUE TITLE
Snake Trap can trigger on a full board

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#27]
If your board is full, Snake Trap will still trigger when one of your minions is attacked and produce no snakes. This is inconsistent because Noble Sacrifice, Mirror Entity and Spellbender do not trigger if your board is full. However, an argument can be made that this is because Snake Trap has the potential to offer partial value (0 to 3 snakes), while the other secrets are "all or nothing" value.

https://www.reddit.com/r/hearthstone/comments/2ybrrn/secrets_inconsistency_duplicatesnake_trapenoble/
[[Hearthstone Science] various Ogre Brute and Traps interactions ](https://www.youtube.com/watch?v=eVcQO3BlRe8&t=2m16s)

Snake Trap and Duplicate triggering and doing nothing is confirmed to be a bug by Ben Brode:

* https://twitter.com/bdbrode/status/641772668841164801

**Comment by Patashu** [comment]
Duplicate triggers if your hand is full, also.

**Comment by Patashu** [comment]
Confirmed to be a bug by Ben Brode:

https://twitter.com/bdbrode/status/641772668841164801

**Comment by Patashu** [comment]
Snake Trap confirmed in 3.1 by Adys.

Duplicate not re-confirmed

**Comment by Patashu** [comment]
Duplicate and Snake Trap need to be confirmed in 4.0

**Comment by culinko** [comment]
Tested and Snake Trap no longer triggers with full board, Duplicate no longer triggers with full hand.
