### ISSUE TITLE
Sometimes, if your opponent plays an Unearthed Raptor, your client will hang

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#270]
Sometimes, if your opponent plays an Unearthed Raptor, your client will hang and you will have to reconnect in order to continue. This bug has been observed with or without copying a deathrattle and on multiple platforms. An easy way to tell whether you're affected is that the sidebar entry won't be created.

Bloodmage Thalnos:
* https://www.reddit.com/r/hearthstone/comments/3thaz0/unearthed_raptor_breaks_the_game/

Loot Hoarder:
* https://www.reddit.com/r/hearthstone/comments/3thcry/the_new_unearthed_raptor_may_be_bugged/cx65scd?context=100

Nerubian Egg:
* https://www.reddit.com/r/hearthstone/comments/3tl2lv/botters_are_unable_to_play_against_new_cards/cx71i9b
* http://us.battle.net/hearthstone/en/forum/topic/19973717312

**Comment by jleclanche** [comment]
This seems extremely unlikely to be caused by "draw a card". I want to see a Power.log...

**Comment by Xinhuan** [comment]
http://us.battle.net/hearthstone/en/forum/topic/19974347318

This player thinks playing it on his creeper/egg is causing his opponents to disconnect randomly; might not be related to card draw deathrattles.

**Comment by PattuX** [comment]
Can confirm for both.

**Comment by PattuX** [comment]
Unfortunally, I have no screenshot, but earlier today when I played on my iPad, my opponent disconnected when I just played Raptor without using his battlecry.

**Comment by PattuX** [comment]
I just made the AI disconnect...
http://imgur.com/a/9lZsD (see timestamps)
Also I can't concede.
When restarting HS I just got into main menu as if nothing happened.
Logs (from playing Unearthed until end): https://gist.github.com/PattuX/b717bfb761bc1ec2f498

**Comment by culinko** [comment]
We have verified the bug being fixed.

**Comment by jleclanche** [comment]
Part of this was hotfixed in 4.0.
