### ISSUE TITLE
You don't get overloaded if your opponent has a Fel Reaver

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#272]
If your opponent has a Fel Reaver in play and you play an Overload card, you don't gain any Overload. So cards like Tunnel Trogg will not gain any Attack.

* http://us.battle.net/hearthstone/en/forum/topic/1997403725
* https://www.youtube.com/watch?v=5CGK9WgyaHc

**Comment by culinko** [comment]
The link is not working for me.

**Comment by Xinhuan** [comment]
The correct Battle.net link is missing the digit "6" at the end:

http://us.battle.net/hearthstone/en/forum/topic/19974037256

**Comment by PattuX** [comment]
There's a report which states that the overload doesn't apply aswell (twice):
http://us.battle.net/hearthstone/en/forum/topic/19973427459

**Comment by culinko** [comment]
More tests, also stating the player does not gain overload: 
https://www.reddit.com/r/hearthstone/comments/3tp4kd/bug_making_your_opponent_burn_cards_with_fel/

**Comment by Xinhuan** [comment]
Another report confirms this:
http://us.battle.net/hearthstone/en/forum/topic/19973187317

**Comment by ericBG** [comment]
According to [this](https://www.reddit.com/r/hearthstone/comments/3tp4kd/bug_making_your_opponent_burn_cards_with_fel/) Reddit link this only happens when the fel reaver actually burns cards.

**Comment by PattuX** [comment]
http://imgur.com/a/stjzm
https://imgur.com/a/wm034 (last picture)
Should disprove that theory.
As I don't see any similarities, my only suggestion would be dominant player bug, but I don't think so.

**Comment by Xinhuan** [comment]
Maybe the bug only applies to Overload spells, and works correctly with Overload minions?

**Comment by PattuX** [comment]
Stating the obvious: connection to #265 and Brann Bronzebeard
https://twitter.com/bdbrode/status/666459940249178112

At least it fits the proofs and makes sense somehow.

**Comment by 10925** [comment]
My personal guess:
If you opponent have Fel Reaver, and you didn't control  Tunnel Troggs:
No overloaded.
If you opponent have Fel Reaver, and you do control Tunnel Troggs:
Overloaded normally, but cannot trigger Troggs effect.

**Comment by Xinhuan** [comment]
> If you opponent have Fel Reaver, and you do control Tunnel Troggs:
Overloaded normally, but cannot trigger Troggs effect.

Disproven: https://www.reddit.com/r/hearthstone/comments/3u08z9/fel_reaver_overload_bug_issue_with_tunnel_trogg/

Overload still doesn't occur, Tunnel Trogg doesn't trigger either.

**Comment by 10925** [comment]
Someone says that Fel Reaver and Overloaded doesn't occur only happens after blizzard latest hot-fix.(Should be 21st I think).
Is there any report that overload still occurs with Fel Reaver (and Fel Reaver burn cards) after 21st?

**Comment by jleclanche** [comment]
No I don't believe this was in the hotfix.

**Comment by 10925** [comment]
I mean, before hot fix.
Only report about Tunnel Troggs cannot gain attack with Fel Reaver.(Overloads are normal)
After hot fix
Fel Reaver makes overloaded doesn't occur at all. Of course Tunnel Troggs still cannot gain attack.

**Comment by Patashu** [comment]
I could believe it starting in the hot fix - shamans and fel reavers existed at the start of patch 4.0, after all, and no one noticed the bug yet.

**Comment by culinko** [comment]
Me and Xinhuan tested it in 4.1 and this bug no longer happens.
