### ISSUE TITLE
When using Gang Up on a friendly minion with Djinni of Zephyrs in play, the animation does not appear for the Djinni

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#274]
https://www.reddit.com/r/hearthstone/comments/3sodzj/djinni_also_copies_gang_up/
http://us.battle.net/hearthstone/en/forum/topic/19973957204

To elaborate, the 3 cards appear for the target minion and visually gets shuffled into the deck, but the 3 cards do not appear for the Djinni copying the spell. The size of the deck does increase by 6 though, so it is just a visual bug.

**Comment by theAprel** [comment]
I think this is intended. The animation on Djinni does not appear for *any* copied spell, so Gang Up is not different. This gets reported by players because it is the only meaningful spell animation.

Likely a design decision because seeing the animation twice is boring and wastes turn time.

**Comment by troggnostupidhs** [comment]
Djinni now copies all animations, including Gang Up

![hearthstone screenshot 07-30-17 15 04 02](https://user-images.githubusercontent.com/22508641/28756239-997a145a-7538-11e7-9d16-75c8f19978de.png)

![hearthstone screenshot 07-30-17 15 04 07](https://user-images.githubusercontent.com/22508641/28756240-9ba16486-7538-11e7-95ac-e5bb5028a11c.png)
