### ISSUE TITLE
"All tables are full" message popping for a split second when you start the game

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#276]
"All tables are full" message is popping for a split second when you start the game. Tables are not full, this is just a visual bug that started happening couple of patches ago.
- https://www.reddit.com/r/hearthstone/comments/3pcv9u/list_of_current_hearthstone_bugs/

**Comment by culinko** [comment]
This used to happen a lot. I haven't seen it in 4.1 so far, so closing.

**Comment by culinko** [comment]
Had this happen to me in 4.1.

**Comment by troggnostupidhs** [comment]
To me, this seems mostly fixed. Can anyone else confirm?
