### ISSUE TITLE
Blank in-game notification when starting the game

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#277]
Sometimes, there is a blank in-game notification when starting the game. This started happening couple of patches ago.

![missing in-game notification text after login 4 0](https://cloud.githubusercontent.com/assets/11700272/11320337/da5434a8-9095-11e5-9cb1-7573a818aa1e.png)

**Comment by troggnostupidhs** [comment]
I don't think this has happened for a long time. It should probably be closed.

**Comment by troggnostupidhs** [comment]
Can't say when this was fixed, but this should be closed.

It can be re-opened if anyone sees it.
