### ISSUE TITLE
Bouncing an Unearthed Raptor to the hand, replaying it and targeting it with a second Unearthed Raptor allows you to stack different minion Deathrattles

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#279]
If you play an Unearthed Raptor (giving it a Deathrattle), bounce it to your hand, play it again (giving it a different Deathrattle), then play a second Unearthed Raptor copying the first one, the second Unearthed Raptor will obtain both of the Deathrattles previously copied by the first Raptor.

* https://www.reddit.com/r/hearthstone/comments/3tqtqq/new_unearthed_raptor_vanish_bug_two_different/
* https://www.youtube.com/watch?v=DdPWkJpoifg

**Comment by Patashu** [comment]
Me and Xinhuan couldn't reproduce this with Vanish or with Sap, but we might be missing something... (We used Brann, Zombie Chow and Leper Gnome)

**Comment by PattuX** [comment]
Two ideas:
When they replayed it, they didn't copy it directly but via another Raptor who copied a Leper Gnome.
The original target (Zombie Chow) was returned by Brewmaster before Vanish. State of the original minion might have an impact, just as with the Spare Part bug.

**Comment by Xinhuan** [comment]
Toast was able to reproduce it in video, even though me/Patashu was not:

https://www.youtube.com/watch?v=MPyZ-M_k0PU

Treating it as verified.

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=DdPWkJpoifg

Hunter of the North does it and explains how to do it

**Comment by 10925** [comment]
Still occur in 4.1.Just test it myself.
I reproduce this by Brewmaster.

**Comment by culinko** [comment]
Can you tell me the exact setup you used to reproduce this issue? I am trying with Shadowstep, Sap and Brewmaster and haven't been succesfull yet.

**Comment by 10925** [comment]
Let's use Zombie Chow and Leper Gnome as a example.
First, use Unearthed Raptor(1) to  copy a Leper Gnome's deathrattle.
Next Bounce back it to your hand(whatever way you want. I test shadostep in 4.0,and Brewmaster in 4.1)
Then use Unearthed Raptor(1) to copy  Zombie Chow's deathrattle.
Finally use Unearthed Raptor(2) to copy Unearthed Raptor(1)'s deathrattle.
Then Unearthed Raptor(2) should contain both deathrattle. It would trigger both deathrattle when it death.
And Unearthed Raptor(1) may only contain Zombie Chow's? I forgot to test it.

**Comment by culinko** [comment]
Alright, I reproduced it with the steps you provided, thank you! I will update the first post.

**Comment by Xinhuan** [comment]
New video from Hunter of the North, showcasing this bug again, along with footage of the setup.

https://www.youtube.com/watch?v=jCGEdH0l8SQ

This time, he stacks Deathlord + Sylvanas DRs together, resulting in the purple particle effects "stealing animation" appearing as though it steals minions out of the enemy deck.

**Comment by Patashu** [comment]
HysteriA claims that this is fixed in Patch 4.2.

https://twitter.com/HysteriAHS/status/709913086019420160

**Comment by culinko** [comment]
Couldn't reproduce in 4.2, it's fixed.
