### ISSUE TITLE
Using Preparation on an Overload spell causes Overload not to occur

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#280]
If you play Preparation then a spell with Overload, you do not gain the Overload.

Preparation creates an Aura attached to your Hero that destroys itself as a trigger in the On Play Phase. The moment it does, it has some unusual properties:

* It immediately updates the Mana Cost of all spells in your hand. (Normally, Auras do not update in the middle of a Phase.) This leads to a bug with Preparation and Summoning Stone/Gazlowe: https://github.com/HearthSim/hs-bugs/issues/273
* It makes the currently being played spell give 0 Overload.

If Preparation is played before a Tunnel Trogg, Tunnel Trogg will not see any overload and not gain any Attack. If Preparation is played after, Tunnel Trogg will gain Attack equal to overload, then Preparation will remove the overload.

Unbound Elemental triggers regardless of order of play compared to Preparation.

It is unrelated to the amount of Mana the Spell cost. For example, casting the Spell for 0 Mana using Emperor Thaurissan doesn't matter.
* https://www.youtube.com/watch?v=Z8-1HTW1IC0
* http://us.battle.net/hearthstone/en/forum/topic/19974767578

**Comment by Patashu** [comment]
video:

https://www.youtube.com/watch?v=Z8-1HTW1IC0

**Comment by Patashu** [comment]
also, this is related to https://github.com/HearthSim/hs-bugs/issues/273 , I feel like both of them will be fixed the same way

**Comment by culinko** [comment]
Playing Overload spell after playing Preparation overloads you and it also buffs your Trogg/Unbound in 4.1.
