### ISSUE TITLE
If you disconnect during the Discover selection choice screen, you cannot click on any card on reconnection

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#282]
https://www.reddit.com/r/hearthstone/comments/3tsrde/cant_click_on_discovered_cards_after/

I verified this by playing a game against AI, playing a Discover card, and then killing the Hearthstone.exe process while the 3 choices are on screen. On reconnecting to the game, the 3 card choices are still shown, the Show/Hide button still works, but you cannot select any of the 3 cards.

Since this test game is against the AI, there is no time limit on the player's turn. Against a real human opponent though, I believe (but didn't test) that the server auto selects the leftmost card at end of turn, so the game should still proceed from that point onwards. Nevertheless, it is still a bug, because it essentially skips the remainder of the player's turn on reconnect.

Conceding via the menu still works.

**Comment by culinko** [comment]
Fixed in 4.1, I just tested it and you can pick your card without any problems after reconnecting.
