### ISSUE TITLE
Sacred Trial is missing animation if it kills Lord Jaraxxus (the hero)

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#283]
After the hotfix for #255, there is now a missing animation when Sacred Trial kills Jaraxxus. It will probably be fixed in the next client patch.
* https://www.youtube.com/watch?v=079AdKILZM8 (Paladin viewpoint)
* https://www.youtube.com/watch?v=zWPrPJGfDTI (Warlock viewpoint)

Ben Brode said "Laser animation requires a client patch, so can't hotfix that." here:
https://www.reddit.com/r/hearthstone/comments/3tsl4z/sacred_trial_vs_lord_jaraxxus_got_hotfixed_lord/cx98rd1

**Comment by jleclanche** [comment]
Fixed in 4.1

**Comment by culinko** [comment]
Just to note, the last time they hotfixed the interaction, the animation went missing. They reverted the hotfix in 4.1, so if they fix the interaction again, its animation should be re-tested.

**Comment by jleclanche** [comment]
Agreed yeah.
