### ISSUE TITLE
Sometimes when your opponent plays Vol'jin, your game will hang

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#287]
http://us.battle.net/hearthstone/en/forum/topic/19974607517

Video reproduction of issue: https://www.youtube.com/watch?v=0Nbi6k7d-jQ
Power.log of video: https://gist.github.com/Patashu/2088dc6109ed1437d501

When your opponent plays Vol'jin, your game will hang. The health swap visually does not occur although the animation occurs. The game is still able to receive the events of following plays/turns from the opponent. If you exit your game and reconnect, you will able to continue.

**Comment by Xinhuan** [comment]
This bug might not be specific to the Fel Reaver. There are further reports of it happening on the following minions:

Ragnaros: http://us.battle.net/hearthstone/en/forum/topic/19974607517#2
No minion specified: http://us.battle.net/hearthstone/en/forum/topic/20044694486#1
Sludge Belcher: http://us.battle.net/hearthstone/en/forum/topic/20044694376#2
Dr Boom: https://www.reddit.com/r/hearthstone/comments/3uprtj/a_bug_with_voljin/ (Has SS)

**Comment by culinko** [comment]
Patashu and Xinhuan tested Vol'jin and Fel Reaver in 4.0 and it no longer hangs.
