### ISSUE TITLE
Attacking past a Taunt minion while it is being summoned by an enemy Mounted Raptor/Hogger, Doom of Elwynn will cause it to shrink

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#288]
When your opponent's Mounted Raptor Deathrattle summons a Taunt minion, if you try to attack past it at the same time as it is being summoned, it may get stuck at a very tiny size. This is because the animation of the minion appearing and the client changing the taunt minion's size to indicate you can't attack past it interfere.
- https://www.youtube.com/watch?v=hO7fRYhgrg0
- https://www.reddit.com/r/hearthstone/comments/3td6ud/hilarious_tiny_taunt_bug/
- https://www.reddit.com/r/hearthstone/comments/3sqn46/just_a_tiny_taunt_minion/

Occurs on mobile too:
- https://www.reddit.com/r/hearthstone/comments/3ucpbn/i_just_lost_because_a_taunt_minion_was_so_small_i/
- https://www.reddit.com/r/hearthstone/comments/3u67ep/ʳᵉᵃᵈʸ_ᶠᵒʳ_ᵃᶜᵗᶦᵒᶰ/

![Goldshire Inchman](https://cloud.githubusercontent.com/assets/235410/11611112/5dbe1fea-9bc5-11e5-88f5-d5648e75837e.jpg)

Occurs with Hogger, Doom of Elwynn also (with gfycat):
- https://www.reddit.com/r/hearthstone/comments/4jnnrz/what_is_this_a_gnoll_for_ants/

**Comment by Xinhuan** [comment]
Still occurs in 4.1: http://us.battle.net/hearthstone/en/forum/topic/20044326876

**Comment by Patashu** [comment]
Video occurence;

https://www.youtube.com/watch?v=hO7fRYhgrg0

**Comment by Patashu** [comment]
Confirmed in 4.2

https://www.reddit.com/r/hearthstone/comments/4afdq4/i_guess_i_wont_pass_new_bug/

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4fhek1/almost_lost_to_a_mini_shieldbearer_that_was_so/

Confirmed in 4.3

**Comment by Patashu** [comment]
Here's a report of it happening with Hogger, Doom of Elwynn:

https://www.reddit.com/r/hearthstone/comments/4hv39n/bug_brann_blackwing_corruptor_on_new_hogger/

**Comment by culinko** [comment]
Another report with Hogger, Doom of Elwynn (including footage): https://www.reddit.com/r/hearthstone/comments/4jnnrz/what_is_this_a_gnoll_for_ants/.

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13030

http://us.battle.net/hearthstone/en/forum/topic/20745086159

**Comment by troggnostupidhs** [comment]
From my testing, this seems fixed.

![img001](https://user-images.githubusercontent.com/22508641/32867573-db4b66ce-ca3b-11e7-96dd-7a496f32814a.png)
![img004](https://user-images.githubusercontent.com/22508641/32867574-db57ac5e-ca3b-11e7-84b8-ec5577e6cc81.png)
![img005](https://user-images.githubusercontent.com/22508641/32867575-db6a972e-ca3b-11e7-8c4c-03635bc7cdfd.png)
![img007](https://user-images.githubusercontent.com/22508641/32867576-db79b9fc-ca3b-11e7-9ec3-0e56f2ff8993.png)


Priest Deck 
AAEBAa0GAqCwAuq/Ag7cAeUEyQalCdIK0wrXCvoRoawC6L8C0cEC0sEC5cwCtM4CAA==

Paladin Deck
AAEBAaToAgAPngGzAf8C/gOIBdcF1gaaB9kNt2yKrgKBvQLexAK4xwLiygIA

Deck are not optimal. Probably swap out Resurrect and Death for Priest and add some buffs for Paladin.

**Comment by troggnostupidhs** [comment]
Closing this issue. Can reopen if needed.
