### ISSUE TITLE
You can softlock 'My Collection' by clicking on 'New Deck' again too fast

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#289]
1) Select 'new deck' to make a deck in your final slot.
2) Select priest and click 'choose'. VERY QUICKLY AFTER THAT, click the 'new deck' button again before animations finish.
3) It should prompt you to select a class again. However, Hearthstone thinks you should be building a deck right now, and you are softlocked. You must quit and re-open Hearthstone to continue.
- https://www.youtube.com/watch?v=f-oAATtqoVU

**Comment by Patashu** [comment]
Could not reproduce in 5.0, but did get some other visual glitchiness:

https://youtu.be/H2XKWpgUdMY

**Comment by troggnostupidhs** [comment]
I was able to get it to soft lock after trying a couple of times.

**Comment by troggnostupidhs** [comment]
I think this is fixed. Can someone else verify?

**Comment by troggnostupidhs** [comment]
I tested again with the timing from the video and it seems okay for me. I'm leaving the old milestone just because it was likely fixed by then.
