### ISSUE TITLE
Mirror Entity after Sacred Trial does not copy the 'pending destroy' state

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#292]
If you play Sacred Trial then Mirror Entity and your opponent plays a minion (satisfying the Sacred Trial condition), Sacred Trial will trigger, setting the minion pending destroy, then Mirror Entity will copy the minion. However, the copy will NOT be pending destroy, and will survive.

It is unknown if this bug was caused by the fix to the Vaporize vs Freezing Trap bug (whenever a minion enters play, TO_BE_DESTROYED tag is cleared) or if it is an old bug that was simply not visible until this patch.
- https://www.youtube.com/watch?v=1Q6byGuNYJU

**Comment by jleclanche** [comment]
There's nothing that would make me think this is a bug. This is down to design.

**Comment by Patashu** [comment]
Isn't it a bug if the Copy effect copies every user-visible property of a minion... except for TO_BE_DESTROYED?

**Comment by jleclanche** [comment]
T_B_D is not a user-visible property.

**Comment by Patashu** [comment]
Confirmed in 5.0 by KatyHearthstone

[13:05] <KatyHearthstone> btw it turns out if you have sacred trial and mirror entity up (as a hunter, obviously)
[13:05] <KatyHearthstone> that if the opponent plays a minion, sacred trial destroys it but you still get a copy on your side of the board
[13:05] <Patashu> in that order?
[13:05] <KatyHearthstone> yep
[13:06] <KatyHearthstone> I saw it get killed by trial
[13:06] <KatyHearthstone> then mirror entity triggered

**Comment by VoidMayonnaise** [comment]
#698 Now Mirror Entity won't trigger if the minion is pending-destroyed, but Sacred Trial will trigger.
