### ISSUE TITLE
Crafting Vol'jin, Varian or Wilfred crashes the iOS client

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#294]
Based on reports, the game client crashes to the Home Screen in the middle of the crafting animation, and this only happens on iOS (both iPhones and iPads). Affected players are able to craft the cards on OSX and Windows.

Blue confirmation: http://us.battle.net/hearthstone/en/forum/topic/19136834900?page=1#7

The links below link to forum searches that each link to many threads about the crashes for each of the cards:
* http://us.battle.net/hearthstone/en/search?f=post&forum=10591462&q=craft%20varian&sort=time&dir=d
* http://us.battle.net/hearthstone/en/search?f=post&forum=10591462&q=craft%20vol%27jin&sort=time&dir=d
* http://us.battle.net/hearthstone/en/search?f=post&forum=10591462&q=craft%20wilfred&sort=time&dir=d

After the crash and relogging in, the dust remains unspent.

Illidan: https://www.reddit.com/r/hearthstone/comments/3uxzxp/bug_crafting_illidan_stormrage_on_ios_crashes_the/

**Comment by PattuX** [comment]
Appearently this happened with all Legendaries but was fixec in 4.1 according to iPad patch notes.

**Comment by Xinhuan** [comment]
Screenshot of full patch notes for 4.1 on iOS:

![img_1070](https://cloud.githubusercontent.com/assets/17907/11611926/760d7302-9c1f-11e5-81cd-cb1bbeda4196.PNG)

I tried crafting Wilfred on my iPad and no crash (and DEed him right after to get the dust back). Will assume that the crash is fixed as the patch notes claims (and reopen if there are any new reports).
