### ISSUE TITLE
AI passing the turn with no actions made

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#296]
Sometimes, the AI just passes the turn without making any actions (I observed this with Innkeeper Priest). The Priest has a minion on the board which can attack, the Priest doesn't have full Health, so he can heal himself, also he has cards in hand to play. Happens randomly and AI will continue playing next turn like nothing happened.

**Comment by culinko** [comment]
Reproduced in 4.1. AI played Bloodfen Raptor turn 2, I coined out Feral Spirit. AI just passed the next turn without any actions made.

**Comment by troggnostupidhs** [comment]
While testing several issues, I haven't noticed this at all. Can someone else check to see if it seems to be fixed?

**Comment by culinko** [comment]
Issues like this are hard to test because Blizzard keep changing the AI in every patch. I'll close the issue for now, but it's certainly possible that it will occur again at some point in the future.
