### ISSUE TITLE
Seasonal rewards from the ranked chest don't show in the collection until client restart

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#297]
After you receive your seasonal rewards from the ranked chest, you have to restart your client to be able to see them in your collection. This started happening in 4.0. Not sure if it happens to all the players, but it happened to a lot of them.

**Comment by culinko** [comment]
Happens in 4.1: https://www.reddit.com/r/hearthstone/comments/3z01tt/can_confirm_some_people_getting_wrong_card_back/cyi7jsf

**Comment by culinko** [comment]
This bug has been fixed.

**Comment by culinko** [comment]
Confirmed still happening in this thread: https://www.reddit.com/r/hearthstone/comments/4h9mq0/season_rewards_bug/.

**Comment by riQQ** [comment]
Can confirm, this happened to me, too.

**Comment by PattuX** [comment]
Still happening.

**Comment by culinko** [comment]
Still happens in 6.0: https://www.reddit.com/r/hearthstone/comments/50lqys/season_rewards_bugged_on_eu/.

**Comment by troggnostupidhs** [comment]
7.0 report

https://www.reddit.com/r/hearthstone/comments/5lincq/ranked_reward_bug/

**Comment by troggnostupidhs** [comment]
Potentially fixed.

http://us.battle.net/hearthstone/en/blog/20562933/hearthstone-update-february-28-2-28-2017

> Resolved an issue where seasonal reward cards could take a while to show up in the Collection Manager.

**Comment by troggnostupidhs** [comment]
This worked for me. It can possibly be closed.

**Comment by PattuX** [comment]
For me as well.

I'd suggest we wait one day and if there are no reports, we can close this.

**Comment by troggnostupidhs** [comment]
As far as I can tell, there have been no reports.
