### ISSUE TITLE
Casting Polymorph: Boar on Fjola Lightbane may leave a visually glitched Divine Shield on the battlefield

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#298]
If you cast Polymorph: Boar on Fjola Lightbane, depending on the timing of the animations, a visually glitched Divine Shield will remain on the board in the same location Fjola Lightbane was. It will continue to remain there even as minions are added and removed from play. Gameplay continues as normal.
- https://www.reddit.com/r/hearthstone/comments/3i98uv/interaction_with_fjola_lightbane_and_polymorph/
- http://us.battle.net/hearthstone/en/forum/topic/20042654684

It also happens when you recombobulate a Cobalt Guardian into a Mech:
- http://us.battle.net/hearthstone/en/forum/topic/20742818598

**Comment by Patashu** [comment]
Maybe it's possible to do this with Taunt too?

https://www.reddit.com/r/hearthstone/comments/3vc3a0/polymorph_or_twilight_guardian_bug/

**Comment by Patashu** [comment]
Confirmed in 4.1

https://www.reddit.com/r/hearthstone/comments/3yidfn/til_casting_polymorphboar_on_fjola_lightbane/

**Comment by napu3c** [comment]
Also recombobulating a cobalt guardian into a mech the visually glitched Divine Shield will remain on the board

**Comment by ericBG** [comment]
Has anyone tested if this will happen with normal Poly?

**Comment by Patashu** [comment]
Confirmed in 4.2

http://us.battle.net/hearthstone/en/forum/topic/20742835249

**Comment by PattuX** [comment]
It seems like creating a Divine Shield on a minoin and then moving that minion to Setaside causes this bug.
Does it bug for GY too?
Play a Timber Wolf, in SRS Buzzard draws Flame Leviathan and Steward of Darkshire applies divine shield to the Wolf.

**Comment by culinko** [comment]
This issue was fixed in Patch 6.0.0.13921: http://hearthstone.gamepedia.com/Patch_6.0.0.13921.

Re-tested both Fjola Lightbane + Polymorph and Cobalt Guardian + Recombobulator and no visual glitches anymore.
