### ISSUE TITLE
Playing resurrect without having lost a minion can copy an opponent's dead minion

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#30]
If Player 1 has no dead minions since the start of the game and Player 2 does, if Player 2 plays Resurrect (this one will function correctly), any subsequent Resurrects played by Player 1 while his dead minions list remains empty will instead resurrect a minion from Player 2's list of dead minions.
* https://www.reddit.com/r/hearthstone/comments/32rkvi/resurrect_bug/
* http://us.battle.net/hearthstone/en/forum/topic/17085508705
* [[Hearthstone Science] Resurrect Enemy Minion (short version)](https://www.youtube.com/watch?v=zGEgreBqzlI)
* [[Hearthstone Science] Resurrect Bug resurrects enemy minion](https://www.youtube.com/watch?v=zWFWXMhJstc)

**Comment by NightKev** [comment]
I recall someone mentioning this had been fixed with the TGT patch, if someone could confirm then we can close the issue.

**Comment by jleclanche** [comment]
This is no longer reproducible because resurrect is no longer playable without having lost a minion beforehand.
