### ISSUE TITLE
Casting Entomb when your board is full puts the minion in your opponent's deck

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#302]
Entomb is coded the following way:

1. Change the minion's controller to be equal to the casting player.
2. Change the minion's zone to Deck

This means that if you cast Entomb on an enemy minion when your board is full:

1. Since your board is full, it tries to change controllers but cannot, so instead it dies and goes to the Graveyard zone.
2. It goes from the Graveyard zone to the Deck zone. Since it did not change controllers, this means it is now in your opponent's Deck, not your Deck.

* https://www.youtube.com/watch?v=Hq1mdRxvz9s
* https://gist.github.com/Patashu/59f9e63790b9d7938498

Interestingly, the minion's Deathrattle does not run, and any on-death triggers do not run. This is likely related to the fact that the minion is in the Deck zone before the Death Event even starts to resolve.

* https://www.youtube.com/watch?v=17stvEpxF1M

However, the minion REALLY did die, for the purposes of Kel'Thuzad, Anyfin Can Happen, etc.

* https://gist.github.com/Patashu/3c79ca53592f8bb5d0f0
* https://www.youtube.com/watch?v=_ULA79lmelg

**Comment by Patashu** [comment]
What a goofy bug. How does this even happen?

**Comment by culinko** [comment]
Listing two reddit reports, just in case we need more links:
* https://www.reddit.com/r/hearthstone/comments/3vbgof/entomb_bug/
* https://www.reddit.com/r/hearthstone/comments/3vbgho/bug_with_entomb/

**Comment by NightKev** [comment]
[Power.log.txt](https://github.com/HearthSim/hs-bugs/files/51432/Power.log.txt)
Also, here's the relevant log.

**Comment by Patashu** [comment]
Edited bug description and added log snippet

**Comment by Patashu** [comment]
Interestingly, out of the 5 times NightKev + DisguisedToast have reproduced the bug, all 5 times the entombed minion was on the bottom of the opponent's deck.

This leads me to wonder if Malorne (who, when he dies, goes from GY->DECK as well) will also have this bug of also being at the bottom of the deck guaranteed.

**Comment by culinko** [comment]
Toast tested this in 4.1 and the bug still occurs.

**Comment by thetaphi** [comment]
Tested Malorne in 4.1 just now, two games against Innkeeper. He came back once with 14 cards left, once with 1.

**Comment by Patashu** [comment]
Forgot to add this tweet, @ywoo_dev has liked it so bug acknowledged:

https://twitter.com/Patashu0/status/672541667006615552

**Comment by Patashu** [comment]
Added information about this bug:

**Comment by Grasty** [comment]
Reportedly, this will also happen if your board isnt full but your deck is empty (you are fatiguing)
http://us.battle.net/hearthstone/en/forum/topic/20043466944

**Comment by Xinhuan** [comment]
There's a second report of it happening on an empty deck with a non-full board: http://us.battle.net/hearthstone/en/forum/topic/20042706912

We'll test it out tomorrow.

**Comment by culinko** [comment]
I just tested it and it worked correctly. The stolen card went to the deck.

**Comment by Patashu** [comment]
Interestingly, Kel'Thuzad will resurrect the minion you killed with Entomb.

https://gist.github.com/Patashu/3c79ca53592f8bb5d0f0

**Comment by willaien** [comment]
Murlocs that are entombed with this bug will be summoned by Anyfin.

**Comment by Patashu** [comment]
Edited the original post to clarify this interaction.

**Comment by livejamie** [comment]
Being discussed here potentially: https://www.reddit.com/r/hearthstone/comments/4ad3as/gamebreaking_bug_entombdeathlord/

**Comment by Patashu** [comment]
Confirmed in 4.2:

http://us.battle.net/hearthstone/en/forum/topic/20742934514

**Comment by Patashu** [comment]
Confirmed in 4.3:

https://www.reddit.com/r/hearthstone/comments/4f4pqx/entomb_bugs_game_breaking_nozdormulady_nazjar_bug/

**Comment by 10925** [comment]
It's fixed in patch 5.0
video proofhttps://youtu.be/5C4dhQRa__M
