### ISSUE TITLE
Giantfin can use his Hero Power 'Mrglmrgl MRGL!' for free, even after Saboteur

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#304]
Giantfin (Normal mode) autocasts his Hero Power 'Mrglmrgl MRGL!' (ID LOEA10_2) at the start of each turn. Even if it costs mana due to Saboteur, he will use it for free. This is in contrast to how the Temple Escape works. If you use Saboteur against Temple Escape, the Hero Power will not be used unless sufficient Mana is available.
* https://www.youtube.com/watch?v=4Zp6oGnGYGk
* https://gist.github.com/Patashu/262743075d7ac3623cb9

![hearthstone screenshot 01-14-16 23 24 49](https://cloud.githubusercontent.com/assets/11700272/12340137/44b25304-bb19-11e5-8c3b-7e2a5258ccea.png)

**Comment by culinko** [comment]
I just tested it in 4.1, the bug happens only in Normal mode.

**Comment by Patashu** [comment]
Chromaggus Heroic also ignores Saboteur and always uses his Hero Power for free:

http://us.battle.net/hearthstone/en/forum/topic/20419312925

**Comment by culinko** [comment]
Fixed in 4.2.
