### ISSUE TITLE
Heroic Naz'jar: Hero Power ignores enemy cards that cost >= 10 mana

### ISSUE THREAD

**Issue by megablue** [HearthSim/hs-bugs#306]
Heroic Naz'jar's hero power doesn't replace Sea Giants despite there are other 10 cost minions in the game.

Video Evidence: https://youtube.com/watch?t=419&v=i5aJHGXGfPc

**Comment by culinko** [comment]
Related report: 
* https://www.reddit.com/r/hearthstone/comments/3vf1kp/buggy_interaction_during_lady_nazjar_fight/

**Comment by postcasio** [comment]
The hero power replaces minions with ones that cost *1 more* mana and there are no minions that cost 11 mana.

**Comment by megablue** [comment]
@postcasio no, you're confusing it with the normal hero power.

The heroric ones only upgrades its own minions instead of all minions.

![image](https://cloud.githubusercontent.com/assets/164641/11592648/d461009a-9ada-11e5-80eb-9eac9f7327c2.png) check this screenshot.

and also, my video @ 5:47 https://gaming.youtube.com/watch?t=337&v=i5aJHGXGfPc my flame juggler (2 cost) got transformed into nerubian egg (2 cost as well)

**Comment by postcasio** [comment]
Whoops, I missed the heroic part, my bad. Sounds like a bug then. I guess the check to see if a minion could be transformed was not updated to fit with the heroic power, and it's still checking the mana cost + 1.

**Comment by jleclanche** [comment]
So basically Naz ignores enemy minions when she should not.

**Comment by culinko** [comment]
I re-tested interaction in Patch 9.2.0.21517 and it has been fixed. My damaged Sea Giant was transformed into Faceless Behemoth.
