### ISSUE TITLE
Tunnel Trogg only gains "+1 Attack", instead "+1 Attack per locked Mana Crystal"

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#307]
New bug in Patch 4.1.0.10956.

When an Overload card is played, Tunnel Trogg only gains exactly +1 Attack regardless of the number of locked crystals.

Ancestral Spirit, Feral Spirits, Forked Lightning, Doomhammer, Earth Elemental and Neptulon have all been reported to have this bug in various screenshots (spells, weapon and minions all covered).

* https://www.reddit.com/r/hearthstone/comments/3vg5x7/tunnel_trog_bug/
* https://www.reddit.com/r/hearthstone/comments/3vg8gz/did_the_new_patch_break_tunnel_trogg/
* https://www.reddit.com/r/hearthstone/comments/3vgbof/tunnel_trogg_feral_spirit/
* https://www.reddit.com/r/hearthstone/comments/3vghbj/bug_with_tunnel_trogg/
* https://www.reddit.com/r/hearthstone/comments/3vgguy/tunnel_trogg_bug/
* https://www.reddit.com/r/hearthstone/comments/3vghho/til_tunnel_trogg_bugged_in_recent_patch/
* http://us.battle.net/hearthstone/en/forum/topic/20043655129
* http://us.battle.net/hearthstone/en/forum/topic/20044325218

This is not related to the Fel Reaver/Overload bug - there are no Fel Reavers in play.

This bug is acknowledged by Blizzard: https://twitter.com/PlayHearthstone/status/672883882581082112
Hotfix has been announced. "Should to be resolved momentarily": http://us.battle.net/hearthstone/en/forum/topic/20044325218?page=2#26

**Comment by Patashu** [comment]
I made a video describing the Patch 4.1 pre-hotfix model of playing a spell, and why this bug exists.

https://www.youtube.com/watch?v=7dkicRaiEIE

After the hotfix lands we need to test the model again.

**Comment by Patashu** [comment]
https://twitter.com/ywoo_dev/status/672956231934324736

According to Yong Woo the hotfix has landed.
