### ISSUE TITLE
Card filter bug in Collection Manager

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#308]
You can filter cards in your Collection Manager by an entire set in 2 ways:

1. Use the filter popup menu in the lower left corner to select the card set you want.
2. Type in the search box the full name of a set, or its abbreviated name (case insensitive).

---

When using Method 2, the search string "tgt" and the search string "the grand tournament" yields different results. Using the search string "tgt" correctly gives the same result as using Method 1. However, 22 cards are missing when using "the grand tournament" as the search string.
* http://us.battle.net/hearthstone/en/forum/topic/18706411977#2

**Druid**
Druid of the Saber
Knight of the Wild

**Hunter**
Brave Archer
Powershot
Dreadscale
Acidmaw

**Mage**
Effigy

**Paladin**
Enter the Coliseum
Mysterious Challenger
Eadric the Pure

**Priest**
Confuse

**Rogue**
Cutpurse
Beneath the Grounds

**Shaman**
The Mistcaller

**Warlock** (none)

**Warrior**
Magnataur Alpha
Varian Wrynn

**Neutral**
Fencing Coach
Gormok the Impaler
Maiden of the Lake
Mukla's Champion
Mogor's Champion
The Skeleton Knight

This bug is acknowledged in the Bug Report forums sticky:
http://us.battle.net/hearthstone/en/forum/topic/9677847863
> “TGT” or “The Grand Tournament” is not correctly filtering cards in the Collection Manager.

---

When using Method 2, the search string "loe" and the search string "the league of explorers" yields different results. Using the search string "loe" gives the same result as using Method 1. However, 12 cards are missing when using "the league of explorers" as the search string.
* http://us.battle.net/hearthstone/en/forum/topic/20043165009?page=1#2

**Druid** (none)

**Hunter**
Desert Camel

**Mage**
Ethereal Conjurer

**Paladin**
Sacred Trial

**Priest** (none)

**Rogue**
Unearthed Raptor

**Shaman** (none)

**Warlock**
Curse of Rafaam
Reliquary Seeker

**Warrior**
Obsidian Destroyer

**Neutral**
Eerie Statue
Elise Starseeker
Gorillabot A-3
Djinni of Zephyrs
Summoning Stone

**Comment by culinko** [comment]
This has been fixed in 4.2.
