### ISSUE TITLE
Decks Assemble: Headcrack comboed effect does not work

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#310]
In the "Decks Assemble!" tavern brawl, when playing a comboed Headcrack, a copy of Headcrack is shuffled into the deck, but the comboed effect of returning the card to your hand next turn does not work.
- https://www.reddit.com/r/CompetitiveHS/comments/3v5dsg/tavern_brawl_thread_wednesday_december_02_2015/cxkxget
- http://us.battle.net/hearthstone/en/forum/topic/20043365153

Video from Fisker: https://www.youtube.com/watch?v=A-C3cG3nU24
Power.log: https://gist.github.com/Xinhuan/a3aabed3cdafd3905111
Log contains turns 8, 9 and 10 (Fisker's Turn 4, opponent's Turn 5, and Fisker's Turn 5, Fisker conceded after that). The cardID for Headcrack is 171 in this game, goes to graveyard and doesn't appear after that (nor does any other Headcrack for the remainder of the game).

**Comment by troggnostupidhs** [comment]
Playing two worked for me.

![hearthstone screenshot 11-23-17 03 43 56](https://user-images.githubusercontent.com/22508641/33164891-c5e43f00-d002-11e7-8244-8fc7c6a884c4.png)
![hearthstone screenshot 11-23-17 03 44 01](https://user-images.githubusercontent.com/22508641/33164892-c5f5f5d8-d002-11e7-8f63-d07fc3828c63.png)
![hearthstone screenshot 11-23-17 03 44 06](https://user-images.githubusercontent.com/22508641/33164893-c60eb8a2-d002-11e7-9e4a-0c2fba6b9abf.png)
![hearthstone screenshot 11-23-17 03 44 13](https://user-images.githubusercontent.com/22508641/33164894-c6213310-d002-11e7-8c96-2d407fbb5030.png)
