### ISSUE TITLE
When Malorne's Deathrattle resolves, any added Deathrattles do not resolve afterwards

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#313]
If you cast an added Deathrattle such as Ancestral Spirit, Soul of the Forest or Explorer's Hat on Malorne, if Malorne's Deathrattle resolves (either by dying or by Feign Death), any of these added Deathrattles will not resolve.

* http://us.battle.net/hearthstone/en/forum/topic/15538984032
* http://www.reddit.com/r/hearthstone/comments/2vfmms/soul_of_the_forest_bugged/
* https://www.reddit.com/r/hearthstone/comments/3t9h1q/psa_dont_equip_malorne_with_an_explorers_hat/cx4bf60

This seems to be unique to Malorne's Deathrattle, which moves the original copy of Malorne to the Setaside Zone.

This is still true after Patch 4.0.0.10833, which changed Malorne's Deathrattle to move Malorne to the Deck Zone (instead of creating and shuffling a new copy).

It should be noted that Malorne does die when killed. Other on-death triggers run and he can be brought back to life by Resurrect and Kel'Thuzad.

Finally, we know that added Deathrattles trigger if the minion dies (trivial), is in play (Feign Death) or is in the hand (Anub'arak + Soul of the Forest). So the technical reason for the bug seems to be that Deathrattles cannot trigger if the related minion moves to the Setaside or Deck Zone.

Being looked into: 
https://twitter.com/bdbrode/status/673423732132589568
https://twitter.com/ywoo_dev/status/673749910408159232

**Comment by Patashu** [comment]
As jleclanche notes, it's unclear if the bug is actually that KT/Ress can bring Malorne back to life (if he never dies, then it follows that the added DRs should not resolve).

**Comment by Xinhuan** [comment]
My view is that Malorne's effect is a Deathrattle. Deathrattles very definition is "Does something when it dies", and for Deathrattles to happen the minion has to die. As such, Resurrect/KT should resurrect Malorne. "Shuffle back into deck" doesn't negate the fact that the death happened.

**Comment by Patashu** [comment]
Confirmed in 4.1 for Malorne and for Unearthed Raptor. Video/log:
* https://youtu.be/RW6ZA_vlB1U
* https://youtu.be/Yok8If2_1Rw

**Comment by jleclanche** [comment]
I'm now under the impression that this is caused specifically because the *buff* clears out too early when the card enters the deck.

**Comment by Patashu** [comment]
Ben Brode says 'we'll take a look':
https://twitter.com/bdbrode/status/673423732132589568
How ambiguous!

**Comment by Patashu** [comment]
Added information about this bug: On-death triggers played later than Malorne still trigger after Malorne.

https://youtu.be/17stvEpxF1M

**Comment by Patashu** [comment]
Suggested follow-up test by DicePower:

"Play Malorne, Cult Master, Soul of the Forest. Kill Malorne. Cult Master must draw Malorne. NOW does Soul of the Forest DR resolve?"

**Comment by Patashu** [comment]
Confirmed in 4.2:

https://www.reddit.com/r/hearthstone/comments/4bl178/malorne_bug/

**Comment by Patashu** [comment]
DicePower's follow-up test has been done. The Soul of the Forest DR still does not resolve. It seems Malorne entering the Deck immediately invalidates all remaining Deathrattles somehow.

https://www.youtube.com/watch?v=QeJUcnTvDwQ

**Comment by Patashu** [comment]
Confirmed in 4.3

http://us.battle.net/hearthstone/en/forum/topic/20743384350

**Comment by PattuX** [comment]
Me and edk tested, works correctly now. We tried Ancestral Spirit and Soul of the Forest on a Malorne.
