### ISSUE TITLE
Game crashes after hovering over a fatigue sidebar entry

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#314]
Happens exclusively on iPhones (not on iPads). Don't mistake this issue with #428, which is another bug with entering the fatigue that happens exclusively on Galaxy S7 and Galaxy S7 Edge.

* https://www.reddit.com/r/hearthstone/comments/3vpmcy/bug_on_mobile_when_expanding_fatigue_thumbnail_on/

**Comment by PattuX** [comment]
Wasn't able to reproduce this against Innkeeper (Patch 4.1).

**Comment by Xinhuan** [comment]
Also wasn't able to reproduce it on my iPad/Patch 4.1. I tested this with culinko when we tested for a different bug (reconnecting to a game used to show a full deck image over an empty deck).

**Comment by Xinhuan** [comment]
Found another report of it crashing when checking Fatigue in patch 4.1 on the iPhone: http://us.battle.net/hearthstone/en/forum/topic/20042845625

**Comment by culinko** [comment]
Another report mentioning iPhone:
* https://www.reddit.com/r/hearthstone/comments/42xk4i/iphone_bug_checking_past_fatigue_damage/

**Comment by Patashu** [comment]
Another report:

http://us.battle.net/hearthstone/en/forum/topic/20742784597

**Comment by culinko** [comment]
Happens on Galaxy S7 Edge (Android 6.0.1): https://www.reddit.com/r/hearthstone/comments/4atnht/android_client_crashing_on_latest_patch_when_game/.

**Comment by lcpunkrawk** [comment]
I was the Reddit user with the Galaxy S7 Edge. It doesn't just happen with the sidebar. It happens every game that goes to fatigue.

**Comment by Xinhuan** [comment]
I think it is 2 separate issues then.

1. On iOS iPhones (and specifically not iPads), it only crashes if you put your finger over the history sidebar fatigue entry to view how much damage was dealt.

2. On Android certain models, it crashes most of the time just entering fatigue without requiring any user input.

**Comment by culinko** [comment]
Yeah, this looks like 2 separate issues: https://www.reddit.com/r/hearthstone/comments/4c85h0/consistent_crashes_on_my_galaxy_s7_when_going/.

**Comment by Patashu** [comment]
iPhone 6 report

http://us.battle.net/hearthstone/en/forum/topic/20742909945

**Comment by Patashu** [comment]
Has this been fixed now?

**Comment by culinko** [comment]
The latest report on reddit that I could find is from April 27 (Patch 4.3): https://www.reddit.com/r/hearthstone/comments/4gofuk/dear_blizzard_can_you_please_perform_some/.
