### ISSUE TITLE
Clicking on your hero quickly after equipping a weapon that gives immune will not display the immune effect

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#316]
If you equip Gladiator's Longbow and quickly click on your hero, the Immune visual effect will not be displayed for you until you attack into an enemy character or cancel your attack. This is only visual bug and only the player equipping the weapon will see it. This issue is related to #74. SimFri got it on video:
- https://www.youtube.com/watch?v=Bk10idLbzSI

**Comment by troggnostupidhs** [comment]
Also happens with Candleshot

**Comment by troggnostupidhs** [comment]
Deck
AAEBAR8AD40B+wGcArQCtwK1A8kEuQbtCfcNzq4C180C3dIC39IC4eMCAA==

https://www.youtube.com/watch?v=U02HgCnrEfs

**Comment by troggnostupidhs** [comment]
This is fixed. The immune display happens immediately.
