### ISSUE TITLE
Conceal/Finicky Cloakfield doesn't remove its start turn trigger buff after you attack with the stealthed minion

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#318]
If you use Conceal or Finicky Cloakfield on your minion and attack with it, the start turn trigger buff for removing stealth will still remain applied on the minion. If you then give stealth to your minion with Master of Disguise, the stealth will still wear off at the start of your next turn. SimFri got it on video:
* https://www.youtube.com/watch?v=S5kGUQZ8cIw

**Comment by PattuX** [comment]
More specific case of #383, can be merged.
