### ISSUE TITLE
Entomb on transformed minions gets revealed Flame Leviathan style when drawn

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#320]
When your opponent uses Entomb on your minion, and this minion is one that is created by transform effects (Polymorph, Faceless, Druid of the Claw, Recombobulator, etc), when the opponent draws the entombed minion, it gets revealed to you Flame Leviathan style.
- https://www.youtube.com/watch?v=5rBvtp6xWZg (Druid of the Saber, Recombobulator, Druid of the Flame, Polymorph, Polymorph:Boar) 
- https://www.youtube.com/watch?v=7eyQxd-4s8M (Druid of the Claw)
- http://www.hearthpwn.com/forums/hearthstone-general/general-discussion/87306-entomb-bug (Druid of the Claw)
- https://www.reddit.com/r/hearthstone/comments/3vcjrp/entomb_bug_on_a_full_board/ (Lady Naz'Jar's hero power)

Other reports:
- https://www.reddit.com/r/hearthstone/comments/3vbgof/entomb_bug/cxm47dl
- http://www.hearthpwn.com/cards/27238-entomb?comment=173 (Dark Cultist - speculated to be transformed from something else)

**Comment by Patashu** [comment]
A related bug is that if you transform Malorne after he has died and shuffled into the deck, when the transformed minion is drawn, it is revealed to the other player.

**Comment by Patashu** [comment]
Tweeted to Yong Woo: https://twitter.com/Patashu0/status/674358230328315904

**Comment by Patashu** [comment]
Confirmed in 4.2 with video

https://www.reddit.com/r/hearthstone/comments/4aiesw/entomb_bug_on_transformed_minions_happens_yet/

**Comment by culinko** [comment]
Confirmed in 4.3

https://www.reddit.com/r/hearthstone/comments/4f6kkb/entomb_bug/

**Comment by theAprel** [comment]
Video for 5.0.0.12574:

https://www.twitch.tv/nl_kripp/v/63415627?t=50m15s

**Comment by Xinhuan** [comment]
Another occurrence in 5.0: https://www.youtube.com/watch?v=kL8jR_KxFvE&t=723

Amaz vs Forsen. Earlier in the game, Amaz entombed Forsen's Chromaggus. The Chromaggus was transformed into via the Shaman spell Evolve.

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13030:

http://us.battle.net/hearthstone/en/forum/topic/20745034975

**Comment by Jecoms** [comment]
Just happened when an Evolve minion was Entombed.

**Comment by ncisc** [comment]
here is a gif: [https://gyazo.com/5ec419bd11f2e5e92561b02c6bad5c91](https://gyazo.com/5ec419bd11f2e5e92561b02c6bad5c91)

**Comment by culinko** [comment]
Confirmed in 5.2: https://www.reddit.com/r/hearthstone/comments/4tb4yd/potential_entomb_bug/.

**Comment by culinko** [comment]
Confirmed in 6.0: https://www.reddit.com/r/hearthstone/comments/4xl0ns/bug_with_interaction_between_evolve_entomb/.

**Comment by Patashu** [comment]
Confirmed in 6.1.1 by wiki user Aegonostic.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/56j3ly/cards_taken_from_entomb_are_now_revealed_to_you/ confirmed in 14830

**Comment by troggnostupidhs** [comment]
Potentially fixed.
http://us.battle.net/hearthstone/en/blog/20328179/hearthstone-update-october-20-2016-10-20-2016

**Comment by troggnostupidhs** [comment]
There haven't been reports of this. It should be fixed.
