### ISSUE TITLE
Faceless Manipulator on self-buffing minions that have been effected by a direct set Enchantment copies stats incorrectly

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#321]
If a self buffing minion buffs itself, then is effected by a direct set Enchantment (such as Hunter's Mark, Humility or Reversing Switch), then is copied by Faceless Manpiulator, the copy's stats will be incorrect. In particular, one instance of the self buff is applied first, then the copy's other buffs are applied and finally all remaining stacks of the self-buff are applied.

* http://us.battle.net/hearthstone/en/forum/topic/20042845142
* http://us.battle.net/hearthstone/en/forum/topic/20043315367
* https://www.reddit.com/r/hearthstone/comments/454ukw/is_this_how_faceless_manipulator_is_supposed_to/

**Comment by Patashu** [comment]
Tweeted to Yong Woo: https://twitter.com/Patashu0/status/674358151563509761

**Comment by culinko** [comment]
Tested this in 4.1. I had 5/5 Shade of Naxxramas, damaged it to 5/4, casted Humility on it (1/4), then used Faceless Manipulator and the copy was 3/4, not 1/4.

![hearthstone screenshot 12-08-15 23 40 32](https://cloud.githubusercontent.com/assets/11700272/11670989/63abb2b8-9e05-11e5-9b25-2974f4d7e9e3.png)

**Comment by Patashu** [comment]
Video proof:

https://www.reddit.com/r/hearthstone/comments/3xdwf6/can_anyone_explain_this_questing_adventurer/

**Comment by PattuX** [comment]
The current outcome prediction method isn't valid. 
The links Patashu mentioned are even counterexamples themselves:
* http://us.battle.net/hearthstone/en/forum/topic/20043315367 (should've been 6/1)
* https://www.youtube.com/watch?v=jd5YO_qX5P4&feature=youtu.be (the total stats gain was 15, the copy has 19 tho)

**Comment by Patashu** [comment]
Another report:

https://www.reddit.com/r/hearthstone/comments/454ukw/is_this_how_faceless_manipulator_is_supposed_to/

![image](https://cloud.githubusercontent.com/assets/666597/12964214/1016fa74-d0a3-11e5-8b4d-a4a6e71c54f0.png)

**Comment by PattuX** [comment]
What happens is that all buffs that are on the minion are applied exactly once first (in order of play for the first occurence) and then all remaining instances of the buff are applied again.
It still has to be figured out: 
1) In what order do the remaining buffs in the second step apply?
2) What happens if Crazed Alchemist is one of the buffs? (My current theory on this, is that Attack and Health are calculated seperately and the wrong order messes up Crazed Alch)

This is most likely a lazy fix of #245

**Comment by Patashu** [comment]
Another occurrence

http://us.battle.net/hearthstone/en/forum/topic/20742584583

"I was doing my Heroic in Naxx and i attacked a 2-2 minion using my 18-3 treat (double spore buff) and then swapped it to a 1 -18 with Crazed Alchemist, but when the cpu copied it with Faceless it gave him a 9 -18. 

Here's a screenshot 
http://postimg.org/image/tcod2nrsn/
"

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20742956058 Another example in 4.2

**Comment by Patashu** [comment]
Confirmed in 4.3:

http://us.battle.net/hearthstone/en/forum/topic/20743354461

**Comment by PattuX** [comment]
edk/qi and me just tested:

Micro Machine x4 (5/2), Crazed Alchemist (2/5), Micro Machine x5 (7/5).

According to the bug, the outcome should've been Micro Machine x1 (2/2), Crazed Alchemist (2/5), Micro Machine x8 (10/5). Also there were no reports of this, so closing this.

![image](https://cloud.githubusercontent.com/assets/15743638/15264147/9de38758-1970-11e6-9436-0badffde71ff.png)
