### ISSUE TITLE
Seal of Light (turned to damage by Auchenai Soulpriest) is not buffed by Spell Damage +1

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#322]
Seal of Light (turned to damage by Auchenai Soulpriest) is not buffed by Spell Damage +1. That is, it does 4 damage instead of 5 or more.

https://www.youtube.com/watch?v=tOtx0gCUzHw

The technical reason is because Seal of Light is erroneously tagged immune to spell damage:

http://www.hearthhead.com/mechanic=70/immune-to-spell-damage#mentionedby

**Comment by Patashu** [comment]
Tweeted to @ywoo_dev: https://twitter.com/Patashu0/status/675186249221672960

**Comment by culinko** [comment]
This bug has been fixed in 5.0.0.12051, `GameTag.ImmuneToSpellpower`was removed from Seal of Light.
