### ISSUE TITLE
Spell Damage applied incorrectly to Crown of Kael'thas

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#323]
**Crown of Kael'thas (Deal 10 damage randomly split among ALL characters.)**
With Spell Damage +2, instead of dealing 1 damage 12 times (total 12 damage), it instead does 3 damage 12 times (total 36 damage), so the spell is double dipping on spell damage.
* https://www.reddit.com/r/hearthstone/comments/3w9iw3/bug_on_last_fight_of_loe/ (video)
* https://www.reddit.com/r/hearthstone/comments/3wau25/loe_adventure_crown_of_kaelthas_bug/ (screenshots)
* https://www.reddit.com/r/hearthstone/comments/3wayr1/crown_of_kaelthas_doubles_down_on_spelldamage/
* https://www.reddit.com/r/hearthstone/comments/3w9mfo/found_a_hilarious_bug_with_rafaam_unleashed/
* Another video: https://www.youtube.com/watch?v=3nDu_9C9XAo

This spell is inconsistent with Arcane Missiles, Avenging Wrath and Timepiece of Horror which have the same wording (Deal X damage randomly split among all enemies.)

**Comment by Patashu** [comment]
Tweeted to @ywoo_dev: https://twitter.com/Patashu0/status/675190100314189824

**Comment by culinko** [comment]
This bug has been fixed.

**Comment by jleclanche** [comment]
Fixed in 12051 (Crown of Kael'thas gained `ImmuneToSpellpower`.
