### ISSUE TITLE
Brann gets stuck onscreen in the wrong place and at the wrong angle

### ISSUE THREAD

**Issue by HearthstoneBugs** [HearthSim/hs-bugs#326]
This bug can be seen here:

http://www.twitch.tv/nl_kripp/v/29676803?t=04h22m32s

I've also had this happen to me.

It appears to happen if you attack with a minion as Brann is swinging in.

**Comment by culinko** [comment]
I don't think he's "stuck", just misplaced. If you clicked on him on your next turn, he would probably go back to his proper position.

**Comment by culinko** [comment]
Confirmed in 4.2: https://www.reddit.com/r/hearthstone/comments/4cemug/bug_brann_bronzebeard_stuck_on_board_midflight/.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4h07zn/brann_animation_stops_when_played_hooded_acolyte/ Confirmed in 5.0

**Comment by Xinhuan** [comment]
https://www.reddit.com/r/hearthstone/comments/4i9s8q/bug_brann_literally_dissapeared_when_i_played_him/

Brann can literally be stuck off-screen, so you can't click on him at all. Video of this happening from the thread: https://www.youtube.com/watch?v=AAcIcpuN-08

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20745194873

Is this related or different?

**Comment by culinko** [comment]
Report in 5.0.0.13030: https://www.reddit.com/r/hearthstone/comments/4njfjp/my_bran_glitched/.

**Comment by culinko** [comment]
Confirmed in 5.2? https://www.reddit.com/r/hearthstone/comments/4suu7g/brann_kind_of_missed_his_entrance/

**Comment by Patashu** [comment]
Confirmed in 6.0

https://www.reddit.com/r/hearthstone/comments/516jyn/brann_get_down_from_there/

**Comment by Patashu** [comment]
Confirmed in 7.0? https://clips.twitch.tv/kolento/TalentedButterflyFunRun

**Comment by troggnostupidhs** [comment]
This doesn't happen when I test it currently. I also don't see any reports of it. I believe it should be closed.

Deck
AAEBAf0EAu0FhRcOTfsBtAK7AtMChQOWBbkGiawCk60C9K8CrbwCrMICmMQCAA==.

**Comment by troggnostupidhs** [comment]
I am closing this one for now. Brann is still commonly played and I haven't seen reports of this issue.

**Comment by Patashu** [comment]
Is 22nd November recent enough? https://www.reddit.com/r/hearthstone/comments/9zdg6h/brann_come_down_please/

![image](https://user-images.githubusercontent.com/22508641/49975630-b66bab00-ff0c-11e8-868b-b272f31131c6.png)

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/brann-bronzebeard-animation-freezes/4769

> Not sure how much this will be a concern since it isnt gamebreaking and both are wild cards but if you play brann Bronzebeard and immediately play Queen Carnassa before his animation finishes he will freeze in place wherever he was swinging in. The enemy seems to see him in the right place though. I have been able to reproduce this reliably 4 times so I thought I’d report it since it is pretty easy to test. Had a screenshot but I guess i cant post links… can send it if it helps just tell me where.

**Comment by troggnostupidhs** [comment]
That part is fixed

https://playhearthstone.com/en-us/blog/23076826

> Fixed an issue causing
Brann Bronzebeard to float off the board if
Queen Carnassa was quickly played after Brann.
