### ISSUE TITLE
Minions whose Deathrattles affect a friendly minion behave inconsistently when triggered by Feign Death

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#329]
Anub'ar Ambusher goes back into your hand after you play Feign Death and he is your only minion:
https://gist.github.com/culinko/6e12de28e0dcee53ec00

Dark Cultist won't buff itself after you play Feign Death and he is your only minion:
https://gist.github.com/culinko/02c658ae55547da02b2d

Anubisath Sentinel also won't buff itself after you play Feign Death and he is your only minion:
https://gist.github.com/culinko/3146ab2651df5a8e2e5e

This is inconsistent because none of these minions specify 'another random friendly minion', they just specify 'random friendly minion', yet one of them can affect itself when triggered by Feign Death whereas the other two cannot.

**Comment by Patashu** [comment]
tweeted to @ywoo_dev: https://twitter.com/Patashu0/status/676201113272516608

**Comment by Xinhuan** [comment]
Putting a link to an actual Bug Report from someone else on the forums about this potential bug with Anubisath Sentinel:
http://us.battle.net/hearthstone/en/forum/topic/20043055975

From a quick google search, Dark Cultist not buffing itself with Feign Death was mentioned in early Feb 2015 here: http://forums.d2jsp.org/topic.php?t=72297513&f=221

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=KeIWDu5WutM

Made a video of all 3 interactions. Works the same as culinko says, just now we have footage.

**Comment by Patashu** [comment]
Anubisath confirmed in 5.0

http://us.battle.net/hearthstone/en/forum/topic/20743644538

**Comment by Patashu** [comment]
Fixed in 6.0, cool.

https://www.reddit.com/r/hearthstone/comments/51wted/til_if_you_use_huhuran_on_anubisath_sentinel_it/
