### ISSUE TITLE
Canceling a Battlecry minion prevents you from attacking with your Hero until you play it again

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#330]
Only occurs on mobile.
- http://us.battle.net/hearthstone/en/forum/topic/20043466719

"I had 1 durability left on my eaglehorn bow and went to use an Owl to silence something. I changed my mind and canceled the Battlecry and went to attack with my weapon, but it wouldn't work. Also, if I just tapped my hero as to emote, it would just bring up my hand (I only had 2 cards in my hand at the time, so it's not that I was hitting my cards by accident). The following turn it continued to not let me attack with the weapon until I played my Owl."

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4el9tg/known_game_ruining_bug_galaxy_s6_edge/ Another occurrence of this?

**Comment by troggnostupidhs** [comment]
I tried this a couple of times, and did not experience an issue. I tried with an Eaglehorn Bow and was always able to attack after canceling a battlecry. Tested with a Galaxy S5.
