### ISSUE TITLE
If the card drawn by 'Map to the Golden Monkey' is 'Golden Monkey', it will appear larger

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#331]
If the card drawn by 'Map to the Golden Monkey' is 'Golden Monkey', it will appear larger to your opponent. This is an info leak - your opponent now knows the Golden Monkey is in your hand, without even having to look at the logs.

https://www.youtube.com/watch?v=UZKgi_bqik4

**Comment by Xinhuan** [comment]
Another report of it today on forums: http://us.battle.net/hearthstone/en/forum/topic/20042656339

Also linking Toast's video of the bug that is posted on his Twitter: https://twitter.com/DisguisedToast/status/675145606478880769

**Comment by culinko** [comment]
It appears big for you, too, not just for the opponent.

**Comment by Xinhuan** [comment]
Video from Kripp, showing multiple times the big Golden Monkey card near start of video for himself (8:45 and 9:20). At 19:00 shows both opponent and himself: https://www.youtube.com/watch?v=z-0GiJvAdlI&t=19m00s

**Comment by Patashu** [comment]
Confirmed in 4.2

http://us.battle.net/hearthstone/en/forum/topic/20742894534

**Comment by culinko** [comment]
This has been fixed in 6.0. Tested with player's pov, but I assume it's also fixed for the opponent.

**Comment by jleclanche** [comment]
Wasnt this fixed last patch?

**Comment by culinko** [comment]
It was fixed in 6.0. This vod is from last patch and it's still bugged there: https://www.twitch.tv/savjz/v/80971868?t=143m8s.
