### ISSUE TITLE
Cursed! copied by Lorewalker Cho into your opponent's hand lacks visual effects

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#332]
If Lorewalker Cho copies Cursed! into your opponent's hand, it does not glow red and does not reveal itself at the start of your opponent's turn. All other properties of Cursed! copies (including gameplay effects, and visual effects while in your hand) function correctly.

https://www.youtube.com/watch?v=qj2U0LCyQBk

**Comment by Xinhuan** [comment]
Video from Noxious showing the bug: https://www.youtube.com/watch?v=LNQNDcBrAFA&t=2m50s

**Comment by troggnostupidhs** [comment]
Fixed

![img000](https://user-images.githubusercontent.com/22508641/32686165-412cf0ce-c66e-11e7-8653-cd26971212d9.png)
![img001](https://user-images.githubusercontent.com/22508641/32686166-413966ba-c66e-11e7-8627-b1538ed9c52d.png)
