### ISSUE TITLE
Golden Animated Armor added to a constructed deck turns into non-Golden

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#333]
Players who add a Golden Animated Armor to a constructed deck find that when playing with that deck, the Animated Armor will not be Golden.

(Reports are divided on whether the Golden Animated Armor becomes non-Golden in the decklist, and replacing it does not help, or whether the Golden Animated Armor is still Golden in the decklist but shows up as non-Golden in-game anyway.)
- http://us.battle.net/hearthstone/en/forum/topic/20043467168
- http://us.battle.net/hearthstone/en/forum/topic/20043655962
- http://us.battle.net/hearthstone/en/forum/topic/20042826618
- http://us.battle.net/hearthstone/en/forum/topic/20044526619
- http://us.battle.net/hearthstone/en/forum/topic/20042845581
- http://us.battle.net/hearthstone/en/forum/topic/20351045258
- http://us.battle.net/hearthstone/en/forum/topic/20044526619
- http://us.battle.net/hearthstone/en/forum/topic/20042826618
- http://us.battle.net/hearthstone/en/forum/topic/20419011735

**Comment by jleclanche** [comment]
You saying Animated Armor is not Animated?

**Comment by Patashu** [comment]
This report claims that you can put two golden Animated Armors in, but not one golden and one non-golden:

* http://us.battle.net/hearthstone/en/forum/topic/20419011735

**Comment by troggnostupidhs** [comment]
I haven't seen reports of this and it did not happen when I tested it

![Hearthstone Screenshot 03-16-19 14 41 18](https://user-images.githubusercontent.com/22508641/54480084-c9876300-47fa-11e9-83a0-9914f3f4ffa6.png)

![Hearthstone Screenshot 03-16-19 14 47 42](https://user-images.githubusercontent.com/22508641/54480085-c9876300-47fa-11e9-9f8c-449c20efb3cb.png)

![Hearthstone Screenshot 03-16-19 14 48 06](https://user-images.githubusercontent.com/22508641/54480088-d2783480-47fa-11e9-9715-8a04005e634a.png)

AAEBAf0EBO0Fj5oCiawCpIcDDU37AbsCyQOrBMsE5gSWBYoH7AfHxwKm8AK5/wIA
