### ISSUE TITLE
Baron Rivendare + The Skeleton Knight runs the same joust twice

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#334]
* https://www.youtube.com/watch?v=8w4labPSEHk
* https://www.youtube.com/watch?v=aQ49JRFpamU&t=31m15s

**Comment by beheh** [comment]
Tracked in Fireplace here: jleclanche/fireplace#249.

**Comment by Xinhuan** [comment]
Disproven. https://www.youtube.com/watch?v=ekULqns8QuY
