### ISSUE TITLE
Inconsistency between persistent effects attaching to the Hero or Player

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#335]
When a card provides a persistent effect (either for this turn or until X happens), it is impossible to tell from the card text whether it attaches to your Hero (and therefore ends when you replace your Hero) or to your Player (and therefore persists). The ambiguity can be fixed by either making cards that attach to your Hero use the word 'Hero' or by making them attach to your Player.

**Attaches to your Hero:**
* Preparation: https://www.reddit.com/r/hearthstone/comments/3xoklv/lord_jaraxxus_counts_as_spell/
* Commanding Shout's Enchantment (that triggers to buff minions played/summoned after casting Commanding Shout): https://gist.github.com/Patashu/2fc76629f9188bcd0430#file-commanding-shout-then-steal-silence-play-log
* Ice Block's Enchantment: https://www.youtube.com/watch?v=EWUZwAownAs
* Kirin Tor Mage: http://us.battle.net/hearthstone/en/forum/topic/18596062639

**Attaches to your Player:**
* Lock and Load: https://www.reddit.com/r/hearthstone/comments/3xoklv/lord_jaraxxus_counts_as_spell/cy6ut2z
* Dragon Consort:  https://www.reddit.com/r/hearthstone/comments/3xoklv/lord_jaraxxus_counts_as_spell/cy6u8w0
* Frost Giant uses NUM_TIMES_HERO_POWER_USED_THIS_GAME tag, which is on the Player Entity: https://github.com/HearthSim/hs-bugs/issues/335#issuecomment-166445700
* The Mistcaller: https://gist.github.com/culinko/76a14a72adf6386ce10c
* Millhouse Manastorm and Loatheb: http://hearthstone.gamepedia.com/Millhouse_Manastorm#Notes
* Saboteur, Fencing Coach

**Other/unclassified:**
* Garrison Commander uses HEROPOWER_ACTIVATIONS_THIS_TURN tag, which is on the Player Entity, but is refreshed by replacing your Hero Power (and therefore also replacing your Hero): https://gist.github.com/Patashu/bff54988f876710987c5#file-replacing-your-hero-power-resets-heropower_activations_this_turn-log
* Secrets are in the Secret Zone, not attached to your Hero/Player.

**Comment by Patashu** [comment]
(other effects that need to be added: Fencing Coach, Saboteur, Kirin Tor Mage, maybe others?)

(Also, Ice Block's Enchantment attaches itself to your Hero and Secrets are just in play (well, technically in the Secret Zone).)

**Comment by Patashu** [comment]
Garrison Commander uses HEROPOWER_ACTIVATIONS_THIS_TURN tag, which is on the Player Entity, but is refreshed by replacing your Hero or Hero Power.

https://gist.github.com/Patashu/bff54988f876710987c5#file-replacing-your-hero-power-resets-heropower_activations_this_turn-log

https://gist.github.com/Patashu/bff54988f876710987c5#file-becoming-ragnaros-resets-heropower_activations_this_turn-txt

**Comment by mthuurne** [comment]
Hero power use counter (NUM_TIMES_HERO_POWER_USED_THIS_GAME) is attached to the player entity:

    ACTION_START Entity=[name=Life Tap id=67 zone=PLAY zonePos=0 cardId=CS2_056 player=2] BlockType=PLAY Index=0 Target=0
        TAG_CHANGE Entity=MyNick tag=NUM_RESOURCES_SPENT_THIS_GAME value=8
        TAG_CHANGE Entity=MyNick tag=RESOURCES_USED value=2
        ACTION_START Entity=[name=Life Tap id=67 zone=PLAY zonePos=0 cardId=CS2_056 player=2] BlockType=POWER Index=-1 Target=0
            META_DATA - Meta=TARGET Data=0 Info=1
            TAG_CHANGE Entity=[name=Gul'dan id=66 zone=PLAY zonePos=0 cardId=HERO_07 player=2] tag=PREDAMAGE value=2
            TAG_CHANGE Entity=[name=Gul'dan id=66 zone=PLAY zonePos=0 cardId=HERO_07 player=2] tag=PREDAMAGE value=0
            META_DATA - Meta=DAMAGE Data=2 Info=1
            TAG_CHANGE Entity=[name=Gul'dan id=66 zone=PLAY zonePos=0 cardId=HERO_07 player=2] tag=LAST_AFFECTED_BY value=67
            TAG_CHANGE Entity=[name=Gul'dan id=66 zone=PLAY zonePos=0 cardId=HERO_07 player=2] tag=DAMAGE value=5
            SHOW_ENTITY - Updating Entity=[id=51 cardId= type=INVALID zone=DECK zonePos=0 player=2] CardID=NEW1_003
                tag=ZONE value=HAND
                tag=CARDTYPE value=SPELL
                tag=RARITY value=COMMON
            TAG_CHANGE Entity=[id=51 cardId= type=INVALID zone=DECK zonePos=0 player=2] tag=ZONE_POSITION value=8
            TAG_CHANGE Entity=MyNick tag=NUM_CARDS_DRAWN_THIS_TURN value=2
        ACTION_END
        TAG_CHANGE Entity=MyNick tag=HEROPOWER_ACTIVATIONS_THIS_TURN value=1
        TAG_CHANGE Entity=[name=Life Tap id=67 zone=PLAY zonePos=0 cardId=CS2_056 player=2] tag=EXHAUSTED value=1
        ACTION_START Entity=MyNick BlockType=TRIGGER Index=-1 Target=0
            TAG_CHANGE Entity=MyNick tag=NUM_TIMES_HERO_POWER_USED_THIS_GAME value=2
        ACTION_END
        TAG_CHANGE Entity=MyNick tag=NUM_OPTIONS_PLAYED_THIS_TURN value=1
    ACTION_END

**Comment by culinko** [comment]
Mistcaller is attached to Player: https://gist.github.com/culinko/76a14a72adf6386ce10c
Overload is attached to Player: https://gist.github.com/culinko/27f96db06369cf2f7172

**Comment by Patashu** [comment]
Commanding Shout appears to attach itself to your Hero, not Player. See:

https://gist.github.com/Patashu/2fc76629f9188bcd0430#file-commanding-shout-then-steal-silence-play-log

**Comment by Patashu** [comment]
Millhouse Manastorm and Loatheb; Tested by Xinhuan. They attach to the Player.

http://hearthstone.gamepedia.com/Millhouse_Manastorm#Notes

**Comment by Patashu** [comment]
I had a source for Kirin Tor Mage all along -.-! http://us.battle.net/hearthstone/en/forum/topic/18596062639 Silly me~

**Comment by culinko** [comment]
I tested Commanding Shout, Kirin Tor Mage and Preparation and all are fixed in 5.0.

Commanding Shout: https://gist.github.com/culinko/cf4d7d089a183473c93c3da2b6cecadf
![hearthstone screenshot 05-11-16 11 42 23](https://cloud.githubusercontent.com/assets/11700272/15177612/35660a62-1771-11e6-8941-8a7de5d845df.png)

Kirin Tor Mage: https://gist.github.com/culinko/8d3e8e51c0460a3a93032e39349257ca
![hearthstone screenshot 05-11-16 11 49 31](https://cloud.githubusercontent.com/assets/11700272/15177619/3eca6c4c-1771-11e6-840b-8b1b7701ed18.png)

Preparation: https://gist.github.com/culinko/1f2e83acf2a4b7a2f81afca3984f8ae2
![hearthstone screenshot 05-11-16 11 57 29](https://cloud.githubusercontent.com/assets/11700272/15177623/4825a4be-1771-11e6-809d-f44be58092f3.png)
