### ISSUE TITLE
Master of Ceremonies will gain +2/+2 if your opponent has a Jungle Moonkin

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#337]
If you play Master of Ceremonies and your opponent has a Jungle Moonkin on the board, it will gain +2/+2 from its battlecry. However, this contradicts its card text about you having a minion with the spell damage. It is currently not sure whether the card text or the card effect is incorrect.
* http://us.battle.net/hearthstone/en/forum/topic/20044695725

Log: https://gist.github.com/culinko/387114354c899d80ba97

Master of Ceremonies will be glowing in your hand.
![hearthstone screenshot 12-27-15 18 52 01](https://cloud.githubusercontent.com/assets/11700272/12011419/77bd2f78-accb-11e5-937e-c2efb48b67e6.png)

![hearthstone screenshot 12-27-15 18 52 16](https://cloud.githubusercontent.com/assets/11700272/12011420/84c4d0b8-accb-11e5-8b4d-b55015ae7dd0.png)

**Comment by Patashu** [comment]
If you put Velen's Chosen on a minion in your Hand, Graveyard or Deck (using Illidan Stormrage/Violet Teacher), this will probably also trigger Master of Ceremonies. (not worth attempting, just as a note)

**Comment by PattuX** [comment]
Xinhuan and me just tested with Velens in setaside (Brann + Faceless on minion with Velens) and Master of Ceremonies triggers on it as Patashu assumed.

**Comment by culinko** [comment]
Master of Ceremonies no longer gets buffed by opponent's Jungle Moonkin. I'll close this after the remaining stuff is tested as well.
