### ISSUE TITLE
Deathlord-played minion dying instantly causes board-covering graphical glitch

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#34]
If a sequence of events causes a Deathlord to die, and its Deathrattle brings into play a low health minion (let's call this Minion X) that dies immediately to another Deathrattle (usually Explosive Sheep, Abomination or Unstable Ghoul), Minion X's card image will stay bugged on the board in its death position and physically prevent any interaction with any future minion that occupies that same board position. This is because the minion under Minion X's card image cannot be targeted by the mouse cursor.

http://us.battle.net/hearthstone/en/forum/topic/16774527730

http://us.battle.net/hearthstone/en/forum/topic/17259567134

http://us.battle.net/hearthstone/en/forum/topic/17346224814

http://www.reddit.com/r/hearthstone/comments/2w8adp/bug_possible_deathlord_abomination_bug/

http://www.reddit.com/r/hearthstone/comments/31qku3/gamebreaking_bug_couldnt_target_minions_in_the/

http://us.battle.net/hearthstone/en/forum/topic/18710643731

It seems it may also occur with Chillmaw and Effigy:

https://www.reddit.com/r/hearthstone/comments/3izks7/game_breaking_bug/

**Comment by Patashu** [comment]
Confirmed in 3.0:

http://us.battle.net/hearthstone/en/forum/topic/18710643731

**Comment by Patashu** [comment]
Confirmed in 3.1:

http://us.battle.net/hearthstone/en/forum/topic/19136064902

**Comment by Patashu** [comment]
Confirmed in 3.2:

https://www.reddit.com/r/hearthstone/comments/3rjmbg/deathlord_to_druid_of_the_claw_bug/

**Comment by culinko** [comment]
We tested this with PattuX and it's fixed! I suspect it was fixed in the same Patch that fixed #71.
