### ISSUE TITLE
Incorrect card back awarded for December 2015 Season

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#340]
A large number of users have reported receiving the February 2016 card back (Thunderbluff) instead of the December 2015 card back (Thrall), with enough screenshots. The Thrall card back is the correct one. (See Issue #311 where the wrong season was listed for these 2 card backs and later patched.)

* http://us.battle.net/hearthstone/en/forum/topic/20419911878
* http://us.battle.net/hearthstone/en/forum/topic/20419931929
* http://us.battle.net/hearthstone/en/forum/topic/20419931928
* http://us.battle.net/hearthstone/en/forum/topic/20420201927
* http://us.battle.net/hearthstone/en/forum/topic/20420602026
* http://us.battle.net/hearthstone/en/forum/topic/20418901861
* https://www.reddit.com/r/hearthstone/comments/3z01tt/can_confirm_some_people_getting_wrong_card_back/
* https://www.reddit.com/r/hearthstone/comments/3z0223/looks_like_we_got_thunder_bluff_card_back_a_month/
* https://www.reddit.com/r/hearthstone/comments/3z01ln/incorrect_card_back_for_2015_december_season/
* https://www.reddit.com/r/hearthstone/comments/3z03om/i_have_the_thunder_bluff_card_back_february_2016/
* https://www.reddit.com/r/hearthstone/comments/3yypsz/did_anyone_else_receive_the_card_back_for/
* https://www.reddit.com/r/hearthstone/comments/3z02u8/uhh_did_i_break_it/
* https://www.reddit.com/r/hearthstone/comments/3yyqs9/i_got_the_wrong_cardback_as_a_season_reward/

**Comment by Martios** [comment]
I think this is fixed, right? The seasons passed, everyone got the correct card backs by now.

**Comment by jleclanche** [comment]
Right.
