### ISSUE TITLE
Holy Wrath doesn't show the sparkling visual effect if you have Spell Damage

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#342]
If you have a minion with Spell Damage, Holy Wrath doesn't show the sparkling visual effect. The damage is boosted correctly, so this is just a visual bug.
* http://us.battle.net/hearthstone/en/forum/topic/12673559803

![hearthstone screenshot 01-04-16 04 18 23](https://cloud.githubusercontent.com/assets/11700272/12082916/3d3817f8-b29a-11e5-93ee-e7dad5093f40.png)

**Comment by culinko** [comment]
This is now fixed (most likely in 5.0.0.12574).

**Comment by jleclanche** [comment]
It was fixed in 12051 (Holy Wrath gained `AFFECTED_BY_SPELL_POWER`)
