### ISSUE TITLE
Presummon Triggers (Murloc Tidecaller/Cobalt Guardian vs Mirror Entity)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#35]
When a Murloc Tidecaller is copied by the effect of Mirror Entity, even though a Murloc Tidecaller is being summoned, the original Murloc Tidecaller does not trigger at all.

---

(Before unknown patch between 5.0-7.0):

When a Cobalt Guardian or Murloc Tidecaller is copied by the effect of Mirror Entity, the on-summon trigger goes off before the copy even begins, and when the copy happens, it copies the post-trigger state rather than the pre-trigger state. Despite using the wording 'whenever you summon' like Summon Resolution Step triggers, their timing is totally different.

For example, if you play Murloc Tidecaller into Mirror Entity, the played Tidecaller will buff in response to the copied Tidecaller, then the copied Tidecaller enters play as a 2/2 as well.

[[Hearthstone Science] Murloc Tidecaller into Mirror Entity](https://www.youtube.com/watch?v=Wl6QyeeMEgs)

---

(In previous patches, these minions also triggered on Transforms. But this has since been fixed.)

[[Hearthstone Science] Murloc Tidecallers and Faceless Manipulators](https://www.youtube.com/watch?v=QNpUgSTEWFI&t=5m55s)

[[Hearthstone Science] Cobalt Guardian, Faceless Manipulator and Knife Juggler](https://www.youtube.com/watch?v=hSIrCsOc_dA)

**Comment by Patashu** [comment]
Confirmed in 3.0 by quasarc, including recombobulator -> target dummy -> cobalt guardian triggers:

https://www.youtube.com/watch?v=Fh44iz3-PGs

https://www.youtube.com/watch?v=SrHVKYAyxig

https://www.youtube.com/watch?v=hfoxyv5uLbw

**Comment by Patashu** [comment]
(Confirmed in 3.1?) Another consequence is that if you Recombobulate a Cobalt Guardian into another Mech, the Cobalt Guardian gains Divine Shield before disappearing, and it remains visually glitched on the board afterwards:

http://us.battle.net/hearthstone/en/forum/topic/19288930009

**Comment by culinko** [comment]
I tested the following interactions in 4.1:

Faceless on Murloc Tidecaller (2 buffed minions)
Faceless on Cobalt Guardian (2 minions with Divine Shield)
Mirror Entity on Murloc Tidecaller (2 buffed minions)
**Mirror Entity on Cobalt Guardian (No Divine Shield)**

Log of the last interaction: https://gist.github.com/culinko/5617e6fe3459e5df0d7b

**Comment by 10925** [comment]
"Mirror Entity on Cobalt Guardian (No Divine Shield)"
That's obviously, since Cobalt only trigger by friendly mechs.

**Comment by culinko** [comment]
Oh right, you are correct.

**Comment by PattuX** [comment]
Pre-summon reaction bug + visual glitch with divine shield not disappearing confirmed in 4.2

**Comment by Patashu** [comment]
Modernized

**Comment by culinko** [comment]
Tested this in 7.0 and it appears to be fixed. However, playing Murloc Tidecaller into Mirror Entity didn't buff any of the Tidecallers and using Faceless Manipulator on Cobalt Guardian didn't buff the initial minion as well. Is this intended?

Log: https://gist.github.com/culinko/162bb332f84784a5e682fb90c359a654.

![hearthstone screenshot 12-14-16 19 20 04](https://cloud.githubusercontent.com/assets/11700272/21197298/4278245e-c23b-11e6-8747-858ec139e484.png)

**Comment by Patashu** [comment]
I guess this means that minions created by a Transform effect don't run Presummon triggers anymore (which is how it should work, IMO - transforming into something isn't summoning it, after all). I'll update the advanced rulebook.

**Comment by 10925** [comment]
Murloc Tidecaller only trigger by friendly murloc now, so I think that's normal?

And I don't think that would be a fix, since the text is same with summon-resolution minions. So the transforming minion like faceless into a mech should trigger Cobalt Guardian's effect. Just like Durids trigger Knight of the Wild's effect.

**Comment by Patashu** [comment]
> Murloc Tidecaller only trigger by friendly murloc now, so I think that's normal?

Oops. Now to go and rework all my edits *sweatdrop*

> And I don't think that would be a fix, since the text is same with summon-resolution minions. So the transforming minion like faceless into a mech should trigger Cobalt Guardian's effect. Just like Durids trigger Knight of the Wild's effect.

Yeah, I'm... I'm not sure what Blizzard should do for everything to be considered 'non-bugged'. I guess it's going to be some kind of bug/inconsistency at least until all cards that say 'whenever you summon an X' are the same mechanic.

**Comment by 10925** [comment]
From my and kybxd's' test, we believe that Murloc Tidecaller and Cobalt Guardian are summon resolution step now (which same with other card text with "whenever summon")

**Comment by Kybxd** [comment]
![image](https://user-images.githubusercontent.com/18246091/29565283-deb74f82-8777-11e7-82bd-0b45093be7d6.png)
![image](https://user-images.githubusercontent.com/18246091/29565288-e5b8df3a-8777-11e7-9a3a-115cf55a4be3.png)

**Comment by Patashu** [comment]
RIP Presummon Triggers.

**Comment by troggnostupidhs** [comment]
Is this fixed?

**Comment by Patashu** [comment]
Fixed by virtue of not existing as a mechanic anymore.

**Comment by 10925** [comment]
And the Awaking the Creator became after summon  step.
Which means you can adapt to gain Deathrattle to do the quest, or copy minions with add-on deathrattle( like Ancestral Spirit) to do the quest.
