### ISSUE TITLE
Game runs in slow motion after your previous game ended in a Draw

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#354]
After your recent game ended in a Draw, the game will run in slow motion until you restart your client. This bug happens in every mode, not just in Tavern Brawl with Gearmaster Mechazod as previously assumed. I had this happen with SimFri after testing the 89 turn limit. Just tested it now in practice and reproduced it 2 out of 3 times.
- http://us.battle.net/hearthstone/en/forum/topic/19649325819
- https://www.reddit.com/r/hearthstone/comments/3pcv9u/list_of_current_hearthstone_bugs/cw5pe9l

**Comment by theAprel** [comment]
I think it's caused by both hero portraits exploding. I've only seen it happen after losing these brawls, not after winning.

**Comment by culinko** [comment]
I specifically didn't mention winning or losing, because it can happen after both. Me and my friend had this happen after a win (separate games).

**Comment by culinko** [comment]
I had this happen again today, but after a loss this time. You might want to actually remove the strikethrough, because now I am actually doubting my previous statement.

**Comment by PattuX** [comment]
Report of this in another brawl:

* http://us.battle.net/hearthstone/en/forum/topic/20743324242?page=1

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4jypd7/tavern_brawl_feels_like_its_in_slow_motion/ Is this confirmed in 5.0 then?

**Comment by Patashu** [comment]
Confimed in 5.0.0.13030:

http://us.battle.net/hearthstone/en/forum/topic/20745084836

**Comment by troggnostupidhs** [comment]
I believe this is fixed.

**Comment by culinko** [comment]
Couldn't reproduce it 3 times against an Innkeeper.
