### ISSUE TITLE
Getting your 500th win against an alternate hero won't change your hero into golden in the following animation

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#356]
If you win your 500th game against Alleria, Magni or Medivh, in the following animation, your hero won't turn into its golden version, instead it will turn into non-golden Rexxar, Garrosh or Jaina (depending on the alternate hero of your opponent). If you go back into the main menu, your hero will be correctly golden.
- https://www.reddit.com/r/hearthstone/comments/3dc98y/weird_bug_when_getting_500_wins_against_magni/
- https://www.reddit.com/r/hearthstone/comments/3a4fkc/umm_actually_it_was_paladin/
- https://www.reddit.com/r/hearthstone/comments/414cax/finally_got_my_500th_ranked_win_with_mage_then/

**Comment by troggnostupidhs** [comment]
Does this image give any information for this ticket?

https://www.reddit.com/r/hearthstone/comments/9pmb1t/500_wins_ending_with_bloodreaver_guldan/

![image](https://user-images.githubusercontent.com/22508641/47235815-2dbb0d80-d3a8-11e8-866f-396bd759883a.png)

**Comment by culinko** [comment]
Not really. The image could be pre-transformation or post-transformation, also it's on mobile platform which might behave differently to pc version (e.g. the background is grayscale, no idea how is it in pc version currently).

**Comment by troggnostupidhs** [comment]
Is this fixed?

https://youtu.be/tGgxl8RTLEo?t=1020

**Comment by culinko** [comment]
The 500th win has to be **against** one of the hero skins and in this case it was just an Anduin :)

**Comment by troggnostupidhs** [comment]
This is fixed

https://www.youtube.com/watch?v=W8_9MCvtt1w&t=15
