### ISSUE TITLE
Discover effects do not add their card to your hand until the end of the current Sequence

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#358]
1) The card chosen during a Discover spell or Battlecry is not added to your hand until the current Sequence fully resolves. If we fill our hand before then (such as by using Knife Juggler or Wild Pyromancer), it cannot be added anymore. (In the log, it goes from SETASIDE to GRAVEYARD, and your opponent can see it in the sidebar.)

2) Brann Bronzebeard normally gives your minion a second Battlecry if you control him during the Battlecry Phase. However, for Discover minions, you must control Brann Bronzebeard when the Sequence ends to get your second Discover effect at this timing. (The played minion, however, does not have to remain alive.)

(Also, Tracking is equivalent to Discover here.)

It is unclear if these behaviours are working as intended or are bugs.
- https://www.youtube.com/watch?v=q_BfpGdT_r4

It also happens with Discover-like effects (Like Kazacus):

https://www.reddit.com/r/hearthstone/comments/5hlnph/potion_of_polymorph_transforms_kazakus_in_the/

**Comment by Patashu** [comment]
To confirm that this is real and not some weird visual glitch, have the opponent play Snipe or Sacred Trial, then you play your Discover minion. If the Knife Juggler is really triggering between the two Discover battlecries, he will trigger. If he really isn't, Snipe/Sacred Trial will trigger first, kill the Discover minion, and during the After Summon Phase Knife Juggler will not trigger because the played minion is not in play anymore.

You can also test using Sword of Justice instead of Knife Juggler.

**Comment by Patashu** [comment]
I tested this further with Xinhuan. The results of my tests are in this video. Read description and logs for further information.

https://www.youtube.com/watch?v=q_BfpGdT_r4

We will want to edit the hs-bugs entry AND the wiki in light of this new information. Then, we have to decide (or ask) if this is a bug or working as intended.

**Comment by Patashu** [comment]
Sir Finley Mrrgglton needs to be tested to see if he has the same 'delayed Discovery' behaviour, or if both of his Battlecries are in the Battlecry Phase. Can use a dying Majordomo to test timing.

**Comment by PattuX** [comment]
Tested Finley, HP replaycement is delayed aswell.

https://youtu.be/NJfmmBH_uJs

**Comment by Patashu** [comment]
Confirmed in 7.0 in an unexpected way: After you play Kazacus and choose mana cost, Potion of Polymorph resolves before you continue with the potion.

https://www.reddit.com/r/hearthstone/comments/5hlnph/potion_of_polymorph_transforms_kazakus_in_the/

**Comment by VoidMayonnaise** [comment]
The delayed discover bug no longer works in 8.0. Seems that this issue can be closed.

**Comment by culinko** [comment]
Verified all the scenarios mentioned in this issue with PattuX and can confirm the Discover effects are not delayed anymore.
