### ISSUE TITLE
Lesser Heal cannot be discovered by Sir Finley Mrrgglton if you are a Priest in Shadowform

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#364]
If you are a Priest in Shadowform and play Sir Finley Mrrgglton, Lesser Heal cannot be offered as one of the three options. This is likely because Mind Spike/Mind Shatter are Priest Hero Powers as considered by the game. (This also implies that if you have a specific Upgraded Hero Power, you cannot be offered the Basic version, and if you have a Neutral Hero Power, you can be offered every Basic Hero Power.) It's unclear if this is intended or an oversight.
- http://us.battle.net/hearthstone/en/forum/topic/20419913118#9

Based on the above post, screenshots are displayed for 12 attempts. If you could discover Lesser Heal as a Priest in Shadowform, there is a chance of only ~1/130 to not see Lesser Heal once in 12 attempts.

Fury has also claimed to have not seen Lesser Heal in 72 total attempts. If you could discover Lesser Heal as a Priest in Shadowform, this is a 1/4.77e12 chance occurrence. So while technically impossible to prove, it is very likely this is a real bug.

The bug is not specific to Priest. Lord Jaraxxus will not be offered Life Tap because INFERNO! is a Warlock Hero Power:
- http://us.battle.net/hearthstone/en/forum/topic/20419913118#11

**Comment by Patashu** [comment]
(Since the rule seems to be something like 'Sir Finley Mrrgglton will not offer the Basic Hero Power corresponding to the Class of your current Hero Power, and this prevents cases like being offered the Basic version of your Upgraded Hero Power automatically, it's not clear if this is intended or an oversight.)

**Comment by Patashu** [comment]
Another one to check: Jolt (from Charged Hammer Deathrattle) is a Shaman Hero Power, so it should be impossible to be offered Totemic Call.

**Comment by PattuX** [comment]
Vilefin Inquisitor should be tested aswell.

**Comment by troggnostupidhs** [comment]
I was going to test everything, but I got lucky on my first try. Do the other classes need to be tested?

![img000](https://user-images.githubusercontent.com/22508641/32861871-298ba71c-ca24-11e7-81dd-6de7f9c0bc78.png)


Priest Deck
AAEBAZ/HAgLtBYQXDvsBtALlBLkGyQbTCtcK7K4C+rACtbsC8LsC4b8C0cEC2MECAA==

Shaman Deck
AAEBAfe5AgLtBYQXDr0B7gH7AbQC9QT+BbkG8RGyFLkU96oC+aoCoLYC3boCAA==

Paladin Deck
AAEBAaToAgKEF7y9Ag77AbQC3AP0BbkGrwePCeoPyRbTqgKzwQKIxwLjywKmzgIA
