### ISSUE TITLE
Lock and Load's crosshair animation persists after becoming another hero and ending the turn

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#367]
If you use Lock and Load, then transform into another hero, such as Lord Jaraxxus or Ragnaros, the crosshair's animation will not terminate after you end your turn. Your opponent will also see the animation persist. This is only an audio-visual bug, because you don't receive any Hunter cards after playing more spells.
- https://www.reddit.com/r/hearthstone/comments/3xoklv/lord_jaraxxus_counts_as_spell/cy6ut2z
- https://www.youtube.com/watch?v=1gg9jMllHtg

**Comment by PattuX** [comment]
Never thought this would happen, but confirmed in a real game.

https://youtu.be/NG2HxkpEQUA?t=7m15s

**Comment by troggnostupidhs** [comment]
Fixed for me.

![hearthstone screenshot 09-07-17 08 26 10](https://user-images.githubusercontent.com/22508641/30163304-7c13abe2-93a6-11e7-92be-ea93333b9b2b.png)
![hearthstone screenshot 09-07-17 08 26 30](https://user-images.githubusercontent.com/22508641/30163303-7c139b52-93a6-11e7-843d-5ffe28c266da.png)
![hearthstone screenshot 09-07-17 08 26 36](https://user-images.githubusercontent.com/22508641/30163305-7c14a902-93a6-11e7-8aa7-74bbb80fe33c.png)

**Comment by troggnostupidhs** [comment]
Also tested with Deathstalker Rexxar, and it is fine.

Deck
AAEBAR8E6RG0E9PNAobTAg2NAbUD6wftCceuAs6uArm0Auq7AqbBAonDAorDAo7DAtfNAgA=
