### ISSUE TITLE
Far Sight and Call Pet have an early priority

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#368]
When playing Far Sight or Call Pet, their cost reduction will always apply first. This contradicts the current model and leads to the unintuitive behaviour of making a card cost (5) when drawn by Far Sight/Call Pet while Naga Sea Witch is on board.

* https://youtu.be/RNrXJGFETXw?t=3m41s

Whether Far Sight/Call Pet apply even before Summoning Portal is untested atm.

**Comment by jleclanche** [comment]
This is a design issue... whether it's unintuitive isn't a problem unless the devs say it's a problem.

**Comment by jleclanche** [comment]
Closing this. Reopen if you can find an actual inconsistency between existing cards that are supposed to behave the same way.
