### ISSUE TITLE
Spell Damage animation persists on spells after Spell Damage minion dies.

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#369]
The sparkling effect sometimes stays on cards affacted by Spell Damage, even after your minion with Spell Damage dies. 
After hovering over the spell, the animation correctly disappears.

![tteakf4](https://cloud.githubusercontent.com/assets/11700272/12663805/5585fe2a-c62b-11e5-800a-416f08c32af2.jpg)

**Comment by Patashu** [comment]
Fixed according to http://us.battle.net/forums/en/hearthstone/topic/20749867298

**Comment by troggnostupidhs** [comment]
There haven't been reports of this. It should be fixed.
