### ISSUE TITLE
Auchenai Soulpriest flipped heals on a Divine Shield minion trigger on-damage triggers

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#37]
Normally, a Frothing Berserker does not trigger on damage reduced to 0, such as by a Divine Shield. But if you use an Auchenai Soulpriest and hit a Divine Shielded minion with a heal inverted into damage, the Frothing Berserker triggers once.

[[Hearthstone Science] Soulpriest-flipped Heal into Divine Shield, Frothing Berserker bug ](https://www.youtube.com/watch?v=PA40IjxYUJI)

It also appears to happen with other on-damage triggers such as Acolyte of Pain.

http://us.battle.net/hearthstone/en/forum/topic/14395499457

**Comment by Patashu** [comment]
Fixed in 2.8, 3.0 or 3.1 (exact timing unknown), confirmed by ZeroRin in 3.1.

**Comment by jleclanche** [comment]
Was fixed in 3.0
