### ISSUE TITLE
Transforming into Ragnaros mid-attack will result in client hang

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#370]
If you have damaged Majordomo Executus on the board and you attack with a weapon or an attack buff into an enemy hero who played Explosive Trap, your attack will get correctly cancelled. But Ragnaros won't display any attack value and if you decide to attack again, your client will hang. (The remaining secret was Misdirection, so it wouldn't trigger anyway.)
- http://us.battle.net/hearthstone/en/forum/topic/20419434002
- http://us.battle.net/hearthstone/en/forum/topic/20419284270

Log of the interaction: https://gist.github.com/culinko/10138b87090d3e05a4b3.

![hearthstone screenshot 01-29-16 01 05 12](https://cloud.githubusercontent.com/assets/11700272/12663209/44bfdd90-c626-11e5-84bd-b805458ed9a1.png)

![hearthstone screenshot 01-29-16 01 05 21](https://cloud.githubusercontent.com/assets/11700272/12663213/4e56c6c0-c626-11e5-9936-75ecfebaaa4e.png)

It also seems to hang if your next action is using your Hero Power.

![image](https://cloud.githubusercontent.com/assets/666597/12706073/c2ef967c-c8d0-11e5-954c-91a86636e45b.png)

**Comment by Patashu** [comment]
Tweeted at @ywoo_dev here: https://twitter.com/Patashu0/status/692865474820845569

**Comment by Patashu** [comment]
Added a new screenshot/report - it looks like it also hangs if your next action is using your Hero Power (rather than attacking).

**Comment by PattuX** [comment]
Replacing the defender mid-attack does not cause any hang.

Whether you are able to attack again should depend on https://github.com/HearthSim/hs-bugs/issues/16.
(Majordomo dieing in the first death phase is currently untested, him dieing in a subsequent death phase leaves the attacker exhausted)

**Comment by culinko** [comment]
Confirmed this hang with replacing attacker mid-attack with Explosive Trap, also both players will hang, not just the attacking player.

**Comment by troggnostupidhs** [comment]
Fixed.

![img001](https://user-images.githubusercontent.com/22508641/32642877-4755b16c-c5a5-11e7-8de5-cadf15d5cee2.png)
![Uploading img002.png…]()
![Uploading img003.png…]()
