### ISSUE TITLE
'Battlecry canceled' appears after canceling playing of combo minion

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#373]
After you cancel playing a combo minion, a message 'Battlecry canceled' appears. Only happens on mobile platforms. Reproduced by PattuX on an iPad.
- https://www.reddit.com/r/hearthstone/comments/44fonh/why_is_combo_coded_as_a_battlecry_but_doesnt_act/

**Comment by troggnostupidhs** [comment]
This now says 'Targeting canceled.'

![screenshot_2016-12-08-17-20-54](https://cloud.githubusercontent.com/assets/22508641/21030113/d9f407ec-bd6a-11e6-892d-9cb41e030e4a.png)

**Comment by culinko** [comment]
I'm actually surprised that they fixed this one! Btw. Druid's choose one cards (Keeper of the Grove, Ancient of Lore) do not display any text when you cancel their targeted effects after choosing one of them.
