### ISSUE TITLE
Emperor Thaurissan: Uses his hero power 'Deal 30 damage' on a minion instead of your hero

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#374]
If you manage to kill Moira Bronzebeard and have Ysera or Confessor Paletress on the board (presumably other high-priority legendaries work too), Emperor Thaurissan will use his hero power on them instead of killing you. This is a very specific issue and easily reproducible (I reproduced it with Ysera), so I decided to add it.
- https://www.reddit.com/r/hearthstone/comments/3ux8lt/til_heroic_emperor_thaurissan_can_target_minions/
- https://www.reddit.com/r/hearthstone/comments/402fyw/thats_not_how_youre_supposed_to_use_that/

**Comment by troggnostupidhs** [comment]
This is fixed. Tested on Normal.

Deck
AAEBAZ/HAgSiCfsT4b8C8uwCDfsBkALlBLkG+AfTCtcK8gyQD+yuApK0AvC7AtjBAgA=
