### ISSUE TITLE
Card permanently displaced after playing a spell

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#377]
If you play two (or more) spell within a short span of time, all cards right to the card played will be displayed right to their usual position.
- http://us.battle.net/hearthstone/en/forum/topic/20742484138
- https://www.reddit.com/r/hearthstone/comments/45d9ur/is_anyone_else_getting_a_weird_hand_glitch/

I managed to reproduce it on iPad Air, iOS 9.2. In contrast to what the report said I was able to play the card by tapping on it (on the displaced card, not the gap) as usual.

![image](https://cloud.githubusercontent.com/assets/15743638/12992582/8db58208-d115-11e5-90b2-fe577f8851c8.png)

**Comment by Xinhuan** [comment]
This one seems like a duplicate, or at least, related to #97. Both are caused by playing spells, except that in the other issue, the gap is temporary, this one seems to be permanent.

**Comment by Patashu** [comment]
Is this a repro outside of Brawl?

https://www.reddit.com/r/hearthstone/comments/47s8u7/i_lost_a_ranked_game_because_of_a_glitch/

**Comment by culinko** [comment]
I had this issue happen with Preparation and Nefarian in a friendly match, but didn't pay much attention to it, because I couldn't reproduce it again. Let me check if I can find the screenshot.

**Comment by culinko** [comment]
Happened to me in the current 'Deal Your Fate' Tavern Brawl by playing multiple coins:

![hearthstone screenshot 03-05-16 20 15 26](https://cloud.githubusercontent.com/assets/11700272/13550301/f96cfc6c-e31a-11e5-8b64-615d898598e3.png)

**Comment by culinko** [comment]
Happened to me again by playing Malygos, Eviscerate, Preparation (already happened to me once with Preparation before). The second Eviscerate was in the position 2, but there was a gap at position 2, so it appeared at position 3. I managed to click it after some moments of restless clicking. Attaching logs which might or might not help.

Power.log: https://gist.github.com/culinko/567c46dbf8b9f433612f
Zone.log: https://gist.github.com/culinko/b7f7ce225286fb6304b6

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20743016436 Instance in 4.2 I think?

**Comment by culinko** [comment]
I believe that's #97. He mentioned the Consecration being clickable right before the turn ended, so I imagine the queued animations just resolved and Consecration went to the correct spot. The permanent gap is not fixed unless you draw a card or play another card from your hand (to make your hand update).

**Comment by PattuX** [comment]
Report in 5.0

* http://imgur.com/8CzGDaw

**Comment by PattuX** [comment]
Video of this bug:

* https://youtu.be/oPO3kSiLS7M?t=9m57s

Again it is Prep causing the issue, but he didn't even play the spells that fast...

**Comment by Patashu** [comment]
Another report:

https://www.reddit.com/r/hearthstone/comments/4hd2uf/nearly_lost_a_game_due_to_the_shifting_cards_bug/

**Comment by Patashu** [comment]
And another: Fireball, Arcane Explosion

http://us.battle.net/hearthstone/en/forum/topic/20743645152

**Comment by culinko** [comment]
Another possible occurrence of this? (mobile): https://www.reddit.com/r/hearthstone/comments/4ia22s/a_glitch_caused_by_curse_of_rafaam_just_cost_me_a/.

**Comment by Patashu** [comment]
Video example: https://www.youtube.com/watch?v=AXq3S_2dH7E&feature=youtu.be&t=12m3s

**Comment by Patashu** [comment]
Version in 5.0.0.13030 making a card unplayable:

http://us.battle.net/hearthstone/en/forum/topic/20745205200

**Comment by Patashu** [comment]
Confirmed in 5.2.0

http://us.battle.net/hearthstone/en/forum/topic/20746954723

**Comment by culinko** [comment]
Confirmed in 6.0: https://www.reddit.com/r/hearthstone/comments/504kpi/just_had_this_very_annoying_bug_could_not_cast/.

**Comment by Patashu** [comment]
Potentially fixed according to http://us.battle.net/forums/en/hearthstone/topic/20749867298

**Comment by troggnostupidhs** [comment]
This one should probably be closed. I don't think it's been seen since it was reported as fixed.
