### ISSUE TITLE
Card in hand visually moves to foreground

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#379]
When spectating a player who plays a card with a targeted effect, picks a target and cancels it, there will be a visual bug for the spectating player that will show the parts of the canceled card in the foreground. This visual bug will be fixed for the spectating player if either of the players hover over the bugged card. This issue is 100% reproducible.

Parts of the Shadow Word: Death are in the foreground:
![hearthstone screenshot 02-16-16 20 03 49](https://cloud.githubusercontent.com/assets/11700272/13088028/e2f0e716-d4ea-11e5-914a-2e256cf6741d.png)

There is a similar bug unrelated to spectating. When you hover over your cards right when your turn starts (might be related to any animation) and before you draw a card, you can get one of your cards bugged the same way. You don't need to click the cards, hovering is enough. This happens with any card, not just cards with targeted effects like the spectator bug. Hovering over the bugged card fixes the problem as well. **However, this is much harder to reproduce reliably.**

Parts of Elise Starseeker are in the foreground:
![hearthstone screenshot 02-16-16 19 41 28](https://cloud.githubusercontent.com/assets/11700272/13088822/23d73cd2-d4ee-11e5-9090-027df89ff728.png)

**Comment by PattuX** [comment]
Confirmed for Patch 4.2

![hearthstone screenshot 03-14-16 22 44 45](https://cloud.githubusercontent.com/assets/15743638/13761058/9e799d1a-ea36-11e5-9364-7ecab98f8bd4.png)

**Comment by troggnostupidhs** [comment]
Happened to me not in spectator mode.

![hearthstone screenshot 12-09-16 21 25 11](https://cloud.githubusercontent.com/assets/22508641/21071287/37b63666-be6a-11e6-8066-9108918ed408.png)

**Comment by troggnostupidhs** [comment]
Still happens not in spectator.

**Comment by troggnostupidhs** [comment]
The easiest way to reproduce this is mouse over the card right when your turn starts, just as the 'Your Turn' banner starts to appear, and to swipe right over the other cards. Timed right, the card will be displaced.

![img000](https://user-images.githubusercontent.com/22508641/34704486-5dd2a868-f4c7-11e7-8f39-b9f9d14cdeed.png)
![img001](https://user-images.githubusercontent.com/22508641/34704487-5de1099e-f4c7-11e7-8561-c2b77d982180.png)
![img002](https://user-images.githubusercontent.com/22508641/34704488-5debda40-f4c7-11e7-9e65-fbadb1d61136.png)

---

![img003](https://user-images.githubusercontent.com/22508641/34704491-626a7d56-f4c7-11e7-94f0-d83f6c3c0fef.png)
![img004](https://user-images.githubusercontent.com/22508641/34704493-62a44090-f4c7-11e7-9dce-890dd4ba1472.png)

---

![img005](https://user-images.githubusercontent.com/22508641/34704496-68456c40-f4c7-11e7-9b68-fadba7625aa1.png)
![img006](https://user-images.githubusercontent.com/22508641/34704497-68a38fc8-f4c7-11e7-9f9f-33e3a2a6a23d.png)

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=Qx0lKKrRdpU

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21964710

> Cards in hand no longer incorrectly overlap each other.

**Comment by ceceita** [comment]
cant reproduce it , mb fixed or im doing it wrong

**Comment by troggnostupidhs** [comment]
original report was for spectator mode

**Comment by culinko** [comment]
It happened for both spectator and normal as well. The first screenshot is me spectating, the second screenshot is me playing.

**Comment by troggnostupidhs** [comment]
There are two reproduction cases.

While playing, mouse over the cards at the start of your turn.

In spectator, observe the player canceling a targeting effect.

**Comment by troggnostupidhs** [comment]
Multiple cancels, no problem

![hearthstone screenshot 10-16-18 09 04 20](https://user-images.githubusercontent.com/22508641/47018331-8b3e2880-d122-11e8-93c6-98ff597db38a.png)
