### ISSUE TITLE
All-Character AoE damage ignores 0 Health minions, All-Minion AoE damage hits them

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#38]
AoE damage that hits all Characters, such as Abomination, Flame Leviathan and Explosive Trap, does not hit minions that have already been reduced to 0 or less Health ('mortally wounded').

However, AoE damage that hits all Minions, such as Explosive Sheep, hits minions that have been reduced to 0 or less Health, and continues to trigger on-damage triggers.

It is not clear which is the intended behaviour and which is the bug.

[[Hearthstone Science] Does AoE Damage Overkill Minions?](https://www.youtube.com/watch?v=V7Y0V2kKM2A)

Note that as of Patch 3.0, this behaviour may have been standardized to always hitting 0 Health minions:

\<quasarc\> If you have 2x abom, a 1/5 acolyte and a soulpriest on the board and you play circle of healing, it used to be that you would only draw 2 cards. They recently changed that and you draw 3 now. I don't know if you guys know this already.
\<quasarc\> I tested it today, i don't know since when it's like that
\<quasarc\> Last patch maybe

Note that The Grand Tournament adds Spawn of Shadows, which deals damage to both Heroes and can be triggered multiple times in the Inspire Phase, so it should be tested whether this overkills Heroes that are already at 0 Health or ignores them.

**Comment by NightKev** [comment]
[Video from quasarc showing the change in 3.0](https://youtu.be/E4wYoUKMi_Q)

**Comment by Patashu** [comment]
As the behaviour is now consistent in 3.0, I have closed this bug.

**Comment by culinko** [comment]
Relevant issue: #165. Not adding this fixed issue into the fixed wiki bugs yet.
