### ISSUE TITLE
At the start of your turn, clicking at the bottom right of your hand can grab the drawn card before animations finish

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#384]
- https://www.youtube.com/watch?v=eyoOrOttQWQ
- http://gph.is/1WzCrJV

Additionally, doing this bug fast enough will cause a client animation hang at the start of your next turn - see https://github.com/HearthSim/hs-bugs/issues/324 .

**Comment by culinko** [comment]
This bug no longer happens, it was probably fixed in the same patch as #324.
