### ISSUE TITLE
Queue button glitch

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#389]
Clicking the button to queue into the game immediately after clicking on the game mode from the main menu (before the screen fully loads) will make the loading 'spinning wheel' appear over the whole screen.
- https://www.youtube.com/watch?v=0yDTpBx8BtE

The circle is an approximate location of the queue button (left for Tavern Brawl, right for Play Mode):
![buttons](https://cloud.githubusercontent.com/assets/11700272/13325349/b6acb740-dbe1-11e5-8866-369a1723d003.png)

You can also do this the other way around (tested in Tavern Brawl). If you go to Brawl menu, click the 'Back' button, then quickly click the queue button.
- https://www.youtube.com/watch?v=wZ3Xeaavziw (If you manage to do this multiple times in a row, you'll receive the 'Playful Sprites' error. After restarting your client, you can be reconnected into your ongoing brawl game if the servers successfully connected you to another player before you got the error.)

![hearthstone screenshot 03-19-16 12 57 47](https://cloud.githubusercontent.com/assets/11700272/13898473/3243c946-edd2-11e5-9778-a69ca870534c.png)

**Comment by culinko** [comment]
If you do it the other way around, go to brawl menu, click 'Back', then quickly click the queue button, the you will get 'Playful Sprites' error. After restarting your client, you will be reconnected into your brawl game.

**Comment by Patashu** [comment]
https://youtu.be/wZ3Xeaavziw Video repro

**Comment by culinko** [comment]
Confirmed in 6.0: https://www.reddit.com/r/hearthstone/comments/523f23/figured_out_a_few_ui_bugs/

**Comment by troggnostupidhs** [comment]
From testing, all of these seem to be fixed.
