### ISSUE TITLE
Playing Recombobulator on Golemagg causes a server hang

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#39]
If you use Recombobulator on Golemagg, the game crashes server-side because there are no collectible 50 mana minions it could turn into.

http://www.reddit.com/r/hearthstone/comments/3ah5eg/found_a_highpriority_gamebreaking_new_bug/

**Comment by Patashu** [comment]
It is hypothesized that by using https://github.com/HearthSim/hs-bugs/issues/33 you could play Recombobulator targeting a 11-19 mana cost minion in your hand and cause the crash this way. This has not been tested yet.

**Comment by culinko** [comment]
We tested transforming 15 and 16 mana Molten Giants in hand with Recombobulator. The card just disappears from hand and the game continues normally. I assume this bug has been fixed.
* https://www.youtube.com/watch?v=zHqzIjAZmPI

Log: https://gist.github.com/culinko/652f4c84ad73b1fcc0bb.
