### ISSUE TITLE
Being challenged while editing a deck name will leave the deck name displayed permanently

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#391]
If you edit a deck name and you get challenged, the deck name will stay on your screen permanently.
Interestingly, the enter button to open the recent conversation won't work. The bug will be fixed if you either click on a chat bubble after someone messages you or open your friendlist (presumably with Esc too). You can also click on the text and the cursor will appear. You can then edit the name and press enter to save, the text will disappear but the value won't actually be saved.

![hearthstone screenshot 02-26-16 12 56 10](https://cloud.githubusercontent.com/assets/11700272/13351783/7072fc8c-dc89-11e5-9a0c-e551c6684ed6.png)

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 12-10-16 14 01 57](https://cloud.githubusercontent.com/assets/22508641/21075503/bd0ea8ee-bee1-11e6-874a-9c3a45fba5a7.png)

**Comment by troggnostupidhs** [comment]
I think this is fixed. I was challenged while editing the deck name and it didn't stay up.

**Comment by troggnostupidhs** [comment]
If you modify the name but stay in edit mode, it saves the name when you accept the challenge.
