### ISSUE TITLE
Game client "re-awarding" completed adventure cards

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#392]
Since 26 Feb 2016, players have reported randomly completing a game (can be Tavern Brawl, or ranked ladder, arena, etc) and then receiving rewards for Naxxramas adventure cards via the quest complete animation at the end of the game, for example, "Grand Widow Faerlina defeated. Nerub'ar Weblord unlocked".

On going to their collection, players discover they have 4 of those Naxx adventure cards (2 for Legendaries) which are currently not disenchantable. The extra copies disappear on restarting the client.
- https://www.reddit.com/r/hearthstone/comments/47qxl3/just_earned_two_challenge_cards_from_ranked_what/
- https://www.reddit.com/r/hearthstone/comments/47rbkj/free_naxxramas_cards/
- https://www.reddit.com/r/hearthstone/comments/47tejx/so_this_randomly_happened_after_i_won_a_match/
- https://www.reddit.com/r/hearthstone/comments/47u4ns/lpt_if_you_find_and_defeat_the_naxx_bosses_secret/
- https://www.reddit.com/r/hearthstone/comments/47ua6g/someone_conceded_to_me_and_i_unlocked_naxxramas/
- https://www.reddit.com/r/hearthstone/comments/47ualf/extra_naxx_cards_bug/
- http://us.battle.net/hearthstone/en/forum/topic/20742694292
- http://us.battle.net/hearthstone/en/forum/topic/20742754302

Most of the threads above contain multiple screenshots. It is speculated this is caused by a server update for the upcoming Standard/Wild modes since there is no client patch, and because the BRM/LoE cards do not have this problem.

**Comment by astradamus** [comment]
Interesting, I had this happen with Old Murk-Eye, and it was before they announced that Reward cards would not be Standard. If your theory on server updates is correct, I guess I missed a hint!

**Comment by culinko** [comment]
The issue with Old Murk-Eye is #188 and is not related to this issue.

**Comment by astradamus** [comment]
Are you certain? #188 doesn't describe quite the same behavior--it seems to only describe having an increased number appear in the collection, whereas I had precisely the behavior here: I won a match (I think it was Tavern Brawl), and it showed me the whole reward popup over again, on top of showing the increased count in collection. Also, it happened after the announcement of formats, but before the FAQ was updated to note that Rewards would not be Standard.

**Comment by culinko** [comment]
It shows you the pop-up after a match as well. It has been happening since beta. I will add the missing information into the issue.

**Comment by culinko** [comment]
It happened again after the recent patch, this time with LoE, BRM or the free C'Thun cards (such as Beckoner of Evil):

* https://www.reddit.com/r/hearthstone/comments/4x4n8z/random_loe_launch_bug/
* https://www.reddit.com/r/hearthstone/comments/4wxfic/did_anyone_get_a_bug_with_the_recent_update/
* https://www.reddit.com/r/hearthstone/comments/4wxtxy/bug_i_am_getting_rewarded_cards_from_blackrock/
* https://www.reddit.com/r/hearthstone/comments/4wzdh9/adventures_bug/
* https://www.reddit.com/r/hearthstone/comments/4x11de/weird_bug_after_update/
* https://www.reddit.com/r/hearthstone/comments/4x7r8r/hs_bug_since_update_help/
* https://www.reddit.com/r/hearthstone/comments/4x364o/weird_bug_at_login_after_the_patch/

**Comment by troggnostupidhs** [comment]
Can this be considered 'fixed'?

**Comment by culinko** [comment]
I am not so sure. I believe this happens every time there's a new adventure. Last time it happened just after One Night in Karazhan has been released. I think we should wait for the next adventure to see whether this issue is still present.

**Comment by troggnostupidhs** [comment]
This hasn't happened with the latest adventure that was included with Knights of the Frozen Throne. Supposedly, there won't be anymore stand alone adventures. https://playhearthstone.com/en-us/blog/20475356

Can this be closed?
