### ISSUE TITLE
Alleria is using Lady Liadrin's entrance animation

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#403]
Alleria's entrance animation was accidentally changed into Lady Liadrin's entrance animation.
* https://www.reddit.com/r/hearthstone/comments/4aeswp/bug_with_allerias_entrance_animation/

**Comment by SimFriHS** [comment]
Video documentation can be seen here: https://www.youtube.com/watch?v=11fkBSqKs8w

**Comment by jleclanche** [comment]
Acked at https://twitter.com/bdbrode/status/711237088138567680

**Comment by PattuX** [comment]
http://www.hearthpwn.com/news/1347-new-mage-hero-khadgar-available-on-ios-only#c58

"Alleria will no longer use Lady Liadrin's entrance animation when starting a game."

Hearthpwn says they quote Blizzard, but I can't find the original...

**Comment by culinko** [comment]
This bug has been fixed.
