### ISSUE TITLE
Mimiron's Head summoning V-07-TR-0N causes a client animation hang

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#406]
Sometimes when Mimiron's Head triggers and summons V-07-TR-0N, your client will hang just after the animation (e.g. before you draw a card). The hang seems to be due to Clockwork Gnome or Mechanical Yeti's Deathrattle resolving during the animation. You must disconnect and reconnect in order to continue playing.

* https://www.youtube.com/watch?v=RhF2WQksOmU&feature=youtu.be
* http://us.battle.net/hearthstone/en/forum/topic/20742994541
* http://us.battle.net/hearthstone/en/forum/topic/20742944588
* http://us.battle.net/hearthstone/en/forum/topic/20743024582 (includes 2 screenshot albums)
* https://www.reddit.com/r/hearthstone/comments/4awmh0/weird_v07tr0n_bug/ (with screenshot)

Ben Brode has tweeted that it will be fixed in the next patch.

* https://twitter.com/RandomHero313/status/711368959417786369

**Comment by culinko** [comment]
I wasn't able to reproduce the hang, so something has to be required.

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20743024582 just had a second screenshot album uploaded to it, if you need more data.

**Comment by culinko** [comment]
Another report: https://www.reddit.com/r/hearthstone/comments/4awmh0/weird_v07tr0n_bug/.

**Comment by Patashu** [comment]
Theory: Since Mimiron's Head no longer uses a Forced Death Phase (my guess), the deathrattles from the minions it kills to summon V-07-TR-0N now occur after or during the animation, which causes a hang in some cases. So it must depend on which deathrattle effects run.

**Comment by culinko** [comment]
My guess is that it's a card added to hand from the deathrattles + another card (start turn draw) responsible for the hang (since we know that Clockwork Gnome and Mechanical Yeti are affected).

**Comment by Patashu** [comment]
added Ben Brode tweet

**Comment by Patashu** [comment]
Added video https://www.youtube.com/watch?v=RhF2WQksOmU&feature=youtu.be

**Comment by Patashu** [comment]
According to reddit the Forced Death Phase change was reverted. If so, this bug should not happen anymore.

But if the Forced Death Phase change is unreverted, it will come back unless they specifically fixed it.

**Comment by Patashu** [comment]
Going to close this
