### ISSUE TITLE
Looking at a deck recipe causes all saved decks to display the recipe's list

### ISSUE THREAD

**Issue by rkachniarz** [HearthSim/hs-bugs#407]
Steps to reproduce:

- Open the Collection Manager
- Make sure you have at least one saved deck of your own in the collection
- Click the New Deck button and select a class
- Click one of the deck recipes
- Click Back twice to go back to the list of your decks
- Select one of your saved decks

Result: The previously seen deck recipe will be shown instead of your deck

**Comment by Patashu** [comment]
Was this closed as a duplicate? Just making sure (duplicate label needs to be added if so)

**Comment by culinko** [comment]
Duplicate of #402.
