### ISSUE TITLE
Sacred Trial triggers on Lord Jaraxxus the Hero even if there are no other minions in play

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#408]
Lord Jaraxxus is killed 100% of the time when played against an active Sacred Trial, without the need of having 3 or more minions on the board at the time Sacred Trial triggers (after the Battlecry). This bug got introduced in Patch 4.2, the same patch that fixed #255 (for the second time).
* https://www.youtube.com/watch?v=PMZPUfQgCIM
* https://www.youtube.com/watch?v=3-SLvFL9kgM

**Comment by Patashu** [comment]
According to a blue post this just got hotfixed.

http://us.battle.net/hearthstone/en/forum/topic/20742954702#3

If it is, we need to work out the EXACT number of other minions that need to be in play after LJ Battlecry for Sacred Trial to trigger (whether it's 3+ or 4+). So please film both, thanks

**Comment by 10925** [comment]
2 minions: Not trigger
https://www.youtube.com/watch?v=FMojP2lLFb0&feature=youtu.be
3 minions: trigger and kill LJ.
https://www.youtube.com/watch?v=uTROehLWNlE

**Comment by Patashu** [comment]
Finally the interaction is 100% correct \o/

**Comment by jleclanche** [comment]
See you next patch.
