### ISSUE TITLE
Chromaggus: Chromatic Dragonkin's buff Draconic Lineage has a missing texture

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#409]
Draconic Lineage (BRMA12_8te) buff from Chromatic Dragonkin has a missing texture. This new buff got added in 4.2 when they fixed #135. Currently it uses this placeholder texture instead:

![cezegqm](https://cloud.githubusercontent.com/assets/11700272/13810811/1cd6acb6-eb72-11e5-8bc5-70a6df1b39f4.png)

![hearthstone screenshot 03-16-16 12 11 41](https://cloud.githubusercontent.com/assets/11700272/13810782/f69542d8-eb71-11e5-8da2-b3c46ad76a72.png)

**Comment by troggnostupidhs** [comment]
![img000](https://user-images.githubusercontent.com/22508641/31848285-dd6531e0-b5fc-11e7-8bd9-c99599b59228.png)
