### ISSUE TITLE
Fallen Hero extra damage bypasses Immune effect

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#41]
If you have a Fallen Hero in play, a Mal'Ganis to make your Hero Immune and use your Hero Power on yourself, the base damage is prevented but the added damage by Fallen Hero goes through.

https://www.reddit.com/r/hearthstone/comments/3i500j/bug_with_malganis_and_fallen_hero_when_jaina_hero/

http://tieba.baidu.com/p/4104346870

It also works with Ragnaros's Hero Power:

http://us.battle.net/hearthstone/en/forum/topic/18710644804

However: Fallen Hero and Ice Block Immune works correctly.

http://tieba.baidu.com/p/4104073562

Additional notes:

Spell Damage +1 and Immune works correctly.

It is unknown if Fallen Hero and Immune Minions has the same bug. It is unknown if Fallen Hero and Divine Shield minions has the same bug, but it is likely correct (as this is a very common situation in this Tavern Brawl).

**Comment by Patashu** [comment]
In 3.1, Fallen Hero + Hunter Hero Power does not deal damage past Ice Block Immunity:

**Comment by jleclanche** [comment]
@Patashu Doesn't look like that to me at all, it just seems like it can trigger ice block but I dont think it actually *deals* damage...

**Comment by Patashu** [comment]
Confirmed in 3.2:

https://www.reddit.com/r/hearthstone/comments/3qczlw/bug_fallen_hero_with_hunter_hero_power_deals_1/

**Comment by Patashu** [comment]
Weird report that says after popping Ice Block, they could target the enemy Immune Hero with the Mage Hero Power, deal 1 damage (due to having Fallen Hero) and win:

https://www.reddit.com/r/hearthstone/comments/3qmqsu/has_this_happened_to_anyone/

**Comment by culinko** [comment]
Just to be sure, I managed to create the situation described in the previous post and can confirm that you can't target the Immune Hero with Mage Hero Power even with Fallen Hero on the board: http://imgur.com/qpSUE9r.

**Comment by Patashu** [comment]
fixed in 4.0

https://youtu.be/cCCwRoXZHMQ
