### ISSUE TITLE
New Deck button is clickable underneath the UI

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#410]
You can click on the New Deck button when it's scrolled down and not visible. While clicking, the button will be partially visible and will overlap with the rest of the UI.
- http://us.battle.net/hearthstone/en/forum/topic/20742984455

![j3ppebd](https://cloud.githubusercontent.com/assets/11700272/13814747/c7e6633e-eb87-11e5-8ee2-186777b7695e.png)

**Comment by Martios** [comment]
Still happens on 4.3

**Comment by troggnostupidhs** [comment]
Similar issue on mobile

https://www.reddit.com/r/hearthstone/comments/7py3zi/please_blizzard_make_this_part_of_the_menu_non/

![image](https://user-images.githubusercontent.com/22508641/34889503-2cf76a62-f79c-11e7-81e3-e715c48e8c75.png)

**Comment by troggnostupidhs** [comment]
I think this is (finally) fixed.
