### ISSUE TITLE
Decks in slots 3, 6 and 9 are clickable from the second page

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#411]
If you go to the second deck page, you can still click on your rightmost decks from the first page (slots 3, 6 and 9).
* http://us.battle.net/hearthstone/en/forum/topic/20742934574
* https://www.reddit.com/r/hearthstone/comments/4bujd2/blizzard_fix_deck_selection_pls/

**Comment by Martios** [comment]
Still happens on 4.3

**Comment by culinko** [comment]
Fixed in 5.0.0.12574.
