### ISSUE TITLE
Stealing opponent's Dalaran Aspirant or minion buffed by Ancient Mage's battlecry will maintain his buff for original owner

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#412]
If you steal opponent's Dalaran Aspirant after it has been enhanced by using a hero power, your opponent will still keep the spell power bonus.
* http://us.battle.net/hearthstone/en/forum/topic/20742934510
* https://www.reddit.com/r/hearthstone/comments/4apam8/if_you_steal_an_opponents_buffed_dalaran_aspirant/
* https://www.youtube.com/watch?v=dAupq0kvrKU&feature=youtu.be
* http://us.battle.net/hearthstone/en/forum/topic/20742824612?page=1#0

Same happens with stealing opponent's minion that got buffed by Ancient Mage's battlecry:
* https://www.youtube.com/watch?v=W_t2N0sqh58

**Comment by Xinhuan** [comment]
Additional confirmation from Reddit:

https://www.reddit.com/r/hearthstone/comments/4apam8/if_you_steal_an_opponents_buffed_dalaran_aspirant/

**Comment by Patashu** [comment]
Someone test Velen's Chosen and Ancient Mage please?

**Comment by 10925** [comment]
https://www.youtube.com/watch?v=W_t2N0sqh58&feature=youtu.be
Interestingly.
Velen's Chosen would work correctly(since I think because their is an old bug same with this one and they already fix for Velen's Chosen).
But Minion Buff by Ancient Mage would leave the spell power for its origin owner, same as Dalaran Aspirant .

**Comment by Patashu** [comment]
Very likely related to https://github.com/HearthSim/hs-bugs/issues/418

**Comment by Patashu** [comment]
According to https://www.reddit.com/r/hearthstone/comments/4d77mo/why_did_this_jaina_maintain_her_spell_power_after/d1oec64 if you replace your Hero you lose the SPell Damage buff. Is it true?

**Comment by culinko** [comment]
You don't. I just tested it. Innkeeper stole my Dalaran Aspirant, then I transformed into Ragnaros.
Log: https://gist.github.com/culinko/2bc3917cdb82780cc998340bafef14fa.

![hearthstone screenshot 04-04-16 03 13 51](https://cloud.githubusercontent.com/assets/11700272/14236315/ae843c50-fa13-11e5-943c-88c300d6a06b.png)

![hearthstone screenshot 04-04-16 03 14 08](https://cloud.githubusercontent.com/assets/11700272/14236316/b2a66bfa-fa13-11e5-9f21-dde9492c7a83.png)

**Comment by Patashu** [comment]
Interestingly, when you mind control a Dalaran Aspirant, the attached Enchantment that provides Spell Damage does not also change controllers (like it normally would). This is probably part of the bug. I imagine if you logged the same scenario but with Velen's, the attached Enchantment would change controllers.

**Comment by Patashu** [comment]
Looks like this bug is still around in 4.3

http://us.battle.net/hearthstone/en/forum/topic/20743124398

http://us.battle.net/hearthstone/en/forum/topic/20743044389

**Comment by Patashu** [comment]
Can this be re-tested please?

**Comment by culinko** [comment]
Fixed in 5.0.0.12574.

Log: https://gist.github.com/culinko/242c389c308d242a1c764c400d279b15.

![hearthstone screenshot 04-26-16 02 09 13](https://cloud.githubusercontent.com/assets/11700272/14802808/18b389ae-0b54-11e6-811c-82a3518e7eda.png)
