### ISSUE TITLE
Sometimes, after your opponent plays Kezan Mystic, your client will hang

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#415]
This hang happens only on mobile. The cause is unknown, but it appears that the opponent has 2 (or more) active secrets and steals another secret from you with Kezan Mystic. The message "Last Spell Kill" with a timestamp is shown in the bottom right corner.
- https://www.reddit.com/r/hearthstone/comments/3ngilf/last_spell_kill/
- https://www.reddit.com/r/hearthstone/comments/47kuj7/weird_kezan_mysticmirror_entity_interaction_bug/
- http://us.battle.net/hearthstone/en/forum/topic/20742734760
- http://us.battle.net/hearthstone/en/forum/topic/20742654466
- http://us.battle.net/hearthstone/en/forum/topic/20742954581
- https://www.reddit.com/r/hearthstone/comments/4awgzq/bug_infinite_turn_length/
- https://www.reddit.com/r/hearthstone/comments/4awcyp/broke_the_tavern_brawl/
- http://forum.canardpc.com/threads/94478-Hearthstone-Le-topic-2-0/page286

**Comment by Patashu** [comment]
Is there a specific Secret that is always present? Vaporize? Mirror Entity?

Does the hang occur before Kezan Mystic's Battlecry, after Kezan Mystic's Battlecry, when you attack with a minion or when you play with a minion? Is it before, during or after a Secret is revealed?

**Comment by Matthewmob** [comment]
From my short experience with it, here's the info I can give when it happened to me.

- iPhone 5C on mobile data, running iOS 9.2.1 (13D15).
- [Screenshot during the hang](https://i.imgur.com/d41dHKl.jpg). The text box in the bottom right says "Last spell kill: 13:25", the time taking this screenshot was 13:26 (the turn had already gone on for over two minutes).
- I had Counter Spell in play, he had Mirror Entity in play. I attacked with Frigid Snobold to kill his Mad Scientist which gave him no secrets. I then played Dr. Boom which activated his Mirror Entity to copy it onto his board. Ending my turn, he then played Kezan Mystic to take my Counter Spell, and then pinged my face, this is when the hang happened. I only noticed after the game finished, looking back at the screenshot, but in the screenshot he has two secrets when infact he only had one (after Mirror Entity triggered earlier), maybe part of the bug? I restarted my game after about 7-8 minutes of waiting, and there was no message of "You were disconnected from your ranked game" when I started it up again, either.

Hope this helps!

**Comment by culinko** [comment]
Ok, I believe the hang happens on the start of your turn, when the opponent's secrets become active. The client thinks that your opponent has 2 secrets, but he only has one (If you're 100% sure that his Mad Scientist didn't fetch him another). Can you remember if the secret disappeared from his hero portrait after you played Boom? Also, I don't think this is related to specific secrets, since I've seen images of Paladin and Hunter opponents with their secrets. However, they played Kezan Mystic every time.

**Comment by Matthewmob** [comment]
From what I can remember the animation of it played but the number didn't actually decrease. I only noticed this after it happened, so I could be wrong, but I don't know what else could have happened because he had two secrets, one triggered, and then he still had two secrets, I am sure of that.

**Comment by Patashu** [comment]
Another occurrence:

http://us.battle.net/hearthstone/en/forum/topic/20742936023

![image](https://cloud.githubusercontent.com/assets/666597/14230834/092328e0-f9ad-11e5-963d-4d2d7fd10cd6.png)

**Comment by Patashu** [comment]
Is there any other known hang that causes 'last spell kill'?
https://www.reddit.com/r/hearthstone/comments/4fihmw/yoggsarons_tracker_is_already_implemented/

http://m.imgur.com/D47lCAL

I don't see kezan in this report.

**Comment by culinko** [comment]
He added a screenshot of the board and there is Kezan Mystic in the sidebar. However, the hang didn't occur right away, but only after playing a minion. This would imply his opponent stole Mirror Entity and it hanged after he played Zombie Chow.

**Comment by troggnostupidhs** [comment]
Playing Kezan Mystic into Mirror Entity worked fine. The opponent was my account on my mobile device, and it did not have the problem.

![hearthstone screenshot 06-14-17 22 16 59](https://user-images.githubusercontent.com/22508641/27162450-4922185c-514f-11e7-8ffb-0764e9166513.png)

**Comment by culinko** [comment]
This bug only happens randomly under some unknown circumstances and I remember that someone from the community couldn't reproduce the bug at the time it was still happening. However it might be already fixed if there are no relatively recent reports on official forums/reddit.

**Comment by troggnostupidhs** [comment]
Closing since there haven't been any recent reports.
