### ISSUE TITLE
Master of Ceremonies won't get buffed if you have a minion with Velen's Chosen

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#418]
If you have a minion buffed by Velen's Chosen, the Master of Ceremonies won't get buffed when you play her from hand. Regular spell damage minions, Dalaran Aspirant and minion buffed by Ancient Mage's battlecry work properly. This bug was introduced in Patch 4.2, the same patch that fixed #337.

* http://us.battle.net/hearthstone/en/forum/topic/20742814514
* http://us.battle.net/hearthstone/en/forum/topic/20743024620
* https://www.reddit.com/r/hearthstone/comments/4b36v5/discovered_a_new_bug_with_velens_chosen/

**Comment by Patashu** [comment]
Very likely related to https://github.com/HearthSim/hs-bugs/issues/412

**Comment by Patashu** [comment]
Confirmed in 4.3

https://www.reddit.com/r/hearthstone/comments/4f0jnt/failed_master_of_ceremonies_trigger/

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20743444662 says that it works if you buff your own deathlord, but not if you buff a treant (created by your opponent's Poison Seeds).

Can this be re-tested please?

**Comment by culinko** [comment]
Worked fine for me just now.

![hearthstone screenshot 04-26-16 03 05 08](https://cloud.githubusercontent.com/assets/11700272/14803791/24528ee6-0b5d-11e6-80b1-bf89775f0c58.png)

**Comment by culinko** [comment]
I assume this is fixed, feel free to reopen when more people will report this still not working.
