### ISSUE TITLE
Steamwheedle Sniper inconsistency - can target your own Hero

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#42]
Contrary to the card text of Steamwheedle Sniper, you can target your own hero with your Hunter Hero Power. It might vary depending on whether your hero is Rexxar or Alleria or whether you upgraded your hero power with Justicar Trueheart.
* https://www.reddit.com/r/hearthstone/comments/3hnma0/some_irrelevant_text_inconsistency_with/
* http://us.battle.net/hearthstone/en/forum/topic/18724763499

This happens because the hero powers have differend IDs for each hero, same for upgrading the hero power with Justicar Trueheart. Below is the list of outcomes for every hunter hero power with screenshots.

Rexxar's Steady Shot (DS1h_292) - can't target your hero
Rexxar's Ballista Shot (AT_132_HUNTER) - **can target your hero**
Alleria's Steady Shot (DS1h_292_H1) - **can target your hero**
Alleria's Ballista Shot (DS1h_292_H1_AT_132) - **can target your hero**

Rexxar's Steady Shot:
![hearthstone screenshot 12-08-15 05 27 06](https://cloud.githubusercontent.com/assets/11700272/11647817/01aef630-9d6d-11e5-84d8-202e9b198fbc.png)

Rexxar's Ballista Shot:
![hearthstone screenshot 12-08-15 05 15 59](https://cloud.githubusercontent.com/assets/11700272/11647820/0bb561aa-9d6d-11e5-856e-681347bdd1d0.png)

Alleria's Steady Shot:
![hearthstone screenshot 01-12-16 13 31 09](https://cloud.githubusercontent.com/assets/11700272/12263878/e46c60bc-b932-11e5-80a7-cf1defa1271d.png)

Alleria's Ballista Shot:
![hearthstone screenshot 01-12-16 13 37 24](https://cloud.githubusercontent.com/assets/11700272/12263886/ee628312-b932-11e5-8c22-be30f3478306.png)

**Comment by culinko** [comment]
As a Rexxar with Steamwheedle Sniper on the board, I couldn't target my hero with Steady Shot, but I could target my hero with Ballista Shot (hero power upgraded by Justicar Trueheart). Tested in 4.1:
Steady Shot:
![hearthstone screenshot 12-08-15 05 27 06](https://cloud.githubusercontent.com/assets/11700272/11647817/01aef630-9d6d-11e5-84d8-202e9b198fbc.png)
Ballista Shot:
![hearthstone screenshot 12-08-15 05 15 59](https://cloud.githubusercontent.com/assets/11700272/11647820/0bb561aa-9d6d-11e5-856e-681347bdd1d0.png)

**Comment by jleclanche** [comment]
This should have been fixed in 12051 (Ballista Shot gained `PlayReq.REQ_MINION_OR_ENEMY_HERO).
