### ISSUE TITLE
An Evil Exchange: Legendary brawl-specific minions aren't Legendary

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#421]
The Legendary minions in Brawl "An Evil Exchange" have the 'dragon' Legendary card border, but no Legendary gem, and weren't set as 'Legendary' rarity. For example, Sapphiron can't be targeted by Rend Blackhand. The inconsistency between the legendary border and the legendary gem/rarity is a bug.

* http://us.battle.net/hearthstone/en/forum/topic/20742835233
* http://us.battle.net/hearthstone/en/forum/topic/20742935203

**Comment by culinko** [comment]
However, they have no legendary gems, so this could be the intended behavior.

**Comment by Patashu** [comment]
But they have the legendary card border. It's an inconsistency no matter which behaviour is intended.

**Comment by jleclanche** [comment]
The "legendary card border" is actually just the "elite" border. Some legendary minions don't have it (not in the collectible set though).

You should just ask bbrode.

**Comment by Xinhuan** [comment]
The elite card border isn't tied to rarity. It is just a separate card property and only affects visuals. It only so happens that all collectible Legendary minions have that "elite" tag set to 1.

There are non-collectible Legendary minions that don't have the border, and there are cards with elite border without a rarity.

**Comment by culinko** [comment]
The minions have been assigned a legendary rarity (GameTag.RARITY = 5) in 5.2.0.13619, so this issue is now resolved.
