### ISSUE TITLE
An Evil Exchange: Grand Widow Faerlina's Aura has inappropriate priority

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#422]
Normally Auras that affect attack have priority later than all Enchantments. Every exception to this rule in the past has been fixed (Cogmaster, Old Murkeye).

Grand Widow Faerlina, if set to a 3/3 by Keeper of Uldaman, does not gain attack no matter how many cards are in your opponent's hand.
- http://us.battle.net/hearthstone/en/forum/topic/20742845215

![image](https://cloud.githubusercontent.com/assets/666597/14002491/7c0e4b6a-f1a0-11e5-9b80-544518e0c3c0.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6yj5n7/faerlina_doesnt_get_buffed_by_noth_in_the_tavern/

> 
> I was playing this week's Tavern Brawl when I noticed this odd bug. Faerlina's text reads "Has +1 attack for each card in your opponent's hand," but it works like "This minion's attack is equal to how many cards your opponent has". I buffed Faerlina with Noth (the 2/5 who buffs your minions by +1/+1 and summons a skeleton each time an enemy minion dies) and only the health went up. I want my free packs Blizzard!
> Link: http://imgur.com/WPt6xIN
> Edit: I just realized that it's hard to see Faerlina's attack, but you can make out the shape of the 3 and see that my opponent has only 3 cards in their hand.

![image](https://user-images.githubusercontent.com/22508641/30145455-569b78aa-935f-11e7-80c0-b7c056f9b225.png)

**Comment by troggnostupidhs** [comment]
I think the aura priority is fixed, but now the text isn't correct (see previous post). 

![hearthstone screenshot 09-07-17 00 24 55](https://user-images.githubusercontent.com/22508641/30146058-c0b51102-9363-11e7-85f2-58775ab8604a.png)
![hearthstone screenshot 09-07-17 00 25 04](https://user-images.githubusercontent.com/22508641/30146057-c0b4d96c-9363-11e7-8883-944330a8a2fe.png)
![hearthstone screenshot 09-07-17 00 25 12](https://user-images.githubusercontent.com/22508641/30146059-c0b5ccc8-9363-11e7-8178-8a071cfae1a6.png)

**Comment by troggnostupidhs** [comment]
It should have the similar wording to Lightspawn. "This minion's Attack is always equal to the number of cards in your opponent's hand."

![image](https://user-images.githubusercontent.com/22508641/30146214-c85a9ad4-9364-11e7-87d8-f8d96d5fc9ed.png)
