### ISSUE TITLE
Mac: Rainbow Bug

### ISSUE THREAD

**Issue by JelaniThompson** [HearthSim/hs-bugs#426]
Hearthstone has a game-breaking that causes the game to crash anytime after 5+ games. It only happens on Macs with an Intel Iris graphics card. It's been going on for over a year now. Hopefully this gets fixed soon.
- http://us.battle.net/hearthstone/en/forum/topic/17086220493

![rainbow glitch](https://cloud.githubusercontent.com/assets/11928206/14062815/6b3192a4-f383-11e5-8421-2b3e3467ba37.jpg)

**Comment by Patashu** [comment]
Thanks for the report (especially information on what causes it is the most useful). If you see any other bugs we're missing feel free to file them.

**Comment by jleclanche** [comment]
Uh this sounds like a graphics driver bug especially if it's on specific graphics card.

**Comment by Patashu** [comment]
Is this the same bug or unrelated, anyone know?

http://us.battle.net/hearthstone/en/forum/topic/20742835998

![image](https://cloud.githubusercontent.com/assets/666597/14224230/fbf59c06-f8e0-11e5-9d8f-cf07b347c74e.png)

**Comment by Patashu** [comment]
Confirmed in 5.0

http://us.battle.net/hearthstone/en/forum/topic/20743484694

**Comment by Patashu** [comment]
I think another instance, with computer information:

https://www.reddit.com/r/hearthstone/comments/4jio2y/macbook_anyone_else_crashing_due_to_deathrattles/

**Comment by Patashu** [comment]
Confirmed in 7.0

https://twitter.com/InfinitNutshell/status/804558719451271168

**Comment by postcasio** [comment]
AFAIK this is on any Retina Mac, not just those with Iris cards - I have encountered this on a 2016 Retina Macbook which has an Intel HD 515.

**Comment by lrose07** [comment]
Adding info: happening on my early 2014 MBA (so, non-retina display) with Intel HD Graphics 5000.

**Comment by PattuX** [comment]
According to this post, this is fixed, but replaced by another bug which makes the macOS version crash: https://www.reddit.com/r/hearthstone/comments/5y1x2z/patch_71_has_broke_the_macos_version_of/

**Comment by troggnostupidhs** [comment]
It might not be fixed until later this year.

> The engine upgrade is expected to alleviate the "rainbow glitch" as well. But we are still in the process of confirming this.

https://www.reddit.com/r/hearthstone/comments/5y7z2b/blizzard_really_needs_to_fix_the_ios_bug/deo2p4p/?context=1

> This one is unfortunately an engine issue and we've been holding off on the engine upgrade because it's a chunk of work. We are planning on it later in the year though. Sorry about this!

https://www.reddit.com/r/hearthstone/comments/5y7z2b/blizzard_really_needs_to_fix_the_ios_bug/deo1xiv/?context=1

**Comment by troggnostupidhs** [comment]
>Hey all,

> First let me say I am deeply sorry for the time it's taken for an update to this thread on this issue. Largely it's been due to locating the cause and the best course of resolution to the issue.

> Recently, Game Producer Yong Woo was able to comment about this in a reddit thread and mentioned the plan on fixing this issue. That said, the fix is going end up being a game engine update; so not a small undertaking. In the end, this should fix not only this issue but several others in the process. While we don't have an ETA for this it's something that is being actively worked on. We'll be sure to keep you all posted as we get more information.

https://us.battle.net/forums/en/hearthstone/topic/17086220493?page=22#post-440

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/17086220493?page=23

**Comment by troggnostupidhs** [comment]
Latest report is from August 6

**Comment by troggnostupidhs** [comment]
Reports are that this is fixed

https://us.battle.net/forums/en/hearthstone/topic/17086220493?page=28

>  Problem is solved!!
Download macOs high sierra

> If you update to MacOs High Sierra the problem no longer persists!

https://us.battle.net/forums/en/hearthstone/topic/20759370522

**Comment by JelaniThompson** [comment]
Sweet!
