### ISSUE TITLE
When you get 'Your opponent left' during your turn, the game does not end until you take your next action

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#427]
When you get the 'Your opponent left' notification, the game has already ended in a win in your favour. However if it happens during your turn, the game will not visually end (enemy hero portrait exploding, etc) until you attempt to take your next action or wait for a bit longer.

It's problematic if this happens while you're in the middle of a targeting animation, because you won't be able to perform the next action and visually finish the game until you either restart your client or wait a bit longer.
* http://us.battle.net/hearthstone/en/forum/topic/18724767777

(Note for testers: 'Your opponent left' appears 3 minutes after you end the Hearthstone process.)

**Comment by riQQ** [comment]
I can confirm this. My opponent left just when I heropowered. I got the targeting animation and I wasn't able to do anything. Only end turn helped.

**Comment by PattuX** [comment]
Video footage:

* https://youtu.be/94r0qtVDFzQ?t=24m30s

**Comment by culinko** [comment]
Confirmed in 6.0? https://www.reddit.com/r/hearthstone/comments/4y4f2q/bug_when_an_opponent_leaves/

**Comment by Patashu** [comment]
Confirmed in 7.0:

https://us.battle.net/forums/en/hearthstone/topic/20752455835

**Comment by troggnostupidhs** [comment]
I think this is fixed. I've had a few games where it ends right away. I also confirmed it while playing a friend.

**Comment by troggnostupidhs** [comment]
I was wrong about this. I just had a game where the message showed on my turn and I had to take an action for it to end the game.

**Comment by troggnostupidhs** [comment]
Possibly fixed. It was my turn, but a card was being summoned. I didn't have to take an action for the game to end.

**Comment by troggnostupidhs** [comment]
I didn't take an action this time, and the game ended right away on my turn.

**Comment by troggnostupidhs** [comment]
I can confirm this is fixed. It happened in the middle of my turn but I did not have to take an action.
