### ISSUE TITLE
Game crashes after getting to fatigue

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#428]
Happens exclusively on Samsung Galaxy S7 and Samsung Galaxy S7 Edge phones. According to /u/locomiser , it happens only for the US versions (snapdragon not exynos). Don't mistake this issue with #314, which is another bug with hovering over the fatigue sidebar entry that happens exclusively on iPhones.

* https://www.reddit.com/r/hearthstone/comments/4ivwpg/this_weeks_tavern_brawl_is_not_only_a_lot_of_fun/ (many reports, including a video: https://youtu.be/vROt3dYRXmw )
* https://www.reddit.com/r/hearthstone/comments/4atnht/android_client_crashing_on_latest_patch_when_game/
* https://www.reddit.com/r/hearthstone/comments/4c85h0/consistent_crashes_on_my_galaxy_s7_when_going/

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20742836265 Another Galaxy S7 Edge report

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20742927186 Does it happen on Nexus 6 or am I miscategorizing this?

**Comment by lcpunkrawk** [comment]
Can confirm this still exists for S7 Edge on 4.3.0.12266

**Comment by Patashu** [comment]
Confirmed in 5.0 unfortunately!

**Comment by culinko** [comment]
Another report in 5.0: https://www.reddit.com/r/hearthstone/comments/4k4ah8/blizzard_you_desperately_need_to_address_this/.

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13:

https://www.reddit.com/r/hearthstone/comments/4m9jsx/still_crashing_when_going_into_fatigue_on_mobile/

**Comment by Patashu** [comment]
Might be related, apparently Galaxy S7 phones also crash when Gadgetzan triggers a lot? (or it could just be fatigue again)

https://www.reddit.com/r/hearthstone/comments/4mldvi/rogue_locks_up_androids_with_gadgetzan_auctioneer/

**Comment by Patashu** [comment]
A reddit user made a mod that removes the fatigue related skull, which may or may not fix the crash. Untested, use at your own risk.

https://www.reddit.com/r/hearthstone/comments/4o6uis/can_we_bring_awareness_to_a_game_breaking_bug/d4a1d3m

**Comment by Patashu** [comment]
This is supposedly fixed in the newest patch.

**Comment by culinko** [comment]
Yeah, this is in the google play store patch notes: 
"Fatigue damage will no longer result in a crash on Samsung Galaxy S7 with Snapdragon CPUs".
