### ISSUE TITLE
Missing basic cards

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#429]
Randomly, your account will be missing basic cards. After restarting the client, the basic cards will appear correctly.
- http://us.battle.net/hearthstone/en/forum/topic/20743024534
- http://us.battle.net/hearthstone/en/forum/topic/20742944498
- http://us.battle.net/hearthstone/en/forum/topic/20742974585
- https://www.reddit.com/r/hearthstone/comments/4bda71/uh_whered_they_go/
- https://www.reddit.com/r/hearthstone/comments/4bhfds/bug_missing_all_my_basic_cards_for_mage/
- https://www.reddit.com/r/hearthstone/comments/4bkxw7/druid_errorswipe_and_savage_roar_missing/
- https://www.reddit.com/r/hearthstone/comments/4c1mv1/why_am_i_missing_some_of_my_priest_basic_cards/
- https://www.reddit.com/r/hearthstone/comments/4c998k/any_one_else_i_missing_his_basic_cards_this/

**Comment by PattuX** [comment]
Confirmed in 4.3. All cards obtained by leveling up that class are missing (Golden Basic and cards obtained by hitting Lv. 2 or higher)

![image](https://cloud.githubusercontent.com/assets/15743638/14767098/16a51f74-0a1e-11e6-9016-c77e3f0bf527.png)

![image](https://cloud.githubusercontent.com/assets/15743638/14767103/2395ffbe-0a1e-11e6-912f-ad1fa39facb7.png)

Also my last game yesterday was as a druid and I closed the game while I was in the end game screen. Might be related.

**Comment by troggnostupidhs** [comment]
There hasn't been reports of this in months. I believe it is fixed.

**Comment by troggnostupidhs** [comment]
Could be related to or fixed with #454

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/13816371599?page=1#8

> Yes-huh! I commented on a post recently about this. ;)
> 
> I have noticed the increase of these reports. However, I wasn't able to get any follow up on this. If you level up to level 10 and do not get your appropriate cards, we have found that logging out for a few minutes had helped to get Hearthstone caught up and get the cards granted.
> 
> Now, I do see that it is being said that this is not working for some. I am having the issue looked into more on this side to see what may be going on. During this time, anyone who is experiencing this, if you are randomly granted your cards, can you please let me know. It would help a great deal. I will also see what I can get figured out so we can get this resolved for everyone. Thanks guys.
> 
> - Rolkyr

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/13816371599?page=1#post-19

> Actually everyone,
> 
> I have created a specific thread to better gather information on this issue. This will help with both investigating and tracking so we can make sure everyone gets taken card of. If you could all post in this thread:
> 
> http://us.battle.net/hearthstone/en/forum/topic/13922932638
> 
> With the information asked in the initial post, it would help a great deal. Also, MVPs, if you see anyone reports on this topic, please refer them to this thread as you guys usually do. Thanks everyone!
> 
> - Rolkyr

The linked thread has been deleted.
