### ISSUE TITLE
Rend Blackhand minor visual glitch

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#43]
There have been reports of a minor visual glitch when playing Rend Blackhand after Patch 3.0.

https://www.reddit.com/r/hearthstone/comments/3hhict/hearthstone_30_unofficial_patch_notes/cu7ul12

Here is a video of it:

https://www.youtube.com/watch?v=XFK6zSvccC8&t=1m53s

**Comment by Patashu** [comment]
It's on video:

https://www.youtube.com/watch?v=XFK6zSvccC8&t=1m53s

**Comment by ThePsionic** [comment]
Reproduced in 4.1.0.10956

**Comment by culinko** [comment]
For some reason, if you are the one playing Rend Blackhand, the orange-red circle appears on the same spot every time right after you place him on the board, then it adjusts to his supposed board position.

![hearthstone screenshot 12-09-15 21 32 02](https://cloud.githubusercontent.com/assets/11700272/11698048/1430f078-9ebd-11e5-9577-45948cff5645.png)

![hearthstone screenshot 12-09-15 21 32 08](https://cloud.githubusercontent.com/assets/11700272/11698055/1aa97fe2-9ebd-11e5-8441-43ca8bc1a83c.png)

The glitched spot is still a couple of pixels below to the closes board position, as can be seen here (compare image 2 and 3).

![hearthstone screenshot 12-09-15 21 32 21](https://cloud.githubusercontent.com/assets/11700272/11698089/4f7e9770-9ebd-11e5-90cc-19fb42fff898.png)

**Comment by Patashu** [comment]
Confirmed in 7.0

http://us.battle.net/forums/en/hearthstone/topic/20752298622

**Comment by troggnostupidhs** [comment]
Fixed

![img000](https://user-images.githubusercontent.com/22508641/44312909-7ddc1a80-a3cd-11e8-8124-c19e3856a1ed.png)


Deck
AAEBAfqUAwrrAsUE4AXtBdYR6BGEEoW4ApG8Ap3HAgr7AZwCtALhBLkGxAiCtQLHywLy0AKm8AIA
