### ISSUE TITLE
Unresponsive buttons after deleting a Tavern Brawl deck

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#432]
After losing a Tavern Brawl game and deleting your deck, the buttons in the Tavern Brawl screen are not able to be clicked. You can fix this by clicking Options -> Credits and clicking 'Back' to return to the main menu.
* http://us.battle.net/hearthstone/en/forum/topic/20742965942
* http://us.battle.net/hearthstone/en/forum/topic/20742915888

Video by Kokokatten capturing the issue:
[![Hearthstone - Bugged Stuff 6](https://img.youtube.com/vi/YnlbQgxIuu4/0.jpg)](https://www.youtube.com/watch?v=YnlbQgxIuu4)

**Comment by culinko** [comment]
Confirmed in 5.0: https://www.reddit.com/r/hearthstone/comments/4l4enh/brawl_bug/.

**Comment by PattuX** [comment]
Fixed, according to Patch Notes.
I'd suggest we wait for the next Tavern Brawl requiring to build a deck tho before closing.
