### ISSUE TITLE
Reconnecting into the game after the fuse has already started burning will not display it

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#435]
If you disconnect or close your client and then reconnect into your game after your fuse has already started burning, it will be invisible to you after reconnecting.
- https://www.youtube.com/watch?v=OFGGUZUhbqk

**Comment by culinko** [comment]
Confirmed in 6.0: https://www.reddit.com/r/hearthstone/comments/4yz9wz/blizzard_please_display_the_turn_rope_upon/.

**Comment by troggnostupidhs** [comment]
Potentially fixed

https://playhearthstone.com/en-gb/blog/21183932

> The rope animation will now correctly appear even if a player was disconnected when it began.

**Comment by troggnostupidhs** [comment]
Worked for me several times in a Friendly Challenge.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8wh7fv/the_worst_feeling/
