### ISSUE TITLE
Hobgoblin/Mistcaller buffed minion can become immortal

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#44]
Under unknown circumstances, a minion buffed by Hobgoblin or Mistcaller can become immortal at 0 Health. This is not a visual bug - the Server will send you actions involving it, you can attempt to attack with it and fail (it moves a bit then the Server sends you your next set of actions, and it is still selectable), it takes up space on your board, you can target it with spells and both you and your opponent see it.

It can be targeted and buffed by spells, damaged, set TO_BE_DESTROYED without dying,  healed, attempted to attack or attack with (the attack fails if either minion is at 0 Health, but buffs and heals can be used to make the minion valid for combat again). If its Health goes below 0, it is set back to 0. If it has Taunt, it can't be attacked past. If it is bounced to the hand and played again, it stops being immortal. If it has a triggered effect, it works normally ( https://www.reddit.com/r/hearthstone/comments/3ruu99/vitality_totem_glitchmight_be_gamebreaking/ ).

The minions it has been observed with are Echoing Ooze, Haunted Creeper, Micro Machine, Novice Engineer and Argent Squire (and possibly more). However, an Echoing Ooze is usually (always?) on the board at some point in the past.

NEW: Reliable reproduction steps!!!
http://us.battle.net/hearthstone/en/forum/topic/19648775642?page=1#4
In addition, Blessing of Wisdom is confirmed to draw a card.

NEW: Full game footage, including the turn the Hobgoblin/Echoing Ooze is played, how it died, attempts to attack, showing that it can be revived, showing that if it goes below 0 Health it jumps to 0 Health immediately afterwards, etc: https://www.reddit.com/r/hearthstone/comments/3iiiez/twas_the_night_before_tgt_and_an_interesting/

NEW: 'The one missing picture is that the Haunted Creeper died immediately upon being replayed after the Sap.' This is after Shadowflame was played on it, so TO_BE_DESTROYED was maintained on the minion when it got sapped, when it got replayed, and it lost its immortality and died.
https://www.reddit.com/r/hearthstone/comments/3jb5va/this_haunted_creeper_really_didnt_want_to_die/
INCLUDES LOG: https://www.dropbox.com/s/t4a9gxm8q9k5o55/zerohealthcreeper.log?dl=0 (haunted creeper id=10)

INCLUDES LOG: https://www.reddit.com/r/hearthstone/comments/3izdfz/weird_brawl_bug/ -> https://gist.githubusercontent.com/jleclanche/bc19d470e132bbb4f7c9/raw/db99d55473125b03e47e545f6e8ba3267362887f/gistfile1.txt (argent squire id=7)

NEW: Apparently, very rarely, you can get an immortal weapon that does not get destroyed by negative durability: https://www.reddit.com/r/hearthstone/comments/3nrfho/1_durability_weapon/
https://www.reddit.com/r/hearthstone/comments/3nu0hi/i_recreated_the_1_durability_weapon_bug/
https://www.reddit.com/r/hearthstone/comments/3nxg75/i_also_recreated_the_1_durability_bug_with/
https://www.reddit.com/r/hearthstone/comments/3r2dte/infinite_weapon_bug_with_negative_durability/ (claims no hobgoblin or echoing ooze was played)

NEW: The bug is claimed to have happened on a Stampeding Kodo without an Echoing Ooze/Hobgoblin having been played at any point in the game. (But Faceless was, and Mirror Entity might have been.) https://www.reddit.com/r/hearthstone/comments/3nypv4/my_minions_just_stayed_on_the_board_with_0_health/

Includes video:

http://us.battle.net/hearthstone/en/forum/topic/18596063143
https://www.reddit.com/r/hearthstone/comments/3hv9ud/weird_bug_immortal_haunted_creeper/
https://www.reddit.com/r/hearthstone/comments/3isjj0/the_undying_echoing_ooze/
https://www.reddit.com/r/hearthstone/comments/3j3gtt/echoing_ooze_bug_feels_like_hacking_this_should/
https://www.reddit.com/r/hearthstone/comments/3qrlvk/funny_bug_with_echoing_ooze_turning_invulnerable/
https://www.reddit.com/r/hearthstone/comments/3r3vok/we_got_the_echoing_ooze_bug_in_the_middle_of_our/

Death caused by Power Overwhelming:

http://us.battle.net/hearthstone/en/forum/topic/18719273428

Other reports:

http://us.battle.net/hearthstone/en/forum/topic/18710642906
http://us.battle.net/hearthstone/en/forum/topic/18706412646
http://us.battle.net/hearthstone/en/forum/topic/18596063381
https://www.reddit.com/r/hearthstone/comments/3ht505/the_soul_of_an_echoing_ooze_lets_me_down_in_my/
http://us.battle.net/hearthstone/en/forum/topic/18716983597
https://www.reddit.com/r/hearthstone/comments/3i9dgp/zero_health_echoing_ooze_lives_on/
http://us.battle.net/hearthstone/en/forum/topic/18596067249
https://www.reddit.com/r/hearthstone/comments/3k3t6k/crazy_ooze_bug_in_ranked_play_shown_as_comic_strip/

It can also happen with Mistcaller instead of Hobgoblin:

http://us.battle.net/hearthstone/en/forum/topic/18705073115
http://us.battle.net/hearthstone/en/forum/topic/18710643668
https://www.facebook.com/photo.php?fbid=1140029286010922&set=gm.391801437661682&type=1&theater < seemingly has no echoing oozes, but does have mistcaller

It can also happen with Execute:

http://us.battle.net/hearthstone/en/forum/topic/18704213230

Can it happen with NO attached enchantments?

https://www.reddit.com/r/hearthstone/comments/3icezq/the_silver_hand_recruit_that_wouldnt_die/

If the immortal minion has Taunt, it prevents the opponent from attacking past it:

http://us.battle.net/hearthstone/en/forum/topic/18695102746

Lowly Squire: http://us.battle.net/hearthstone/en/forum/topic/19288909472

Lightspawn: http://us.battle.net/hearthstone/en/forum/topic/19288659907

Elven Archer: http://us.battle.net/hearthstone/en/forum/topic/19288250165

Haunted Creeper: https://www.reddit.com/r/hearthstone/comments/3per21/as_if_haunted_creeper_wasnt_annoying_enough/

**Comment by Patashu** [comment]
Me and culinko attempted to reproduce this for 30 minutes by following reports, but could not.

**Comment by Patashu** [comment]
Happening with Mistcaller too, so updated the topic title.

**Comment by jleclanche** [comment]
I'd be interested to see a Power.log of this.

**Comment by Patashu** [comment]
Same, but no one knows how to reproduce it :(

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3icezq/the_silver_hand_recruit_that_wouldnt_die/ < report with no Hobgoblin/Mistcaller buff

**Comment by Patashu** [comment]
NEW: Full game footage, including the turn the Hobgoblin/Echoing Ooze is played, how it died, attempts to attack, showing that it can be revived, showing that if it goes below 0 Health it jumps to 0 Health immediately afterwards, etc: https://www.reddit.com/r/hearthstone/comments/3iiiez/twas_the_night_before_tgt_and_an_interesting/

**Comment by jleclanche** [comment]
More reports

https://www.reddit.com/r/hearthstone/comments/3inlhu/really_weird_bug_leaves_my_minion_completely/

**Comment by Drikam** [comment]
Even more: 
https://www.reddit.com/r/hearthstone/comments/3izdfz/weird_brawl_bug/

**Comment by jleclanche** [comment]
@Drikam thanks, that report got us a log file:

https://gist.githubusercontent.com/jleclanche/bc19d470e132bbb4f7c9/raw/db99d55473125b03e47e545f6e8ba3267362887f/gistfile1.txt

Argent Squire is id=7 in there.

**Comment by jleclanche** [comment]
The brawl correctly sets `TO_BE_DESTROYED` on all the minions including the squire, but then it's just missing from the `DEATHS` block.

**Comment by jleclanche** [comment]
Tried to reproduce this as closely as possible - no luck. Either there's a random element to it (only happens to some players, accounts, entities, ...) or we're missing something.

**Comment by jleclanche** [comment]
Another report. https://www.reddit.com/r/hearthstone/comments/3j7768/my_immortal_game_breaking_infinite_value/

Millhouse out of a shredder. Hobgoblin-buffed Ooze is present on the opposite side of the board.

**Comment by skaforey** [comment]
>Tried to reproduce this as closely as possible - no luck. Either there's a random element to it (only happens to some players, accounts, entities, ...) or we're missing something.

This may be a dumb suggestion, but did you try to reproduce it with the player_id 1 and 2 to see if that happens to make a difference?

**Comment by jleclanche** [comment]
@skaforey Yeah I thought about it; we did a few runs with both players playing oozes, didn't help.

Something else must be needed to trigger the issue. @mischanix suggested it could even be a race condition.

**Comment by Patashu** [comment]
NEW: 'The one missing picture is that the Haunted Creeper died immediately upon being replayed after the Sap.' This is after Shadowflame was played on it, so TO_BE_DESTROYED was maintained on the minion when it got sapped, when it got replayed, and it lost its immortality and died.
https://www.reddit.com/r/hearthstone/comments/3jb5va/this_haunted_creeper_really_didnt_want_to_die/

**Comment by Patashu** [comment]
https://www.dropbox.com/s/t4a9gxm8q9k5o55/zerohealthcreeper.log?dl=0 Log for previous, id=10 for haunted creeper

**Comment by Moghwyn** [comment]
Looking at the reports, one of the triggers might be minions spawning other minions in places other than the most rightmost one. The video shows the Ooze being played on the left, which is pretty unusual for almost all games. Maybe the spawn going in between and getting buffed afterwards somehow causes death to be associated to the wrong minion.

**Comment by jleclanche** [comment]
@Moghwyn Tried to reproduce it with an ooze on the left and in the middle. Didn't help. :/

**Comment by jleclanche** [comment]
Another report with 10 screenshots https://www.reddit.com/r/hearthstone/comments/3k3ql3/undying_card_revived/

**Comment by Apexultima** [comment]
https://www.youtube.com/watch?v=Nnqgih8Sku4

Just happened to me, auto loss :(

**Comment by namshub3** [comment]
Another report by a user on Reddit.

https://www.reddit.com/r/hearthstone/comments/3krs8f/can_anyone_explain_what_just_happend_in_my_game/

The user provides additional screenshots on how they arrived at that position:

http://imgur.com/a/rVQib

In the following screenshot, the history bar shows the presence of Echoing Ooze, what is understood to be a key trigger in this bug.

http://i.imgur.com/DJmBXwD.png

**Comment by Patashu** [comment]
Interesting report with Frost Giant and lots of screenshots/documentation:

http://us.battle.net/hearthstone/en/forum/topic/19072467237

**Comment by Patashu** [comment]
Another:

https://www.reddit.com/r/hearthstone/comments/3m3fjy/i_had_a_pretty_interesting_buggy_game_today/

**Comment by Patashu** [comment]
Another report with video:

http://us.battle.net/hearthstone/en/forum/topic/19072447667

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/19136294068

Confirmed in 3.1

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3nrfho/1_durability_weapon/

This is really cool lol

**Comment by Xinhuan** [comment]
A Reddit user reproduced the 1 durability weapon bug twice:

https://www.reddit.com/r/hearthstone/comments/3nu0hi/i_recreated_the_1_durability_weapon_bug/

(It is the same sequence of cards played as in Kibler's VOD - Kibler's turn starts, he plays Warbot, Echoing Ooze then Waraxe, attacks with Waraxe, then the turn ends and Ooze duplicates, and the weapon becomes bugged.)

**Comment by Patashu** [comment]
Another -1 durability weapon reproduction:

https://www.reddit.com/r/hearthstone/comments/3nxg75/i_also_recreated_the_1_durability_bug_with/

**Comment by Patashu** [comment]
The bug is claimed to have happened on a Stampeding Kodo without an Echoing Ooze/Hobgoblin having been played at any point in the game. https://www.reddit.com/r/hearthstone/comments/3nypv4/my_minions_just_stayed_on_the_board_with_0_health/

**Comment by NightKev** [comment]
Another video: https://www.youtube.com/watch?v=KEoabXizsKc

**Comment by Patashu** [comment]
Another video: http://us.battle.net/hearthstone/en/forum/topic/19288110551

**Comment by Patashu** [comment]
Confirmed in 3.2:

http://us.battle.net/hearthstone/en/forum/topic/19288800616

**Comment by JonAbrams** [comment]
Occurred on a Fire Elemental with taunt, preventing attacking on other non-taunt targets.

https://www.youtube.com/watch?v=5zMxDUElsQY

https://www.reddit.com/r/hearthstone/comments/3qyxsa/gamebreaking_hearthstone_bug/

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3r2dte/infinite_weapon_bug_with_negative_durability/ 

infinite durability Light's Justice

**Comment by Patashu** [comment]
another video:

https://www.reddit.com/r/hearthstone/comments/3r3vok/we_got_the_echoing_ooze_bug_in_the_middle_of_our/

**Comment by Patashu** [comment]
NEW: Reliable reproduction steps!!!
http://us.battle.net/hearthstone/en/forum/topic/19648775642?page=1#4
In addition, Blessing of Wisdom is confirmed to draw a card.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3ruu99/vitality_totem_glitchmight_be_gamebreaking/ Vitality Totem

**Comment by Patashu** [comment]
No reports yet, probably fixed in 4.0

**Comment by jleclanche** [comment]
I'm going to close it because it's almost definitely fixed in 4.0, ywoo said they had a handle on it in 3.1 already. Reopen if new reports.

**Comment by Patashu** [comment]
Confirmation for the fix: https://www.youtube.com/watch?v=a0h6qIGaH1k
