### ISSUE TITLE
Golden alternate heroes don't have golden hero powers in Arena

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#443]
If you have a golden hero of a specific class and set an alternate hero of the same class (Alleria Windrunner, Khadgar, Lady Liadrin, Magni Bronzebeard or Medivh) as your favorite, their hero power will not be golden in Arena.
* https://www.reddit.com/r/hearthstone/comments/4b4fm5/bug_lady_liadrin_arena/
* https://www.reddit.com/r/hearthstone/comments/4bmuax/arena_golden/
* https://www.reddit.com/r/hearthstone/comments/4dqu2p/bug_first_world_problems_golden_hero_power_with/

**Comment by Fernlox** [comment]
Also happens with Khadgar

**Comment by culinko** [comment]
Merged into #186.
