### ISSUE TITLE
Lady Liadrin's sound effects do not play on mobile

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#446]
Sound when the graphic is circling the portrait and the sound of it swooping into the board slot do not play when you play as Lady Liadrin (doesn't necessarily have to be mirror match). The report below happened on iPhone (iOS 9), SimFri also confirmed it on Galaxy S6. Other heroes are working fine, he also tested Magni, Medivh and Uther.
- https://www.reddit.com/r/hearthstone/comments/4b9vpk/liadrin_entrance_sound_is_bugged_on_mobile/

**Comment by troggnostupidhs** [comment]
This works for me on a Galaxy S5
