### ISSUE TITLE
Mac/iOS - game crashes when you open the friends list

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#447]
* http://us.battle.net/hearthstone/en/forum/topic/20743484595 (largest thread)
* https://www.reddit.com/r/hearthstone/comments/4gbjwb/bug_on_mac_osx_game_crashes_when_accessing/
* https://www.reddit.com/r/hearthstone/comments/4gbr60/bug_game_immediately_crashes_when_i_try_to_lcick/
* https://www.reddit.com/r/hearthstone/comments/4gb54x/mac_bug_after_new_patch/

Also happens on iPad and iPhone. Confirmed by Patashu. If you click 'Play' then spam click friends list, the app crashes.
* http://us.battle.net/hearthstone/en/forum/topic/20743624815

**Comment by culinko** [comment]
Apparently it also happens on iOS: https://www.reddit.com/r/hearthstone/comments/4huc7o/hey_blizzard_i_dont_know_how_else_to_put_this/d2sqseu?context=3.

**Comment by Patashu** [comment]
https://t.co/CdEELCxAIE should be hotfixed

**Comment by culinko** [comment]
This is not hotfixed, I found a report today: https://www.reddit.com/r/hearthstone/comments/4lfb6c/hearthstone_on_mac_need_hotfix_asap/.

Also Blizzard removed it from the post on the following day.

**Comment by Patashu** [comment]
Confirmed that this bug happens on iPad.

**Comment by Patashu** [comment]
Confirmed in 5.0.0.103:

http://us.battle.net/hearthstone/en/forum/topic/20745264550

**Comment by culinko** [comment]
Another report: https://www.reddit.com/r/hearthstone/comments/4po27k/game_crash_bug_on_mobile/.

**Comment by culinko** [comment]
According to this post it crashes when you open the friendlist while transitioning to another screen: https://www.reddit.com/r/hearthstone/comments/4qlark/as_a_mainly_mobile_user_can_my_app_stop_instantly/d4u68rw.

**Comment by culinko** [comment]
This might be fixed (or only on phones?) according to the mobile patch notes: 
"You should no longer crash when clicking on the Social button to bring up the friends list on phones."

**Comment by PattuX** [comment]
Fixed in 5.2.0.13619
