### ISSUE TITLE
Tinkertown Technician's glow is incorrect

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#448]
It seems to use 'your opponent controls a Mech' instead of 'you control a Mech'.

* https://www.reddit.com/r/hearthstone/comments/4gb8mb/tinkertown_technician_bugged/ 
* https://www.reddit.com/r/hearthstone/comments/4gb8ew/tinkertown_technician_visible_bug/

**Comment by theAprel** [comment]
Also https://www.twitch.tv/nl_kripp/v/62677330?t=4h45m20s

**Comment by Shockah** [comment]
http://i.imgur.com/yFd5Dgs.png

**Comment by Patashu** [comment]
Confirmed in 5.0.1?

http://us.battle.net/hearthstone/en/forum/topic/20745054344

**Comment by JonvarH** [comment]
I can confirm that it still exists, this happened today:
![hearthstone screenshot 06-14-16 20 34 56](https://cloud.githubusercontent.com/assets/17293883/16055438/9191696a-3271-11e6-968d-39e4e6799fb8.png)

**Comment by troggnostupidhs** [comment]
People don't post about this any more. I'm assuming it might be fixed.

**Comment by Patashu** [comment]
Seems likely, I'll close it as 5.2.
