### ISSUE TITLE
Emperor Thaurissan Solo Adventure - Moira Bronzebeard can attack non-Taunts

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#449]
Normally Moira Bronzebeard can only attack a minion if the Hero is not a valid target for attacking. Now she will attack minions anyway. This might be a side-effect of making the AI fight for board control more aggressively.

* https://www.youtube.com/watch?v=yuNIXzAK8-w

**Comment by Xinhuan** [comment]
A Reddit report on this bug with screenshot: https://www.reddit.com/r/hearthstone/comments/4gcptd/northshire_cleric_has_taunt/

**Comment by Patashu** [comment]
Should be hotfixed: https://t.co/CdEELCxAIE
