### ISSUE TITLE
Poultryizer transforms target minion before animation finishes

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#45]
New in Patch 3.0, Poultryizer transforms the target minion before the animation finishes.

Video:

https://www.reddit.com/r/hearthstone/comments/3hhict/hearthstone_30_unofficial_patch_notes/cu7isr2

http://us.battle.net/hearthstone/en/forum/topic/18716983021

**Comment by SimFriHS** [comment]
Tested in 4.1. It's fixed: https://www.youtube.com/watch?v=09P5qxcXO_8
