### ISSUE TITLE
Fan of Knives animation is incorrect if your opponent plays it

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#450]
When your opponent uses Fan of Knives, the animation will be incorrect. It seems to be facing the wrong direction.

* https://www.reddit.com/r/hearthstone/comments/4gcy6i/fan_of_knive_bug/
* http://us.battle.net/hearthstone/en/forum/topic/20743344607

**Comment by PattuX** [comment]
I just had it that my opponent played Fan, but the animation was correct. Every time this happened I had no board.

**Comment by PattuX** [comment]
Fixed in 5.2.0.13619
