### ISSUE TITLE
Countered Choose One spell continues sfx/vfx forever

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#451]
'Just did the update that made all the balance changes live for neutral, rouge, druid cards today (april 24th). Went into tavern brawl and played the raven idol spell. It got countered-spelled but the visual effect and sound played indefinitely. When I cast the spell again the following turn, it created a second ring, and that one also stuck around forever. It was a very soothing sound to be fair. '
- http://us.battle.net/hearthstone/en/forum/topic/20743344629

**Comment by Patashu** [comment]
It doesn't seem to be specific to Raven Idol. It also happens with Wrath vs Counterspell.

https://www.reddit.com/r/hearthstone/comments/4gdy81/counterspell_buff/

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4gm5zr/bug_counter_spelled_living_roots_causes_the/ 

Living Roots too

**Comment by Patashu** [comment]
Confirmed in 5.0.0.103

https://www.reddit.com/r/hearthstone/comments/4mi74d/bug_living_roots_animationsound_playing_for_the/

**Comment by PattuX** [comment]
Also for Wrath:

![image](https://cloud.githubusercontent.com/assets/15743638/15866623/bc368fa2-2cdf-11e6-9f7c-b3c5eb3c5b70.png)
http://puu.sh/pkcrT/f9ac77d8a0.jpg
![image](https://cloud.githubusercontent.com/assets/15743638/15866634/ccb68eea-2cdf-11e6-9ffb-7394b70b57dd.png)

Could test Nourish as well.

**Comment by culinko** [comment]
Is this the same bug? Instead of Counterspell it's played right before the turn ends: https://www.reddit.com/r/hearthstone/comments/4r9pym/yogg_gives_my_druid_a_pretty_bug/.

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 12-12-16 21 09 16](https://cloud.githubusercontent.com/assets/22508641/21125038/9aaa386a-c0b0-11e6-860a-d02206fa9b1b.png)

![hearthstone screenshot 12-12-16 21 17 01](https://cloud.githubusercontent.com/assets/22508641/21125040/9d35eb9c-c0b0-11e6-9af6-659e7319c17a.png)

**Comment by troggnostupidhs** [comment]
I tested Wrath and Living Roots, and this is fine for me.
