### ISSUE TITLE
The tooltip of Force of Nature still mentions Charge despite being changed

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#452]
If you hover over Force of Nature (either in your collection or in game), the tooltip will still mention Charge, even though the summoned Treants no longer have charge.

![hearthstone screenshot 04-25-16 21 21 41](https://cloud.githubusercontent.com/assets/11700272/14796100/f15f1440-0b2b-11e6-993b-afe54d04b835.png)

**Comment by troggnostupidhs** [comment]
This is fixed.
