### ISSUE TITLE
Fallen Hero + Life Tap/Prophet Velen won't visually indicate the increased damage

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#453]
If you have Fallen Hero or Prophet Velen on the board, Life Tap won't visually indicate the increased damage (no sparkling effect and the text will only show 2 damage). However, this is only a visual bug and you still take additional damage.

Acked at https://twitter.com/ywoo_dev/status/724807949873369089.

![hearthstone screenshot 04-25-16 21 49 08](https://cloud.githubusercontent.com/assets/11700272/14796810/91480702-0b2f-11e6-8647-3860cbac2d0c.png)

![hearthstone screenshot 04-25-16 21 49 18](https://cloud.githubusercontent.com/assets/11700272/14796813/9453d048-0b2f-11e6-9b7e-dd997b05fc6b.png)

**Comment by Xinhuan** [comment]
Cause of this bug:

-Draw a card and take $2 damage.</enUS>
+Draw a card and take 2 damage.</enUS>

All the other languages still use $2, where the $ indicates that it is a modifiable number.

**Comment by culinko** [comment]
Fixed in 5.2.0.13619.
