### ISSUE TITLE
Playing multiple spells with Archmage Antonidas/Trade Prince Gallywix out may cause a client animation hang

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#455]
If you cast two spells with Archmage Antonidas/Trade Prince Gallywix triggering on them, sometimes the animation will never finish, causing a client animation hang. Since this state will last forever, the only solution is to disconnect/reconnect or end the process.
- http://oddshot.tv/shot/nl-kripp-2016052772539435
- https://www.twitch.tv/savjz/v/63704627?t=2h49m45s
- http://us.battle.net/hearthstone/en/forum/topic/20743454604
- https://www.reddit.com/r/hearthstone/comments/4ge8hk/bug_the_exodia_combo_causes_disconnect/
- https://www.reddit.com/r/hearthstone/comments/4gd8w6/exodia_otk_combomage_not_working_properly_after/
- http://us.battle.net/hearthstone/en/forum/topic/20743554303
- http://us.battle.net/hearthstone/en/forum/topic/20743724389
- http://us.battle.net/hearthstone/en/forum/topic/20743734335 (evolve)

It can happen even if you wait for animations to finish:
- https://youtu.be/yONoo1mH6Zk?t=11m43s
- http://us.battle.net/hearthstone/en/forum/topic/20744924990#5

It can even happen if your opponent does the combo:
- https://www.reddit.com/r/hearthstone/comments/4lovoh/exodia_combo_still_causes_a_disconnect/d3pxk0a?context=3
- https://www.reddit.com/r/hearthstone/comments/4lovoh/exodia_combo_still_causes_a_disconnect/d3pveu0?context=3
- https://www.reddit.com/r/hearthstone/comments/4n5y8g/opponent_antonidas_seems_to_have_frozen_the_game/

**Comment by Patashu** [comment]
This is probably actually a client animation hang not a disconnect, pending screenshot/video proving it.

**Comment by Patashu** [comment]
found a non-fireball report: http://us.battle.net/hearthstone/en/forum/topic/20743554303

**Comment by Patashu** [comment]
https://www.twitch.tv/savjz/v/63704627?t=2h49m45s video

**Comment by culinko** [comment]
Another report: https://www.reddit.com/r/hearthstone/comments/4h9sja/archimage_bug/.

**Comment by jleclanche** [comment]
Happened to Day9 this morning, with Gallywix.

**Comment by PattuX** [comment]
Another one: https://youtu.be/E4LQNsRgniw?t=17m50s

**Comment by Patashu** [comment]
Sometimes the client animation hang will happen even if you wait for the animation to finish, but it should be rarer the longer you wait.

* https://youtu.be/yONoo1mH6Zk?t=11m43s

**Comment by Patashu** [comment]
Confirmed in 5.0.1

http://us.battle.net/hearthstone/en/forum/topic/20744924990#5

**Comment by Patashu** [comment]
According to https://www.reddit.com/r/hearthstone/comments/4oag4f/end_turn_bug_during_tavern_brawl/ it can happen if your opponent triggers antonidas then you steal and trigger that antonidas.

**Comment by trevoranderson** [comment]
It's not just multiple spells. I just had a disconnect on the first spell played.

**Comment by culinko** [comment]
You played Echo of Medivh and Fireball, that is 2 spells. Also, this is not a disconnect, this is an animation hang. Your connection is not interrupted at all.

**Comment by Patashu** [comment]
Confirmed in latest 5.2.0

http://us.battle.net/hearthstone/en/forum/topic/20747125130

**Comment by culinko** [comment]
Unfortunately still happens in 6.0: https://www.reddit.com/r/hearthstone/comments/4xd2cj/malchezaarantonidas_bug/.

**Comment by Smagjus** [comment]
Still happens in 6.2. New example while playing really slowly:
https://www.youtube.com/watch?v=qmipv-NZrok

**Comment by troggnostupidhs** [comment]
This is potentially fixed.

> We ﬁxed a Spectator Mode issue that could occur when Raven idol is played.
https://www.reddit.com/r/hearthstone/comments/5fkw8z/update_is_out/
