### ISSUE TITLE
Transparent gap on weapons you don't own

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#456]
If you look at the weapon you don't have in your collection, a part of it will be transparent. The best way to spot this bug is to view one of the deck recipes. This only happens to weapon cards and only to those you don't have.
- http://us.battle.net/hearthstone/en/forum/topic/20743304641

![hearthstone screenshot 04-26-16 02 32 43](https://cloud.githubusercontent.com/assets/11700272/14803233/1d5f9b42-0b58-11e6-8840-55f5efa10a85.png)

**Comment by jleclanche** [comment]
That's supposed to be the class border.

**Comment by culinko** [comment]
This has been fixed.
