### ISSUE TITLE
Erroneous display of skull when attacking with a minion drawn by King's Elekk

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#46]
If you play a minion drawn by King's Elekk and attack with it, a skull will appear over the minion you are attacking with, even if it would not die as a result of that combat. (Confirmed to be the reason here: http://us.battle.net/hearthstone/en/forum/topic/9677847863 )

Here are many reports of the bug in Tavern Brawl 'Grand Tournament Match':

http://us.battle.net/hearthstone/en/forum/topic/18706671945
http://us.battle.net/hearthstone/en/forum/topic/18704971933
https://www.reddit.com/r/hearthstone/comments/3hm0s4/bug_skull_appearing_over_attacking_minions_even/
http://us.battle.net/hearthstone/en/forum/topic/18719273149?page=1#3
http://us.battle.net/hearthstone/en/forum/topic/18700821736
http://us.battle.net/hearthstone/en/forum/topic/18724763606
https://www.reddit.com/r/hearthstone/comments/3hw5i4/urmthats_not_how_numbers_work_blizz/
https://www.reddit.com/r/hearthstone/comments/3hzzvg/bug_with_minion_will_die_icon_in_brawl/

Here are reports of the bug outside of Tavern Brawl:

https://www.reddit.com/r/hearthstone/comments/3icyy5/til_shows_a_skull_on_your_minion_when_your/
https://www.reddit.com/r/hearthstone/comments/3ikxwn/bug_attacking_hero_shows_minion_will_perish/
https://www.reddit.com/r/hearthstone/comments/3ikz8r/mechanical_yeti_lacks_confidence/

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3icyy5/til_shows_a_skull_on_your_minion_when_your/ Confirmed outside of Brawl

**Comment by culinko** [comment]
https://www.reddit.com/r/hearthstone/comments/3i3dp3/visual_bug_targeting_face_with_kings_elekk/ another one

**Comment by Patashu** [comment]
Confirmed to be due to King's Elekk here:

http://us.battle.net/hearthstone/en/forum/topic/9677847863
