### ISSUE TITLE
Damage battlecry with Brann on the board only shows the initial damage

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#460]
**Both players see this bug.**

If you play a minion with a damage battlecry, the sidebar will only show the damage from the first battlecry if it hits the same target.

![hearthstone screenshot 04-27-16 17 26 47](https://cloud.githubusercontent.com/assets/11700272/14858017/b3a866aa-0c9e-11e6-8157-8f9d0c6f82d4.png)

![hearthstone screenshot 04-27-16 17 46 20](https://cloud.githubusercontent.com/assets/11700272/14858532/b3e837a6-0ca0-11e6-902d-9ab11b3c9848.png)

![hearthstone screenshot 04-27-16 17 47 55](https://cloud.githubusercontent.com/assets/11700272/14858516/acf0210c-0ca0-11e6-8904-beae2363ed74.png)

However, if the second battlecry hits a different target, both will be shown.

![hearthstone screenshot 04-27-16 17 50 54](https://cloud.githubusercontent.com/assets/11700272/14858563/d16223fa-0ca0-11e6-825d-d9d64f590936.png)

**Comment by troggnostupidhs** [comment]
This still happens.

![hearthstone screenshot 12-06-16 23 24 14](https://cloud.githubusercontent.com/assets/22508641/20954813/6fe59dca-bc0c-11e6-9af5-5667c48511c0.png)

**Comment by troggnostupidhs** [comment]
This is fixed.

Deck
AAEBAf0EAu0FhRcOTfsBtAK7AtMChQOWBbkGiawCk60C9K8CrbwCrMICmMQCAA==

![img000](https://user-images.githubusercontent.com/22508641/32918355-272c6b60-caf0-11e7-9270-70ce5033842e.png)
![img001](https://user-images.githubusercontent.com/22508641/32918356-2778f1b0-caf0-11e7-9bb1-8dac8ff35fc0.png)
![img002](https://user-images.githubusercontent.com/22508641/32918357-279d45ce-caf0-11e7-8c9a-808800a9e455.png)
