### ISSUE TITLE
Demented Frostcaller's trigger is not shown in the sidebar

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#461]
**Both players see the bug.**
- https://www.reddit.com/r/hearthstone/comments/4gqpt3/another_conistency_bug_found/

![image](https://cloud.githubusercontent.com/assets/235410/14911244/ca8df894-0dfc-11e6-80ea-52b4a83cb79f.png)

**Comment by troggnostupidhs** [comment]
> Several cards now properly generate a history tile when played.

http://us.battle.net/hearthstone/en/blog/20382066/hearthstone-update-november-29-2016-11-29-2016

This might be fixed.

**Comment by culinko** [comment]
Can confirm this being fixed in the current patch.
