### ISSUE TITLE
Scaled Nightmare stops doubling Attack if its Attack value is Direct Set

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#462]
If Scaled Nightmare's Attack is Direct Set after the first time it would double its Attack, Scaled Nightmare will stop doubling its attack at the start of each turn. This indicates that the initial Enchantment is erroneously being re-used.

* https://www.youtube.com/watch?v=ePmc3SRT_TE
* https://www.reddit.com/r/hearthstone/comments/4gklit/scaled_nightmare_bugged/ 

Copies made by Herald Volazj do not double their attack.

* https://www.reddit.com/r/hearthstone/comments/4gkw51/herald_volazjs_copies_of_scaled_nightmare_dont/

**Comment by Xinhuan** [comment]
I think this needs testing with Gahz'rilla as well.

**Comment by culinko** [comment]
Eadric + Scaled Nightmare: https://www.reddit.com/r/hearthstone/comments/4gvfn0/scaled_nightmare_bug/.

**Comment by Martios** [comment]
Inner Fire + Scaled Nightmare
https://www.reddit.com/r/hearthstone/comments/4gzie6/bug_when_you_inner_fire_scaled_nightmare_it_no/

**Comment by Patashu** [comment]
Oh, maybe it's not to do with early priority. Maybe it's to do with the fact that it goes back and doubles the initial Enchantment, rather than making new ones. (Though we know in the log that self-buffers don't make extra Enchantments, but yet they all process in the right order of application, so I don't know WTF is going on under the hood exactly.)

Also, there's this weird Blessed Champion thing:

http://us.battle.net/hearthstone/en/forum/topic/20743704626

**Comment by PattuX** [comment]
Scaled Nightmare has a stored buff value which it sets the attack to at the start of the turn.

This value starts at 0 and is increased by the current attack at the start of every turn.

This means, there is always only one instance of the buff, which makes all direct-attack-set-buffs that have a later timestamp override it. Also this explains why it triples the attack every turn with Blessed Champion applied.

Might have been an attempt to fix #321.

**Comment by bprussell** [comment]
I don't know if this is helpful or not, but last night my opponent Aldor'd my Scaled Nightmare, and the next turn it doubled to 2 attack. Then my opponent Aldor'd it again, and then it stayed at 1 attack for the next couple of turns.

**Comment by PattuX** [comment]
@bprussell do you use HDT? If yes, can you upload the logs?

**Comment by bprussell** [comment]
@PattuX unfortunately, I was on my phone.

**Comment by Xinhuan** [comment]
@bprussell Your Scaled Nightmare probably doubled from 1 to 2 because it hasn't gotten an initial "doubling buff" yet. Once it gets a "doubling buff" it gets modified every turn rather than tacking on a new buff every turn, which is why Aldor overrides it after that as it has a newer timestamp.

**Comment by bprussell** [comment]
@Xinhuan Yes, I didn't explicitly specify it, but the first time my opponent Aldor'd my Scaled Nightmare was the turn right after I played it. Its attack had not yet been doubled. After it received the first "doubling buff" and then got another Aldor Peacekeeper enchantment, it stopped doubling. The enchantment ordering explains why it doubled the first time but not the second, but that aspect of the bug isn't stated in the bug description, so I thought my anecdote might add a little value.

**Comment by Xinhuan** [comment]
DisguisedToast has put out a full length video explaining this bug: https://www.youtube.com/watch?v=ePmc3SRT_TE

**Comment by culinko** [comment]
Still bugged in 5.0.1.13030, despite patch notes mentioning its bug fix.

**Comment by Patashu** [comment]
Are we 100% sure this is fixed? Here's a report today saying Aldor on Scaled Nightmare prevented it from doubling.

https://www.reddit.com/r/hearthstone/comments/4mqnim/how_does_aldor_peacekeepers_ability_work/

**Comment by culinko** [comment]
I just re-tested it with Aldor (had it double first, then second) and both cases work fine. I am pretty sure that "I was recently in Arena" happened pre-patch.

**Comment by PattuX** [comment]
Note that 5.0.0.13030 isn't live on iOS and Android yet. I asked him for his platform.
