### ISSUE TITLE
Ancient Harbinger can pull 10 cost spells from your deck

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#464]
Ancient Harbinger is meant to only pull 10 cost minions, but can also pull 10 cost spells.

* https://www.reddit.com/r/hearthstone/comments/4gkr4d/ancient_harbinger_glitch/
* https://www.reddit.com/r/hearthstone/comments/4gkqna/little_bug_with_ancient_harbinger/
* https://www.reddit.com/r/hearthstone/comments/4gl5ik/ancient_harbinger_just_pulled_a_pyroblast_into_my/

**Comment by riQQ** [comment]
You mean 10 cost **minions**.

**Comment by Patashu** [comment]
Relatedly, does anyone know if Ancient Harbinger interacts with on-draw triggers?

**Comment by Patashu** [comment]
https://t.co/CdEELCxAIE should be hotfixed
