### ISSUE TITLE
After Play/After Summon triggers (Repentance, Addled Grizzly, Knife Juggler) do not trigger on Choose One self-transformers when Fandral Staghelm is in effect

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#465]
They work fine for normal self-transforming minions. The bug seems to be that Fandral Staghelm handles the transformation on behalf of the minion, and as a result the game does not update 'which minion is currently being played', preventing further triggers from knowing what minion to run on.

Repentance:
- https://youtu.be/6rK9-9C-D0U
- http://us.battle.net/hearthstone/en/forum/topic/20743544279

Sacred Trial:
- https://www.youtube.com/watch?v=NhL-lFd3DJk
- https://youtu.be/2TssNwGrzN0 (this behaviour no longer happens - the minion dying in setaside now has no side-effects)
- http://us.battle.net/hearthstone/en/forum/topic/20743594436
- https://www.reddit.com/r/hearthstone/comments/4h87rp/a_bug_with_and_sacret_trial/

Addled Grizzly:
- http://us.battle.net/hearthstone/en/forum/topic/20743744271

Knife Juggler:
- http://us.battle.net/hearthstone/en/forum/topic/20743544399

Snipe:
- https://youtu.be/8tSlgnWuJwk

Most interesting: Mirror Entity triggers on the untransformed minion:
- https://www.reddit.com/r/hearthstone/comments/4h03pa/bug_mirror_entity_fandral_staghelms_minions/

**Comment by PattuX** [comment]
The Knife Juggler Report also mentions Living Roots not triggering KJ. If this interaction is real, I have no idea why it is the case. Will try to reproduce later.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4h03pa/bug_mirror_entity_fandral_staghelms_minions/ lmao

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20743674972 had three videos, added them all

**Comment by culinko** [comment]
Another exhaustive report, has screenshots: https://www.reddit.com/r/hearthstone/comments/4hut3k/fandral_staghelm_transform_minions_bugged_vs/.

**Comment by PattuX** [comment]
Sacred Trial killing the non-transformed minion in steaside does NOT trigger Cult Master anymore

* https://youtu.be/NhL-lFd3DJk

Logs:

* https://gist.github.com/PattuX/b61ffa15ded4688ef671a326e0a7f2c7

for comparison, without Fandral: 

* https://gist.github.com/PattuX/9e6acebfb2f2fdf26ecba7aa9eae0596

I honestly thought that the transformed DotC would have Fandral as its creator which probably would have been the reason why the 'currently played minion' doesn't change, but the creator is actually the non-transformed DotC.

**Comment by Patashu** [comment]
"I honestly thought that the transformed DotC would have Fandral as its creator which probably would have been the reason why the 'currently played minion' doesn't change, but the creator is actually the non-transformed DotC."

I think that the tag or whatever for 'which minion is the currently played minion' is not shown in power.log, so we can't tell what the internal difference is.

**Comment by culinko** [comment]
Another report: https://www.reddit.com/r/hearthstone/comments/4ibv0m/bug_with_fandral_minions_and_sacred_trial/.

**Comment by Patashu** [comment]
Confirmed in 5.0.1?

https://github.com/HearthSim/hs-bugs/issues/465

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13 http://us.battle.net/hearthstone/en/forum/topic/20745044415?page=1#3

**Comment by VoidMayonnaise** [comment]
https://youtu.be/voZylHGztZM
Already fixed.

**Comment by culinko** [comment]
Additionally confirmed by testing Addled Grizzly, Repentance and Sacred Trial + Cult Master.
