### ISSUE TITLE
If Shifter Zerus becomes two different Choose One minions, the Choose One choices of the first minion are erroneously saved

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#466]
As a result, you will be prompted with the Choose One choices of the previous minion, which may not work as intended (or at all).

* http://us.battle.net/hearthstone/en/forum/topic/20743564271
* https://www.reddit.com/r/hearthstone/comments/4gmi7k/bug_shifting_zerus/
* https://www.reddit.com/r/hearthstone/comments/4go24d/bug_shifter_zerus_choose_one_bug/ 
* http://us.battle.net/hearthstone/en/forum/topic/20743694382

Sometimes only one choice is from the previous minion.
* http://us.battle.net/hearthstone/en/forum/topic/20743624516

Three or more choices can be shown.
* https://www.reddit.com/r/hearthstone/comments/4h8qak/critical_bug_with_shifter_zerus_and_druid_forms/

**Comment by culinko** [comment]
Fixed in 5.0.1.13030.
