### ISSUE TITLE
Renounce Darkness Mana Cost Enchantment does not detach from played minions

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#468]
All Mana Cost Enchantments should detach from played minions to ensure that Effigy, Recombobulator, etc. works correctly with them. However, Renounce Darkness does not. It also has placeholder art (which would not matter if this bug is fixed).

* https://www.reddit.com/r/hearthstone/comments/4glzir/looks_like_some_placeholder_art_got_through_qa/
* https://www.reddit.com/r/hearthstone/comments/4gsyzj/evolution_bug_with_renounce_darkness/

**Comment by culinko** [comment]
Fixed in 5.2.0.13619.
