### ISSUE TITLE
Vilefin Inquisitor Hero Power can be used with a full board

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#469]
Normally summoning Hero Powers can't be used with a full board. But Vilefin Inquisitor's granted Hero Power can be.

* https://www.reddit.com/r/hearthstone/comments/4glzlh/apparently_you_can_use_the_murloc_hero_power_with/
* http://us.battle.net/hearthstone/en/forum/topic/20743634390

**Comment by culinko** [comment]
Fixed in 5.2.0.13619.
