### ISSUE TITLE
Rarity gem is incorrect for Wild-only cards

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#471]
'The gem below the flavor text does not show the correct rarity. The example above has a pic of Old Murk-Eye, however, the gem is blue, marking a "Rare" card. This also applies to ALL wild-only cards.'

* https://www.reddit.com/r/hearthstone/comments/4gkqnp/wildexclusive_cards_have_a_bug/

Undertaker appears to be Common at first, then shows as Rare when opened.

* http://us.battle.net/hearthstone/en/forum/topic/20743714964

Many examples here: 

* http://us.battle.net/hearthstone/en/forum/topic/20743864266
* http://us.battle.net/hearthstone/en/forum/topic/20745014501

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13030:

https://www.reddit.com/r/hearthstone/comments/4mq5w8/wild_epics_and_legendaries_show_the_rare_gem_in/

**Comment by culinko** [comment]
Fixed in 5.2.0.13619.
