### ISSUE TITLE
C'Thun's current Health is not set to 1 when summoned by Redemption

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#472]
Instead, it is the full, with buffs, health of C'Thun. Maybe the (Summon Resolution Step?) trigger that applies old ritual buffs to new C'Thuns erroneously sets DAMAGE tag to 0?

* https://www.reddit.com/r/hearthstone/comments/4gnpkg/cthun_redemption_bugweird_rulling/
* https://www.reddit.com/r/hearthstone/comments/4go0ei/interesting_interaction_with_cthun_and_redemption/ 

Note that this interaction only happens if C'Thun has at least one ritual buff.

![image](https://cloud.githubusercontent.com/assets/235410/14876448/9cb0771a-0d1d-11e6-80f2-50c0c5dd928e.png)

**Comment by 10925** [comment]
Well, not for a buff less C'Thun, it would set to 1.
http://i65.tinypic.com/6qbp0p.jpg

**Comment by Patashu** [comment]
Nice catch, thanks. Makes sense.

**Comment by Patashu** [comment]
Happens with Repentance too???

**Comment by 10925** [comment]
it's Redemption in its picture

also, the situation it described should trigger Redemption ,but not repentance

I think he/she just confused these 2 serects

**Comment by Patashu** [comment]
Thanks.

**Comment by culinko** [comment]
Still bugged in 5.0.1.13030, despite patch notes mentioning its bug fix.
