### ISSUE TITLE
Cards that discard another cards from your hand do not display the discarded cards in the sidebar

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#48]
**Only the player sees the bug.**

New to 3.0, when you play a card that discards another cards from your hand and mouse over the sidebar, the cards it discarded are not shown.
- https://www.reddit.com/r/hearthstone/comments/3hmizz/doomguard_does_not_show_the_minions_it_discarded/
- http://us.battle.net/hearthstone/en/forum/topic/18596064399
- http://us.battle.net/hearthstone/en/forum/topic/19466046482

![xtcdpig](https://cloud.githubusercontent.com/assets/11700272/12882360/61784c6e-ce51-11e5-9c55-6eb6367b7f28.png)

Your opponent's sidebar will show the discarded cards correctly.

![vezqe6s](https://cloud.githubusercontent.com/assets/11700272/12882372/709798ee-ce51-11e5-83a0-59fe327db2c2.jpg)

**Comment by culinko** [comment]
>(This needs retesting after the hotfix that fixed Fel Reaver discards.)

Not only that, you always need to test sidebar stuff with both players, so you will know if it happens only for player, opponent or both.

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/19466046482

Confirmed in 3.2

**Comment by culinko** [comment]
Confirmed with Darkshire Librarian in 5.0: http://imgur.com/m0rB1Oi.

**Comment by Patashu** [comment]
Looks like this finally got fixed? https://www.reddit.com/r/hearthstone/comments/5g2xqa/doomguard_now_shows_which_cards_he_discarded_in/
