### ISSUE TITLE
Minion position swapping bug returned

### ISSUE THREAD

**Issue by becelot** [HearthSim/hs-bugs#481]
Seems like an old bug has returned to hearthstone: [Video](https://www.youtube.com/watch?v=3V9r0ZVwPHE). 

The bug has happened to me in a few number of matches today. It seems to be rather rare, however it only occurred against druid. I don't have any footage of the rest of the game to determine, what may have caused this bug. I just started recording when it happened again. The minion swapping occurred 4 turns before I started recording and ended, when the video ends. After that, it seems to be fine (although this might be due to the druid having only 2 minions on board at most).

I'm pretty sure, that in all those matches where this bug occurred, an opponents Sylvanas took one of my minions and the rest of the minions started to rotate around that stolen minion (the totem in the video). Not sure, if this is really related to that issue, but it is the only thing as far as I can remember that all games had in common. I was however not able to reproduce this bug when I tried later. So it might be something different entirely.

**Comment by Patashu** [comment]
Can be merged with https://github.com/HearthSim/hs-bugs/issues/217
