### ISSUE TITLE
If you play Fandral Staghelm + a Choose One card quickly, a visual effect will remain on the board permanently

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#486]
- https://www.reddit.com/r/hearthstone/comments/4h2s5u/fandral_staghelm_glitch_visual/

**Comment by culinko** [comment]
Another report: https://www.reddit.com/r/hearthstone/comments/4ijq27/fandral_staghelm_visual_bug/.

**Comment by bastosdiegol** [comment]
It just happened to me twice. Both cases Fandral followed with Wrath.
The "choose both" aura remained until the end of the game.
And it's position was placed near the minion who I aimed the Wrath.
Note: on a mobile device this time.

![screenshot_20160520-114747](https://cloud.githubusercontent.com/assets/8089638/15432371/4f239996-1e84-11e6-997e-a1c03236c217.png)
![screenshot_20160520-120144](https://cloud.githubusercontent.com/assets/8089638/15432379/56af590c-1e84-11e6-9351-3e7a9098a0e1.png)

**Comment by troggnostupidhs** [comment]
I believe this is fixed.

Deck
AAEBAZICBO0F9xGuqwKZ0wINQPsBnAK0ArQFuQbEBosI9BHqFpdoi8ACpMICAA==

![img000](https://user-images.githubusercontent.com/22508641/31846803-9ba2103e-b5de-11e7-9bff-879ab476bd69.png)
![img001](https://user-images.githubusercontent.com/22508641/31846804-9baaa5f0-b5de-11e7-8b6e-02dd1f09d5e0.png)
