### ISSUE TITLE
Yogg-Saron, Hope's End's Battlecry ends immediately if your Hero dies but continues if the enemy Hero dies

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#487]
The intended behaviour, confirmed by Blizzard, is that the Battlecry should end immediately if either Hero dies.

* https://www.youtube.com/watch?v=Xs7TLL3ZqDg
* http://us.battle.net/hearthstone/en/forum/topic/20743664702
* http://us.battle.net/hearthstone/en/forum/topic/20743624267
* https://www.youtube.com/watch?v=Kcm2tIPk2cQ

**Comment by Xinhuan** [comment]
I went back to check the exact Tweet where Blizzard confirmed this behavior:

https://twitter.com/PlayHearthstone/status/718137544609828865

Q: if yogg saron fire balls your own hero, but then heals them into the positive for health, do you live?
A: If the Fireball would do lethal damage, then the rest of the spells stop casting.

So the tweet is correct, if your hero dies, Yogg stops immediately. The tweet does not cover the case where the opponent hero dies, but it is assumed by many people to also be the case.

A user tweeted in reply on 28 April asking "my hero die，it will stop；the opposite hero die，it will not stop？" (https://twitter.com/zjzjbao/status/725691999014281216) but the question did not get a reply.

**Comment by Kybxd** [comment]
I guess yogg wont cast spells for a dead hero.

We can test like this:First yogg kills the enemy hero,then kills an enemy Sylvanas and is stolen.Will yogg continue casting spells?

**Comment by Patashu** [comment]
Interesting idea for a test.

**Comment by jleclanche** [comment]
We'll need @YoggSaron's help for that one.

**Comment by Patashu** [comment]
This may have been fixed in the hotfix. Several videos of Yogg show that he stops casting spells when the enemy Hero dies.

**Comment by culinko** [comment]
Confirmed with SimFri. He casted 26 spells that game, but the game ended after his Yogg-Saron killed me with 12th spell.
