### ISSUE TITLE
If Servant of Yogg-Saron Polymorphs himself, Mirror Entity will copy Servant of Yogg-Saron, not Sheep

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#488]
This is similar to the bug with Fandral Staghelm, Choose One minions and Mirror Entity. ( https://github.com/HearthSim/hs-bugs/issues/465 ) In that bug, Mirror Entity also copies the original minion. It seems that only certain kinds of transformations are set up to correctly update 'what is the played minion'. It's very likely that all other after play/after summon triggers fizzle when this happens, because the two bugs seem very similar.
- https://www.youtube.com/watch?v=OeggkMSbgas&t=2m27s

**Comment by PattuX** [comment]
Just want to quickly point out that this test got way easier now we have Tortollan Primalist. I'd be interested whether this bug still exists to get a better understanding of the whole transform menchanic.

**Comment by VoidMayonnaise** [comment]
#698 Seems that Mirror Entity won't trigger if the minion has already left play. Maybe this one is already fixed, but it's difficult to test.

**Comment by VoidMayonnaise** [comment]
https://youtu.be/295MrOwvSHw
Already fixed. Maybe fixed in 7.1.

**Comment by troggnostupidhs** [comment]
It probably should trigger. Faceless Manipulator and the Druid transform minions should probably be tested.

**Comment by PattuX** [comment]
Yogg + Evolve does not trigger ME

* https://hsreplay.net/replay/aJCe6D57QLvswgdZTHraBG#turn=14a

**Comment by Jetz72** [comment]
This one seems like it almost definitely would have been fixed with the 11.2 transformation changes. It's actually my working theory that those changes were _because_ of interactions like this and ME+Faceless Manipulator. Should be possible to confirm with Mirror Entity vs Tess+Polymorph, if anyone wants to make sure.

**Comment by troggnostupidhs** [comment]
![Hearthstone Screenshot 03-17-19 19 45 41](https://user-images.githubusercontent.com/22508641/54499904-94a80880-48ed-11e9-88dd-ee54c64f8e5e.png)

![Hearthstone Screenshot 03-17-19 19 45 50](https://user-images.githubusercontent.com/22508641/54499905-94a80880-48ed-11e9-9f4d-4fa45e5e8ddc.png)

Rogue 
AAEBAaIHAu8I6/ACDrMBvwH7AZwCtAK9BJsFuQaYDbds4soCp80CpvACzIkDAA==

Mage
AAEBAf0EAu0F7wgOswHDAfsBnAK0AogF7AW5BpgNt2zBwQLiygKm8ALMiQMA

**Comment by troggnostupidhs** [comment]
> Jetz
> All is probably well then.
> Should be safe to backdate it to 11.2 and close it
