### ISSUE TITLE
Silenced C'Thun minions can leave the 'lightning bolt' visually in play

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#490]
Not sure if it happens all the time or just some of the time.
- https://www.reddit.com/r/hearthstone/comments/4h82b8/bug_silenced_crazed_worshipper_keeps_the_effect/

**Comment by culinko** [comment]
Also happens with Twilight Elder and Hooded Acolyte (probably with all of the C'Thun minions): https://www.reddit.com/r/hearthstone/comments/4h6ctm/twilight_elder_visual_bug/.

**Comment by culinko** [comment]
Another report: https://www.reddit.com/r/hearthstone/comments/4icpxj/bug_with_hooded_acolyte/.

**Comment by culinko** [comment]
Report in 5.0.0.13030: https://www.reddit.com/r/hearthstone/comments/4pjofy/gameplaybug_anyone_else_find_this_annoying/.

**Comment by Patashu** [comment]
Confirmed in 5.2.0

http://us.battle.net/hearthstone/en/forum/topic/20746964798

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4wt530/cult_sorcerer_does_not_lose_her_effect_symbol/

Confirmed in 5.2.2

**Comment by troggnostupidhs** [comment]
Twilight Elder and Hooded Acolyte are fixed.
