### ISSUE TITLE
Spectating your friend playing the other mode than you have selected will show you the other players' ranks

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#492]
After setting your play mode to Wild and spectating a Standard match, you will see Wild ranks of spectated players and vice versa. Note: Playing a friendly Wild match or creating a new Wild deck will also set your mode to Wild and vice versa.
* https://www.reddit.com/r/hearthstone/comments/4h4wo8/bug_when_you_have_a_friendly_wild_battle_and_you/
* https://www.reddit.com/r/hearthstone/comments/4h79h1/spectator_bug/

**Comment by PattuX** [comment]
The spectator will also see the opponents Wild rank.

**Comment by Patashu** [comment]
Is this related? 'Is it a known bug that spectating a Wild game doesn't work properly? No "vines" on rank symbols and sometimes even shows a standard rank of the player, even if it is clearly a Wild game(with wild cards).'

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13030:

http://us.battle.net/hearthstone/en/forum/topic/20745144746

**Comment by culinko** [comment]
Fixed in 5.2.0.13619.
