### ISSUE TITLE
In power.log you can tell if your opponent is holding a Shifter Zerus

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#496]
During the Start of Turn Phase Shifter Zerus attaches Enchantment OG_123e to itself. However, both players can see this happening in power.log.

Zerus holder's perspective: https://gist.github.com/Patashu/3da0e2001d84a4ab9d023e38acb7be1d

Opponent's perspective: https://gist.github.com/Xinhuan/55fd368a214e99da75b513f726819754

**Comment by jleclanche** [comment]
Dupe.
