### ISSUE TITLE
Gadgetzan Auctioneer's trigger is missing from the sidebar

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#497]
**Both players see the bug.**
- https://www.youtube.com/watch?v=bz3gffzsWjc&t=13m25s
- https://www.youtube.com/watch?v=l4_SYvYFVlk&t=5m

**Comment by troggnostupidhs** [comment]
> Several cards now properly generate a history tile when played.

http://us.battle.net/hearthstone/en/blog/20382066/hearthstone-update-november-29-2016-11-29-2016

This might be fixed.

**Comment by culinko** [comment]
Still happens in current patch.

**Comment by culinko** [comment]
Merged into #640.
