### ISSUE TITLE
Holy Nova has an incorrect animation

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#498]
Happens only to the player casting it. Previously, all visual effects were moving towards the opponent's hero, but currently that's not the case. One layer of the animation effects is moving from your opponent towards your hero. This might be a similar bug which happened with Frost Nova, but has been fixed since.
- https://www.reddit.com/r/hearthstone/comments/4h9618/ok_blizzard_its_been_a_while_fix_your_aoe/
- https://www.youtube.com/watch?v=oG1xOvA49w8&t=11m15s - old correct animation
- https://www.youtube.com/watch?v=xBMxirkf5xs&t=10m30s - new bugged animation

**Comment by troggnostupidhs** [comment]
As far as I can tell, this seems fixed. It's slightly hard to see the animation issue, but I think I can tell the difference. Looking above the End Turn button, the bugged animation has a effect moving down. I don't notice that currently. It's worth someone else looking at to make sure.

**Comment by culinko** [comment]
I'll try to find a video from the current patch to see if it's fixed (it's too fast to analyze in game). I took the relevant part from the Trump's video, slowed it down and made it into a gif, so you can see the animation issue more clearly:
![trump](https://cloud.githubusercontent.com/assets/11700272/21004183/5f997328-bd2f-11e6-9d3d-074196018f96.gif)
As you can see, one "particle wave" is coming from the Druid, but that wasn't the case in the Kripp's video couple of patches ago.

**Comment by troggnostupidhs** [comment]
Thanks for checking this. It's much clearer with the animation slowed down. At full speed, it goes by quickly and I wanted to make sure I was seeing it correctly.
