### ISSUE TITLE
Text in dialogue boxes misaligned

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#5]
Since Patch 2.6.0.8834, the chat text and add friend dialogue boxes have text vertically misaligned within the typing area. This occurs on all platforms, and is more pronounced at certain screen resolutions.

* http://us.battle.net/hearthstone/en/forum/topic/17345877008
* [[Hearthstone Visual Bug] Gladiator's Longbow vs Blade Flurry = Fake Immune](https://www.youtube.com/watch?v=N5tN7-YYwOI&t=44s)

**Comment by jleclanche** [comment]
Fixed in 4.0.0.10833 according to @NightKev
