### ISSUE TITLE
Failure to transition out of Mulligan Phase

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#500]
Technically this is not a client animation hang, but as you are unable to take any actions it is as bad as one.

You will see the full extent of your opponent's turns, but never be able to play anything on your own turns. The visual effects of the mulligan Phase will never end.

The only known workaround is to disconnect/reconnect (or close and open the process).
- http://us.battle.net/hearthstone/en/forum/topic/20743025649
- http://us.battle.net/hearthstone/en/forum/topic/20742864551
- http://us.battle.net/hearthstone/en/forum/topic/20743645154

**Comment by culinko** [comment]
Is this related? https://www.reddit.com/r/hearthstone/comments/4k2200/tavern_brawl_bug/

**Comment by Patashu** [comment]
Think this is related

http://us.battle.net/hearthstone/en/forum/topic/20745105352

**Comment by Patashu** [comment]
May be related:

https://www.reddit.com/r/hearthstone/comments/4nwa12/stuck_at_card_mulligan/

**Comment by culinko** [comment]
The following report looks like this bug, however it might be related to the recent DDoS attacks: https://www.reddit.com/r/hearthstone/comments/4z5ooh/weird_bug_lost_me_a_ranked_game/.

**Comment by Patashu** [comment]
Confirmed in 6.0?

https://www.reddit.com/r/hearthstone/comments/507vf9/game_breaking_glitch_from_a_lag_in_queue/

**Comment by culinko** [comment]
Is this related? Player reporting that the Mulligan Phase doesn't even start: https://www.reddit.com/r/hearthstone/comments/51oxbk/my_15_loss_because_of_a_bug_where_mulligan_doesnt/.

**Comment by culinko** [comment]
Is this related? https://github.com/HearthSim/hs-bugs/issues/769#issue-239747270

**Comment by troggnostupidhs** [comment]
> Went to brawl (All-star) with paladin and the 1 mana spell that summons two 1/1s.
Mulligan my whole hand, game wont do anything, I've been waiting for about 10 minutes now.
All other UI elements work, I can take screenshots (no text appears in-game that I've took a screenshot, but file is saved on desktop), send/recieve messages, conceding does nothing, but the options menu works.

![image](https://user-images.githubusercontent.com/22508641/29255435-5ef21ea8-806f-11e7-8804-a7bf43d54ab7.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6wlvfl/gamebreaking_bug_before_mulligan_phase/

> My game has been like this for 10 minutes, and it seems it will stay that way. Game started normally, but no cards have appeared, just nothing happens. I am sorry if this was posted before

![image](https://user-images.githubusercontent.com/22508641/29803717-d033563a-8c4b-11e7-8b00-43cc730689ee.png)

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21507224/hearthstone-update-10-2-february-6-ranked-play-update

> Resolved an issue that could cause a player to become stuck when reconnecting before the first turn.

**Comment by troggnostupidhs** [comment]
I haven't seen reports of this since the update. I will close this and it can be reopened if there is any proof of it happening.
