### ISSUE TITLE
Bottom rank tooltip in games is covered by other UI elements

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#504]
If you hover over the bottom rank in a ranked match, its tool-tip will be too much down on the screen. The bottom part of the tool-tip will be off-screen and it can be covered by the current time and spectator icon. Probably only happens at lower resolutions.
- https://www.reddit.com/r/hearthstone/comments/4gtnbo/heartstone_bugs_literally_unplayable/

![hearthstone screenshot 05-05-16 20 25 35](https://cloud.githubusercontent.com/assets/11700272/15055289/088f1c7c-130c-11e6-8613-d40303b42739.png)

![hearthstone screenshot 05-05-16 21 32 24](https://cloud.githubusercontent.com/assets/11700272/15055290/089e4d3c-130c-11e6-9880-15ccdb7cfc77.png)

**Comment by troggnostupidhs** [comment]
I think this might be  fixed. I think they removed the tool tip, so the issue doesn't occur anymore.

**Comment by culinko** [comment]
Yep, looks the tool-tip was removed.
