### ISSUE TITLE
Forbidden Healing (turned into damage with Auchenai Soulpriest) with spell damage and 0 available mana doesn't do any damage

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#505]
If you have Auchenai Soulpriest, spell damage and you use Forbidden Healing with no remaining mana, the spell does 0 damage. This is inconsistent with other effects, namely Shield Slam, Blade Flurry, Shadowflame, Savagery and Lightbomb. All of these effects do damage based on how much spell damage do you have.

![hearthstone screenshot 05-06-16 05 25 43](https://cloud.githubusercontent.com/assets/11700272/15063932/d143a42a-134e-11e6-9019-c79095ccfedc.png)

**Comment by Kybxd** [comment]
This bug has been fixed. In my pictures, Auchenai has Spell Damage+1 from Velen's Chosen.
* http://imgur.com/a/pTCgf
