### ISSUE TITLE
Eater of Secrets doesn't display destroyed secrets for the opponent

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#506]
**Only the opponent sees the bug.**

If you use Eater of Secrets to destroy your opponent's secrets, they will be missing in his sidebar.

![hearthstone screenshot 05-06-16 03 22 00](https://cloud.githubusercontent.com/assets/11700272/15063619/16639c3e-134c-11e6-9fa2-e88a2af54e58.png)

Your sidebar will display it correctly.

![lihsjrt](https://cloud.githubusercontent.com/assets/11700272/15063966/2a1704c0-134f-11e6-9582-2a22b5ebf09e.jpg)

**Comment by troggnostupidhs** [comment]
Just tested this and it works for both players.
