### ISSUE TITLE
When playing Yogg-Saron, if your Hero is killed but has positive health+armor, the game does not end

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#507]
Normally Yogg-Saron ends the game if your Hero dies (and should end the game if your opponent's Hero dies too - see https://github.com/HearthSim/hs-bugs/issues/487 ). However, if you simultaneously die and gain Armour, the game continues. (Bash on your own Hero at 3 or less Health will do this.) Possibly this is because Yogg-Saron checks HEALTH + ARMOR - DAMAGE and sees that it is positive.

If you enter this state and have an attack buff up, the attack buff will rise with each spell Yogg casts, similar to https://github.com/HearthSim/hs-bugs/issues/12 . The technical reason is because your Hero isn't in play to reset its attack to 0, but the attack buff still is, so every time attack/health updates it increases without resetting.
- https://www.reddit.com/r/YoggSaron/comments/4h9dhp/heroic_strike_glitch_yoggsaron/
- http://us.battle.net/hearthstone/en/forum/topic/20743794700

Sacrificial Pact also causes Yogg-Saron to continue casting spells even though a Hero died, for a similar reason (HEALTH + ARMOR - DAMAGE is positive).
- https://www.reddit.com/r/hearthstone/comments/4lifm8/even_after_seeing_so_muchyogg_still_has_surprises/

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4k8tau/strange_glitch_with_yogg/ raises an interesting question - if with your multiplied attack Yogg casts Savagery, will it do more damage? If so, #12 is truly a gameplay bug after all and needs recategorization.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4lifm8/even_after_seeing_so_muchyogg_still_has_surprises/ It looks like if your Hero is Destroyed by Sacrificial Pact, this also does not end the game immediately. This could be fixed if Yogg-Saron checked the PLAYSTATE tag instead of calculating health.

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13030

https://www.reddit.com/r/hearthstone/comments/4n3r42/til_you_can_have_0_or_minus_life_and_still_survive/

**Comment by VoidMayonnaise** [comment]
I tested by Grand Archivist and Bash, and the hero with 0 health and 3 armor died. I think it's time to close this old issue, since the similar one #742 was fixed.
![1](https://user-images.githubusercontent.com/28046803/36830247-c5308b06-1d5d-11e8-9b9c-bc6e540d4ce5.png)
![2](https://user-images.githubusercontent.com/28046803/36830249-c5ff8f32-1d5d-11e8-8177-34619b36f10a.png)
![3](https://user-images.githubusercontent.com/28046803/36830251-c739505e-1d5d-11e8-98c7-1f67f8a09067.png)

**Comment by troggnostupidhs** [comment]
Grand Archivist has an end of turn effect, Yogg is a battlecry. I'm not fully convinced this specific bug is fixed.

**Comment by Kybxd** [comment]
Lynessa Sunsorrow has similar mechanics with Yogg, so this could be tested by Lynessa + Blessing of Kings + Cobra Shot + Bash.

Besides, we used to think Yogg has a Forced Death Phase between each spells he casts. But actually he uses a standard Death Phase - new Death Phase follows the last one, and Yogg doesn't cast the next spell until no death occurs. Lynessa, Brann + Servant of Yogg, Brann + Tortollan Primalist and The Runespear also use this mechanic.
(Video: https://www.bilibili.com/video/av20271567/)

About The Runespear - actually 'Discover a spell' is an After Attack Trigger. And then after a standard Death Phase the spell is resolved. This results:
1. The order of 'Discover a spell' and Bear Trap is decided by Dominant Player, but the spell can always work on the bear (both AoE and targeted spells).
2. Ancestral Healing cannot save the minion you kill by The Runespear, for it has left board.

**Comment by Kybxd** [comment]
Lynessa stops if your hero is at 0 Health + positive Armor. 
(Video: https://www.bilibili.com/video/av20274922/)
