### ISSUE TITLE
Warrior AI doesn't use Execute

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#510]
Warrior AI doesn't use Execute anymore. This bug was introduced recently, alongside #449 (already hotfixed) and #478. I was able to reproduce it today, Warrior still had 2 cards in hand after we went to fatigue, haven't played a single Execute and I had damaged minions.
- http://us.battle.net/hearthstone/en/forum/topic/20743724586

**Comment by troggnostupidhs** [comment]
This is fixed. I played on Normal and the AI used Execute.
