### ISSUE TITLE
Bugs with golden promotional cards

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#511]
If you don't own golden copy of Gelbin Mekkatorque and Elite Tauren Chieftain, they are displayed with blue highlight, indicating that they could be crafted (even if you don't have any Arcane Dust). However, this is just a visual bug, since these two promotional cards can't be crafted with Arcane Dust at all. Additionally, the two cards are visible even without selecting the "Include Uncraftable Cards" filter.

![hearthstone screenshot 05-07-16 03 22 33](https://cloud.githubusercontent.com/assets/11700272/15089425/fc5c19da-1402-11e6-9548-9c39e2798735.png)

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 12-05-16 20 53 49](https://cloud.githubusercontent.com/assets/22508641/20910034/1ffe8ad6-bb2d-11e6-9cec-283eea29b150.png)

![hearthstone screenshot 12-05-16 20 53 54](https://cloud.githubusercontent.com/assets/22508641/20910038/2496ab0a-bb2d-11e6-8bd0-80fec53786b1.png)

**Comment by troggnostupidhs** [comment]
This might be fixed, but I don't have enough dust to determine if it would be highlighted when 'Include Uncraftable Cards' is selected.
