### ISSUE TITLE
Yogg-Saron (stolen by Sylvanas) does not resolve Choose One spells

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#512]
They will fizzle even if both options are valid.

https://www.youtube.com/watch?v=lX-Q62yQXgA&t=17m00s
- At 17:25 Yogg-Saron is stolen.
- At 17:37, Wrath is displayed with a valid target in play (Yogg-Saron) but nothing happens.
- At 17:43, Feral Rage is displayed but nothing happens.

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13030

https://www.reddit.com/r/hearthstone/comments/4nmqzi/bug_my_opponents_stolen_yogg_saron_didnt_give_me/

**Comment by VoidMayonnaise** [comment]
https://www.bilibili.com/video/av13650103
About 03:25, Yogg stolen by Sylvanas cast Wrath on himself, deal 1 damage and draw a card. So this bug has already fixed.
