### ISSUE TITLE
Combo played card count only is reset at the start of each player’s turn

### ISSUE THREAD

**Issue by bbbbbbbbba** [HearthSim/hs-bugs#515]
Original Title: Active Combo only gets cleared on beginning of own turn, affects stolen Yogg-Saron battlecry

---

https://www.youtube.com/watch?v=lX-Q62yQXgA&t=16m45s

The Hunter plays Yogg-Saron. Yogg was stolen during the battlecry, and plays Headcrack for the Warrior (among other spells). The hunter passes. The Warrior uses the hero power (Tank Up!) and passes, then Headcrack returns to the Warrior's hand at the end of turn.

This contradicts with this tweet, stating that combo won't trigger unless a card was played before Yogg:
https://twitter.com/PlayHearthstone/status/718193454707273729

**Comment by Patashu** [comment]
This is ambiguous. While the Hunter did not play a card before playing Yogg, the Warrior did on his previous turn. So the question is if the state of being in Combo is intended to last during your opponent's turn or not - and right now I don't know what the devs would say.

We have one other data point - a comboed SI:7 Agent (stolen before Battlecry) becoming uncomboed. https://gist.github.com/culinko/8728f42ef02f7399bb1e1ea22847c1be But it should be re-tested in 5.0 with the stealing player having activated combo the turn previous. If it works differently to the Yogg-Saron interaction, it's an inconsistency and therefore unambiguously a bug.

**Comment by culinko** [comment]
Re-tested stealing SI:7 combo with opponent playing a card on the previous turn. SI:7's 2 damage combo was successfully activated after being stolen and is therefore consistent with stolen Yogg + Headcrack. It's likely that this interaction is intended, but confirmation from devs would be ideal. Log here: https://gist.github.com/culinko/f0dbcccb24d70bd976fec48d2253daec.

**Comment by PattuX** [comment]
https://www.twitch.tv/videos/216114848?t=02h53m14s

**Comment by Jetz72** [comment]
Still happens. The replay isn't all that helpful since the Scroll of Wonder spells aren't currently shown, but one of the scrolls drawn by my opponent cast Sabotage, destroying my weapon at the start of turn 20b (my turn; they drew due to one of my own Scrolls). Was the Battle of the Bans brawl for the record.

https://hsreplay.net/replay/dPyGt79qCCUCyTfF3rJYx2#turn=20b

**Comment by Jetz72** [comment]
https://www.reddit.com/r/hearthstone/comments/bjw84c/i_found_bug/embufsf/
>You are right u/krevetky, this is a bug. Expect a fix for it in an upcoming patch. If you’re curious why this happened, Combo works by checking how many cards you played this turn. That value was only being reset at the start of each player’s turn. So, when your opponent played [[Unseen Saboteur]] and cast your [[Raiding Party]], Raiding Party checked how many cards you played this turn, the value of which is still set to the number of cards you played last turn. Since you played a card the previous turn, the conditions for Combo were met. If you hadn’t played a card the previous turn, Raiding Party would have only drawn pirates.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/bfaorv/bug_or_intended_why_does_it_do_4_damage/

![image](https://user-images.githubusercontent.com/22508641/57179854-58564a80-6e50-11e9-91f5-3a2dfb74179a.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/bjw84c/i_found_bug/embufsf/

> You are right u/krevetky, this is a bug. Expect a fix for it in an upcoming patch. If you’re curious why this happened, Combo works by checking how many cards you played this turn. That value was only being reset at the start of each player’s turn. So, when your opponent played [[Unseen Saboteur]] and cast your [[Raiding Party]], Raiding Party checked how many cards you played this turn, the value of which is still set to the number of cards you played last turn. Since you played a card the previous turn, the conditions for Combo were met. If you hadn’t played a card the previous turn, Raiding Party would have only drawn pirates.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22933721
> Fixed an issue where Eviscerate pulled from Unseen Saboteur can deal its combo damage if the Eviscerate's owner had combo activated on the previous turn.

**Comment by Jetz72** [comment]
Looking over a log of a turn ending, the COMBO_ACTIVE flag is now indeed cleared at the end of a turn rather than the start.
```
TAG_CHANGE Entity=[entityName=Hydrologist id=8 zone=PLAY zonePos=1 cardId=UNG_011 player=1] tag=1196 value=0 
TAG_CHANGE Entity=GameEntity tag=STEP value=MAIN_END 
BLOCK_START BlockType=TRIGGER Entity=Jetz#1946 EffectCardId= EffectIndex=-1 Target=0 SubOption=-1 TriggerKeyword=0
    TAG_CHANGE Entity=GameEntity tag=NEXT_STEP value=MAIN_CLEANUP 
BLOCK_END
BLOCK_START BlockType=TRIGGER Entity=Jetz#1946 EffectCardId= EffectIndex=-1 Target=0 SubOption=-1 TriggerKeyword=0
BLOCK_END
BLOCK_START BlockType=TRIGGER Entity=The Innkeeper EffectCardId= EffectIndex=-1 Target=0 SubOption=-1 TriggerKeyword=0
BLOCK_END
TAG_CHANGE Entity=GameEntity tag=STEP value=MAIN_CLEANUP 
BLOCK_START BlockType=TRIGGER Entity=Jetz#1946 EffectCardId= EffectIndex=-1 Target=0 SubOption=-1 TriggerKeyword=0
    TAG_CHANGE Entity=[entityName=Hydrologist id=8 zone=PLAY zonePos=1 cardId=UNG_011 player=1] tag=JUST_PLAYED value=0 
    TAG_CHANGE Entity=Jetz#1946 tag=COMBO_ACTIVE value=0 
    TAG_CHANGE Entity=GameEntity tag=NEXT_STEP value=MAIN_NEXT 
BLOCK_END
```
