### ISSUE TITLE
Animation bug with Thaddius

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#516]
If your Feugen or Stalagg dies and spawns Thaddius, the lightning animation will be obscured by an invisible texture. Previously, the lightning bolts connected at the Thaddius' image.
- https://www.youtube.com/watch?v=vzVxyYrZ4R8&t=5m43s (old correct animation)
- https://www.youtube.com/watch?v=y-UDKBIzKJk&t=1m55s (new bugged animation)
- https://www.youtube.com/watch?v=9bOKsvjpwT8&t=4m54s (new bugged animation)

**Comment by troggnostupidhs** [comment]
https://youtu.be/ufLRHJa_7Y0?t=185

I think this is fixed
