### ISSUE TITLE
Siphon Soul and Sacrificial Pact have inconsistent ordering

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#519]
Sacrificial Pact reads

"Destroy a Demon. Restore 5 Health to your hero."

It sets the target minion TO_BE_DESTROYED before healing. Proof here: https://www.youtube.com/watch?v=jcniWFdCBKY

Siphon Soul reads
Destroy a minion. Restore 3 Health to your hero.

It heals before setting the target minion TO_BE_DESTROYED. Proof here: http://paste.ubuntu.com/16335398/

**[12:52] <ZeroRin>** Tested and confirmed, siphon soul heal the hero before setting to_be_destroyed to 1

To be consistent with Sacrificial Pact and with its own card text, it should set the target minion TO_BE_DESTROYED first.

This has game mechanical side-effects because pending destroy minions are now ignored by random negative effects like Shadowboxer.

**Comment by ZeroRin** [comment]
http://paste.ubuntu.com/16335398/

**Comment by Patashu** [comment]
According to http://us.battle.net/hearthstone/en/forum/topic/20745755197 Shadowflame might have this bug too.

**Comment by Kybxd** [comment]
Siphon Soul now works correctly.(https://youtu.be/6iD1R0Q0U4Q)

**Comment by Patashu** [comment]
Cool, I'll edit the wiki. Thanks! (maybe test Shadowflame too?)

**Comment by Kybxd** [comment]
Shadowflame still deals AoE damage first.(https://youtu.be/NeRZCfzCiIs)

**Comment by Patashu** [comment]
Thanks, I'll open a new issue for it.
