### ISSUE TITLE
Lock and Load may not work with some spells

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#52]
Some people report that Lock and Load did not give them a spell after casting a spell. However, other people report Lock and Load working fine with the very same spells. So either this is a dud or a non-deterministic bug.

https://www.reddit.com/r/hearthstone/comments/3hn836/lock_n_load_bug/ 

https://www.reddit.com/r/hearthstone/comments/3hlg65/lock_and_load_only_triggers_on_hunter_spells/ 
https://www.reddit.com/r/hearthstone/comments/3hotej/til_coin_doesnt_work_with_lock_n_load/

**Comment by jleclanche** [comment]
With no further reports im going to call this a dud.
