### ISSUE TITLE
Minions killed by Destroy effects don't count towards 'Destroy them All' quest

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#524]
Seen with Naturalize, Shadow Word: Pain and Shadow Word: Death.
- http://us.battle.net/hearthstone/en/forum/topic/20743596158
- https://www.reddit.com/r/hearthstone/comments/4j3bf7/bug_naturalize_not_counting_for_destroy_40/
- http://www.hearthhead.com/quest=50/destroy-them-all#comments:id=2229900
- https://www.reddit.com/r/hearthstone/comments/4j6b6a/naturalize_and_destroy_them_all_quest/

**Comment by Patashu** [comment]
Vanish too? https://www.reddit.com/r/hearthstone/comments/57j7j3/vanish_kills_dont_count_towards_the_destroy_them/

**Comment by troggnostupidhs** [comment]
Tested with Shadow Word Pain, and it doesn't work. You can see the before and after based on the timestamps.

![hearthstone screenshot 12-11-16 10 04 18](https://cloud.githubusercontent.com/assets/22508641/21080941/ac03e192-bf89-11e6-8093-784f3a7e3b6d.png)

![hearthstone screenshot 12-11-16 10 06 40](https://cloud.githubusercontent.com/assets/22508641/21080942/aec190aa-bf89-11e6-9491-404a1459d89d.png)

![hearthstone screenshot 12-11-16 10 07 10](https://cloud.githubusercontent.com/assets/22508641/21080944/b1d89612-bf89-11e6-8e75-79cc986cc27a.png)

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20757535577?page=1#post-2

> Naturalize uses is not counting toward the Destroy them All quest. I've seen a couple topics about it in the last couple years, but there has never been a fix implemented it seems.
Please fix!

**Comment by troggnostupidhs** [comment]
This is fixed.

![hearthstone screenshot 11-11-17 09 50 53](https://user-images.githubusercontent.com/22508641/32690547-930af88e-c6c6-11e7-809e-fd446f34dd8d.png)
![hearthstone screenshot 11-11-17 09 55 10](https://user-images.githubusercontent.com/22508641/32690548-931536a0-c6c6-11e7-9a84-1f210960e9d5.png)
![hearthstone screenshot 11-11-17 09 55 47](https://user-images.githubusercontent.com/22508641/32690549-93222e78-c6c6-11e7-8e43-f3b985b00216.png)
