### ISSUE TITLE
Sacred Trial triggers on minions that have left play

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#526]
Normally triggers related to playing/summoning a minion check that the minion is still in play. However, Sacred Trial does not do this check, allowing it to destroy minions in your hand, for example.
- https://www.reddit.com/r/hearthstone/comments/4j4otj/sacred_trial_sniped_yogg_out_of_my_hand/
- https://www.youtube.com/watch?v=9HRBj180sRU

And in the graveyard:
- https://www.reddit.com/r/hearthstone/comments/4jyftq/yoggsaron_will_activate_sacred_trial_even_if_he/
- https://www.reddit.com/r/hearthstone/comments/4m4817/sacred_trial_will_trigger_on_a_dead_yogg/

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/4jyftq/yoggsaron_will_activate_sacred_trial_even_if_he/ graveyard report

**Comment by Patashu** [comment]
Maybe confirmed in 5.0.1: https://www.reddit.com/r/hearthstone/comments/4m4817/sacred_trial_will_trigger_on_a_dead_yogg/

**Comment by Patashu** [comment]
Confirmed in 5.0.0.13030 for sure:

https://www.reddit.com/r/hearthstone/comments/4mzz5s/if_you_have_sacred_trial_and_enemy_yogg_summons_3/

**Comment by VoidMayonnaise** [comment]
https://youtu.be/BISNy3y36pk
Already fixed in 8.2.2.
