### ISSUE TITLE
Glitched UI after being challenged from your collection

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#528]
After you being challenged from your collection, you will see glitched UI while being transitioned to the friendly challenge screen.

![hearthstone screenshot 05-13-16 12 53 39](https://cloud.githubusercontent.com/assets/11700272/15247717/518c40de-1916-11e6-90da-e6eecc9e8f34.png)

**Comment by troggnostupidhs** [comment]
This is fixed. The UI is fine when being challenged from the Collection Manager.

**Comment by culinko** [comment]
I am actually surprised that they fixed this issue. However, there is now small visual glitch at the bottom of the screen.

![hearthstone screenshot 12-13-16 17 08 05](https://cloud.githubusercontent.com/assets/11700272/21147993/18e75874-c157-11e6-97b4-e20507d6ca4b.png)

**Comment by troggnostupidhs** [comment]
The resolution I test with is smaller. I'll test later to see if I have a similar result. Should we re-open this issue?

**Comment by troggnostupidhs** [comment]
I also see the decklist while it transitions.

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 10-17-17 21 31 40](https://user-images.githubusercontent.com/22508641/31696977-b5b63332-b382-11e7-98f7-283d920077c9.png)
