### ISSUE TITLE
Animation bug with Mukla, Tyrant of the Vale

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#529]
After playing Mukla, Tyrant of the Vale, part of the animation will be obscured by invisible textures. Your opponent will see this animation correctly. This issue might be related to #516.
- https://www.youtube.com/watch?v=7SoALhqaOXU

**Comment by troggnostupidhs** [comment]
This still happens

![hearthstone screenshot 12-18-16 13 49 08](https://cloud.githubusercontent.com/assets/22508641/21295707/fb4fefd0-c528-11e6-9024-bf955a69731b.png)

**Comment by troggnostupidhs** [comment]
This is fixed

![hearthstone screenshot 12-18-16 14 40 49](https://cloud.githubusercontent.com/assets/22508641/21296041/27cd035c-c530-11e6-8658-74d83389fc4d.png)
