### ISSUE TITLE
Boneguard Lieutenant's Inspire effect may fail to trigger if picked up for combat

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#53]
This may be a dud. There are two reports of people picking up Boneguard Lieutenant after using their Hero Power and not getting the Inspire effect.

http://us.battle.net/hearthstone/en/forum/topic/18704211943
http://us.battle.net/hearthstone/en/forum/topic/18724764021

**Comment by culinko** [comment]
Me and PattuX tried to test both reports, but failed. We concluded that it's a dud.
