### ISSUE TITLE
Doomcaller has misleading card text

### ISSUE THREAD

**Issue by edk0** [HearthSim/hs-bugs#533]
[Doomcaller](http://hearthstone.gamepedia.com/Doomcaller) reads

> **Battlecry:** Give your C'Thun +2/+2 (wherever it is). If it's dead, shuffle it into your deck.

implying that it moves an entity like Entomb or Malorne do, but it's really just a resurrect. It creates a new copy of C'Thun and shuffles that into your deck. I suspect (but haven't had a chance to prove yet) that doing the VT+KJ+Entomb setup on C'Thun and then playing Doomcaller will resurrect it, despite the controlling player not owning a C'Thun at all.

**Comment by jleclanche** [comment]
We don't file card text bugs.
