### ISSUE TITLE
Bloodsail Cultist incorrectly uses 'control a Pirate' instead of 'control another Pirate'

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#534]
Because Bloodsail Cultist does not trigger on herself being a Pirate and under your control, this means it should actually read 'another'.

Confirmed as a bug by Ben Brode. https://twitter.com/bdbrode/status/723719628673798146

**Comment by culinko** [comment]
This has been fixed.

**Comment by jleclanche** [comment]
Fixed in 13921
