### ISSUE TITLE
Playing Frost Nova after using Mage hero power on your enemy displays a black box

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#535]
If you play Frost Nova after using Mage hero power on your opponent, a black box will be displayed. Haven't tested this with other hero powers, such as Lesser Heal or Lightning Jolt, but it might be similar. This has started happening in one of the latest Patches.
- https://www.reddit.com/r/hearthstone/comments/4jhprm/graphical_error_i_found_during_tavern_brawl/

![jk3ytaz](https://cloud.githubusercontent.com/assets/11700272/15293674/69cfbf34-1b89-11e6-89a1-8bdd105398ce.png)

**Comment by PattuX** [comment]
Also works the other way around. The black box is over your hero power then.

**Comment by SimFriHS** [comment]
A similar thing has been observed when playing hellfire https://www.twitch.tv/retrogold/v/71046466?t=03h03m25s

**Comment by troggnostupidhs** [comment]
This did not happen for me. Can someone else verify if this is fixed?

**Comment by culinko** [comment]
I doesn't happen to me as well, so it looks like it's fixed.
