### ISSUE TITLE
App crashes while opening packs on iPhone

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#539]
Two reports of random crashing of the Hearthstone app on iPhone when opening packs, happens with all kinds of packs. User mentioned: "100% of the pack-opening crashes I've gotten, after placing the pack in the slot, it starts to open, and at the exact moment of it bursting open, with the noise, it crashes me out of the app." The temporary workaround is to rotate the phone upright while opening packs, listed in the first thread.
- https://www.reddit.com/r/hearthstone/comments/4hm9bl/ios_game_crash_when_opening_packs_heres_a/ (5 crashes in 40 packs, iPhone 5s)
- https://www.reddit.com/r/hearthstone/comments/4jxqxv/card_opening_crash_still_not_fixed/

Another report, but the reporter confirmed that it's been fixed for him since. 
- https://www.reddit.com/r/hearthstone/comments/4gm55l/ios_crashes_almost_every_pack_i_open/

**Comment by troggnostupidhs** [comment]
This should probably be closed. Searching doesn't produce anything significant.
