### ISSUE TITLE
Fandral Staghelm + Spellpower +1 = 5 damage wrath

### ISSUE THREAD

**Issue by Raeyn** [HearthSim/hs-bugs#540]
With an Azure Drake on board, providing spellpower +1, and a Fandral Staghelm, wrath only does 5 damage and draws a card, when it should deal 6 damage and draw a card.

**Comment by Patashu** [comment]
This is the intended interaction. Fandral Staghelm does not perform the two effects sequentially - he performs a third effect, that logically combines the two previous effects. Since damage is dealt only once, spell damage bonuses are only applied once.
