### ISSUE TITLE
Crafting/disenchanting UI glitch

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#544]
Crafting or disenchanting a card followed by quickly clicking in the background will make the crafting UI to remain displayed. You need to restart the client in order to fix this bug.
- https://www.youtube.com/watch?v=ZSmIAeyBTig
- https://www.youtube.com/watch?v=PhgO5ZAWVoI&t=3m54s

**Comment by troggnostupidhs** [comment]
This might be fixed. I can't reproduce it when Disenchanting.

**Comment by culinko** [comment]
I couldn't reproduce it myself at the time it was bugged, though. Not sure what exact timing is needed.

**Comment by troggnostupidhs** [comment]
I am going to close this. We can reopen it if there are additional reports.
