### ISSUE TITLE
App crashes if chatting while a game ends on iPhone/iPad

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#545]
- http://us.battle.net/hearthstone/en/forum/topic/20744894587

**Comment by culinko** [comment]
Maybe this is #447?

**Comment by troggnostupidhs** [comment]
Haven't seen reports in a while. 

Arcca did some testing
> Tho I did manage to check so far, as to if the bug is there and easily reproducible, it has to be with incoming messages.
Just have to have another person for that
And I got someone to help me test receiving messages - was not able to crash the game.
