### ISSUE TITLE
Destroying Nozdormu at the start of your turn against AI will cause a hang

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#547]
If you play against AI and you kill Nozdormu at the start of your turn (with effects such as Doomsayer or Corruption), your client will hang. This hang does not happen against another human opponent.
- http://us.battle.net/hearthstone/en/forum/topic/20042985661

![hearthstone screenshot 06-02-16 20 02 22](https://cloud.githubusercontent.com/assets/11700272/15756076/e1716140-28ff-11e6-9e39-394c0fb67185.png)

![hearthstone screenshot 06-02-16 20 13 50](https://cloud.githubusercontent.com/assets/11700272/15756077/e17dc840-28ff-11e6-906a-48c96d68013a.png)

**Comment by Patashu** [comment]
Is it confirmed to be AI only?

**Comment by PattuX** [comment]
Yes, culinko and me confirmed it.

**Comment by culinko** [comment]
Confirmed in 6.0: https://www.reddit.com/r/hearthstone/comments/4zlcjb/a_strange_glitch_against_the_curator/.

**Comment by troggnostupidhs** [comment]
Fixed. Does not happen against The Innkeeper or in Adventure mode.

Deck
AAEBAf0EBJsD7QXWEdTOAg1NigH7AbQCuwKLA6sEywTmBJYFuQajtgKWxwIA
