### ISSUE TITLE
Season Rewards softlock

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#548]
If you spam click on the season rewards 'next' button, it may softlock like so:

![image](https://cloud.githubusercontent.com/assets/666597/15797008/7a1dc55c-2a4d-11e6-8f59-0c09f4037f94.png)

Strangely, taking a screenshot fixed it and allowed me to continue progressing, but the 'Next' button never unlit.

![image](https://cloud.githubusercontent.com/assets/666597/15797011/86fc2d36-2a4d-11e6-9ed9-acbf2d150614.png)

**Comment by Patashu** [comment]
Another report: http://us.battle.net/hearthstone/en/forum/topic/20745044646

**Comment by culinko** [comment]
You are supposed to click the Chest, not the 'Next' button, which is disabled. It should probably be dimmed or even hidden, though. Anyway, there is no soft-lock.

**Comment by troggnostupidhs** [comment]
Even though this was never really a bug, it is now 'fixed' as of 11.1.1. On mobile, there is no next button on the chest screen and the chest is highlighted. And on PC, I think you can just keep pressing the next button (I will confirm later).
