### ISSUE TITLE
Fandral Staghelm does not show added Deathrattles

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#549]
Tested with Soul of the Forest.

![image](https://cloud.githubusercontent.com/assets/235410/15805245/f9bfef30-2b2c-11e6-8587-c0b454c0b367.png)
![image](https://cloud.githubusercontent.com/assets/235410/15805247/02d96682-2b2d-11e6-9c0c-c01274edcc5d.png)
![image](https://cloud.githubusercontent.com/assets/235410/15805249/0af37024-2b2d-11e6-8a3f-34420e09e47b.png)

**Comment by Patashu** [comment]
Probably related to https://github.com/HearthSim/hs-bugs/issues/543

**Comment by troggnostupidhs** [comment]
Fixed

Deck
AAEBAZICBO0FrqsCzbsCmdMCDekB+wG0Av0C9wO0BbkGiwj0EeoWl2ifwAKkwgIA

![img000](https://user-images.githubusercontent.com/22508641/31843493-52cb6fe4-b5c1-11e7-86b2-44b1ab3dd63c.png)
