### ISSUE TITLE
Gorehowl/Misdirection/Explosive Trap bug

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#55]
If you attack with Gorehowl into an opponent's hero, get redirected by Misdirection into one of your minions that dies to Explosive Trap, your attack gets cancelled and you can attack that turn again. If you attack again into opponent's hero or his minions, Gorehowl's attack or durability will not reduce. This is a bug. If you attack again next turn, the attack or durability will reduce properly.
- http://us.battle.net/hearthstone/en/forum/topic/11306270971
- https://gist.github.com/culinko/9abb1e02dfef9bb8a507 Misdirection + Gorehowl
- https://gist.github.com/culinko/7738381a3cd0205bdf4f Misdirection + Explosive + Gorehowl

![hearthstone screenshot 01-17-16 05 16 25](https://cloud.githubusercontent.com/assets/11700272/12375956/813e8b5e-bcda-11e5-835b-6bfe404e3118.png)

**Comment by Patashu** [comment]
Culinko tested this in patch 2.7 and created a log of it. I don't know where it is ATM.

**Comment by Patashu** [comment]
Gorehowl/Misdirection/Explosive setup confirmed in 4.1. Xinhuan was the dominant player but Gorehowl still triggered after Misdirection/Explosive, so Gorehowl triggers on a later event than Misdirection/Explosive do. Xinhuan attacked face twice after doing the bug, the first attack had no durability or attack lost, the second attack worked as normal. Video uploading later.

https://gist.github.com/Patashu/5faf68f8d209c473375b

**Comment by Patashu** [comment]
Bug does not occur with Gladiator's Longbow. Tested by Culinko.

**Comment by Patashu** [comment]
Gorehowl having "Bloodlust" attached, and thus being Immune, prevents durability damage from enemy Bloodsail Corsair. Tested by Culinko.

* http://imgur.com/WUn0MTe
* https://gist.github.com/culinko/b7559f2938017be684de

**Comment by culinko** [comment]
We now have a video of the interaction: https://www.youtube.com/watch?v=pTyouegZ7Wc.

**Comment by VoidMayonnaise** [comment]
https://youtu.be/y3WrJR3sKsU
Already fixed. A coooooooooool bug has gone away...
We can see that the Gorehowl appeared light spots for a second, means that the "Bloodlust" enchantment was attached then removed.
