### ISSUE TITLE
Game becomes blurry after pressing "Play" and "Quests"

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#550]
Press on "Play" wait half a second and press on "Quests". Tested on the Galaxy Note 5 and iPhone SE. 
- http://us.battle.net/hearthstone/en/forum/topic/20744404468

**Comment by troggnostupidhs** [comment]
This still happens. Tested on a Galaxy S5.

**Comment by troggnostupidhs** [comment]
When this happens, the back button to return to the main menu will not work. Going to 'My Collection' and then returning to the deck selection screen will make the back button work again.

**Comment by troggnostupidhs** [comment]
Steps to remove the blur:

1. Return to main menu
    1.  If you are unable to return
        1. Go to 'My Collection'
        1. Return to the deck selection menu
        1. Return to the main menu
1. Do the following
    1. Method 1
        1. Open the Quest screen
        1. Lock your phone's screen
        1. Use the back button in the UI
        1. Use your phone's hardware back button
1. If the previous step does not work, try
    1. Method 2
        1. Open the Quest screen
        1. Use the hardware back button twice
    1. Method 3
        1. Open the Quest screen
        1. Use the UI back button
        1. Use the hardware back button
    1. Method 4
        1. Repeating Method 2 or 3 several times in a row
    1. Wait 1-3 minutes and try the methods again

**Comment by troggnostupidhs** [comment]
This is fixed for me. The quest screen can still pop up, but it will automatically be closed and everything works.
