### ISSUE TITLE
Crafting a missing card for a deck recipe won't update it

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#551]
The deck recipe won't update after you craft a card you were missing. You have to grab the darkened card out of the recipe and add it again for it to update. Closing and opening the deck won't update it either, only auto-filling the missing cards will update it.
- http://us.battle.net/hearthstone/en/forum/topic/20745244773

**Comment by troggnostupidhs** [comment]
Worked both ways.

![img002](https://user-images.githubusercontent.com/22508641/31843725-9ec17af0-b5c2-11e7-94d8-69b77c11ff6d.png)
![img003](https://user-images.githubusercontent.com/22508641/31843726-9ecb7730-b5c2-11e7-9e67-a08cc7538dce.png)
![img004](https://user-images.githubusercontent.com/22508641/31843727-9ed3b1ca-b5c2-11e7-96e6-aa9916bee0d1.png)
![img005](https://user-images.githubusercontent.com/22508641/31843728-9ee34cf2-b5c2-11e7-8c6b-5c03ab471cc6.png)
![img006](https://user-images.githubusercontent.com/22508641/31843729-9ef2835c-b5c2-11e7-9994-ee976f8bdbda.png)
![img007](https://user-images.githubusercontent.com/22508641/31843730-9f0318b6-b5c2-11e7-9a88-b7372cbea132.png)
