### ISSUE TITLE
Master of Disguise on a permanently stealthed minion will unstealth it at the start of your turn

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#552]
This is inconsistent with how all other temporary Stealth effects work (see https://github.com/HearthSim/hs-bugs/issues/383 )
- http://us.battle.net/hearthstone/en/forum/topic/20745164963

**Comment by troggnostupidhs** [comment]
This is fixed.

![hearthstone screenshot 06-03-17 11 40 40](https://cloud.githubusercontent.com/assets/22508641/26754929/a695085c-4851-11e7-8ea7-2b55429dfb43.png)

![hearthstone screenshot 06-03-17 11 40 46](https://cloud.githubusercontent.com/assets/22508641/26754930/a8a79db2-4851-11e7-9e07-4be0b64bb8aa.png)
