### ISSUE TITLE
Deleting a Tavern Brawl deck from the top will leave your UI glitched

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#556]
Deleting a Tavern Brawl deck from the top drop-down after hovering over the deck name will cause the UI to remain glitched. The only button that is able to be clicked is the empty button on the top which will open the class selection. However, even after you create a new deck, the "Back" button on the bottom will still remain unresponsive so you can't return to main menu anymore (however you are still able to queue into a Brawl game). This bug only happens if you are on the screen where you can click the "Brawl" button to queue up. If you have an incomplete deck, or you press the "Edit" button first or you click the "Delete" button on the bottom, the UI will transition properly to the class selection and you will be able to click "Back" to return to the main menu properly.
- https://www.reddit.com/r/hearthstone/comments/4odh1f/bugandroid/

**Comment by troggnostupidhs** [comment]
I'm not sure how to reproduce this, so I'm not sure if it's fixed or not. On the screen with the Brawl button, there's only an 'Edit Deck' button. There's no way to hover over the deck name or delete the deck without first using 'Edit Deck'. Deleting the deck after using edit seems to work fine. Tested with a Galaxy S5.

**Comment by culinko** [comment]
Are you sure you're on the mobile UI and not the tablet UI? As far as I remember, the bug was when you were hovering over the deck name of your Brawl deck and then you clicked the "Delete" button from the drop-down.

**Comment by troggnostupidhs** [comment]
I'm testing with the mobile UI. From the screen below, the deck doesn't appear unless I use the 'Edit Deck' button. I can only find one delete button from that screen, by clicking the hero. That method of deleting seems fine for me.

![screenshot_2016-12-07-15-16-59](https://cloud.githubusercontent.com/assets/22508641/20984980/763ce4f6-bc90-11e6-80e0-3c0298453d5b.png)

**Comment by riQQ** [comment]
I can confirm @troggnostupidhs' observations. After deleting I'm returned to the class selection page automatically.
