### ISSUE TITLE
Sometimes when you grab a card, you will grab the one left of it instead

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#559]
Sometimes when you mouse over a card, the card one left to it will be shown big for one frame. If this happens, when you click the card in preparation to play it, you will instead grab the one left of it and play that.

Animated examples:
- http://imgur.com/CHA6RrT from https://www.reddit.com/r/hearthstone/comments/4r7t6f/kibler_hearthstone_nzoth_priest_wild_win_streak/
- http://imgur.com/lTdcBjq from https://www.reddit.com/r/hearthstone/comments/4qpkj0/day9_with_the_sickest_of_plays/d4v1jvd

A second variant has you grab the card that is one to the right. This variant does not show the other card big for one frame.
- http://imgur.com/6UWyTJZ from https://www.youtube.com/watch?v=JwsmFVK7uGs

This is believed to be caused by the fix to a very old bug, where the card would be inaccessibly placed under another card in your hand: https://youtu.be/6xU1hIESnS0

Acked by devs here: https://twitter.com/culinko/status/750261497956278272.

**Comment by Patashu** [comment]
Potentially fixed in http://us.battle.net/forums/en/hearthstone/topic/20749867298 ?

"Resolved an issue where an intended card played from the hand would occasionally be swapped with an adjacent card."

**Comment by troggnostupidhs** [comment]
There haven't been reports of this. It should be fixed.
