### ISSUE TITLE
Triggering Malorne's Deathrattle with Baron Rivendare makes two Malornes

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#56]
Community Manager Whirthun tweeted that if a Malorne dies with Baron Rivendare in play, only 1 copy of Malorne gets shuffled into the deck (twice). However, actual playtesting reveals that 2 copies of Malorne actually gets shuffled into the deck. It is unclear whether this is a bug at the moment. Community Manager Zeriyah has replied in the same thread that this is being looked into. 

The technical reason why this occurs is that Malorne's Deathrattle is coded as follows: Move the original Malorne to the SETASIDE Zone, generate a new Malorne and place it in the DECK Zone. Repeating this twice makes two new Malornes for your deck.

https://twitter.com/CM_Whirthun/status/539919240933806080

http://www.reddit.com/r/hearthstone/comments/2oumjj/malorne_confirmed_to_work_with_both_kelthuzad_and/

**Comment by Patashu** [comment]
Note that The Skeleton Knight and Anub'arak may have this interaction also.

**Comment by Patashu** [comment]
A related bug(?) is that Malorne's Deathrattle prevents Added Deathrattles, such as Ancestral Spirit, from firing:

http://us.battle.net/hearthstone/en/forum/topic/18695102861

**Comment by Patashu** [comment]
culinko tested in 4.0 that Malorne now goes to Deck with his old ID, rather than going to setaside and making a new Malorne. So this bug is probably fixed.

(Note that Malorne STILL doesn't trigger added DRs in his new state. Anub'arak and The Skeleton Knight do, with buggy animations in the case of Soul of the Forest.)

**Comment by culinko** [comment]
Tested Malorne + Baron Rivendare with SimFri in 4.1, only one Malorne is being shuffled into the deck (twice). So this bug was probably fixed in some patch up to 4.0.

Log of the interaction: https://gist.github.com/culinko/943899dd96fd4ca2657a.
