### ISSUE TITLE
Mobile: Certain cards are not truncated in the deck list despite having a long name

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#564]
Long card names get truncated, however this not apply for Houndmaster, Flamewaker, Preparation and Shadowstep which displays its name over 2 rows instead.
- https://www.reddit.com/r/hearthstone/comments/4skeff/i_think_i_found_a_bug/
- https://www.reddit.com/r/hearthstone/comments/4sp2es/bugs_and_known_issues_in_patch_52/d5bl8dy

![ymjuaca](https://cloud.githubusercontent.com/assets/11700272/16790150/bc848dc0-48b3-11e6-8d0f-dee5546ae558.jpg)

![xemrdyy](https://cloud.githubusercontent.com/assets/11700272/17391646/1ff7226c-5a18-11e6-987a-eda84253011e.jpg)

**Comment by troggnostupidhs** [comment]
Houndmaster, Flamewaker, Preparation and Shadowstep are all truncated correctly on mobile. Tested with a Galaxy S5.

**Comment by Xinhuan** [comment]
Also the ones that didn't truncate (and instead wrapped to 2 lines) are all "single word" card names.

**Comment by culinko** [comment]
@troggnostupidhs just to be sure, since Galaxy S5 has a 5.1" screen, does it show a mobile UI or a tablet UI? Mobile UI looks like this: http://phandroid.s3.amazonaws.com/wp-content/uploads/2015/03/hearthstone-phone-1-640x357.jpg and https://bnetcmsus-a.akamaihd.net/cms/gallery/G2OKRU48VRL71428959630793.jpg. Tablet UI looks similar to a desktop UI.

**Comment by riQQ** [comment]
Houndmaster is correctly truncated on a Z1 compact (4,3" screen).

**Comment by troggnostupidhs** [comment]
@culinko I believe I have the mobile UI

![screenshot_2016-12-07-16-39-25](https://cloud.githubusercontent.com/assets/22508641/20987850/359ea3ba-bc9c-11e6-99be-88a1c320c795.png)

**Comment by culinko** [comment]
Yup, that's the mobile UI. Thanks for the feedback!
