### ISSUE TITLE
Innervate played by your opponent has no sound effect

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#565]
If your opponent plays Innervate, it has no sound effect.
- https://www.reddit.com/r/hearthstone/comments/4sk3f2/golden_innervate_bug/

**Comment by troggnostupidhs** [comment]
Innervate has a sound effect for me when my opponent plays it.

**Comment by troggnostupidhs** [comment]
Forgot to mention, I tested it with the golden and non-golden versions, since the post mentions golden Innervates.
