### ISSUE TITLE
Players in Arena can appear as UNKNOWN

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#566]
The players in Arena can appear as UNKNOWN. This has probably something to do with the fix mentioned in the patch notes.

* https://www.reddit.com/r/hearthstone/comments/4sypnr/i_think_blizzard_is_trolling_me/
* https://www.reddit.com/r/hearthstone/comments/4sk815/bug_arena_opponents_listed_as_unknown_without_any/
* https://www.reddit.com/r/hearthstone/comments/4sk6km/possible_bug_all_my_arena_opponents_was_unknown/
* https://www.reddit.com/r/hearthstone/comments/4skja6/why_are_all_my_opponents_unknown/
* https://www.reddit.com/r/hearthstone/comments/4sksl8/unknown/
* https://www.reddit.com/r/hearthstone/comments/4sj0cw/arena_player_name_unknown/
* https://www.reddit.com/r/hearthstone/comments/4sj0u4/unknown_players_not_anymore_almost/
* https://www.reddit.com/r/hearthstone/comments/4sj4sk/does_anyone_else_get_all_the_opponents_as_unknown/
* https://www.reddit.com/r/hearthstone/comments/4sjrxv/cannot_see_opponents_name_in_arena_on_mobile/
* https://www.reddit.com/r/hearthstone/comments/4sljjf/players_should_no_longer_appear_as_unknown_after/
* https://www.reddit.com/r/hearthstone/comments/4smaq4/all_opponents_unknown_in_arena_on_eu/
* https://www.reddit.com/r/hearthstone/comments/4smxcz/a_man_has_no_name/
* https://www.reddit.com/r/hearthstone/comments/4sn79f/after_new_patch_all_arena_opponents_are_showing/
* https://www.reddit.com/r/hearthstone/comments/4sn9j6/queuing_into_the_unknown/
* https://www.reddit.com/r/hearthstone/comments/4snxr5/why_is_the_guy_im_against_named_as_unkown/

**Comment by culinko** [comment]
Apparently it can also happen in ranked? https://www.reddit.com/r/hearthstone/comments/4t9abt/the_arena_problem_has_spread_to_ranked/

**Comment by culinko** [comment]
Yep, it can happen in ranked, but very rarely: https://www.reddit.com/r/hearthstone/comments/4vutke/unknown_bug_now_also_in_ranked_mode/.

**Comment by NightKev** [comment]
This has been fixed.

**Comment by culinko** [comment]
I encountered this issue after reconnecting before the mulligan in Tavern Brawl. Do you want me to reopen this issue or create a new one? Since this one was related to Arena.

![unknown after reconnecting](https://cloud.githubusercontent.com/assets/11700272/17793614/f49e481a-65a8-11e6-8194-672ba52668ea.png)

**Comment by jleclanche** [comment]
That's just flakiness, nothing to do with this issue.
