### ISSUE TITLE
iPhone SE got changed to use the iPad UI

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#567]
For some reason the UI in iPhone SE got changed into the tablet UI and since the phone is small, it's really hard to use the game properly. This change happened with the recent patch.

* https://www.reddit.com/r/hearthstone/comments/4sjlvz/new_patch_on_mobile/
* https://www.reddit.com/r/hearthstone/comments/4sjaaf/new_patch_hard_to_see_iphone_se/
* https://www.reddit.com/r/hearthstone/comments/4slejg/mobile_phone_ui_after_patch/
* https://www.reddit.com/r/hearthstone/comments/4sme1s/iphone_se_ui_bug_pcui/
* https://www.reddit.com/r/hearthstone/comments/4sok96/ipad_display_is_being_used_on_some_iphones/

**Comment by interro-bang** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/19805843/16830214/7b50cb74-4995-11e6-823c-94aec47cd051.jpg)

**Comment by Xinhuan** [comment]
Not an error by Apple. As an iOS app developer, you can easily write your own code to query what device your code is running on.

In Unity, this is an enum you can query for: UnityEngine.iOS.Device.generation
https://docs.unity3d.com/ScriptReference/iOS.Device-generation.html
https://docs.unity3d.com/ScriptReference/iOS.DeviceGeneration.html
and the return value tells you exactly which Apple device you are running on (of the 30+ of them), and internally you will know what the screen resolution is based on the device. Or you can get it by querying UnityEngine.Screen.Resolution.

**Comment by culinko** [comment]
This issue was fixed in 5.2.2.13807.
