### ISSUE TITLE
[Mac] Disappearing menu bar

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#568]
The menu bar is now disappearing after the recent patch. Blizzard QA is aware of this bug and will hopefully fix it in the recent future.
- https://www.reddit.com/r/hearthstone/comments/4sie3i/help_mac_patch_52_ui_bug/
- https://www.reddit.com/r/hearthstone/comments/4skgu3/todays_update_messed_with_my_settings/
- https://www.reddit.com/r/hearthstone/comments/4skv9a/menubar_on_mac_disappears_with_new_update/
- https://www.reddit.com/r/hearthstone/comments/4so5yk/mac_client_framework_bug/

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20757636972

I was going to say that this had to be fixed, but apparently it is back.

**Comment by troggnostupidhs** [comment]
Reported as fixed.

https://us.battle.net/forums/en/hearthstone/topic/20757636972
