### ISSUE TITLE
Mac: Unreadable font

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#569]
The recent patch caused the font to be unreadable on Mac. Possible workaround might be to change the quality settings to a different value and then back.

![y5bjaq5](https://cloud.githubusercontent.com/assets/11700272/16814961/60a1de7e-4938-11e6-87f6-3299a051984e.jpg)
- https://www.reddit.com/r/hearthstone/comments/4sjilf/font_bug_on_mac/
- https://www.reddit.com/r/hearthstone/comments/4sjy1t/weird_graphical_glitch/
- https://www.reddit.com/r/hearthstone/comments/4sir54/so_after_update_i_get_26_min_queue_estimation_and/
- https://www.reddit.com/r/hearthstone/comments/4smuhl/massive_bug_on_mac_after_new_patch/

**Comment by culinko** [comment]
Is this related? https://www.reddit.com/r/hearthstone/comments/4sm7ii/bug_mac_has_missing_letters_in_tutorial/

**Comment by culinko** [comment]
Still present in 6.0? https://www.reddit.com/r/hearthstone/comments/4zx2hp/anyone_seen_this_bug_before/

**Comment by troggnostupidhs** [comment]
I don't see any recent reports for this. It can be reopened if needed.
