### ISSUE TITLE
Non-English version of the game will have the English game sounds

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#570]
After the recent patch, the Non-English versions of the game now play English game sounds.
- https://www.reddit.com/r/hearthstone/comments/4siq7u/new_update_bugged_voices_dub/
- https://www.reddit.com/r/hearthstone/comments/4sjwni/after_the_patch_every_audio_in_the_game_changed/
- https://www.reddit.com/r/hearthstone/comments/4sjnq7/this_patch_has_broken_lote/
- https://www.reddit.com/r/hearthstone/comments/4sj1wz/language_bug_post_patch/
- https://www.reddit.com/r/hearthstone/comments/4slqpw/bug_in_russian_localization/

**Comment by troggnostupidhs** [comment]
This should be fixed. There haven't been reports of it and I tested it by playing a game in 'Español (EU)'.
