### ISSUE TITLE
Mac/iOS: The Year of the Kraken tutorial shown on start, then crash after switching game mode

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#571]
After starting up the game, you are introduced The Year of the Kraken tutorial and if you switch game mode, the client crashes. A workaround to make the intro disappear is to log into PC version and click through the intro there.
- https://www.reddit.com/r/hearthstone/comments/4skwp9/game_crashes_when_try_switching_to_wild_mode/
- https://www.reddit.com/r/hearthstone/comments/4sl28a/patch_forces_me_to_replay_the_year_of_the_kraken/
- https://www.reddit.com/r/hearthstone/comments/4sm9qu/unplayable_on_mobile/
- https://www.reddit.com/r/hearthstone/comments/4smf3i/year_of_the_kraken_at_every_restart/

**Comment by troggnostupidhs** [comment]
It's no longer The Year of the Kraken, can this be closed?
