### ISSUE TITLE
Mobile: Morgl the Oracle's hero power is not animated

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#572]
Even though his hero power is animated in the preview and in the game lobby, it's not animated in the actual game. Other Alternate heroes have their hero powers animated in game as well. Morgl himself is animated in game too. This bug is now fixed on PC and now happens only on mobile platforms.
* https://www.reddit.com/r/hearthstone/comments/4skuts/morgl_hero_power_not_glowing/
* https://www.reddit.com/r/hearthstone/comments/4sit5i/morgl_hero_power_not_animated/

![r38mvm5](https://cloud.githubusercontent.com/assets/11700272/16815356/d036ec92-4939-11e6-9eb8-27539cf42369.png)

![cd5seq4](https://cloud.githubusercontent.com/assets/11700272/16815359/d204ef9c-4939-11e6-8d20-55b98c45ca91.png)

**Comment by culinko** [comment]
Fixed in 5.2.0.13714.

**Comment by culinko** [comment]
It's still not animated on tablet and phone UI (probably because they haven't been updated since July 12).

**Comment by jleclanche** [comment]
If it's fixed in 13714 then it's fixed on mobile as well. Doesn't matter that they haven't updated.
