### ISSUE TITLE
Ice Barrier belongs to Proposed Attack Event now

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#581]
https://www.youtube.com/watch?v=ZqHM5H3VW8Y
https://www.youtube.com/watch?v=LKFABBGwFhQ

**Comment by Patashu** [comment]
Thanks for the report, I will document this later.

**Comment by Patashu** [comment]
Done (I only changed Advanced rulebook since it wasn't anywhere else).

**Comment by jleclanche** [comment]
This isn't a bug unless it's specifically acknowledged as one.
