### ISSUE TITLE
If you have a full hand when Shadowcaster's Battlecry resolves, the target minion shrinks

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#585]
![image](https://cloud.githubusercontent.com/assets/666597/16859155/e88b5710-4a6f-11e6-9248-0934c8461cd3.png)
- https://www.reddit.com/r/hearthstone/comments/4ss0lz/bug_my_creep_turned_small_after_a_spell/
- https://www.reddit.com/r/hearthstone/comments/4srjdy/new_tavern_brawl_has_some_interesting_spells/

**Comment by culinko** [comment]
Report in current patch: https://www.reddit.com/r/hearthstone/comments/4w3o1o/tavern_brawl_i_managed_to_reach_the_turn_limit/.

**Comment by troggnostupidhs** [comment]
Is this fixed?

https://www.youtube.com/watch?v=AzewEyndSNA

**Comment by troggnostupidhs** [comment]
Looks like it is fixed

![img001](https://user-images.githubusercontent.com/22508641/35256816-b7834b0e-ffc3-11e7-9e09-3fb118171e4b.png)
![img002](https://user-images.githubusercontent.com/22508641/35256817-b78c5bea-ffc3-11e7-8c95-a1b3115dd8e2.png)
![img003](https://user-images.githubusercontent.com/22508641/35256818-b7958ddc-ffc3-11e7-9d6b-e853a1ad334b.png)
