### ISSUE TITLE
Hovering over an exhausted Totemic Slam will not show the hero power tooltip

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#586]
If you hover over an exhausted Totemic Slam, the tool-tip will not be displayed. This does not happen on any other hero power.

![hearthstone screenshot 07-15-16 03 04 34](https://cloud.githubusercontent.com/assets/11700272/16860509/1c121e20-4a39-11e6-8085-12f1aedf5ce7.png)

For example The Silver Hand correctly displays the tool-tip:
![hearthstone screenshot 07-15-16 03 01 44](https://cloud.githubusercontent.com/assets/11700272/16860510/1e92323e-4a39-11e6-8286-2b4d79823848.png)

**Comment by troggnostupidhs** [comment]
This is fixed.

![hearthstone screenshot 12-12-16 20 48 35](https://cloud.githubusercontent.com/assets/22508641/21124412/e33854a8-c0ac-11e6-9907-71006e6e39ab.png)
