### ISSUE TITLE
Some of the coins on the Excavation Site battleground can stay bugged mid-air

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#587]
If you flip the coins on the Excavation Site battleground, some of them won't go into the chasm and can stay bugged floating mid-air, shrinking until they disappear.
- https://www.reddit.com/r/hearthstone/comments/4sp2es/bugs_and_known_issues_in_patch_52/d5bzggz
- https://www.reddit.com/r/hearthstone/comments/4t3i2j/literally_unplayable/ (including a gif)

I found and old video showing the correct behavior before it was bugged:
- https://www.youtube.com/watch?v=oh9fL9Ld04U

**Comment by troggnostupidhs** [comment]
This seems like it is fixed. I tested it in Adventure mode.
