### ISSUE TITLE
Reappearing fuse bug

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#588]
If you end your turn after the fuse already started burning, it will replay the hero message and show the fuse again for a brief moment. This bug started in Patch 5.2.
- https://www.reddit.com/r/hearthstone/comments/4sp2es/bugs_and_known_issues_in_patch_52/d5c5y3m

**Comment by troggnostupidhs** [comment]
I think this still happens, here's a clip

https://www.youtube.com/watch?v=Es8zu2WBPUI&t=1369

**Comment by troggnostupidhs** [comment]
https://youtu.be/pcZp3iqDucQ?t=427

**Comment by troggnostupidhs** [comment]
https://youtu.be/c0jqeDSJlmY?t=443

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7gqg9m/double_rope_bug_is_still_happening_for_about_2/

**Comment by troggnostupidhs** [comment]
This is possibly fixed

**Comment by troggnostupidhs** [comment]
https://youtu.be/ckxjJxXsmCg?t=887

https://youtu.be/ckxjJxXsmCg?t=1184

https://youtu.be/ckxjJxXsmCg?t=2122

https://youtu.be/ckxjJxXsmCg?t=3330

**Comment by troggnostupidhs** [comment]
Not sure of the milestone for when this was fixed. I don't see anything in the patch notes.
