### ISSUE TITLE
Golden Thrall is displayed as regular in the game

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#590]
If you have golden Thrall, he will be displayed as a regular hero in the game. He is correctly golden in the game lobby. Other heroes (including Morgl) work correctly. According to the reporter, every mode except Tavern Brawl doesn't show golden Thrall, and he is playing on Windows 10. Album here: http://imgur.com/a/kChni.

![tcenobu](https://cloud.githubusercontent.com/assets/11700272/16892145/fded442a-4b09-11e6-84a8-67570dd547f2.jpg)

![wchnum8](https://cloud.githubusercontent.com/assets/11700272/16892146/fdee9dac-4b09-11e6-9a02-58c560f1e9df.jpg)

**Comment by culinko** [comment]
Also reported with Rexxar: https://www.reddit.com/r/hearthstone/comments/4t4j8s/lost_golden_hunter/. However, I was able to find both golden Thrall and golden Rexxar in ranked on Twitch today, so these might be isolated cases.

**Comment by troggnostupidhs** [comment]
Thrall and Rexxar are golden for me in Play mode.

**Comment by culinko** [comment]
Probably fixed in Patch 6.2.0.15181: https://us.battle.net/forums/en/hearthstone/topic/20749867298.

> Golden Heroes will now appear golden in game again for all players.
