### ISSUE TITLE
Karazhan Adventure bosses skip their turn after you play a damage deathrattle minion

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#597]
Heroic Silverware Golem skips its turn if you have an AoE damage deathrattle minion (such as Explosive Sheep or Unstable Ghoul) or a similar minion on your side of the board.

* https://www.youtube.com/watch?v=AKPtq-fypzY
* https://www.reddit.com/r/hearthstone/comments/4xchyq/heroic_silverware_golem_bug/
* https://www.reddit.com/r/hearthstone/comments/4xay9b/possible_bug_on_silverware_golem/
* https://www.reddit.com/r/hearthstone/comments/4xf5d8/small_bug_with_the_silverware_golem/
* https://www.reddit.com/r/hearthstone/comments/4xa4in/heroic_silverware_golem_bug/

**Comment by culinko** [comment]
Also happens with Big Bad Wolf (presumably other Karazhan bosses as well): 
* https://www.reddit.com/r/hearthstone/comments/4ykzp0/if_you_use_abomination_in_solo_adventures_ai/
* https://www.reddit.com/r/hearthstone/comments/4yi0sv/the_ai_bug_brings_easy_heroic_victories/

**Comment by Patashu** [comment]
Hotfixed

http://us.battle.net/hearthstone/en/forum/topic/13840764128?page=1#19
