### ISSUE TITLE
AI won't attack if you have taunt + Kel'Thuzad

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#6]
If the player controls a Kel'Thuzad and has any Taunt minions, the AI will stop attacking with its minions, mistakenly thinking that any Taunt minions it kills will just resurrect at the end of turn. This can be used to defeat most AI and Adventure bosses.
- https://twitter.com/bdbrode/status/596878031999774720

**Comment by culinko** [comment]
Despite this reddit thread: https://www.reddit.com/r/hearthstone/comments/4xtwop/rip_kelthuzad_and_goldshire_footman_a_tale_of_two/, I just tested it against basic Priest AI and the bug is still present.

**Comment by jleclanche** [comment]
It sounds like the original issue was fixed. The AI being dumb is a different issue tbh.

**Comment by jleclanche** [comment]
Closing with the 7.0 AI improvements.
