### ISSUE TITLE
Meizu pro 5 bad graphic optimization

### ISSUE THREAD

**Issue by kamaezz** [HearthSim/hs-bugs#604]
My phone has Samsung Exynos 7420 and Mali-T760 MP8 + 4Gb RAM. Android 5.1
After Hearthstone updated to 5.2.13557, playing it became impossible: any animation is slow, phone heats up more than before. First 1-2 rounds after starting HS all is fine, but ever next turn it became worse and worse, with crash at the end.

**Comment by kamaezz** [comment]
I think other meizu pro 5 or samsung galaxy s6 whave same problems

**Comment by troggnostupidhs** [comment]
Can this be closed?

**Comment by kamaezz** [comment]
Yes, I solved that problem by reflashing the firmware for my phone.

17 нояб. 2017 г. 8:17 пользователь "troggnostupidhs" <
notifications@github.com> написал:
