### ISSUE TITLE
Copy effects don't copy Moat Lurker's Deathrattle properly, but Unearthed Raptor does

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#605]
We should expect both of them to work or neither of them to work, but instead only Unearthed Raptor does.

* https://www.youtube.com/watch?v=gWKZPOyQJnE

**Comment by culinko** [comment]
Also happens with Herald Volazj: https://www.reddit.com/r/hearthstone/comments/4yy93v/moat_lurker_herald_volazj_possible_combo_bug/.

**Comment by PattuX** [comment]
Fixed for Mirror Entity and Moat Lurker. Volajz is technically untested, but very likely fixed, too.
