### ISSUE TITLE
Powermace can't buff mortally wounded minions but Avenge/Dark Cultist can

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#61]
If Powermace's trigger is in the same Phase as all your mechs being reduced to 0 or less Health, Powermace will not trigger on them.

* https://www.youtube.com/watch?v=IUMQ7MAilJ0&t=1m56s

This is in contradiction to how Avenge, Anubisath Sentinel and Dark Cultist work - they can buff 0 or less Health minions and save them from dying as a result.

* https://www.reddit.com/r/hearthstone/comments/3skyme/anubisath_sentinel_bug/
* [[Hearthstone Science] When Do Minions Die?](https://www.youtube.com/watch?v=H3d_qlm4Xws&t=9m17s)
* http://us.battle.net/hearthstone/en/forum/topic/18704976830 (Rolkyr confirms as intended interaction here)

**Comment by Patashu** [comment]
Avenge saving mortally wounded minion confirmed in 3.0: https://www.reddit.com/r/hearthstone/comments/3i9iux/deaths_biteavenge_interaction_working_as_intended/

I'll update the milestone to 3.0 when the other two cards are also retested.

**Comment by Patashu** [comment]
Dark Cultist activating on mortally wounded minion confirmed in 3.0:

https://www.youtube.com/watch?v=hsNUP1SdIOI

**Comment by jleclanche** [comment]
@Patashu Do you think this might have to do with #25?

**Comment by Patashu** [comment]
Jleclanche: No, because the powermace bug was observed by reducing its durability to 0 as well as instantly destroying it, so it's orthogonal to that bug.

**Comment by Patashu** [comment]
Rolkyr confirms that Avenge being able to save mortally wounded is intended:

http://us.battle.net/hearthstone/en/forum/topic/18704976830

Not quite as good as a dev saying it but good to remember.

**Comment by PattuX** [comment]
Avenge no longer saves mortally wounded minions. 
http://imgur.com/a/aIgfw
In the last picture you clearly see that all minions are removed from the board, while secret didn't trigger yet (Trogg is still 5/1).
Play order from left to right, Secret after Ogre.

**Comment by Patashu** [comment]
Hi PattuX, 'Avenge saves mortally wounded minions' means the minion has to become mortally wounded IN the Death Phase. For example, play Explosive Sheep, Novice Engineer, Avenge. Opponent pings your Explosive Sheep. In the Death Phase, Explosive Sheep DR triggers then Avenge. If Avenge saves the Novice Engineer from dying, then Avenge can still save mortally wounded minions.

**Comment by PattuX** [comment]
Oh, right. derped around there, sorry :D

**Comment by PattuX** [comment]
Oh, right. derped around there, sorry :D

I'm not really sure tho about the Powermace one. Is the bug when I attack an Explosive Sheep and reduce the durability to zero by the attack and the Powermace Deathrattle does not save any dieing Mechs as an Avenge would do which results in inconsistency?

**Comment by Patashu** [comment]
Yeah, that's the inconsistency - if Avenge can target a mortally wounded minion, buff it and save it from dying, Powermace should do the same thing.

**Comment by Patashu** [comment]
Avenge confirmed to save mortally wounded minions in 4.0 (many examples).

**Comment by Patashu** [comment]
Dark Cultist and Powermace checked in 4.0, no change to behaviour from previous patches.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/3skyme/anubisath_sentinel_bug/

Anubisath Sentinel saves mortally wounded in 4.0

**Comment by Patashu** [comment]
Avenge confirmed in 4.1 to still save mortally wounded

https://www.reddit.com/r/hearthstone/comments/3vgikx/avenge_onto_0_health_minion/

**Comment by culinko** [comment]
Powermace in 4.1 still doesn't save mortally wounded, I just tested it.

**Comment by Kybxd** [comment]
Powermace bug is fixed in 4.2.Now it can save mortally wounded.

**Comment by culinko** [comment]
Thanks, confirmed.

![hearthstone screenshot 04-03-16 17 41 04](https://cloud.githubusercontent.com/assets/11700272/14233236/5aced1ec-f9c3-11e5-8d12-7a8c2852e066.png)

**Comment by Patashu** [comment]
Kybxd, thank you! I can finally remove this dumb edge case from the advanced rulebook :)
