### ISSUE TITLE
If you play an Alarm-o-Bot, it's stolen by the opponent, then end your turn, it does not trigger the next time your opponent's turn starts (but triggers normally afterwards)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#610]
- https://youtu.be/bYfkVl8htoE
- https://www.reddit.com/r/hearthstone/comments/536ctd/alarmobot_bug/

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 06-03-17 13 24 17](https://cloud.githubusercontent.com/assets/22508641/26755663/04a9de8c-4860-11e7-8539-075ea4f57fd6.png)

**Comment by troggnostupidhs** [comment]
This is fixed

![img000](https://user-images.githubusercontent.com/22508641/32643975-b7ba807a-c5ac-11e7-8aaf-e652147f8fd2.png)
![img001](https://user-images.githubusercontent.com/22508641/32643976-b7ca6f58-c5ac-11e7-8848-8c5db757e3c0.png)
