### ISSUE TITLE
If you cast Purify on a minion that affects costs of cards, all of those cards also get the Purify visual effect (happens also with silence and spirit claws)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#611]
- https://www.reddit.com/r/hearthstone/comments/53ytsl/purify_bug_report/

Tested with Mana Wraith and Venture Co. Mercenary and Nerub'ar Weblord.

Related: If you silence a spell damage minion, the sprit claws also has the silence animation. https://youtu.be/_j9PLVIcbRo?t=31m05s

**Comment by troggnostupidhs** [comment]
This still happens.

**Comment by jleclanche** [comment]
@troggnostupidhs do you want to swing by the [IRC/Discord channel](https://hearthsim.info/join/) some time? If you want to help triage this stuff might as well :)

**Comment by troggnostupidhs** [comment]
Signed up! I've just been working on a couple a day since it something to do, and I figure it helps clean things up.

**Comment by Patashu** [comment]
Related: If you silence a spell damage minion, the sprit claws also has the silence animation. https://youtu.be/_j9PLVIcbRo?t=31m05s

**Comment by troggnostupidhs** [comment]
Fixed

Deck
AAEBAZ/HAgAP+wGcArQC3ALlBMsFuQbiCPIMiA7nFqy0ArC8ApvCAtPFAgA=

![img000](https://user-images.githubusercontent.com/22508641/31847144-de2a36ce-b5e4-11e7-841f-4ac232e48809.png)
![img001](https://user-images.githubusercontent.com/22508641/31847145-de39b180-b5e4-11e7-8f7b-d3a8982c43d6.png)
