### ISSUE TITLE
Making attacks while Silvermoon Portal is summoning a minion may cause the new minion to hang in the air indefinitely

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#613]
https://www.youtube.com/watch?v=jfVgcemCNZ0&t=4m06s

**Comment by Patashu** [comment]
Potentially fixed according to http://us.battle.net/forums/en/hearthstone/topic/20749867298

**Comment by troggnostupidhs** [comment]
I tried this a few times and it seems fine.

Also, there haven't been any reports of this.
