### ISSUE TITLE
If you play Sir Finley as Tyrande, he can offer you Lesser Heal

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#614]
(Likely cause is that Tyrande's Lesser Heal is mistakenly not marked as a Priest Hero Power.)

https://www.reddit.com/r/hearthstone/comments/55aef3/tyrande_bugged_interaction_with_sir_finley/

**Comment by troggnostupidhs** [comment]
I tried this five times, and it was fine. Also, it hasn't been reported for a while.
