### ISSUE TITLE
Malchezaar's Imp can trigger on cards like Ambush triggering and removing themselves from your hand

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#618]
- https://www.reddit.com/r/hearthstone/comments/51dvqn/apparently_malchezaars_imp_is_triggered_by/

This is likely to have been fixed in Patch 6.2.0.15181 (2016-10-20): http://us.battle.net/forums/en/hearthstone/topic/20749867298

**Comment by jleclanche** [comment]
This was fixed.
