### ISSUE TITLE
Weird Welcome Bundle Chest behaviour in Shop

### ISSUE THREAD

**Issue by Sewil** [HearthSim/hs-bugs#620]
https://www.youtube.com/watch?v=YNXeOeb9uwk

**Comment by jleclanche** [comment]
Nothing looks abnormal in that video...

**Comment by Sewil** [comment]
Sorry, I should have mentioned that the first 15 seconds or so was me showing that the chest doesn't behave abnormally when switching between different expansions in the shop window. It starts around 0:15 when I start clicking the shop button very fast. The window doesn't open normally anymore but jumps around and sometimes covers the entire screen as it opens. I believe it's a combination of the upwards animation of the window along with the downwards animation of the chest object that collide with each other.

**Comment by troggnostupidhs** [comment]
This does not currently occur for two reasons.

1. I cannot spam click the Shop button as shown in the video

2. The video shows this animation when opening the Shop. In the current version, that animation is only shown when switching between sets in the Shop.
![Hearthstone Screenshot 03-19-19 20 07 56](https://user-images.githubusercontent.com/22508641/54649981-bc7ca500-4a82-11e9-860c-a943432ab4c0.png)
This is what the shop shows when opening to the Welcome Bundle.
![Hearthstone Screenshot 03-19-19 20 08 02](https://user-images.githubusercontent.com/22508641/54649986-c0a8c280-4a82-11e9-93a2-e58af3db3492.png)
