### ISSUE TITLE
arcanosmith doesn't trigger you shall not pass quest (play 20 taunt minions)

### ISSUE THREAD

**Issue by cleveranecdote** [HearthSim/hs-bugs#621]
I was 3/20 in the quest and played one more arena match with an arcanosmith (Battlecry: Summon a 0/5 minion with Taunt.) and I am still at 3/20.

**Comment by PattuX** [comment]
The quest requires you to play the minion, not summon. That means the minion having Taunt must be played from your hand after you paid the mana cost. This is consostent with other cards that read "play", as Secretkeeper, who doesn't trigger if Mad Scientist pulls a Secret, Hobgoblin, who does not trigger on Silver Hand Recruits from your Hero Power or Stand against Darkness for example, and Illidan Stormrage.

**Comment by cleveranecdote** [comment]
Thought it was odd, but thanks!
