### ISSUE TITLE
Greater Healing Potion text does not take healing power into account

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hs-bugs#623]
https://www.reddit.com/r/hearthstone/comments/5g4hje/bug_greater_healing_potion_is_not_affected_by/

Confirmed this myself earlier today. The heal effect works fine.

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 03-02-17 01 35 28](https://cloud.githubusercontent.com/assets/22508641/23495798/af560c0a-fee8-11e6-9914-04f8bea57a3c.png)
