### ISSUE TITLE
Kazacus potion effects aren't always in the most beneficial order (damage vs random polymorph)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#624]
* https://youtu.be/A3sUBb8aFJo?t=1m4s

In this video, the random polymorph happens before the damage. If the random polymorph happened 2nd, it would ignore the mortally wounded target and hit something else, which would be more beneficial for the player.

(There are probably other examples where the order is strictly not the most beneficial, if so feel free to add them here and update the title to be more general!)

**Comment by jleclanche** [comment]
Who says they should be in the most beneficial order? Given the amount of possible combinations I don't believe it's even possible to make that guarantee.

I don't remember Blizzard officially saying they should be; what makes sense is that they'd be in the order that they were picked. At the very least they should be consistent - but I believe that's the case?

**Comment by Patashu** [comment]
* https://www.reddit.com/r/hearthstone/comments/5b5mlg/the_mean_prerelease_reveal_chart_all_currently/d9mnjzu/

'we fix the order of the spell that is created to always be in the best order for the player. (like sheep happens before dealing damage).'

Interestingly they actually specifically mention sheep vs damage as an example of being in the best order. So either the bug is that the sheep isn't damaged OR that the damage should be first and the sheep target something else if mortally wounded.

**Comment by jleclanche** [comment]
Yeah, I think this is just incorrect information.

**Comment by Patashu** [comment]
Another bug is that the freeze effect can target mortally wounded minions. Since it's a negative random effect, it should ignore mortally wounded minions like all others do.

https://www.reddit.com/r/hearthstone/comments/5gdhzx/kazakus_needs_to_be_fixed/

**Comment by Xinhuan** [comment]
In the latest thread above linked by Patashu, Mike Donais has the following to say:

> We are already working on this. Feel free to post stuff like this on our bug forums.

This is an acknowledgement that they do consider it a bug.

**Comment by jleclanche** [comment]
Yep fair enough. Very surprising I have to say.

**Comment by Patashu** [comment]
http://hearthstone.gamepedia.com/Hotfixes#2016-12-06_hotfix

'Addressed an issue that allowed Kazakus Potions using Icecap to incorrectly target destroyed minions.

No word on if the damage vs polymorph case has changed or not...
