### ISSUE TITLE
Pilfered Power turns your full mana crystals into empty. 

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#625]
Report by reddit:
https://www.reddit.com/r/hearthstone/comments/5fyj4s/pilfered_power_bug/

so I would say it is the same bug with:
#126 

Also you didn't gain Excess Mana while it useless after your mana is full, but maybe intended?

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=Dnr7uzZeMGw video

**Comment by Patashu** [comment]
Hotfixed!

http://hearthstone.gamepedia.com/Hotfixes#2016-12-06_hotfix
