### ISSUE TITLE
Book Wyrm marked as active with a single enemy minion with stealth

### ISSUE THREAD

**Issue by riQQ** [HearthSim/hs-bugs#626]
I had Book Wyrm and another dragon in hand, the enemy had only a single stealth minion and no other minions. My Book Wyrm was marked 'active'.
No real screenshot, sadly:
![2016-12-03 09_22_15-riq vs](https://cloud.githubusercontent.com/assets/3404787/20857974/0c7890e6-b93a-11e6-87ea-a5fc7cbe1652.png)

**Comment by troggnostupidhs** [comment]
Still happens

![hearthstone screenshot 03-02-17 23 19 19](https://cloud.githubusercontent.com/assets/22508641/23538132/faf2f194-ff9e-11e6-8161-0b79e38eca80.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6gtfbk/book_wrym_shouldnt_glow_when_an_enemy_has_a/

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20755676768

Also happens with Hungry Crab + Finja

**Comment by troggnostupidhs** [comment]
Still true for Bookworm and Hungry Crab.

Bookworm and Finja deck
AAEBAa0GArW7AuO+Ag77AZwCtAK7A+EE5QSBBbkG4gfXCoEQ7hGJFKqyAgA=

**Comment by troggnostupidhs** [comment]
https://youtu.be/TWiM-K_eno8?t=6

**Comment by riQQ** [comment]
https://playhearthstone.com/en-us/blog/21964710

    Cards no longer display their yellow activation aura when their target can't be interacted with.

**Comment by troggnostupidhs** [comment]
![img001](https://user-images.githubusercontent.com/22508641/44311875-e242ae00-a3bc-11e8-8ceb-f18a2948bf80.png)

I think both are fixed
