### ISSUE TITLE
Wrathion shows opponents cards drawn

### ISSUE THREAD

**Issue by Xinhuan** [HearthSim/hs-bugs#627]
https://www.reddit.com/r/hearthstone/comments/5g46ka/wrathion_shows_opponent_cards_drawn/

> Is this intended
> [](http://i.imgur.com/ma5ffuk.png)
> ? Seems like a bug to me.
> Opponent played Wrathion. The game played the animation of drawing two cards for him and each one flipped over to reveal what it was, so I knew what cards he had drawn.
> He only showed the dragons that were drawn, though, not the one that ended the sequence.

In the screenshot, the history tile for Wrathion shows the drawn Dragons.

**Comment by Xinhuan** [comment]
Video of this issue: https://clips.twitch.tv/reynad27/CalmOwlOSsloth

**Comment by Patashu** [comment]
I'm not convinced this is a bug? It might be revealing the cards to make it easier for new players to parse why they drew that specific number of cards. (In particular, if it was a physical card game, you'd HAVE to reveal them to prove that you can draw again.)

**Comment by Xinhuan** [comment]
On the other hand, this is a digital game, and every other card that tutor for specific tribal cards do not show your opponents what is drawn. Holy Wrath doesn't show the card, Sense Demons doesn't show them, nor The Curator.

Furthermore, there is no indication to the player casting it that any Dragons are revealed to the opponent.

**Comment by Patashu** [comment]
Hotfixed!

http://hearthstone.gamepedia.com/Hotfixes#2016-12-06_hotfix
