### ISSUE TITLE
Ancestral Spirit/Reincarnate/Moat Lurker summon your Weasel Tunneler to your opponent.

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#628]
So the true effect of them is 'deathrattle : summon a copy of that minion for the controller”

Most of the time the minion turns into your graveyard, so the controller is still you. Sometimes they turns into your hand or deck, but it's still yours.

But Weasel turns himself into your opponent deck, so it summon for your opponent.

Moat Lurker; https://youtu.be/HhZr5Sa7Bms?t=139
(the Ancestral Spirit in this video summon for original controller since it got Rivendare on board,so the Weasel Tunneler reshuffle himself into the original controller's deck)

**Comment by Patashu** [comment]
Other notable interactions:

1) Reincarnate does not make the new Weasel for the opponent. (it's in https://www.youtube.com/watch?v=HhZr5Sa7Bms somewhere)
2) Normally the Death Event Cache (used for Ress, KT, N'Zoth and so on) remembers what controller the minion died for, and only that player can resurrect it as a friendly minion. For example, in this video ( https://www.youtube.com/watch?v=MObXMLTN23Y ) our Shifter Zerus is Entombed by our opponent, but it dies before it's Entombed. Later it's drawn by our opponent. When we play Resurrect, we can get back whatever form Zerus is in, even though it now belongs to our opponent! Basically, this proves that Ancestral Spirit and Moat Lurker do not use the 'Death Event Cache' mechanic.

**Comment by Patashu** [comment]
DisguisedToast ALSO tested Reincarnate vs Weasel Tunneler. He Reincarnated an opponent Weasel Tunneler and got the reincarnated copy. So either Reincarnate always gives YOU the Weasel, or it's random or otherwise unknown how it works.

https://www.youtube.com/watch?v=K_Bn3shK8Cs&t=1m53s

**Comment by 10925** [comment]
I believe the interaction of Reincarnate in  https://www.youtube.com/watch?v=HhZr5Sa7Bms is because Baron Rivendare.

Reincarnate should same with Moat Lurker and Ancestral Spirit .

**Comment by Patashu** [comment]
Oops! You are correct.

**Comment by culinko** [comment]
Malorne and Weasel Tunneler don't move the original entity to the deck anymore, but create a fresh minion instead as Malorne used to some time ago. I found this out in the current patch. It's a recent change cause Malorne wasn't changed in 7.1 yet. Could you please re-test the problematic interactions again when you get some time? I guess same goes for #636. Much appreciated!

**Comment by troggnostupidhs** [comment]
It's possible Weasel Tunneler was changed

https://www.reddit.com/r/hearthstone/comments/6gd5uz/blizzard_updated_weasel_tunneler/

**Comment by VoidMayonnaise** [comment]
However this author didn't retest most of the interactions he mentioned, so I don't think this forum is convincing.
Now WT is already fixed, Moat Lurker has already tested and it interact normally. I need to retest Ancestral Spirit and Reincarnate. Seems that this issue will be closed soon.

**Comment by VoidMayonnaise** [comment]
https://youtu.be/8jzp5yfSkn8
Already fixed. This issue should be closed.

**Comment by troggnostupidhs** [comment]
This is fixed and not affected by the dominant player bug.
