### ISSUE TITLE
Silencing Shadow Madness bypasses the 7 minion limit

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#63]
If you use Shadow Madness to take control of an enemy minion, copy it with Faceless Manipulator and Silence all copied minions, they will all return to your opponent's board and can bypass the 7 minion limit if your opponent's board is full.

[[Hearthstone Science] Mimiron's Head is having a party! (Shadow Madness vs Silence bug)](https://www.youtube.com/watch?v=x8ZuO-cRnls)

**Comment by jleclanche** [comment]
Fixed in 10833.
