### ISSUE TITLE
If Kazakus's Potion is copied by Lorewalker Cho, the text is missing but the effects still work

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#630]
https://www.reddit.com/r/hearthstone/comments/5gbgwp/til_trade_prince_gallywix_perfectly_copies/

**Comment by troggnostupidhs** [comment]
Potentially fixed.

http://us.battle.net/hearthstone/en/blog/20562933/hearthstone-update-february-28-2-28-2017

> Resolved an issue where a Kazakus potion spell cards could appear blank when copied by a minion or spell effect.

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 06-02-17 21 58 21](https://cloud.githubusercontent.com/assets/22508641/26749717/e63bdb02-47de-11e7-9d4a-b0dad558f12b.png)

![hearthstone screenshot 06-02-17 21 58 26](https://cloud.githubusercontent.com/assets/22508641/26749719/e8f80b72-47de-11e7-8345-96d8b02c6d63.png)
