### ISSUE TITLE
Unearthed Raptor targeting Weasel Tunneler someimes maintains the Deathrattle after being replayed

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#632]
https://www.reddit.com/r/hearthstone/comments/5gfxrv/the_weasel_raptor_combo_is_the_real_kazakus_it/

Info and video in the above topic.

**Comment by Patashu** [comment]
Related to https://github.com/HearthSim/hs-bugs/issues/636

**Comment by PattuX** [comment]
I wasn't able to reproduce this: 

* https://hsreplay.net/replay/VRhjjG2xUEYGXtyBeggWZF#turn=24a

The same raptor dies on turn 26a.

My vague theory atm is that this has to do with the limit of 16 DR trigger. I'll try that tomorrow and edit the results in here.

**Comment by PattuX** [comment]
Merged with #636
