### ISSUE TITLE
If your opponent has a minion that Freezes (Snowchugger etc), your Cryomancer will be incorrectly highlighted

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#633]
* https://www.reddit.com/r/hearthstone/comments/5gf3fy/bug_cryomancers_border_turns_yellow_even_if_the/ (see comments)
* https://www.reddit.com/r/hearthstone/comments/5gikcq/bug_with_cryomancer_yellow_glow_with_no_frozen/

**Comment by troggnostupidhs** [comment]
Fixed

![hearthstone screenshot 03-01-17 03 14 14](https://cloud.githubusercontent.com/assets/22508641/23451273/3bb66918-fe2d-11e6-9013-fc32e6fe76ac.png)
