### ISSUE TITLE
Mirror Entity copy of Small-Time Buccaneer incorrectly has the +2 Attack even if your opponent lacks a weapon

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#634]
* https://www.reddit.com/r/hearthstone/comments/5gi1gk/is_this_a_normal_interaction_for_mirror_entity/
* https://www.reddit.com/r/hearthstone/comments/5ghy5c/odd_interaction_playing_smalltime_buccaneer_into/
* https://www.reddit.com/r/hearthstone/comments/5gjapk/mirror_imaged_smalltime_buccaneer_gets_the_buff/
* https://www.reddit.com/r/hearthstone/comments/5gs9ga/is_small_time_buccaneer_supposed_to_receive/

Further information: It seems to only update specifically when your weapon equips/unequips, rather than 'checking every time auras do'.

**Comment by troggnostupidhs** [comment]
This is fixed

![hearthstone screenshot 03-07-17 08 47 28](https://cloud.githubusercontent.com/assets/22508641/23659266/95574eca-0313-11e7-83f2-57c9c9a7e110.png)
