### ISSUE TITLE
Weasel Tunneler + added Deathrattles is affected by the Dominant Player Bug, meaning the added Deathrattle sometimes works immediately and sometimes waits until later

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#636]
* https://www.youtube.com/watch?v=K_Bn3shK8Cs

We observe that Weasel Tunneler/Explorer's Hat gives your opponent a hat, but Weasel Tunneler/Soul of the Forest does nothing... until it's played again and dies again, then a treant is summoned for your (original) opponent).

Note that Soul of the Forest CAN trigger fine in the deck, for example using Malorne ( https://github.com/HearthSim/hs-bugs/issues/313 ). It was fixed in Patch 5.0.

PattuX brought up that this is not inconsistent, it's Dominant Player Bug based:

Rule CEM2b: For Enchantments that add Deathrattles, who gets the effect and whether to queue in the Dominant Player's queue or the Secondary Player's queue. For both of these things, the minion's CONTROLLER is always used instead. (Ancestral Spirit, Explorer's Hat, Soul of the Forest) ( http://hearthstone.gamepedia.com/Advanced_rulebook#Controllers_of_Enchantments_and_Minions )

This means that if the Weasel Tunneler is Dominant Player owned, its DR resolves and makes it Secondary Player, invalidating the queued attached Deathrattles. Now they queue in the Secondary Queue and work fine.

But if the Weasel Tunneler is Secondary Player owned, the Deathrattles have no later queue to trigger in. So apparently they just linger around attached to the minion until they really CAN trigger!

**Comment by Patashu** [comment]
Related to https://github.com/HearthSim/hs-bugs/issues/632

**Comment by Patashu** [comment]
PattuX brought up that this is not inconsistent, it's Dominant Player Bug based.

Rule CEM2b: For Enchantments that add Deathrattles, who gets the effect and whether to queue in the Dominant Player's queue or the Secondary Player's queue. For both of these things, the minion's CONTROLLER is always used instead. (Ancestral Spirit, Explorer's Hat, Soul of the Forest)

This means that if the Weasel Tunneler is Dominant Player owned, its DR resolves and makes it Secondary Player, invalidating the queued attached Deathrattles. Now they queue in the Secondary Queue and work fine.

But if the Weasel Tunneler is Secondary Player owned, the Deathrattles have no later queue to trigger in. So apparently they just linger around attached to the minion until they really CAN trigger!

**Comment by Patashu** [comment]
additional discussion with PattuX

[11:38] <+TardisBot> [discord] <PattuX> @Patashu what about "Rule Z5c: Deck Zone to any other Zone: All Enchantments detached."
[11:38] <+TardisBot> [discord] <PattuX> according to this, sotf should be detatched, right?
[11:40] <+TardisBot> [discord] <PattuX> do you think they changed it, as they added even more in-deck buffs?
[11:40] <+TardisBot> [discord] <PattuX> like the warrior legendary for example
[11:42] <@Patashu> @PattuX consider that when a minion dies, all attached Enchantments (including attached Deathrattles) detach
[11:42] <@Patashu> @PattuX but they trigger anyway, so the fact that an attached Deathrattle is no longer attached is not relevant to whether it triggers or not
[11:42] <@Patashu> @PattuX I think the warrior legendary will have the 'mistcaller bug' but I have not seen anyone test it yet
[11:43] <+TardisBot> [discord] <PattuX> that makes the video even more strange tho
[11:44] <+TardisBot> [discord] <PattuX> https://youtu.be/K_Bn3shK8Cs?t=1m10s
[11:44] <+TardisBot> [discord] <PattuX> to 1:45
[11:48] <@Patashu> @PattuX let me explain it this way. attached DRs detach when the minion dies, but trigger when the minion's Death Event resolves even though they are no longer in play. correct?
[11:48] <@Patashu> @PattuX: in particular, note that this is different to all other trigger mechanics. all other triggers must be in play to trigger (ignore in-hand stuff for this discussion)
[11:48] <@Patashu> @PattuX: this means that 'this added DR got detached, but remember it so it can trigger' is a unique mechanic that does not exist anywhere else in HS.
[11:49] <@Patashu> @PattuX: therefore the bug is that this list does not get cleared if it's non-empty when the death event finishes resolving. so it lingers around, attached to the minion like a ghostly force, still there the next time it dies

**Comment by 10925** [comment]
Oh talking about mist-caller and renounce darkness bug, we believed that one was fixed.

They should now directly buff in deck.

some proof:
http://imgur.com/a/ZpD0c

So I  believe  #110 and #463 probably got fixed.

**Comment by Patashu** [comment]
Thought of another scenario I'd like to see tested. Maybe PattuX or 10925 can try it.

If you have a Baron Rivendare and a Weasel with added Deathrattle in play and the Weasel dies, do you get the added Deathrattle or does it fail to trigger?

In other words, is it the act of changing controllers that causes the trigger to fail to trigger, or is it the act of BEING the wrong controller WHEN the trigger tries to resolve what causes the trigger to fail to trigger?

**Comment by Patashu** [comment]
Tested by /u/cstrindgard:

"I managed to convince a friend to try it out. It all played out as expected. The dominant player weasel's deathrattles get triggered and the secondary player weasel get bugged. We only tried with Soul of the Forest, Explorer's Hat and Infest, but it worked as expected for all those cards."

**Comment by PattuX** [comment]
Being the wrong controller when the trigger tries to resolve is what causes the trigger to fail, not the act of changing controller itself. See [explanation here.](https://github.com/HearthSim/hs-bugs/issues/632#issuecomment-265040347)

**Comment by Kybxd** [comment]
Fixed in 8.0 (https://youtu.be/ew4aymrlfx0)

**Comment by Patashu** [comment]
OK, it's fixed for Weasel Tunneler + Soul of the Forest.

But can you explain this? https://www.youtube.com/watch?v=K-P5nW23DbE&t=2m06s

Why does Weasel Tunneler + Spirit Echo not work?

**Comment by Kybxd** [comment]
One of my friend tested:
1.Malorne + Spirit Echo = Spirit Echo doesn't work.
2.Malorne + Gateway Kodo = Gateway Kodo doesn't work and remains hidden.
3.Malorne + Soul of the Forest = Both work.
4.Gateway Kodo + Malorne = Malorne's deathrattle doesn't work.

It seems that minions returned to hand or deck will not be moved by any other effects, while Soul of the Forest triggers as usual no matter where the minion is or who controls it.

**Comment by Patashu** [comment]
2 (I think) and 3 (definitely) is the same as before patch 8.0.

1 and 4 are new.

What about, say, Getaway Kodo + Malorne (Getaway Kodo is played first), or Getaway Kodo + Weasel Tunneler (Getaway Kodo is played first)?

**Comment by Patashu** [comment]
I would also like to see other on-death trigger interactions with Weasel Tunneler - Redemption (note that due to Redemption's late priority, you can only test Redemption triggering afterwards), Cult Master, Scavenging Hyena, Mekgineer Thermaplugg, Flesheating Ghoul, etc.

**Comment by troggnostupidhs** [comment]
It's possible Weasel Tunneler was changed

https://www.reddit.com/r/hearthstone/comments/6gd5uz/blizzard_updated_weasel_tunneler/

**Comment by VoidMayonnaise** [comment]
https://youtu.be/upGRrrarf68
Test by Weasel Tunneler & Ancestral Spirit, the two players' interaction are exactly the same. This issue should be closed.

**Comment by troggnostupidhs** [comment]
Video is sufficient. Both players have the same results.
