### ISSUE TITLE
Daring Reporter mortally wounded by Mortal Coil draws a card and survives

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#638]
This is reportedly fixed in the 2016-12-06 hotfix:

http://hearthstone.gamepedia.com/Hotfixes#2016-12-06_hotfix

* Addressed an issue that caused Mortal Coil to incorrectly draw a card when played on a Daring Reporter that remains on the board.

But it needs to be tested HOW exactly they fixed it. Keeping in mind https://github.com/HearthSim/hs-bugs/issues/325 they may have only tested the 'Daring Reporter has not buffed itself yet' case, for example.

I would also like to see Wrath tested (since Wrath draws BEFORE dealing damage), any other draw+damage tested (Starfire/whatever) and to see a power.log (maybe the Daring Reporter becomes TO_BE_DESTROYED for example?)

**Comment by Kybxd** [comment]
Daring Reporter can still survive Wrath now.(http://imgur.com/5AIe6oT)(http://imgur.com/YAriCHf)

I guess Daring Reporter can only trigger when it's not mortally wounded/pending destroy,similar to Grim Patron.

**Comment by 10925** [comment]
As you imagine, Wrath cannot kill Daring Reporter, but Shiv could.
here's proof:
http://imgur.com/a/Un8l1

**Comment by Patashu** [comment]
Thanks, this is sufficient evidence to know what was changed :)

I can also update https://github.com/HearthSim/hs-bugs/issues/148 to 7.0.

I'll go and update the wiki now.
