### ISSUE TITLE
Madam Goya can't swap out a minion when played as a 7th minion on the player's board

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#639]
* http://hearthstone.gamepedia.com/Hotfixes#2016-12-06_hotfix

Labelling as potentially fixed because someone now needs to check how Madam Goya is implemented, depending on the implementation there may still be related bugs. In particular for the purposes of interacting with Brann Bronzebeard, as seen here: http://hearthstone.gamepedia.com/index.php?title=Madam_Goya&diff=0&oldid=270222#Notes

**Comment by troggnostupidhs** [comment]
Tested by @culinko
