### ISSUE TITLE
Spellbender fails to trigger if your opponent plays Dark Wispers and has a full board

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#64]
If a player has the Spellbender secret in play with a non-full board, and his opponent has a full board (7 minions), when his opponent plays Dark Wispers and chooses the +5/+5 to a minion option, Spellbender fails to trigger. This bug does not occur with the other Choose One Druid spells.

http://www.reddit.com/r/hearthstone/comments/376led/spellbender_dark_wispers_bug/
https://www.youtube.com/watch?v=YwrAL0Q9voM
https://www.youtube.com/watch?v=ky12nWEytjQ

**Comment by culinko** [comment]
Tested it today with SimFri, Dark Wispers is still bugged. Interestingly enough, if you damage your minion with Living Roots, the Spellbender correctly triggers. I was thinking it's related, but apparently it isn't.

**Comment by Patashu** [comment]
Tested in Patch 4.1, it's fixed. (Have video and log, might upload it)
