### ISSUE TITLE
If Stolen Goods is played but has no effect, After Spell Phase triggers (Wild Pyromancer, Auctionmaster Beardo, etc) will not trigger

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#642]
* https://www.reddit.com/r/hearthstone/comments/5gxfy1/bug_with_stolen_goods_and_pyromancer/
* http://us.battle.net/forums/en/hearthstone/topic/20752348817
* https://www.reddit.com/r/hearthstone/comments/5h3v0w/possible_bug_with_stolen_goods/

![image](https://cloud.githubusercontent.com/assets/666597/20960915/be63b5e0-bcb6-11e6-84d6-ffed086c245a.png)

Doesn't happen with Smuggler's Crate.

It also doesn't discount Arcane Giant:

* https://www.reddit.com/r/hearthstone/comments/5jnmjd/bug_casting_stolen_goods_with_no_taunt_minions_in/

**Comment by Patashu** [comment]
/u/uther321 says "casting stolen goods with no taunt minions in hand will NOT cause arcane giant to be discounted. This is clearly a bug.
I have not tried Yogg-Saron, though I suspect it will also not increasing Yogg's battlecry."

I suspect it's coded to counter itself.

**Comment by troggnostupidhs** [comment]
Atiesh also doesn't trigger
https://www.reddit.com/r/hearthstone/comments/5nhfx4/bug_stolen_goods_atiesh_broken/

**Comment by VoidMayonnaise** [comment]
https://youtu.be/Com1HP2uLN4
Already fixed in 8.2.

**Comment by troggnostupidhs** [comment]
Atiesh and Pyro trigger
