### ISSUE TITLE
Small-Time Buccaneer's Aura has a normal priority instead of a late priority (like the old Cogmaster bug)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#643]
* https://www.reddit.com/r/hearthstone/comments/5gx601/crazed_alchemist_smalltime_buccaneer_interaction/

For example, if you use Crazed Alchemist on a 3/2 Small-Time Buccaneer, it becomes a 2/3 but should become a 4/3.

On the other hand, https://www.reddit.com/r/hearthstone/comments/5gwyz7/another_msog_bug_gamebreaking/daw131r/ says that if you unequip and re-equip a weapon, the new instance of the Aura is last on the Enchantment List and buffs the Small-Time Buccaneer once more. So we know the Aura erroneously has a normal priority.

**Comment by troggnostupidhs** [comment]
Potentially fixed.

http://us.battle.net/hearthstone/en/blog/20562933/hearthstone-update-february-28-2-28-2017

> Resolved inconsistencies in the way that Small Time Buccaneer’s Attack interacts with effects such as those generated by Humility, Keeper of Uldaman, and Crazed Alchemist.

**Comment by troggnostupidhs** [comment]
Swapping now changes it from a 3/1 (post-nerf stats) to a 3/3 minion.

![hearthstone screenshot 03-01-17 00 09 47](https://cloud.githubusercontent.com/assets/22508641/23446679/9cad5d68-fe13-11e6-8f45-91f77c1c5ac2.png)

![hearthstone screenshot 03-01-17 00 09 54](https://cloud.githubusercontent.com/assets/22508641/23446685/9f78a5a2-fe13-11e6-92a9-150f86443650.png)

**Comment by troggnostupidhs** [comment]
Re-equipping a weapon resulted in the minion still being a 3/3
