### ISSUE TITLE
Arcane Blast does not double spell damage when copied by Djinni of Zephyrs

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#645]
* http://us.battle.net/forums/en/hearthstone/topic/20752317411

(unconfirmed as no screenshot/etc)

**Comment by troggnostupidhs** [comment]
Potentially fixed.

http://us.battle.net/hearthstone/en/blog/20562933/hearthstone-update-february-28-2-28-2017

> Djinni of Zephyrs will now correctly copy spells buffed by spell damage.

**Comment by troggnostupidhs** [comment]
It worked for me

![hearthstone screenshot 02-28-17 23 43 58](https://cloud.githubusercontent.com/assets/22508641/23446288/fb10134a-fe0f-11e6-93db-451292a25c3d.png)
