### ISSUE TITLE
Hidden Cache disappears instead of triggering when your opponent plays a Choose One minion

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#646]
* http://us.battle.net/forums/en/hearthstone/topic/20752208420

"Whenever I've been playing against Druids playing a 'Choose one'-effect minion (Mire Keeper, Druid of the Claw, Ancient of War etc.) into my Hidden Cache trap the trap disappears without triggering."

**Comment by troggnostupidhs** [comment]
Tested with Druid of the Saber and Grove Tender and there wasn't an issue. It definitely triggers. The only thing to note is that the sidebar shows the stats before the buff. In my screenshot, Silithid Swarmer was a 7/9 after being buffed.

![hearthstone screenshot 12-10-16 14 18 19](https://cloud.githubusercontent.com/assets/22508641/21075592/fbc9fa3c-bee3-11e6-87a8-d4380882b357.png)
