### ISSUE TITLE
Brann Bronzebeard / Echoing Ooze does not make 3 oozes anymore (hotfix regression)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#647]
* http://us.battle.net/forums/en/hearthstone/topic/20042704902

**Comment by troggnostupidhs** [comment]
This is not bugged for me.

![hearthstone screenshot 12-09-16 21 27 13](https://cloud.githubusercontent.com/assets/22508641/21070611/87dd52aa-be56-11e6-93b7-1a63642dc45c.png)
