### ISSUE TITLE
Wind-Up Burglebot erroneously glows when Fandral Staghelm is in play

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#650]
* http://us.battle.net/forums/en/hearthstone/topic/20752407785

![image](https://cloud.githubusercontent.com/assets/666597/20964440/a9033324-bcc5-11e6-9762-d9d9d6d87bf9.png)

**Comment by troggnostupidhs** [comment]
Fixed

![hearthstone screenshot 03-01-17 02 44 37](https://cloud.githubusercontent.com/assets/22508641/23450426/26cc97a6-fe29-11e6-8023-4324c4b2500a.png)
