### ISSUE TITLE
Incorrect text on Jade Spirit

### ISSUE THREAD

**Issue by Spedwards** [HearthSim/hs-bugs#651]
The "**Jade Golem**" text on Jade Spirit contains an underscore instead of a space. This is evident by searching "Jade_Golem".

EDIT: There are actually a tonne of cards using underscores instead of spaces. Inconsistently too at that.
https://www.reddit.com/r/hearthstone/comments/5gzjvx/unnoticeable_text_errors_and_inconsistencies/?st=iwewb51i&sh=8a88ec19

Maybe close and create a separate issue?

**Comment by Patashu** [comment]
Isn't there a card that uses an nbsp instead of a space somewhere?

**Comment by troggnostupidhs** [comment]
Here's the pastebin link, in case the Reddit thread is deleted.

http://pastebin.com/LxLQBQWG

**Comment by troggnostupidhs** [comment]
In the hearthstonejson api, there's a bunch of 'Â' characters that seem to match the cards listed.

https://api.hearthstonejson.com/v1/15590/enUS/cards.json

**Comment by jleclanche** [comment]
HearthstoneJSON pre-replaces underscore with a non-breaking space. If you're seeing `Â` you need to fix your encoding.

**Comment by troggnostupidhs** [comment]
It's in Firefox. Manually switching the encoding to Unicode fixes it.

**Comment by jleclanche** [comment]
@troggnostupidhs Looks like I don't specify the charset (https://github.com/aws/aws-cli/issues/1346). Please file an issue on https://github.com/HearthSim/HearthstoneJSON and I'll fix it.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20753876336
> Jade Spirit will now correctly appear in searches using the term “Jade Golem”.
