### ISSUE TITLE
Converting Deck modes in Collection Manager no longer re-orders the decks

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#655]
I think the change to organizing deck slots has been reverted.

The new method to put a deck at the bottom of the deck list was

1. Edit a deck

1. Convert to Wild

1. Convert to Standard

1. Save the deck

Now it's back to the old method

1. Edit a deck

1. Convert to Wild

1. Save the deck

1. Edit the same deck

1. Convert to Standard

1. Save the deck

I think this should be changed back to the new, more convenient method.

**Comment by jleclanche** [comment]
I'm closing this. There's no "method to organizing deck slots", decks are not sortable right now and it's an implementation detail that doing this reorders them.

Also, this tracker doesn't take feature requests.

**Comment by troggnostupidhs** [comment]
It was an existing 'feature' though. They had the four step method working. A recent update is what reverted it to the six step method.

**Comment by troggnostupidhs** [comment]
I don't think this is invalid. It is in the patch notes. The change below has been reverted.

> Decks that are converted from one format (Wild or Standard) to the other will now automatically be added to the bottom of their respective list.

http://hearthstone.gamepedia.com/Patch_6.1.3.14830

**Comment by jleclanche** [comment]
Reopening then, but I still have some suspicions about this.

**Comment by troggnostupidhs** [comment]
Thinking about it, what I quoted actually could mean either of the behaviors. But I know the simpler method was working. Some links from Reddit,

https://www.reddit.com/r/hearthstone/comments/55puxh/deckslots_can_now_be_organized_d/
https://www.reddit.com/r/hearthstone/comments/5domio/requestplease_let_us_move_decks/
https://www.reddit.com/r/hearthstone/comments/5g658b/can_we_please_for_the_love_of_god_move_our_decks/

I'm not sure if this should be closed or not, but I really hope Blizzard will change it back.

**Comment by troggnostupidhs** [comment]
At this point, I think it was an intentional change. This should probably be closed.
