### ISSUE TITLE
Knuckles doesn't trigger if he attacks a friendly minion (such as via Misdirection)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#656]
* https://www.youtube.com/watch?v=iOMhu7GAcGM&t=2m23s

**Comment by troggnostupidhs** [comment]
Potentially fixed.

http://us.battle.net/hearthstone/en/blog/20562933/hearthstone-update-february-28-2-28-2017

> Knuckles will now correctly use its effect when under the effects of Misdirection.

**Comment by troggnostupidhs** [comment]
(11 - 3 = 8 health)

![hearthstone screenshot 06-02-17 22 54 42](https://cloud.githubusercontent.com/assets/22508641/26750033/9ced28c2-47e6-11e7-932b-a288bab43164.png)
