### ISSUE TITLE
Kazakus Potion gives incorrect error message 'There must be at least 0 minions on the battlefield'

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#658]
* https://www.reddit.com/r/hearthstone/comments/5honjx/bug_i_noticed_in_amnesiacs_stream/

> As he reached to play the 4/5 guy he accidentally played the Kazakus potion, which prompted him that it required at least 0 minions. It is LITERALLY IMPOSSIBLE to NOT have at least 0 minions on the board...

![image](https://cloud.githubusercontent.com/assets/666597/21079320/fb3190da-bfe2-11e6-81bd-7b355c95e051.png)

**Comment by troggnostupidhs** [comment]
Some more info here

https://us.battle.net/forums/en/hearthstone/topic/20753257954

> There is incorrect wording on the error message that appears when attempting to use a specific Kazakus Potion without the correct criteria being met.
> 
> After creating a 5 mana potion of "Polymorph a random enemy minion. Summon a 5/5 Demon", then attempting to use it on a completely empty board, it could be seen that the resulting message said: "There must be at least 0 minions on the battlefield". Imagining that this should instead say "1" and "minion". Maybe even stipulate that it has to be an enemy minion seeing as the card text specifies that? 

![image](https://user-images.githubusercontent.com/22508641/28046615-ec2f5dee-65b2-11e7-810d-a0cb83c85bd6.png)

![image](https://user-images.githubusercontent.com/22508641/28046629-057f978c-65b3-11e7-8790-a5cf14c05d2e.png)

**Comment by troggnostupidhs** [comment]
I think it is fixed

![hearthstone screenshot 07-11-17 00 15 02](https://user-images.githubusercontent.com/22508641/28050839-25cab718-65ce-11e7-9e72-af887e4634dc.png)

![hearthstone screenshot 07-11-17 00 14 46](https://user-images.githubusercontent.com/22508641/28050864-60fd0354-65ce-11e7-8342-e99994eeb46e.png)
