### ISSUE TITLE
Golden Faceless Summoner has the wrong banner (purple instead of blue) when in your decklist

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#659]
* https://us.battle.net/forums/en/hearthstone/topic/20752655585

"I noticed a very small bug today where the golden version of Faceless Summoner (a mage card) shows up with a purple banner at the bottom of the card like a neutral minion would if you hover over it in your decklist. It does properly show up with the blue mage banner in your collection screen, only when it is added to a deck does it seem to show the wrong banner.

![image](https://cloud.githubusercontent.com/assets/235410/21466339/5b40922c-c9d0-11e6-9c6e-e36223ae6a8d.png)
![image](https://cloud.githubusercontent.com/assets/235410/21466342/6aa3d0da-c9d0-11e6-837d-1f9b5ae15307.png)

For comparison (the top is when it is in a decklist, the bottom is in your collection)"

**Comment by troggnostupidhs** [comment]
Should be fixed

![hearthstone screenshot 10-12-18 23 55 41](https://user-images.githubusercontent.com/22508641/46901052-70e22180-ce7a-11e8-8cd9-9eb804d2b8ec.png)
