### ISSUE TITLE
Charge (card) says 'it can't attack heroes this turn', but if you make a copy of that minion next turn, the copy also can't attack heroes while it has summoning sickness

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#662]
'For example, if you cast Charge on a minion, and then the next turn use Faceless Manipulator on that minion, the copy will not be able to attack heroes.'

True since Charge was changed in 6.3.

* https://www.reddit.com/r/hearthstone/comments/56c1pk/new_charge_doesnt_give_the_keyword_charge_but/
* https://us.battle.net/forums/en/hearthstone/topic/20752445609

**Comment by VoidMayonnaise** [comment]
Peter Whalen replied me that this is a feature...
Twitter:
> Void Mayonnaise: If I copy a Charged Devilsaur (played last turn) by Faceless Manipulator or something, can the copy one attack the enemy hero this turn? I remember that Charge (spell) has the same problem.
Peter Whalen: Yes. Feature, not a bug =)

**Comment by troggnostupidhs** [comment]
Not a bug. Unless he was joking?

**Comment by troggnostupidhs** [comment]
https://twitter.com/LegendaryFerret/status/848002959245950977

**Comment by troggnostupidhs** [comment]
13.0.9.28556

Same turn
![hearthstone screenshot 02-01-19 19 49 07](https://user-images.githubusercontent.com/22508641/52157102-7b5b3d80-265a-11e9-9742-3841a9abd029.png)


Next turn
![hearthstone screenshot 02-01-19 19 38 01](https://user-images.githubusercontent.com/22508641/52156882-1eab5300-2659-11e9-9f9e-a6465905fa4e.png)


Deck
AAEBAQcCHNYRDvsBnQLYApMEogSRBrkG/wfOFoKtAsbCAszNAqbwApvzAgA=

**Comment by troggnostupidhs** [comment]
This behavior is not consistent with copying any other 'this turn' effect on later turns.

It is not exactly clear what Peter Whalen's comment meant, so this will be opened again until we get additional clarification.

**Comment by Jetz72** [comment]
Still happens.
![Hearthstone Screenshot 08-11-19 13 59 26](https://user-images.githubusercontent.com/8607832/62837710-a2fe1480-bc40-11e9-954b-e0849914bd28.png)

**Comment by Jetz72** [comment]
Still happens. Thought it might have been fixed after one of the reports in #1327, but apparently not.
![Hearthstone Screenshot 04-07-20 10 10 27](https://user-images.githubusercontent.com/8607832/78679295-09aefd00-78b8-11ea-8c66-49423a34df86.png)
