### ISSUE TITLE
Hobart Grapplehammer buff has placeholder/missing art

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#663]
* https://us.battle.net/forums/en/hearthstone/topic/20752217769

![image](https://cloud.githubusercontent.com/assets/235410/21295474/7b10dbfa-c55e-11e6-8225-f70c0d644b7a.png)

**Comment by troggnostupidhs** [comment]
This is fine for me. I think this is invalid.

![hearthstone screenshot 12-11-16 18 35 20](https://cloud.githubusercontent.com/assets/22508641/21084407/1e938234-bfd1-11e6-8342-7f4de33b5b3b.png)

**Comment by Patashu** [comment]
Maybe it only happens on mobile? The screenshot doesn't look like mobile though. I don't know then.

**Comment by troggnostupidhs** [comment]
I can test on mobile.

**Comment by PattuX** [comment]
I'd not consider a picture of Wyrmrest Agent as intended q:

**Comment by troggnostupidhs** [comment]
Fixed

![hearthstone screenshot 03-01-17 02 36 28](https://cloud.githubusercontent.com/assets/22508641/23450208/f6f5d700-fe27-11e6-95b9-e9b4e6f80de7.png)
