### ISSUE TITLE
If a Anub'arak, Malorne, or a Weasel Tunneler is shuffled into a deck directly (Entomb, Madam Goya, etc), enemy minion positions may stop updating properly

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#664]
* https://www.youtube.com/watch?v=HhZr5Sa7Bms&t=3m12s
* https://www.reddit.com/r/hearthstone/comments/5hg0ld/incredibly_glitchy_game_of_tavern_brawl/ -> https://youtu.be/GRPEgp7pa5o
* https://www.reddit.com/r/hearthstone/comments/5hsyzm/greatest_glitch_so_far/ -> https://www.youtube.com/watch?v=YM8RUYVpIBk
* possibly https://us.battle.net/forums/en/hearthstone/topic/20752525740

May be additional unknown conditions, as it apparently does not always happen.

7.1 reports with Madam Goya and Weasel Tunneler:

* https://www.reddit.com/r/hearthstone/comments/5xhz72/madam_goya_and_weasel_tunneler_made_for_an/
* https://www.reddit.com/r/hearthstone/comments/5xdzel/thanks_madam_goya/
* https://www.youtube.com/watch?v=u8uwB1D4Ssw
* https://www.youtube.com/watch?v=epB2vgJJNag

Related to https://github.com/HearthSim/hs-bugs/issues/180

**Comment by Patashu** [comment]
Maybe also happens with Anub'arak?

https://www.reddit.com/r/hearthstone/comments/5i0e6n/his_minions_didnt_want_to_stay_on_the_board_so/ See screenshot, small versions of minions can be seen in hand

**Comment by Patashu** [comment]
Confirmed in 7.1 with a new example case

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6pww4o/if_you_entomb_an_anubarak_that_died_and_got/

> If you entomb an Anub'arak that died and got replayed, the game goes complete crazy
> https://www.youtube.com/watch?v=NtWNqX43C70

This is also possibly related to #180

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/712v2m/4_bugs_persisting_after_patch_91/

https://www.youtube.com/watch?v=Oaj3fMb1Zoc

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7i2qob/very_interesting_bug/

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8jjqx0/kazakus_anubarak_bug/

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/944fsm/strange_glitch_after_my_opponent_attacked_his/ Still happening

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/a5kbdy/in_honor_of_janalais_quick_fix_let_us_celebrate/ebo57ku/?context=3

**Comment by troggnostupidhs** [comment]
Weasel Tunneler and Anub'arak seem to be fixed with Entomb (I could not repeat the bug). I cannot currently test Madam Goya or Malorne.

![hearthstone screenshot 12-13-18 00 24 13](https://user-images.githubusercontent.com/22508641/49917831-bb7a1d00-fe6e-11e8-8499-4e6c0abfb804.png)

![hearthstone screenshot 12-13-18 00 27 27](https://user-images.githubusercontent.com/22508641/49917832-bb7a1d00-fe6e-11e8-933f-711a758bf6eb.png)

Priest
AAEBAa0GAA+zAfsBnALlBPUFuQaYDccXt2yxsALlvALRwQLiygKnzQKm8AIA

Rogue
AAEBAaIHAu0FmhQOswG/AfsBnAKFA5MEvQSbBbkGt2yxsALlvALiygKm8AIA

**Comment by troggnostupidhs** [comment]
Goya + Tunneler is fixed

![hearthstone screenshot 02-22-19 21 12 21](https://user-images.githubusercontent.com/22508641/53280569-97964b80-36e9-11e9-8b29-b6a9a39ac64f.png)


Deck
AAEBAa0GAvqwAvHGAg77AeUEuQaKB9MK1wqPDuyuAuW8AuG/AtHBAtnBAtPFAqbwAgA=
