### ISSUE TITLE
Anub'arak + Getaway Kodo causes Anub'arak to disappear from your hand

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#665]
* https://www.reddit.com/r/hearthstone/comments/5htnjt/weird_interaction_anubarak_dispatch_kodo/

"Sorry I could not get screenshots because I lost right after this happend
I was playing rogue and had anub'arak on the board, after anub'arak was killed it's deathrattle went off and it returned to my hand. Then dispatch Getaway kodo activated and anub'arak just disappeared completely from my hand
it was not on the board, not on my hand anymore, it just vanished"

**Comment by VoidMayonnaise** [comment]
https://youtu.be/lBnCKKXDE84
They interact correctly.
Interestingly, the 4/4 Nerubian is always summoned.

**Comment by troggnostupidhs** [comment]
I don't think this was ever confirmed, or reported besides in the linked post. I think it is invalid.
