### ISSUE TITLE
Faceless Manipulator can copy the Charge from Tundra Rhino

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#666]
* https://www.reddit.com/r/hearthstone/comments/5hy9vv/faceless_manipulator_on_a_beast_that_has_charge/

"Sorry for no screenshot, but today i was facing a hunter that had a tundra rhino and a misha on the board. I used faceless manipulator on the misha to gain taunt and hopefully prevent lethal (was not successful at that) and to my suprise the misha had charge even though tundra rhino's text is "your beast have charge". I'm not sure if this is a bug or if intended."

Seems related to https://github.com/HearthSim/hs-bugs/issues/634 .

**Comment by judge2020** [comment]
Confirmed: https://youtu.be/ew7Xo5Y_XBs

**Comment by Patashu** [comment]
This happened to Trump!

https://www.youtube.com/watch?v=bnmW81af3_I&feature=youtu.be&t=2578

**Comment by justinkb** [comment]
confirmed for 8.0.x - https://clips.twitch.tv/SolidArbitraryPorpoiseTBTacoLeft

**Comment by VoidMayonnaise** [comment]
https://youtu.be/Y_3_CMhCBsM
Already fixed.
