### ISSUE TITLE
Nozdormu ending turn immediately when pulled by Dirty Rat

### ISSUE THREAD

**Issue by judge2020** [HearthSim/hs-bugs#667]
https://redd.it/5i0ire

> Just had something pretty neat happen to me. I was playing against a C'thun OTK druid that had used idol to get a minion. My plan was to brann + dirty rat + MC tech to screw up his combo, but **as I summon dirty rat, my turn ends without allowing me to put down MC tech**
Yep, dirty rat had summoned his idoled Nozdormu about 15 seconds into the turn, ending it right away.
So, I guess I found the counter to the Rat & MC combo... ? Tech in Nozdormu...

> Edit : Apparently the bug is hard to replicate, hold on on crafting Nozdormu guys !

**Comment by Patashu** [comment]
I'll mark it as unconfirmed for now, since I know Nozdormu interactions can be influenced by a lot of gameplay-external stuff like how much your connection and computer are lagging.

**Comment by Patashu** [comment]
Confirmed invalid thx to Hysteria

https://www.youtube.com/watch?v=dakCvGIbnXk
