### ISSUE TITLE
Secret played by your opponent will display 0 mana

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#668]
This bug started appearing somewhere around the time Patches 6.1.3 or 6.2 have been released.
* https://www.reddit.com/r/hearthstone/comments/53dg3q/bugsecrets_appear_as_they_cost_0_mana/
* https://www.reddit.com/r/hearthstone/comments/53p03h/when_a_secret_is_played_it_shows_0_mana_instead/

When your opponent plays a secret, the card will show 0 mana cost when it enters play.

![hearthstone screenshot 12-14-16 20 59 08](https://cloud.githubusercontent.com/assets/11700272/21198587/349727e0-c240-11e6-96b8-7206ce056766.png)

**The same bug happens also in sidebar. Only the opponent sees the bug.**

After your opponent plays a secret, your sidebar will display 0 mana cost.

![hearthstone screenshot 12-14-16 20 59 21](https://cloud.githubusercontent.com/assets/11700272/21198596/3b4070a6-c240-11e6-9187-67eff00eb967.png)

**Comment by troggnostupidhs** [comment]
Fixed

![hearthstone screenshot 06-03-17 13 28 17](https://cloud.githubusercontent.com/assets/22508641/26755691/c73a6c32-4860-11e7-9ccc-28a4838459d2.png)

![hearthstone screenshot 06-03-17 13 29 13](https://cloud.githubusercontent.com/assets/22508641/26755692/cef9e4ac-4860-11e7-9df6-99fbc4c19f62.png)
