### ISSUE TITLE
In some Tavern Brawls, wins count for the wrong class

### ISSUE THREAD

**Issue by judge2020** [HearthSim/hs-bugs#669]
Multiple reports from users:

https://redd.it/5id7vj

https://redd.it/5ickt2

https://redd.it/5ic496

https://redd.it/5id8w3

https://redd.it/5idb3m

Based on user reports, the brawl will only award users quest wins for Hunter.

**Comment by troggnostupidhs** [comment]
I think this is a more general problem in brawls

https://www.reddit.com/r/hearthstone/comments/6u30um/this_weeks_tavern_brawl_is_encounter_at_the/

> Why can't you choose the class at least? Now i have to concede until I get druid or warlock. LUL.
Edit: WTF If you get the right class and someone concedes at the start you DONT GET QUEST PROGRESS

> It feels like its bugged. I have the daily quest to win with Shaman/Warlock, got Warlock in the Tavern Brawl, won and yet it did not award that win.

**Comment by troggnostupidhs** [comment]
Likely related to #732

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7r7g0x/theres_something_wrong_here/

![image](https://user-images.githubusercontent.com/22508641/35103721-b484742e-fc34-11e7-9a5c-e1463d48eca0.png)

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761036871

>Hey everyone, just an update on this particular issue. We are aware of it and we have confirmed it is happening. All classes in the Tavern Brawl are counting as Priest right now, so quests that require you to win with a specific class will not update (except for priest, and that will update with any class).
We are unlikely to be able to get a fix completed before this brawl ends, so plan on completing your quests in another mode for the time being.
Sorry for the inconvenience and thanks for understanding! :)

https://us.battle.net/forums/en/hearthstone/topic/20760896945

> Thanks for the report, we are looking into this issue. Locking this thread as we already have an active thread regarding this same thing :)

**Comment by troggnostupidhs** [comment]
> Hey everyone, just an update on this particular issue. We are aware of it and we have confirmed it is happening. All classes in the Tavern Brawl are counting as Priest right now, so quests that require you to win with a specific class will not update (except for priest, and that will update with any class).
We are unlikely to be able to get a fix completed before this brawl ends, so plan on completing your quests in another mode for the time being.
Sorry for the inconvenience and thanks for understanding! :)

**Comment by troggnostupidhs** [comment]
Not sure about the quests in the current brawl, but the exp is often 'wrong'

https://www.reddit.com/r/hearthstone/comments/9ozyhw/hallows_end_this_weeks_tavern_brawl_is_monster/

> Bosses above are not giving experience for their matching classes. For instance, Shudderwock is listed as a Warlock, but gives Shaman experience levels. Wharrgarbl is listed as Shaman, but gives xp for another class, etc. Yes, we have 3 Warlocks

**Comment by Jetz72** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/tavern-brawl-win-as-rogue-triggered-quest-completion/4442
>I just won a tavern brawl as rogue today, but the win triggered a quest completion for 50 gold for a win either as mage or hunter.

Reddit has similar reports: 
https://www.reddit.com/r/hearthstone/comments/bgwdja/this_weeks_tavern_brawl_is_hall_of_champions/elo31d2/

**Comment by troggnostupidhs** [comment]
This is likely not intended, based on this reply

https://us.forums.blizzard.com/en/hearthstone/t/no-credit-for-warlock-win-in-tavern-brawl/4455/5

> Thanks for the report! We are getting a hotfix rolled out to address this issue.

**Comment by judge2020** [comment]
closing as stale
