### ISSUE TITLE
'Force play' effects cause deaths to be resolved in the wrong order

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#67]
Deathlord, Voidcaller, Alarm-o-Bot, Ancestor's Call and Varian Wrynn all have in common that they forcefully move a minion from your hand or your deck into play. They all also have a bug in common that the minion thus summoned is the oldest in the order of play, not newest, when considering simultaneous Deaths. The order of play is non-bugged when considering triggers, such as end of turn trigger order or on-Death trigger order, or when considering other Events, such as simultaneous Damage.

More specifically, for the purposes of simultaneous Deaths, their 'timestamp' (which is updated when an Entity is generated (including summons, effects like Gang Up or at the start of the game) or played) is not updated when force played for the purposes of simultaneous Deaths, but is updated for all other simultaneous ordering purposes.

* https://www.youtube.com/watch?v=jIqPtOOyjQ4 (shows behaviour of Gang Up - force played minion created by Gang Up has the timestamp of Gang Up being cast, w/r/t simultaneous Death Event ordering)
* https://www.youtube.com/watch?v=4Tn2CDxet6k (shows Damage Event ordering, and trigger ordering on a Damage Event, are not affected by this bug)

For example, if a Sylvanas Windrunner is put into play by Deathlord, then later dies simultaneously, its death will always be considered first, no matter how many minions that died with it were played earlier. However, if you play a Flesheating Ghoul then gain one from an enemy Deathlord, they trigger in the expected order of play.

For Voidcaller:
http://www.reddit.com/r/hearthstone/comments/2y79lf/tested_voidcaller_sylvanas_deathrattle_order_bug/
http://www.reddit.com/r/hearthstone/comments/31sxjn/weird_sylvanas_voidcaller_interaction/

For Ancestor's Call:
https://www.youtube.com/watch?v=S7SD77OcIco

For Deathlord:
http://www.reddit.com/r/hearthstone/comments/2hj4ut/sylvanas_deathlord_and_deathrattle/
http://us.battle.net/hearthstone/en/forum/topic/15353777554
http://www.hearthpwn.com/forums/hearthstone-general/general-discussion/40338-weird-deathrattle-interaction
https://www.youtube.com/watch?v=xr_y4AqPUbY

For Alarm-o-Bot:
https://www.youtube.com/watch?v=pV6ruUnry1U

For Varian Wrynn:
https://www.reddit.com/r/hearthstone/comments/3iiiov/varian_deathrattle_order_bug/
https://www.youtube.com/watch?v=zM_MSE2wxqM&t=1m06s (watch until the Twisting Nether and notice Sylvanas steals nothing despite 'order of play')

**Comment by Patashu** [comment]
Two unknowns that need testing:

1) Does the minion force played go before heroes, or just before all minions?

2) Does the minion forced play have this bug for all simultaneous events, or only for simultaneous deaths? For example see http://pastebin.com/45iZraDa

**Comment by Patashu** [comment]
Still current: http://hearthstone.gamepedia.com/Advanced_rulebook#.27Force_play.27_and_play_order_bug

**Comment by culinko** [comment]
Happens with Varian Wrynn as well, confirmed on irc.

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/18704216607

Happens with Effigy, if this is accurate

**Comment by Patashu** [comment]
Our understanding of the 'force play and order of play' bug may be incorrect at the limit. A video by DisguisedToast shows that it isn't always oldest in global order of play, contrary to our documentation and expectations.

http://hearthstone.gamepedia.com/User_talk:Patashu#Limits_of_the_.27force_play_and_order_of_play.27_bug.27

**Comment by Patashu** [comment]
ZeroRin tested something - a minion created by gang up, then force played by a deathlord, triggered later than a minion that was on the field before gang up was casted.

The new theory is that a 'global play order' counter increments whenever an entity is generated, summoned or played from the hand, but not when it is force played.

To confirm this model, two tests need to be recorded:

1) Play Deathrattle minion A. Use Gang Up on Deathrattle minion B, and play a copy created by Gang Up. Play Deathrattle minion C. Kill A+B+C simultaneously. Do their Death Events resolve in order A-B-C or in order B-A-C?

2) Play Armorsmith/Frothing A. Force Play (such as using Alarm-o-Bot) Armorsmith/Frothing B. Play Armorsmith/Frothing C. Create a friendly Damage Event. Do they trigger in order A-B-C or order B-A-C?

**Comment by Patashu** [comment]
The tests have been run, and the hs-bugs entry has been updated with the results.

**Comment by 10925** [comment]
I think recently this bug has been fixed?
At this for deathlord?

**Comment by thlac** [comment]
Ancestor's call:
https://drive.google.com/open?id=0B0LI_KCnxv9Sb0dDLUxkeFNsZG8
Deathlord:
https://drive.google.com/open?id=0B0LI_KCnxv9SVmNJSTRpeGtneEk

**Comment by culinko** [comment]
All the recent tests and evidence shows that this bug has been recently fixed.
