### ISSUE TITLE
If you get the 'Join the Jade Lotus' quest at the same time as you start an arena match, an animation hang can occur

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#673]
* https://us.battle.net/forums/en/hearthstone/topic/20752586494

"I won my second match in arena and at the same time I got to complete a quest or two. I hit the Play button to start another match. Then things got messed up. The screen I had my reward from my quest with a Confirm button that just wouldn't go away, and I couldnt click on it. And while that confirm button was showing I couldn't click on anything else either so that basically got me to lose that match (which was my third loss so that arena session ended) 

I have a screenshot of what it looked like , you'll see one on top of each other the control for selecting my new cards in a new and the quest controls from the last quest i completed. The problem there is there is nothing on the screen I could click on at that point. I tried everything I could, Alt-tabbing back to windows, minimizing the screen, etc... nothing worked.

Here is the screenshot before I just hit Quit (Quit or Concede seem to be the only 2 options I could click on ....) https://1drv.ms/i/s!Ajnh7zOJgCiehy8iNks_hIeyrocv
"

![image](https://cloud.githubusercontent.com/assets/666597/21252903/af6bbf98-c3ae-11e6-95bc-a078ae39108f.png)

**Comment by troggnostupidhs** [comment]
Should this be closed because the quest has been removed?

https://hearthstone.gamepedia.com/Quest#Removed_quests

**Comment by troggnostupidhs** [comment]
This is still open because it could possibly happen with any of the overriding quests

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/b1unle/i_think_psychic_scream_is_rigged/

**Comment by troggnostupidhs** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/new-quest-keeps-looping/1131

**Comment by troggnostupidhs** [comment]
So this was left open to see if Legendary Quests would generally have this problem, and they don't seem to. If there are any other Legendary Quests with animations like the ones in this issue and they cause the same problem, we can reopen this ticket.
