### ISSUE TITLE
Kabal Chemist does not generate Dragonfire Potion

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#680]
It was tested by a weibo (Chinese twitter) user,here is a chinese list:

![image](https://cloud.githubusercontent.com/assets/235410/21960665/376280d6-dafb-11e6-9b72-b4000144b9b9.png)

He repeated totally 1419 times, and no Dragonfire Potion was generated.

**Comment by troggnostupidhs** [comment]
| Name                   | Count | Percentage | 
|------------------------|-------|------------| 
| Blastcrystal Potion    | 3     | 12.00%     | 
| Bloodfurry Potion      | 3     | 12.00%     | 
| Dragonfire Potion      | 0     | 0.00%      | 
| Felfire Potion         | 2     | 8.00%      | 
| Freezing Potion        | 3     | 12.00%     | 
| Greater Healing Potion | 4     | 16.00%     | 
| Pint-Size Potion       | 2     | 8.00%      | 
| Potion of Madness      | 4     | 16.00%     | 
| Potion of Polymorph    | 2     | 8.00%      | 
| Volcanic Potion        | 2     | 8.00%      | 
| Total                  | 25    | 100.00%    |

**Comment by troggnostupidhs** [comment]
Personal results, 51 attempts.

| Name                   | Count | Percentage | 
|------------------------|-------|------------| 
| Blastcrystal Potion    | 4     | 7.84%      | 
| Bloodfurry Potion      | 6     | 11.76%     | 
| Dragonfire Potion      | 0     | 0.00%      | 
| Felfire Potion         | 4     | 7.84%      | 
| Freezing Potion        | 6     | 11.76%     | 
| Greater Healing Potion | 8     | 15.69%     | 
| Pint-Size Potion       | 7     | 13.73%     | 
| Potion of Madness      | 7     | 13.73%     | 
| Potion of Polymorph    | 7     | 13.73%     | 
| Volcanic Potion        | 2     | 3.92%      | 
| Total                  | 51    | 100.00%    |

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/5l63x1/kabal_chemist_does_not_generate_dragonfire_potion/

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/5lguhl/yong_woo_responds_to_kabal_chemist_bug/

https://twitter.com/ywoo_dev/status/815417240371609600

> @Super_Newman @reddit we are looking into fixing this one when we return next week!

**Comment by troggnostupidhs** [comment]
It is working now.

![hearthstone screenshot 01-23-17 22 53 00](https://cloud.githubusercontent.com/assets/22508641/22233615/7c162960-e1bf-11e6-9b8d-9fb42e0b0858.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/5prxh6/kabal_chemist_now_gives_dragon_fire_potion/

**Comment by troggnostupidhs** [comment]
https://twitter.com/troggnostupidhs/status/824365156142641152

@ywoo_dev The Kabal Chemist bug is fixed (thank you). But how/when did this happen? There's no patch or hotfix notes for the change.

@troggnostupidhs the fix went out a few days ago. We'll definitely do better about announcing notes for these changes.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/13840764128?page=2

> * Addressed an issue where Kabal Chemist would not offer Dragonfire Potion as a valid potion option.
> * Addressed an issue where retiring an Arena deck on mobile would cause the next Arena run to display an Arena completion key on the selection of the 30th card.
