### ISSUE TITLE
"Battle of Tol Barad!" Discard Visual Glitch

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#685]
Discarding a generated spell card in the Battle of Tol Barad! Tavern Brawl leaves part of the card animation on the screen. After this happens, the Hero Power may not always be accessible.

https://www.reddit.com/r/hearthstone/comments/5svfms/brawl_discard_bug/

https://www.reddit.com/r/hearthstone/comments/5suv15/bug_tb_discarding_a_card_as_its_generated_causes/

![image](https://cloud.githubusercontent.com/assets/22508641/22757588/7b409cee-ee19-11e6-915b-473cb26e6ffb.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/5svi3m/bug_if_a_card_is_discarded_while_a_minion_is/

**Comment by Patashu** [comment]
Please merge this into https://github.com/HearthSim/hs-bugs/issues/51

**Comment by troggnostupidhs** [comment]
This is a duplicate of https://github.com/HearthSim/hs-bugs/issues/51z
