### ISSUE TITLE
Sense Demons leaks when opponent draws Worthless Imps

### ISSUE THREAD

**Issue by dutchgecko** [HearthSim/hs-bugs#686]
I noticed while playing this week's brawl that my opponent played Sense Demons and HS Deck Tracker was able to determine that the cards drawn were external to the deck (marked with the gift box icon). The cards he played were indeed Worthless Imps.

Unsure if this is intentional or not.

**Comment by Patashu** [comment]
Don't see how this is a bug - you can tell how many cards Sense Demons drew by mousing over their deck before and after casting. And I think it even does the 'drawing' animation, and obviously for every card that isn't drawn, that's one Worthless Imp they got instead.

**Comment by dutchgecko** [comment]
Yeah, card counting actually makes a lot of sense. Please ignore my noise :)
