### ISSUE TITLE
Smuggler's Crate can reveal which card in the hand is being buffed

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#687]
* https://www.reddit.com/r/hearthstone/comments/5u1ino/smugglers_crate_bug_reveals_a_card_in_hand_on/

For comparison, Trogg Beastrager does not.

There may or may not be an additional condition for the card to be revealed.

**Comment by troggnostupidhs** [comment]
Fixed

Deck
AAEBAR8AD40B+wGcArQCuQbEDumrAritArm0Auq7Aue9AqbBAonDAo7DAtfNAgA=

![img000](https://user-images.githubusercontent.com/22508641/32925172-88bb263c-cb0e-11e7-9e6a-298ac0c4aa02.png)
