### ISSUE TITLE
[Invalid] When Krul the Unshackled‘s battlecry summons Mal'Ganis, your hero is immune to the damage from Unlicesed Apothecary

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#689]
I guess there is also an Aura Update (Other) before SRS.
(http://pic3.178.com/3769/37692309/month_1702/82aefd1e4cb7662e400f15dbb17a224e.jpg)

**Comment by Patashu** [comment]
I guess this isn't a bug, just a change in our understanding of mechanics.

I already put it here. Anything else need to change? https://hearthstone.gamepedia.com/Advanced_rulebook#Summon_Resolution_Step

**Comment by Kybxd** [comment]
OK That's all.
