### ISSUE TITLE
Mobile game crashes when tapping a card played by your opponent

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#694]
https://www.reddit.com/r/hearthstone/comments/5wr60l/bug_mobile_gamebreaking_crash_glitch/

https://www.reddit.com/r/hearthstone/comments/5wqk9r/game_is_crashing_after_update/

https://www.reddit.com/r/hearthstone/comments/5wr4sj/am_i_the_only_one_experiencing_problems_on_mobile/

https://www.reddit.com/r/hearthstone/comments/5wqjvd/new_mobile_bug/

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/5wvzf9/ios_bug_tapping_on_the_cards_your_opponent_plays/

**Comment by troggnostupidhs** [comment]
> The fix for this is on the way. If all goes well the optional patch will be available for everyone very soon.
>
> In the meantime, a work around is to keep your hand of cards minimized. The crash occurs specifically when your hand is up AND you click on the opponent's played card.
> 
> Sorry for the inconvenience guys!

https://www.reddit.com/r/hearthstone/comments/5y7z2b/blizzard_really_needs_to_fix_the_ios_bug/deo0o0c/

**Comment by PattuX** [comment]
Fixed according to iOS Patch Notes

**Comment by troggnostupidhs** [comment]
There haven't been any reports.
