### ISSUE TITLE
Copies of minions which had temporary stealth earlier also gain temporary stealth

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#696]
seems relate to #662 
Report from NGA:http://bbs.nga.cn/read.php?tid=11110713&_ff=422
"last turn i play conceal, this turn i play Herald Volazj and got 3 stealth minion"
screenshot:http://imgur.com/a/BVniL

I think that's because the buff from conceal and "charge" card effect would stay on the minions.
And these buffs would apply on the first turn. Since the copy minions' first turn appear on board, so they apply the buffs.

**Comment by PattuX** [comment]
Definetely related, nice catch.

I'll label this as may-be-intended for now, as #662 is as well, but I guess it's up for discussion.

**Comment by PattuX** [comment]
This is also very simmilar to #383 as both are caused by the Conceal/Master of Disguise Enchantment not being removed.

**Comment by troggnostupidhs** [comment]
Is this fixed?

Deck
AAEBAZICAu0FrqsCDkDpAfsBtAKTBLQFuQaCEPQR6haXaLazApC2AqTCAgA=


![img000](https://user-images.githubusercontent.com/22508641/30823126-33e9f2ca-a1f9-11e7-84fb-9639b481917f.png)
![img001](https://user-images.githubusercontent.com/22508641/30823124-33e5770e-a1f9-11e7-9d4d-35d6c765ea71.png)
![img002](https://user-images.githubusercontent.com/22508641/30823125-33e54504-a1f9-11e7-9a45-5ac070b7355a.png)
![img003](https://user-images.githubusercontent.com/22508641/30823123-33e53f46-a1f9-11e7-9340-0838bc6c9146.png)

**Comment by troggnostupidhs** [comment]
Deck
AAEBAYO6AgbZAu0F9waDrALJvwKA0wIMtAGbBYgH0hXEFvKwApK2ApS2Avi9AoHCApvIApTQAgA=

![img000](https://user-images.githubusercontent.com/22508641/30872828-61e66792-a2b9-11e7-916f-70f37ec93197.png)
![img001](https://user-images.githubusercontent.com/22508641/30872827-61e5b874-a2b9-11e7-872a-12024ddebd2c.png)
![img002](https://user-images.githubusercontent.com/22508641/30872830-61e9fd1c-a2b9-11e7-9cb7-c04f294227fe.png)
![img003](https://user-images.githubusercontent.com/22508641/30872829-61e90b28-a2b9-11e7-82bc-00ae5d3a115f.png)

**Comment by troggnostupidhs** [comment]
Tested with Conceal just to be sure

![img000](https://user-images.githubusercontent.com/22508641/30874650-00129e0e-a2bf-11e7-869d-fe7cc57cf48a.png)
![img001](https://user-images.githubusercontent.com/22508641/30874652-001ac4a8-a2bf-11e7-9084-2de5449f680b.png)
![img002](https://user-images.githubusercontent.com/22508641/30874651-0015a612-a2bf-11e7-8ed8-918c8352f7c3.png)
