### ISSUE TITLE
The 1/1 copies of silenced minions summoned by Herald Volazj are not silenced

### ISSUE THREAD

**Issue by doctorinsecto** [HearthSim/hs-bugs#699]
Silenced my opponent's Lorewalker Cho. He summons Herald Volazj, which summoned a 1/1 copy of Lorewalker Cho, also silenced, but when I casted a spell the 1/1 copy was still able to make a copy of the spell for my opponent.

**Comment by Patashu** [comment]
Confirmed with video.

https://www.youtube.com/watch?v=5815hLqyG2c&feature=youtu.be&t=3m14s

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/60hupq/found_a_bug_with_kodo_rider_herold_volajz/

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20753876336

> When Herald Volazj copies a silenced minion, the copies it creates will now correctly also be silenced.
