### ISSUE TITLE
You can enter the Tavern Brawl queue from the deck editing page

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#7]
You can enter the Tavern Brawl queue from the deck editing page.

* https://www.reddit.com/r/hearthstone/comments/3bar82/you_can_go_into_tavern_brawl_queue_through_the/

**Comment by deetr-** [comment]
Unable to replicate on 3.1.0.10357, Windows, Fullscreen, 1920x1080. Potentially fixed?

**Comment by culinko** [comment]
I can confirm it being fixed.
