### ISSUE TITLE
When a card's state changes while invisible to the opponent, the old state will be displayed to the opponent when played

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#70]
When you buff Alarm-o-Bot with a spell (for example Blessing of Kings) before it swaps for another minion and replay the Alarm-o-bot again, it will display incorrect stats on the card (only for the opponent) when it enters the play (4/7 instead of 0/3).

![ter3wre](https://cloud.githubusercontent.com/assets/11700272/11577572/fc447720-9a1e-11e5-8c08-ee14f69be8fd.jpg)

**The same bug happens also in sidebar. Only the opponent sees the bug.**

If your opponent buffs Alarm-o-Bot with a spell such as Blessing of Kings before it swaps for another minion and re-play the bot again, your sidebar will display incorrect stats (4/7 instead of 0/3).

![8thusgr](https://cloud.githubusercontent.com/assets/11700272/11577669/d2c25f7e-9a1f-11e5-8ea7-da8f00f2efa4.png)

Your opponent's sidebar will show the base stats correctly.

![m45svlq](https://cloud.githubusercontent.com/assets/11700272/11577675/da970b64-9a1f-11e5-9bb8-a15add34ffc4.png)

**Comment by culinko** [comment]
This can be observed by buffs and auras that enchant the minion when in hand. Because Swap is different than Return to hand (#90), this can be observed by buffs and auras that enchant minions on the board as well.

**Comment by culinko** [comment]
Observed with Entomb in 4.0: https://www.reddit.com/r/hearthstone/comments/3tht9k/fun_observation_about_entomb/

**Comment by culinko** [comment]
The visual bug with Entomb + minion with modified stats/damaged was fixed in the meantime.

**Comment by culinko** [comment]
This bug has been fixed in the meantime.
