### ISSUE TITLE
If Patches the Pirate can't be played from deck due to full board, he is revealed when later drawn

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#700]
* https://clips.twitch.tv/ColorfulAstuteCookieImGlitch

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 03-20-17 21 48 39](https://cloud.githubusercontent.com/assets/22508641/24129189/3f489d3c-0db7-11e7-8755-14afe5312e2e.png)

**Comment by troggnostupidhs** [comment]
Screenshot was a bit late. I was able to reproduce this bug.

**Comment by troggnostupidhs** [comment]
Happens in All-Star Squad brawl

https://www.reddit.com/r/hearthstone/comments/6k243m/found_a_bug_why_is_it_showing_me_the_card_he_is/

**Comment by Velken** [comment]
Recorded video of the glitch (my d3dgear wasnt working):
https://youtu.be/Rzq0iTIBhZ0

**Comment by troggnostupidhs** [comment]
This is fixed.

Deck
AAECAf0GArasApG8Ag6BApwC1AWKBp4H0AflB+cHiq0C9q4Cp7ICw7QCocICxssCAA==
