### ISSUE TITLE
Commanding Shout's effect is copied by Mirror Entity

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#703]
* https://www.reddit.com/r/hearthstone/comments/61cvas/interesting_interaction_i_found_during_tavern/

This is inconsistent with Commanding Shout's new behaviour, which, for example, will stop giving the Enchantment to minions that are stolen from you after casting (such as via Sylvanas Deathrattle):

https://hearthstone.gamepedia.com/Commanding_Shout

**Comment by Kybxd** [comment]
Still happening in the recent patch.
* http://imgur.com/a/nqtr2

**Comment by troggnostupidhs** [comment]
Fixed

![img000](https://user-images.githubusercontent.com/22508641/32643644-ca434eea-c5aa-11e7-89c8-33e47ecc2308.png)
![img001](https://user-images.githubusercontent.com/22508641/32643645-ca4dc03c-c5aa-11e7-8702-f4a9943f5ff8.png)

**Comment by troggnostupidhs** [comment]
This is fixed.

![img000](https://user-images.githubusercontent.com/22508641/32643957-9ea6d516-c5ac-11e7-8e46-79a275be6c20.png)
![Uploading img001.png…]()
