### ISSUE TITLE
Alarm-o-Bot reduced to 0 mana cost by Far Sight remains 0 mana even after returning to your hand

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#705]
* https://www.reddit.com/r/hearthstone/comments/63bsix/i_found_a_super_cool_bug/

![image](https://cloud.githubusercontent.com/assets/666597/24641166/932ea1a0-1940-11e7-835f-0fe2bf65eda9.png)

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 04-29-17 19 00 11](https://cloud.githubusercontent.com/assets/22508641/25560806/d4fba6ec-2d2b-11e7-9145-4a5815b5773d.png)

**Comment by troggnostupidhs** [comment]
Potentially fixed

http://eu.battle.net/hearthstone/en/blog/20811880/hearthstone-update-june-1-01-06-2017

**Comment by troggnostupidhs** [comment]
Fixed

![hearthstone screenshot 06-03-17 15 41 21](https://cloud.githubusercontent.com/assets/22508641/26756711/df9ea0de-4876-11e7-9fe7-20e9cbd4117e.png)
