### ISSUE TITLE
Anub'ar Ambusher returning attacking minion causes visual glitch

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#71]
If Anub'ar Ambusher dies to Explosive Trap, and its Deathrattle tries to return the surviving attacking minion (that triggered the trap) to your hand, the minion will appear glitched out on the playing field. If you click on the empty space where the returned card should be, the card will appear back in your hand.

* https://www.youtube.com/watch?v=wYvp4dtNExM
* http://us.battle.net/hearthstone/en/forum/topic/17084278501
* http://us.battle.net/hearthstone/en/forum/topic/17605532212
* http://us.battle.net/hearthstone/en/forum/topic/19288248889

**Comment by Patashu** [comment]
Confirmed in 3.1

http://us.battle.net/hearthstone/en/forum/topic/19288248889

**Comment by culinko** [comment]
Tested in 4.1, it's fixed! (or have been for some time).
