### ISSUE TITLE
Living Mana destroys temporary mana crystals without summoning 2/2s

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#713]
In the video, Toast double innervates from 5 to 9 mana. He receives five 2/2s but is brought back to 0/0 mana instead of 4/0 (or instead of getting seven 2/2s and ending up at 2/0 mana)

* https://youtu.be/K-P5nW23DbE?t=45s

**Comment by 10925** [comment]
Personally I didn't think this is a bug. It's actually card uses temporary mana first.
So you got 9/5 mana,uses living mana,become 4/5(use 4 temporary mana and 1 stable mana),then the spell finds you got 5 stable mana（1 empty and 4 full), then destory them and summon 5 2/2s.

**Comment by VoidMayonnaise** [comment]
I agree with 10925. This shouldn't be a bug, just like Innervate & Wild Growth won't give you a card when you have 8/8 mana crystals, because you will firstly spend temporary crystals, then you have 8/8 mana crystals at the start of the Spell Phase.
Need to retest by Innervate*3 & Living Mana when you have less than 4 crystals.

**Comment by troggnostupidhs** [comment]
I believe starting with 4 mana crystals is okay. It gets to 10 mana, 6 temp crystals and 4 permanent ones. Playing Living Mana uses 5 temp crystals, leaving 1 temp and 4 permanent. 

The result is that 4 minions are summoned, not 5.

![2017-06-14](https://user-images.githubusercontent.com/22508641/27163393-0966338c-5155-11e7-84c7-9f9e780c69e2.png)

![2017-06-14 1](https://user-images.githubusercontent.com/22508641/27163398-0de83b12-5155-11e7-9d48-bbcde59ada25.png)

**Comment by 10925** [comment]
So that's same to my oponion.
Card uses temporary mana first.
Living mana would only transform permanent ones(either full or empty).
So 6-5,they leave the uncost temporary mana there. And 4-4,all permanent ones transforms.

**Comment by troggnostupidhs** [comment]
I think it is intended.

https://www.youtube.com/watch?v=0L2NiuVi-VQ&feature=youtu.be&t=3m18s
