### ISSUE TITLE
Amara, Warden of Hope deals damage instead of setting your Health if you have Embrace the Shadow/Auchenai Soulpriest effect

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#714]
* https://www.reddit.com/r/hearthstone/comments/63w2i2/psa_amara_does_not_work_like_alexstrasza/
* https://www.reddit.com/r/hearthstone/comments/63uull/til_auchenai_soul_priestembrace_the_shadow_makes/

Apparently it heals you for 40 after setting your max Health to 40, so maybe it also triggers Lightwarden/etc?

**Comment by Kybxd** [comment]
Fixed in the recent patch.
* http://imgur.com/a/1UUHr

**Comment by troggnostupidhs** [comment]
Confirmed this is fixed.
