### ISSUE TITLE
Giant Anaconda can force play 5+ Attack weapons, like Gladiator's Longbow

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#715]
* https://www.reddit.com/r/hearthstone/comments/63wb2a/bug_with_giant_anaconda/
* https://www.reddit.com/r/hearthstone/comments/64cj5h/giant_anaconda_bug/

**Comment by Patashu** [comment]
2nd report, so now confirmed: https://www.reddit.com/r/hearthstone/comments/64cj5h/giant_anaconda_bug/

**Comment by PattuX** [comment]
https://us.battle.net/forums/en/hearthstone/topic/13840764128?page=2#post-23

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 05-03-17 22 26 46](https://cloud.githubusercontent.com/assets/22508641/25688855/87e817f0-3050-11e7-87a5-feeb6e750f89.png)

![hearthstone screenshot 05-03-17 22 27 24](https://cloud.githubusercontent.com/assets/22508641/25688858/8aee676a-3050-11e7-9f2d-b928cd803aae.png)

![hearthstone screenshot 05-03-17 22 27 31](https://cloud.githubusercontent.com/assets/22508641/25688859/8cd03982-3050-11e7-8575-b7589a61b683.png)

**Comment by troggnostupidhs** [comment]
Giant Anaconda does not play Gladiator's Longbow
