### ISSUE TITLE
The 1/1 copy from Herald Volazj cannot apply Crystal Core's effect

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#716]
![qq 20170407105843](https://cloud.githubusercontent.com/assets/15797857/24783809/2d06ef02-1b81-11e7-8f8b-cf6c9df8c8b1.png)

**Comment by Patashu** [comment]
Case for this being a bug: Herald Volazj + Sword of Justice used to result in a 1/1, it now results in a 2/2.

Case against this being a bug: If Herald Volazj and The Crystal Core are the same 'kind' of effect, timestamp order is used to break ties. Herald Volazj is newer than The Crystal Core. Therefore, the minion becomes a 5/5 then a 1/1 in timestamp order.

I'll put the may-be-intended label to reflect that this is unclear.

**Comment by Patashu** [comment]
I just found out that 1/1 minions created by Barnes and Shadowcaster become 5/5s, even though Herald Volazj/Mirage Caller minions stay as 1/1!

https://youtu.be/SDKrjs7TfQg?t=662

I think I understand why now.

Barnes/Shadowcaster case: Crystal Core Aura likely acts with some between Phases timing, like Aura Update (Health/Attack) or SRS. At this point, the Battlecry Phase has already finished, and the minion is both summoned and set to 1/1. The Crystal Core Aura's Enchantment is then attached, and since it has normal priority, the Enchantment list is now [set to 1/1, set to 5/5] which results in a 5/5.

Herald Volazj/Mirage Caller case: When you copy a minion, you copy all attached enchantments. A copy of a friendly minion copies the attached Crystal Core Enchantment. After the copying is finished, the minion is set to a 1/1. Crystal Core does not re-apply, because the game sees Crystal Core as already having affected that minion. So the Enchantment list is now [set to 5/5, set to 1/1] which results in a 1/1.

While unintuitive, this follows all existing rules without need to invoke any previously unknown new rule. So, 'may-be-intended' label is kept for now.

**Comment by Kybxd** [comment]
Proof for Crystal Core being a AU trigger: 
* https://youtu.be/VHSr3ENUw3s

Obviously different from Miniature Warfare Tavern Brawl rules (SRS trigger): 
* http://imgur.com/s0PGlM4

**Comment by Patashu** [comment]
Another piece of info:

https://www.reddit.com/r/hearthstone/comments/664ll0/i_was_interested_how_the_quest_rogue_deck_would/

Crystal Core vs Big Bad Wolf (ONiK).

When you play Crystal Core all your minions become 5/5.

Future played minions become 1/1s.

**Comment by TTCrackers** [comment]
I encountered another issue with Crystal Core and Redemption. I was playing on ladder and got Redemption from Swashburglar and then, my Youthful Brewmaster died and came back as a 5/4 with Crystal Core active.
I was then testing it with my friend using other cards and Stonetusk Boar came back as a 5/5, Igneous Elemental 5/3 and Stegodon 5/1. 
I think the way Redemption is coded is that the minion takes damage -1 of his initial base health. Therefore, Boar -0, Brew -1, Igneous -2, Stegodon -5 (can't go below 1 health). But, it makes Crystal Core really inconsistent with other cards in the game

![hearthstone screenshot 04-18-17 17 40 24](https://cloud.githubusercontent.com/assets/28037684/25419073/3f10b7a4-2a1e-11e7-8a70-661274f9d0e3.png)
![hearthstone screenshot 04-25-17 22 50 05](https://cloud.githubusercontent.com/assets/28037684/25419077/4660fb0e-2a1e-11e7-9a4f-2c58480a6811.png)
![hearthstone screenshot 04-25-17 22 57 44](https://cloud.githubusercontent.com/assets/28037684/25419083/50807ca4-2a1e-11e7-8434-194e67108a53.png)

**Comment by Patashu** [comment]
Very weird. That should probably be its own issue. It reminds me of the (fixed) https://github.com/HearthSim/hs-bugs/issues/472 .

**Comment by 10925** [comment]
C'thun one is wired because the health is set to full,I think this one is normal.

Just the buff set lately than redemption.

Use Youthful Brewmaster as an example, first brewmaster summoned by Redemption, so summon a 3/1(max health 2)minion, then apply the buff.
As we know, when max health increase, current health would increase the same number (for example slience a Yesra buffed by hunter's mark, the max health increse 11 point, so current health would increase same point too,so we got a 4/12(max health 12) Yesra, not a 4/1(mh 12) one.)
So max health increase 3 point, current health increse 3points too, thus,we got 5/4(max health5) brewmaster.

Then what about mh more or equal to 5 minion?
It's also apply to the same idea, when current health is lower than the new max health, it wouldn;t change, when current health is higher than the new max health, it would change to the new max health.

Thus, since 1hp is lower than 5(new mh),so it would stay at 1.

C'thun one is wired, just because the hp is not equal to max hp-5, but full max hp, the buff of C'thun clear the damage point of C'thun make it wired.

**Comment by Patashu** [comment]
@10925: What about when you have a board of damaged minions and play Crystal Core? They become 5/5s, not 5/xs with some level of damage. Shouldn't Redemption vs Crystal Core work the same as damaged minions vs Crystal Core? You can also steal a minion after playing Crystal Core and it gets the buff, it becomes a 5/5 not damaged 5/x. That's why I think it's a bug.

**Comment by 10925** [comment]
Yeah, it could make Crystal Core applied before set reamain health to 1(which means make 5/1 minions) to make it easy to see.

Set demage point to 0(which means 5/5s) is also make sense for a buff like Keeper of Uldaman's buff, but may make player confused?

**Comment by TTCrackers** [comment]
I think people would be less confused if the minion is always resummoned as a 5/5... instead of sometimes a 1/1-->Herald Volazj/Mirage Caller, sometimes a 5/5 -->Barnes, Hex, Polymorph, Devolve, sometimes a 5/x --> Redemption.

**Comment by Patashu** [comment]
Fixed an issue where Sergeant Sally would only deal 1 damage to enemies when interacting with Crystal Core and Spiritsinger Umbra is in play.

^ This may or may not indicate a generic change in how Crystal Core works.

**Comment by 10925** [comment]
Yeah, I found some report in nga that Herald Volazj's copy minion would be stay in 5/5.

**Comment by Patashu** [comment]
@10925: When you understand how Crystal Core now works, let's update the wiki.

**Comment by 10925** [comment]
@Patashu 
So the way the fixed the bug is make  Herald Volazj and Mirage Caller didn't copy the buff of Crystal Core.
You can try to use priest to take control of a minion with core's buff, and you use Herald Volazj/Mirage Caller on it, you cannot find the core's buff on the buff list of the 1/1s.

And now, about the Crystal Core's buff, I believe it just immediately apply on summon minions and do a Aura Update, so for now, all kinds minions would Redemption at 1 health, and the update it's just before after summon phase(which means Sword of Justice would apply normally too),

so when a minion without buff is summon:
Minion Enter's play
get the core's buff and get a aura update
After Summon Phase

All in all:
Core's buff still only apply once, if heartstone find a minion has the buff, it wouldn't apply it again.
Herald Volazj and Mirage Caller was hard coded to not copy Core's buff.
Core's buff now apply before after summon phase for summoned minion without buff.

**Comment by Patashu** [comment]
OK, I think I made all the necessary edits then: https://hearthstone.gamepedia.com/The_Caverns_Below#Notes

**Comment by troggnostupidhs** [comment]
Is this 'fixed'?

**Comment by Patashu** [comment]
I guess so.

**Comment by TTCrackers** [comment]
Nope
![hearthstone screenshot 05-30-17 16 33 56](https://user-images.githubusercontent.com/28037684/27000444-34259ae6-4d80-11e7-833c-cb7d68500c06.png)

**Comment by TTCrackers** [comment]
Herald Volazj with Crystal Core now summons 5/5 
![hearthstone screenshot 06-27-17 18 01 20](https://user-images.githubusercontent.com/28037684/27698225-71bdd10e-5cc4-11e7-877a-e0f80a6e53f0.png)
