### ISSUE TITLE
Collection Manager New Card Bug

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#717]
The new card bug is back.

Reproduction steps:
1. Have 'new' cards
1. Open the Collection Manager
1. Mark any number of cards as read
1. Restart the Hearthstone client
1. Go back to the Collection Manager
1. The cards are still marked as 'new'

![image](https://cloud.githubusercontent.com/assets/22508641/24784226/14e5a2ae-1b1f-11e7-8a81-18358e0753e8.png)

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/13840764128?page=2#post-22

> Resolved an issue where Journey to Un'Goro cards would always show up as "New" in the Collection Manager.

**Comment by riQQ** [comment]
This one is back for me.

**Comment by troggnostupidhs** [comment]
Same for me.

**Comment by troggnostupidhs** [comment]
It's in the Blizzard client

![image](https://user-images.githubusercontent.com/22508641/29192245-b4b43232-7dee-11e7-8255-662919be1e7d.png)

**Comment by troggnostupidhs** [comment]
Most reliable work around I found. 

1. Go to the Collection Manager
1. Set the filter to KFT
    1. Do not do anything else
    1. Do not search for anything
1. Mouse over all of the 'new' cards
1. Back out of the Collection Manager
1. Restart the client

**Comment by troggnostupidhs** [comment]
It might be fixed now.

**Comment by riQQ** [comment]
Looking good at my end.

**Comment by PattuX** [comment]
https://youtu.be/3yZtKq_iTzs?t=4m8s

They apprearently do that intentionally to relieve the load on the servers. Explains why this happened quite unregularly and wasn't necessarily connected to patches.
