### ISSUE TITLE
Big Game Hunter/Stormpike Commando have incorrect animation if replayed

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#72]
If you use Big Game Hunter or Stormpike Commando's Battlecry, return it back to your hand and then replay the minion at a different board position, their subsequent Battlecry visual effect will appear from original location where they were initially played (your opponent does not see this bug).
http://us.battle.net/hearthstone/en/forum/topic/12504790898
https://www.youtube.com/watch?v=PvtAp0iEeZw

**Comment by Patashu** [comment]
Note that Lightbomb was changed in 3.0 to do all its damage simultaneously. However, Avenging Wrath will still display the bug (if it is not fixed yet).

**Comment by culinko** [comment]
Hemet Nesingwary shares the same animation, confirmed it in 4.1 against an adventure boss.

**Comment by troggnostupidhs** [comment]
This is fixed for me.
