### ISSUE TITLE
Tar Creeper's Aura doesn't have a late priority (Barnes + Tar Creeper remains 1/1)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#721]
* https://www.reddit.com/r/hearthstone/comments/641480/tar_creeper_off_barnes_stays_11_on_your_opponents/

May happen with the other Tar Xs too

**Comment by PattuX** [comment]
With the Rogue Quest completed, Tar Creeper stays a 5/5, even at your opponent's turn

* https://www.reddit.com/r/hearthstone/comments/647vtf/tar_creeper_doesnt_work_as_stated_in_its_text/

Some comments also say that Aldor will change it's attack to 1 permanently.

I think it might be not coded as an Aura, but as a constantly toggling Enchantment.  I haven't looked at any logs yet tho, so just speculating for now.

**Comment by Patashu** [comment]
I mean it's the same bug as Cogmaster, where it worked as an Aura, but the Aura was coded with the wrong priority (normal rather than late) so it could be superceded by later Enchantments (which, by definition, was every Enchantment lol)

**Comment by ThePlayer14** [comment]
I think the enchantments override the Aura effect, like an Aldored "tiny pirate" will stay at 1 Attack, despite its owner has a weapon, and it will not change unless the owner equips a weapon again.

**Comment by 10925** [comment]
Seems being fixed.
Here is a test with humanlity.
https://drive.google.com/file/d/0B2RvTv3FXN-pN1dXbVVfZHJlc3c/view?usp=sharing
I also see Sunkeeper Tarim's battlecry make oppoent's Tar Creeper became 5/3 in a stream. So it should be fixed,
