### ISSUE TITLE
Volatile Elemental doesn't ignore mortally wounded targets

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#725]
* https://www.reddit.com/r/hearthstone/comments/647prj/if_multiple_volatile_elementals_die_at_the_same/

**Comment by PattuX** [comment]
https://us.battle.net/forums/en/hearthstone/topic/13840764128?page=2#post-23

**Comment by VoidMayonnaise** [comment]
https://youtu.be/kapgTSOIl3o
Confirmed to be fixed.
