### ISSUE TITLE
When your deck had no spells, shadow vision may return the lastest card that discoverd by previous shadow vision.

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#726]
https://www.reddit.com/r/hearthstone/comments/648ipc/bug_shadow_visions_adding_a_card_to_opponents_hand/

And a chinese streamer, his first shadow vision got a shadow vision(copy), then he got all the spells, then when he used the shadow vision(copy), the shadow vision(copy) returned to his hand back and back again.

So when the player of shadow vision had no spells.
The shadow vision would returned the last card that latest shadow vision copied(if the owner already use it).

**Comment by PattuX** [comment]
Can you link a video if possible? The reddit post was deleted :/

**Comment by 10925** [comment]
Here is the replay in the post:
https://hsreplay.net/replay/3FsCEKdqg5DzBDrZ9u3bcM

The mage use shadow vision get a frost nova at turn 7, use it at turn 8.
Priest use his the last shadow vision at turn 11, and a frost nova add to mage's hand.

**Comment by Patashu** [comment]
https://www.reddit.com/r/hearthstone/comments/64btte/crazy_priest_game_results_in_an_11_card_hand_bug/

It looks like it can break the 10 card in hand limit.

**Comment by PattuX** [comment]
Another example, this time the player who cast Shadow Visions also cast the last Shadow Visions and therefore gets the card he discovered with his last Shadow Visions:

https://www.reddit.com/r/hearthstone/comments/64c587/bugged_interaction_with_elises_ungoro_pack_and/

**Comment by troggnostupidhs** [comment]
Is this relevant to this bug?

https://www.reddit.com/r/hearthstone/comments/64lhjn/shadow_vision_bug/

**Comment by PattuX** [comment]
https://us.battle.net/forums/en/hearthstone/topic/13840764128?page=2#post-23
