### ISSUE TITLE
If a minion leaves a Crystal Core Rogue's control (e.g. Shadow Madness), it retains the Crystalized buff, rather than reverting

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#728]
* https://www.reddit.com/r/hearthstone/comments/64dbx3/til_if_a_rogue_with_a_crystal_core_uses_shadow/

> My opponent used a Shadow Madness aquired from a Swashburgler to steal my N'zoth, which had been put into play by Barnes. It became a 5/5. He killed the Barnes with it and when it returned to my side of the board it retained the Crystal Core buff.

![image](https://user-images.githubusercontent.com/22508641/44312927-ce537800-a3cd-11e8-8039-56d7c899ab6a.png)

**Comment by Patashu** [comment]
Reason for may-be-intended:

Argument for this being a bug: Crystal Core's effect is treated as an Aura (albeit one with early or normal priority). It works not just for summoning, but also for transforming and stealing. It isn't removed by Silence.

Argument against this being a bug: There aren't any analogous effects to compare it to, so maybe it is developer intended, in some unknown way.

**Comment by Patashu** [comment]
Fixed an issue where Sergeant Sally would only deal 1 damage to enemies when interacting with Crystal Core and Spiritsinger Umbra is in play.

^ This may or may not indicate a generic change in how Crystal Core works.

**Comment by Jetz72** [comment]
Considering no effort was made to change this prior to it being solidified even further through the mechanics change in 15.0, I think it's likely this is how it was always meant to work.

Still a goddamn weird effect though.
