### ISSUE TITLE
2/2 Pyros's deathrattle adds a 6/6 Pyros to your hand rather than returns to your hand then transforms

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#729]
* http://www.bilibili.com/video/av9758741/

At 14:10.This bug may also apply to 6/6 Pyros.

**Comment by Patashu** [comment]
I guess this isn't a bug and they intended the card to work like this, just card text being oversimplified/'flavour reasons' (the whole phoenix rebirth theme). Similar to how Druid of the Claw card text was wrong for a really long time.

**Comment by VoidMayonnaise** [comment]
https://youtu.be/DzKWShGLny0
Confirmed to be fixed in 8.2.

**Comment by VoidMayonnaise** [comment]
So this issue should be closed now. Now Pyros reacts similar as Malorne, Weasel Tunneler, etc, means that Pyros is also a zone-moving effect.

**Comment by troggnostupidhs** [comment]
I believe this is fixed. Playing Pyros with Umbra causes Pyros to die and return to your hand as a 6/6.

**Comment by troggnostupidhs** [comment]
![image](https://user-images.githubusercontent.com/22508641/27144134-ba63c426-50fe-11e7-9db1-2910a1ea4462.png)

![image](https://user-images.githubusercontent.com/22508641/27144146-c2f82438-50fe-11e7-9d8f-5d8bff8a1b18.png)
