### ISSUE TITLE
Obsidian Shard in other classes

### ISSUE THREAD

**Issue by ThePlayer14** [HearthSim/hs-bugs#731]
I was playing against a Rogue which had Obsidian Shard in its hand.
I copied it with Mind Vision, and after copying it, played some cheap spells, and I surprised when the Shard's cost went down to 0.
I think it's intended behavior, as the card's in-hand effect activates when a non-Rogue card was played.

**Comment by Patashu** [comment]
May-be-intended: It's unclear if 'another class' means 'another class besides your hero's class' or 'another class besides the class of Obsidian Shard (rogue)'. (If it worked like the former, by the way, replacing your Hero with Jaraxxus or Ragnaros would be an unusual experience!)

**Comment by troggnostupidhs** [comment]
Same bug @16:05? Or is it different?

https://youtu.be/6JNSn_AwjuU?t=965

**Comment by troggnostupidhs** [comment]
https://hearthstone.gamepedia.com/Obsidian_Shard

> The cost reduction of this card is determined by the number of played cards that are class cards and do not belong to your current class.

As described (assuming OP was a Priest), that would be a bug. However, it currently does not happen (see below) and may never have happened as described in the report. There are not other reports that I know of and screenshots were not provided.

I'm closing this as invalid.

![img000](https://user-images.githubusercontent.com/22508641/32919871-513722f6-caf5-11e7-87af-07e3159c77b9.png)
![img003](https://user-images.githubusercontent.com/22508641/32919872-514c6f1c-caf5-11e7-8ba0-e85ba7f13d43.png)
