### ISSUE TITLE
The game will not end immediately when Adapting a minion

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#736]
https://www.reddit.com/r/hearthstone/comments/691bn1/did_you_know_you_can_keep_your_emeny_at_0_hp/

> I just found something cool. You can keep your emeny at 0 HP while you are picking up adapt.

![image](https://cloud.githubusercontent.com/assets/22508641/25675896/1700a15c-300e-11e7-9370-7f4e10abdd68.png)

**Comment by troggnostupidhs** [comment]
It is not known how Discover works, but I would guess it would be the same.

**Comment by troggnostupidhs** [comment]
I think this is not a huge issue since it shouldn't be able to be abused. When the turn ends, one of the choices should be picked and the game should end.

**Comment by Patashu** [comment]
This isn't even a new mechanic, the game by default doesn't end in the middle of a Sequence (combat excluded, where it can end just before the attack starts). Covered in the advanced rulebook. Not sure why this needs an issue, unless there's something new I'm missing.

**Comment by troggnostupidhs** [comment]
@Patashu I had some similar thoughts. In chat, the thought was that Discover behaved differently.

**Comment by troggnostupidhs** [comment]
So with a discover minion, the knife isn't shot until after the discover choice is chosen.

![hearthstone screenshot 05-03-17 20 48 11](https://cloud.githubusercontent.com/assets/22508641/25687427/1e52cc2e-3044-11e7-8201-ce4185d667f5.png)

With Knife Juggler + Violet Teacher, a discover spell will fire the knife before the discover option is chosen. The discover choices appear to flash quickly, but the game ends immediately.

![hearthstone screenshot 05-03-17 21 02 24](https://cloud.githubusercontent.com/assets/22508641/25687459/685e964a-3044-11e7-8885-3b75f2cd5c20.png)

**Comment by VoidMayonnaise** [comment]
Already fixed.
KJ killed the hero and the game ended without the adapt choices. 
![_20180301_150643 00-00-08 20180303-110046590](https://user-images.githubusercontent.com/28046803/36930142-1f95c47a-1ed6-11e8-9d60-fd50af914de0.jpg)
![_20180301_150643 00-00-12 20180303-11003694](https://user-images.githubusercontent.com/28046803/36930143-2000b14a-1ed6-11e8-99bb-af4e83d7c944.jpg)
