### ISSUE TITLE
You can target your own permanent minions with Combo battlecries

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#738]
* https://www.reddit.com/r/hearthstone/comments/6agmvl/hotform_performs_a_science_experiment/

**Comment by 10925** [comment]
SI:7 could also target Sherazin Seed
http://imgur.com/a/yVNiO

**Comment by VoidMayonnaise** [comment]
https://youtu.be/M2eySRSvWKo
Still works in 8.2.

**Comment by jamjury** [comment]
![Targeting](https://i.imgur.com/SOG9bmy.jpg)

![After battlecry](https://i.imgur.com/SOG9bmy.jpg)

Patch 9.4

**Comment by troggnostupidhs** [comment]
https://hearthstone.gamepedia.com/Permanent

> Permanent cards are minion-like cards that lack Attack and Health, **are untargetable**, are immune to all effects except their own, and take up more or less a permanent residence on the battlefield.

**Comment by troggnostupidhs** [comment]
https://youtu.be/xxmD2r3FSCM?t=196

**Comment by PattuX** [comment]
https://www.reddit.com/r/hearthstone/comments/64gojq/til_if_you_hover_a_bounce_effect_over_a_stage_3/

Interesting interaction with Ferryman.

**Comment by PattuX** [comment]
satibel and me just tested that this also works for Nether Portal and that you can only target your own Seed/Portal, but not the opponent's. If you try to, the message "That character is immune" pops up.

**Comment by riQQ** [comment]
This should be fixed with 10.0.0.22611
> Combo effects can no longer target non-interactable minions such as Sherazin, Seed.

**Comment by troggnostupidhs** [comment]
Fixed 

![img001](https://user-images.githubusercontent.com/22508641/34801852-ab3adefa-f638-11e7-867b-b304f0a89825.png)

![Uploading img002.png…]()


Deck
AAECAYO6AgLtBfbqAg60AfsBnAK9BJsFiAfdCJK2Avi9AvjBAoHCApvIApTQAtvjAgA=
