### ISSUE TITLE
Cancelling Power of the Wild with Knife Juggler can lead to a card incorrectly being displayed in the hand

### ISSUE THREAD

**Issue by Qualimiox** [HearthSim/hs-bugs#740]
Just happened in C4mlann's stream: https://www.twitch.tv/videos/146290341?t=01h48m36s

The Flame Elemental he had just played seemingly returned to his hand after he cancelled playing Power of the Wild, but the card wasn't playable. It then returned back to the board when he eventually played Power of the Wild.

**Comment by troggnostupidhs** [comment]
Seems similar to #85

**Comment by Qualimiox** [comment]
Yup, should be the same issue. I tried searching for a bunch of keywords (including cancelling) before I submitted here but must've overlooked that one.
