### ISSUE TITLE
Majordomo -> Alexstrasza -> Amara, Amara damages instead of healing

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#741]
* https://www.reddit.com/r/hearthstone/comments/6egzzc/glitch_majordomo_alexstraza_amara_instant_death/

**Comment by Kybxd** [comment]
Fixed in the recent patch.
* http://imgur.com/S94VRtg

**Comment by troggnostupidhs** [comment]
Confirmed

![hearthstone screenshot 06-09-17 21 49 02](https://user-images.githubusercontent.com/22508641/26999003-91baaf5c-4d5d-11e7-95d0-709a2222ab89.png)
