### ISSUE TITLE
Bolf immune to fatigue damage.

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#749]
report from nga:http://bbs.nga.cn/read.php?tid=11752789&_ff=422

http://imgur.com/a/3yWTk

**Comment by Kybxd** [comment]
It seems that Bolf's mechanics were changed.
* http://www.bilibili.com/video/av11803058/

It can be inferred from 4m30s of this video that the new damage Bolf creates is still from the original source, not Bolf himself. This may explain why this bug happens.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20758356023?page=1#post-2

**Comment by Kybxd** [comment]
Bug report from NGA: Spell Damage and Velen will be counted twice by Bolf.
* http://bbs.nga.cn/read.php?tid=12121177

Relevant tests the author has done:
1. I have Spell Damage +1 and Darkbomb enemy hero, Bolf takes **5** damage.
2. I have Spell Damage +1 and Darkbomb enemy Wrathguard, Bolf takes 4 damage.
3. I have Spell Damage +1 and Prophet Velen, and Darkbomb enemy hero, Bolf takes **14** damage.
Calculation: (2+1)*2=6, and (6+1)*2=14

**Comment by troggnostupidhs** [comment]
AAEBAf0GBBftBbkNoxQN+wG0ArkGzgbMCMUJgQ7dD/ARzxa0rAL2rgLnwQIA

**Comment by troggnostupidhs** [comment]
This is fixed for me

![hearthstone screenshot 08-08-17 15 24 02](https://user-images.githubusercontent.com/22508641/29090611-1b47e57c-7c4e-11e7-81f3-404f6b9cc0a7.png)

**Comment by troggnostupidhs** [comment]
This is not affected by the dominant player bug.
