### ISSUE TITLE
Sudden Genesis and Frozen Crusher interaction

### ISSUE THREAD

**Issue by vlacorte** [HearthSim/hs-bugs#750]
http://imgur.com/a/63yGJ

My opponent damaged his Frozen Crusher, freezing it afterwards as the card ability states, and proceeded to play Sudden Genesis, copying each of his damaged minions. My issue is that the copied Frozen Crusher was unfrozen, which I believe is a bug/inconsistency when compared to other copy effects.

Is this a known issue?

**Comment by Patashu** [comment]
May be a copy of https://github.com/HearthSim/hs-bugs/issues/18

**Comment by troggnostupidhs** [comment]
With #18, the ooze copy is now also frozen.

Maybe this issue has been fixed.

**Comment by troggnostupidhs** [comment]
The copy is also frozen now. I'm going to close this as a duplicate, because it is likely the same as #18.

![hearthstone screenshot 08-09-17 13 10 10](https://user-images.githubusercontent.com/22508641/29134290-2fb61ea0-7d04-11e7-8641-688e3ed73e77.png)
