### ISSUE TITLE
If Lord Jaraxxus leave board before battlecry, would make game hang.

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#751]
https://www.youtube.com/watch?v=2wB69dwFIDE
Busters just show that no hero replace.(since the cards turns green)

http://www.bilibili.com/video/av10977544/
But this shows jaraxxus back to hand actually replace your hero, just the game and animation hang.

If you tried to emote now, you would found the jaraxxus in hand take the emote.

After reconnect, you should found jaraxxus already replace your hero.

**Comment by Patashu** [comment]
Is this https://github.com/HearthSim/hs-bugs/issues/631 ?

**Comment by 10925** [comment]
Oh, you are right. I didn't notice this.
