### ISSUE TITLE
Using the search after importing a deck causes the UI to lock

### ISSUE THREAD

**Issue by NightOnEarth** [HearthSim/hs-bugs#753]
Hey folks,

when i export a deck to Hearthstone it seems to prioritize golden cards. If i remove the golden cards and add the non golden ones (BEFORE i click done after the export) i cannot click any button in the HS client anymore , nor add or remove any cards. Only button still working is the game menu button in the lower right, i basically have to quit and restart,

If i export the deck, then hit done after the export without switching any cards everything is fine. 

I have never used golden cards, i would  appreciate an option to exclude golden cards as well.

**Comment by troggnostupidhs** [comment]
Thanks for the bug report, I'll check it out.

> I have never used golden cards, i would appreciate an option to exclude golden cards as well.

This isn't maintained by Blizzard, so we can't implement any features. Feature requests also aren't tracked here.

**Comment by troggnostupidhs** [comment]
I am unable to reproduce this. What platform are you on? Can you provide step by step instructions, or a video?

I copied a deck, imported it, replaced all of the golden cards, and pressed Done. The UI still worked for me.

**Comment by NightOnEarth** [comment]
Thank you for your effort troggnotupidhs , this problem occurs to me when i export from hearthstone deck tracker or from hearthpwn.com. I am on Windows 7 64bit

I copy the deck to the clipboard (take this deck for example : http://www.hearthpwn.com/decks/846776-upd-why-not-control-warrior-in-ungoro ). 

There i click "Copy deck for hearthstone"
Then Alt-Tab to the HS client
Then click "My Collection"
Then click "New deck"
Then i confirm i want to create a new deck from clipboard
After the deck filled up i double click on the golden shield blocks to remove them
Then i type block into the search box and hit enter
Then everything freezes up, i can only click the game menu button in the lower right, everything else is unclickable

I just checked again, and the problem still exists. However if i remove ALL golden cards first (not only shield block), like you probably did,  then enter block in the search box it doesnt freeze and i can add the non golden blocks and all other non golden cards and nothing freezes.

Strange ..... but at least i have a mini workaround now. But do it step by step as i described, does the error occur then to you too?

**Comment by NightOnEarth** [comment]
P.S, : Just in case you dont have golden warrior cards, i just double checked with golden paladin cards, i removed golden consecrations , typed consec into the search box, same freeze ... but if i remove all golden paladin cards .... i am fine after , really weird.

**Comment by troggnostupidhs** [comment]
Thank you for the reproductions steps, they were very helpful. The same bug happens for me.

And you are correct, I was removing all of the golden cards and it was fine. It seems like it happens when only some of the golden cards are removed.

**Comment by troggnostupidhs** [comment]
I believe the issue is using the search after importing the deck. If I remove some or all of the golden cards and then search, it will lock. Even if I don't remove any cards and search, it still locks.

**Comment by troggnostupidhs** [comment]
Potentially fixed

http://us.battle.net/hearthstone/en/blog/20852956/hearthstone-update-june-13-6-13-2017

> Fixed an issue that could cause a player to get stuck in their Collection Manager after copying a deck.

**Comment by troggnostupidhs** [comment]
AAECAQcI0gL8BPIFognSrgLKwwLTxQLPxwILS5EDogSRBv8H+wyCrQL+vALGwwLfxALJxwIA

This still happens. They must have fixed a different bug.

**Comment by snapwich** [comment]
I get this same bug :(

**Comment by troggnostupidhs** [comment]
My advice is to import the deck, save it, then open it again for editing. That should avoid the bug until it is fixed.

**Comment by troggnostupidhs** [comment]
Possibly happens when using the other filters, like mana crystals

https://us.battle.net/forums/en/hearthstone/topic/20756935759

**Comment by Nyrk0** [comment]
Hearthstone freeze after import a deck, just when search field is used.
Workaround: save deck first, then use search field.
MacOS Sierra 10.2.5
HS 8.2.2.19632

**Comment by troggnostupidhs** [comment]
Fixed.
