### ISSUE TITLE
Immune Taunt minions can be bypassed with no visual indication

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#76]
Minions with Taunt and Immune should indicate that the Taunt is temporarily disabled by having the visual effect more transparent (like minions with Taunt and Stealth do).
https://www.youtube.com/watch?v=q7NGyGZiH5E

**Comment by Patashu** [comment]
(It's debatable whether this is a visual or gameplay bug.)

**Comment by jleclanche** [comment]
We can't use the tracker for feature requests. Closing.
