### ISSUE TITLE
Jungle Giants has incorrect interaction with Menagerie Warden

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#761]
When I copy a minion with 5 (or more) original attack but Humility(ed), Druid Quest still triggers.
When I copy a minion with 4 (or less) original attack but buffed to 5 or more, Druid Quest won't trigger.
* https://youtu.be/K14lhCUzah8
* https://youtu.be/pPJaot28x48
Guess: Other similar effects may also have the same interaction.(Molten Reflection, Sudden Genesis)

Faceless Manipulator doesn't have the same bug.(I tested but didn't record the video.)
Mirage Caller also won't cause this.
* https://youtu.be/1cAL_Zmseo0

**Comment by troggnostupidhs** [comment]
It looks like it summons the minion, and then applies the buffs.

**Comment by Kybxd** [comment]
This is fixed now. 
![1](https://user-images.githubusercontent.com/18246091/31851423-dbee00f8-b697-11e7-8a0a-cb5ad07726e3.jpg)
![2](https://user-images.githubusercontent.com/18246091/31851424-dd0de430-b697-11e7-8b56-38e6f5703089.jpg)

And Menagerie Warden a Aldored beast which originally has more than 5 Attack is not counted in. But a new bug seems to be introduced: Celestial Dreamer (buffed to 5/5 through its Battlecry) is also not counted in. Forbidden Ancient cannot either.
![1](https://user-images.githubusercontent.com/18246091/31851534-3befa5f4-b69a-11e7-9123-6a932de194a7.png)
![2](https://user-images.githubusercontent.com/18246091/31851535-3ce55990-b69a-11e7-9c69-8664a9ef5241.png)
![3](https://user-images.githubusercontent.com/18246091/31851536-3dd4bbb6-b69a-11e7-8c32-986fb8de6ad9.png)

Another test to find whether Jungle Giants is changed to a SRS trigger: it doesn't count twice for Faceless Manipulator (Grimestreet buffed to 5/5) transforming into Malorne.

**Comment by Kybxd** [comment]
One idea: The interaction with Celestial Dreamer might result from the new official mechanics:
> In order for a trigger to activate from a sequence, it needs to be present and valid at the time the sequence began.
At the start of this sequence it has not reached 5 Attack, so it cannot be counted in. But I think this interaction is really irrational.

**Comment by troggnostupidhs** [comment]
Isn't it summoned as a 3/3, and then buffed to a 5/5? Should that count as summoning a 5 attack minion?

**Comment by Kybxd** [comment]
Here are two more tests about Jungle Giants:
Test 1: I have a Dire Wolf Alpha and play a Chillwind Yeti adjacent to it. This is counted for Jungle Giants.
Test 2: I have two Hobgoblins and play a Leper Gnome. This is also counted for Jungle Giants.

And I think Celestial Dreamer should behave identically with the two examples above.

**Comment by troggnostupidhs** [comment]
Given those two examples, I agree that it should be consistent.

**Comment by troggnostupidhs** [comment]
I created a new issue for the Celestial Dreamer bug.
