### ISSUE TITLE
Rapidly using upgraded Hero Powers with Auctionmaster Beardo can lead to an animation hang

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#763]
https://us.battle.net/forums/en/hearthstone/topic/20757445636

> Auctionmaster Beardo Crashes My Game
>
> I decided to make a deck involving some funky combos using the upgraded hero powers from Justicar Trueheart, hero power replenishing with Auctionmaster Beardo and a lot of spells from Lyra the Sunshard. The problem is that every time I queue up more than two or three hero power uses, the game crashes. The deck revolves on using the hero power a lot in one turn before roping, so it's not efficient to wait for the animations to go through. It seems to be a repeatable bug, and it would be quite sad to see it make one of the less popular cards even more unviable.
>
> Thanks for your time

**Comment by troggnostupidhs** [comment]
jug6ernaut
@troggnostupidhs confirmed
tho it didnt crash, but it did freeze for a good 10-15 seconds
and im not sure if the state is correct after the it came back
looks like it probably is tho

troggnostupidhs
wow, that is surprising, thanks for testing
i could see that if it froze longer, it could do the animation hang stuff possibly
did you use justicar, or just beardo and spells?

jug6ernaut 
justicar & beardo
first game i played shadowform and and then justicar (which didnt upgrade anything) and was not able to reproduce

troggnostupidhs
Ah, so maybe Justicar is part of it

jug6ernaut
yeah its definitely justicar + beardo + lots of spells

**Comment by williamwebb** [comment]
[Video](https://app.box.com/s/hwkncmtvfj13x6zh5ym8muqfc59feo4s) of crash.

**Comment by judge2020** [comment]
Youtube mirror https://youtu.be/OrzHxPslzSs

**Comment by troggnostupidhs** [comment]
Possibly happens with Death Knights.

https://us.battle.net/forums/en/hearthstone/topic/20758577655

> If you want play Paladin DK 4 horsmans with Auctionmaster Beardo and 3 spels, you have chance to bug 1 horseman. If you play that realy fast. Beardo dont refresh last time hero power.

**Comment by troggnostupidhs** [comment]
Had this setup and it was fine. No crash or hang.


![img000](https://user-images.githubusercontent.com/22508641/47956246-e2902580-df77-11e8-9cd7-912715e4b7ba.png)


Deck
AAEBAa0GBNYRsBW3bJ29Ag2XAvgCoQTlBMsI0gqND4gUlhTSwQLYwQKm8ALQ/gIA
