### ISSUE TITLE
Rapidly pressing crafting in the Card Back selection screen causes visual bugs

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#765]
Rapidly pressing Crafting in the Card Back selection screen causes some weird behavior. Eventually the card backs disappear quickly. Then when you go to the Heroes selection screen and press crafting, the card backs look glitched on the screen.

![hearthstone screenshot 06-24-17 22 53 47](https://user-images.githubusercontent.com/22508641/27513337-59637024-5930-11e7-88c4-dcbfee8dc41b.png)

**Comment by troggnostupidhs** [comment]
Discovered while testing #764

**Comment by culinko** [comment]
Interesting, which client did you use? I'm wondering if this isn't this the same issue as #194 (which was fixed) or perhaps is this a new issue?

**Comment by troggnostupidhs** [comment]
It was on PC.

That seems like a similar problem.  I can try to treat to see if it is still fixed.

**Comment by troggnostupidhs** [comment]
Android does not have this problem because the crafting button is not shown in the hero and card back screens.

**Comment by troggnostupidhs** [comment]
#194 is still fixed for me

**Comment by troggnostupidhs** [comment]
This is possibly fixed. They will still sometimes briefly disapper, but they don't glitch on the Hero screen for me.
