### ISSUE TITLE
Mana Geode is not an Elemental

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#766]
https://www.reddit.com/r/hearthstone/comments/6ipe2a/is_there_an_official_reason_why_mana_geode_is_not/

> Is there an official reason why Mana Geode is not an elemental? (self.hearthstone)
> 
> You know that 2 mana 2/3 "whenever you heal this minion summon a 2/2" priest card from The mean streets of Gadgetzan.

Ben Brode says it will be changed soon,

https://www.reddit.com/r/hearthstone/comments/6ipe2a/is_there_an_official_reason_why_mana_geode_is_not/dj8fp1u/

> We are changing it in an upcoming patch.

**Comment by PattuX** [comment]
Mana Geode (and the Crystal, too!) are now Elementals.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/hearthstone/en/blog/20904301/hearthstone-update-july-10-7-10-2017

> The following minions are now Elementals:
>    Jade Spirit, Djinni of Zephyrs, Flame of Azzinoth, Mana Geode, and Hallazeal, the Ascended.
