### ISSUE TITLE
[Android] The client does not asks installing to SD card on some devices 

### ISSUE THREAD

**Issue by ThePlayer14** [HearthSim/hs-bugs#767]
I don't know if it's the right place to submit this issue, but I experiencing it.

I installed the latest version (8.2.19632) from the Play Store, and when I launching it it doesn't asks me if I want to install its files to my SD card which is a feature added in Patch 7.1.0.17720.
On my friend's device it asks to install it on the SD card, so I don't know why I don't get the option.
It always installs itself to the internal storage of the device, which is less than acceptable if the external storage has a lot of free space, but the internal is not.

**Comment by troggnostupidhs** [comment]
This isn't the right place, most likely, for this issue. You will probably have to contact Blizzard support.

A few things,
1. Can you verify that the SD card is installed and working correctly
1. Try uninstall the game and choose the SD Card option when reinstalling
    1. https://us.battle.net/support/en/article/Installing-Hearthstone-on-SD-Card
