### ISSUE TITLE
Game stuck after full hand mulligan

### ISSUE THREAD

**Issue by Velken** [HearthSim/hs-bugs#769]
Went to brawl (All-star) with paladin and the 1 mana spell that summons two 1/1s.
Mulligan my whole hand, game wont do anything, I've been waiting for about 10 minutes now.
All other UI elements work, I can take screenshots (no text appears in-game that I've took a screenshot, but file is saved on desktop), send/recieve messages, conceding does nothing, but the options menu works.
Print: http://imgur.com/a/gbhTP

**Comment by troggnostupidhs** [comment]
Likely something related to a disconnect. Not a bug to track here.

**Comment by culinko** [comment]
Isn't this related to #500?

**Comment by troggnostupidhs** [comment]
Some of the screenshots there look similar, so it could be.
