### ISSUE TITLE
Impact animation for 100+ damage is the same as for 3 damage

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#77]
The impact animation and sound effects for Attacks that deal 100+ damage is using the same ones as for 3 damage.
http://www.reddit.com/r/hearthstone/comments/2rn4vy/heres_a_breakdown_of_all_the_elements_behind_the/
https://www.youtube.com/watch?v=dvkoxqgTK5U (Minions)
https://www.youtube.com/watch?v=3kUabKla5xY (Weapons)

**Comment by troggnostupidhs** [comment]
This is fixed for minions

![hearthstone screenshot 12-18-16 21 42 45 1](https://cloud.githubusercontent.com/assets/22508641/21299596/3d179e12-c56b-11e6-843d-d7e600f7bb2b.png)

**Comment by culinko** [comment]
I verified this today also with weapons and it's fixed for them as well.
