### ISSUE TITLE
Bolf Ramshield takes double damage from Spell Power

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#776]
Report by Kybxd in #749 (which is possibly related):

> Bug report from NGA: Spell Damage and Velen will be counted twice by Bolf.
> * http://bbs.nga.cn/read.php?tid=12121177
> 
> Relevant tests the author has done:
> 1. I have Spell Damage +1 and Darkbomb enemy hero, Bolf takes **5** damage.
> 2. I have Spell Damage +1 and Darkbomb enemy Wrathguard, Bolf takes 4 damage.
> 3. I have Spell Damage +1 and Prophet Velen, and Darkbomb enemy hero, Bolf takes **14** damage.
> Calculation: (2+1)*2=6, and (6+1)*2=14

**Comment by culinko** [comment]
#749 is fixed so this should be re-checked if it's related.

**Comment by troggnostupidhs** [comment]
When targeting Bolf, it works correctly.

![hearthstone screenshot 08-09-17 22 53 53](https://user-images.githubusercontent.com/22508641/29152823-8b6a0380-7d57-11e7-9197-a8d8f0078878.png)

When hitting face, the spell damage is applied twice to Bolf.

![hearthstone screenshot 08-09-17 22 54 25](https://user-images.githubusercontent.com/22508641/29152832-9a09aa76-7d57-11e7-90ad-f55ec48cecd4.png)

![hearthstone screenshot 08-09-17 22 54 35](https://user-images.githubusercontent.com/22508641/29152834-9c2b5bce-7d57-11e7-806f-a17cc8608069.png)

**Comment by troggnostupidhs** [comment]
Can be self inflicted.

Deck
AAEBAf0EAu0FoxQOTfsBnAK0ArsCqwSWBaAFuQbJEewRiawC9K8Co7YCAA==

![img000](https://user-images.githubusercontent.com/22508641/31848029-865aee40-b5f6-11e7-80ff-4688b11f69b6.png)

![img001](https://user-images.githubusercontent.com/22508641/31848030-866d57ba-b5f6-11e7-8448-131eb7d3dfe4.png)

**Comment by troggnostupidhs** [comment]
https://youtu.be/xxmD2r3FSCM?t=678

**Comment by Jetz72** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20766946566

Also affects Hero Power damage boosts, such as Fallen Hero. Presumably any time something meddles with damage events, it sees both the original and Bolf's modified one separately.

**Comment by troggnostupidhs** [comment]
Self damage works as expected. This is probably fixed.

![hearthstone screenshot 02-18-19 10 06 55](https://user-images.githubusercontent.com/22508641/52959796-2c551e00-3365-11e9-9078-9baa96566a63.png)
![hearthstone screenshot 02-18-19 10 07 16](https://user-images.githubusercontent.com/22508641/52959797-2c551e00-3365-11e9-95bb-2efa1f03fadd.png)

**Comment by Jetz72** [comment]
Probably fixed as a result of the 13.0 updates to redirection and modification effects:
https://www.reddit.com/r/hearthstone/comments/a0mc0j/new_card_snapjaw_shellfighter/eaixu48/
>Damage redirection effects should occur before damage modification effects.

https://www.reddit.com/r/hearthstone/comments/a0mc0j/new_card_snapjaw_shellfighter/eaius3f/?context=3
>Yes, changes came about as a result of this card [Snapjaw Shellfighter].
