### ISSUE TITLE
Heroic Lady Naz'jar: Hero Power is reversed

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#781]
https://www.reddit.com/r/hearthstone/comments/6snakk/lady_nazjar_heroic_bugged/

> Her Hero Power is inverted after last patch.
She evolves our minions and hers stay at same cost.
I play on ipad.

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

>Fixed a bug where Heroic Lady Naz’jar would increase the cost of your minions instead of just her own.

**Comment by culinko** [comment]
Can confirm that this has been fixed.
