### ISSUE TITLE
Deathstalker Rexxar's Battlecry activates Lifesteal from your weapon

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#785]
* https://youtu.be/hwrrX0FrFjU

Poisonous may also works.

**Comment by troggnostupidhs** [comment]
This is possibly the same issue?

https://www.reddit.com/r/hearthstone/comments/6tirrb/bugs_introduced_with_the_90_patch/dlkyo8j/

> [[Sword of Justice]] combined with [[Leeching Poison]] seems to heal your hero for one HP each time you summon a minion. Seems like a strange interaction.

**Comment by PattuX** [comment]
I think it's a similar but different issue.

In DK Rexxar's case, HS considers damage dealt by heroes as damage dealt by weapons.

In the SoJ case HS considers the durability loss without attacking as dealing damage (to itself).

**Comment by troggnostupidhs** [comment]
Starts at  2:58

https://youtu.be/OLLqOIvol1o?t=178

**Comment by Roxor9999** [comment]
The interaction with deathstalker Rexxar seems intended to me. Weapons apply all their text to the hero (like windfury with doomhammer) and so when the hero deals damage it also triggers the effects applied to the hero.

**Comment by troggnostupidhs** [comment]
https://youtu.be/xxmD2r3FSCM?t=415

**Comment by riQQ** [comment]
Should be fixed with 10.0.0.22611
> Deathstalker Rexxar’s Battlecry no longer benefits from effects on an equipped weapon, such as Poisonous or Lifesteal.

**Comment by troggnostupidhs** [comment]
Hunter Deck
AAEBAR8E7QXtBu8IhtMCDY0BswH7AZwCtAKFA/4DiAX1BbkGmA23bOLKAgA=

Rogue Deck
AAEBAaIHAu0F7wgOswHyAfsBnAK0AoUD9QW5BpgNt2zqxgLiygKnzQKpzQIA

**Comment by troggnostupidhs** [comment]
![img000](https://user-images.githubusercontent.com/22508641/33811179-782b3ea6-dddd-11e7-815c-60a69fd66dd5.png)
![img001](https://user-images.githubusercontent.com/22508641/33811180-78388250-dddd-11e7-9421-890bcc4570ee.png)
