### ISSUE TITLE
Rapidly using Voidform causes graphical glitches

### ISSUE THREAD

**Issue by ThePlayer14** [HearthSim/hs-bugs#787]
Fast usage of Voidform can make the HS client unresponsive.
I currently don't have video material for it, but I saw on a stream that a 0-cost Voidform (reduced by Raza) and a bunch of low-cost spells can make this issue, Voidform causes graphical artifacts if it's landed on a Hero.

**Comment by troggnostupidhs** [comment]
What platform are you using?

**Comment by ThePlayer14** [comment]
I haven't encountered this problem (I haven't played a normal game yet, just missions), and this bug occurs on PC, possibly it's a video card related thing.
Relevant thread on reddit:
https://www.reddit.com/r/hearthstone/comments/6tirrb/bugs_introduced_with_the_90_patch/

**Comment by troggnostupidhs** [comment]
This is possibly related to #763. Paladin has a similar issue too.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20758577655

> If you want play Paladin DK 4 horsmans with Auctionmaster Beardo and 3 spels, you have chance to bug 1 horseman. If you play that realy fast. Beardo dont refresh last time hero power.

**Comment by troggnostupidhs** [comment]
> something to add to the new priest hero power voidform is that if you and i kid you spam it too quickly it will make your game stop.

**Comment by troggnostupidhs** [comment]
I changed the title, but also note that there are reports of Voidform having a graphical issue.

**Comment by ThePlayer14** [comment]
Others were mentioned an older bug with Archmage Antonidas which caused a similar issue (in the reddit post)

**Comment by troggnostupidhs** [comment]
#455

**Comment by troggnostupidhs** [comment]
I'm assuming this is the visual glitch

**Comment by troggnostupidhs** [comment]
So after seeing the glitch, I think that they are separate issues. I'll assume the freezing is part of the other issue, unless we find out otherwise.

**Comment by troggnostupidhs** [comment]
I don't think it has to be rapid usage either. It seems to do it often.

**Comment by ThePlayer14** [comment]
It's Hero Power animation is broken with the Golden hero:
http://i.imgur.com/s4kSaH6.png

**Comment by ThePlayer14** [comment]
https://www.youtube.com/watch?v=HmRaw_2KJFw

At 06:29-06:34

**Comment by troggnostupidhs** [comment]
I opened #812 for the Hero Power animation issue

**Comment by troggnostupidhs** [comment]
This issue is fixed for me.

https://youtu.be/l-1r0rKVWdU?t=279

Deck
AAECAZ/HAh6KAfsBkALlBMsI0wrXCvIM+rACkrQCobcCg7sCtbsC17sC2LsC8LsCsLwC4b8C6r8C0cEC1cEC2MEC2cEC3MECz8cCmcgCvsgCxswCws4CkNMCAAA=

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=kJSI5OCnnkA

Possibly still happening when your opponent uses their Hero Power.

**Comment by riQQ** [comment]
I saw this happening to Ratsmah, when he was playing Shadowreaper Anduin. So it's not only happening for opponents.

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

>Fixed a visual issue that could occur during certain animations, causing them to flicker or scatter.

**Comment by troggnostupidhs** [comment]
This is currently 'fixed' because the Voidform Hero Power refreshes very slowly. Can't easily test the reproduction case.

**Comment by troggnostupidhs** [comment]
So far, this seems fixed to me. But I think further proof is needed. Maybe a clip from a stream.

**Comment by troggnostupidhs** [comment]
Good enough, I think.

https://youtu.be/AmttamF-B4s?t=369
