### ISSUE TITLE
Cursed Blade's effect does not end if you use a Death Knight Hero

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#789]
* https://www.reddit.com/r/hearthstone/comments/6tqvdr/bug_with_new_rogue_death_knight_hero/

**Comment by troggnostupidhs** [comment]
> ***Edit: This seems to effect at least 3 Death Knight hero cards, but possibly ALL 9. See edit at the bottom of this post.*** 
> 
> 
> 
>  &nbsp;
> 
>  
> 
> So I was just playing a crappy burgle Rogue deck, I burgled a cursed blade from the warrior I was playing.
> 
> 1.  I equipped the cursed blade
> 1.  Hit a couple times
> 1. Then played the Death Knight Rogue card (so I wouldn't take double damage that turn, with the cursed blade equipped and all)
> 1.  Next turn I equipped an Obsidian Shard over the cursed blade, because they had a taunt and I couldn't use the last hit on face
> 1.  KEPT TAKING DOUBLE DAMAGE THE REST OF THE GAME. Something about the stealth maybe kept the double damage aura on my hero?
> 1. If I can't use Cursed Blade then the Rogue death Knight is unplayable IMHO YOLO.
> 
> Opponent immediately added me and the first thing they typed was "Small indie game company". Is there a semi-easy way to steal a cursed blade with Rogue, so we can test this further? 
> 
> .
> .
> .
> .
> ***Also I demand that Brode personally come to my house to deliver me my lost rank 19 star. Thanks in advance, Big Ben.*** 
> 
> 
>  &nbsp;
> 
>  
> EDIT: It works when playing the Warrior and Priest death knight cards on top of an equipped cursed blade too, and it's possible to take at least **16x damage** instead of 2x from the cursed blade! [details here,](https://www.reddit.com/r/hearthstone/comments/6tqvdr/bug_with_new_rogue_death_knight_hero/dlmvpbw/)
> [and here](https://www.reddit.com/r/hearthstone/comments/6tqvdr/bug_with_new_rogue_death_knight_hero/dlmyxwn/)

**Comment by troggnostupidhs** [comment]
https://clips.twitch.tv/TriangularGleamingDoveNinjaGrumpy

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=RvGw9CVwWBA

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

> The Cursed Blade effect will no longer incorrectly be re-applied and become permanent when changing Heroes.

**Comment by troggnostupidhs** [comment]
Fixed with DK Garrosh

![img000](https://user-images.githubusercontent.com/22508641/31695443-ade91be2-b378-11e7-99cc-a43e8c4cda01.png)
![img001](https://user-images.githubusercontent.com/22508641/31695445-adf33622-b378-11e7-97d0-c7d9538f3ac8.png)
![img004](https://user-images.githubusercontent.com/22508641/31695446-adfe32b6-b378-11e7-9a91-1b0068da5945.png)
