### ISSUE TITLE
Friend list issues

### ISSUE THREAD

**Issue by ThePlayer14** [HearthSim/hs-bugs#790]
Since the Frozen Throne expansion has been released, a player have been experiencing issues with his Friends list. 
Often when he tried to scroll through the list, it will either only scroll a small portion of the way down, go completely blank, or collapse into itself. 
This didn't seem like a major issue at first, but then he realized that if he checks his Friend list while searching for a game, the game would consistently become unplayable.

He did even made a video of it:
https://www.youtube.com/watch?v=-z7I2vjSx0w

Thread of the issue:
http://www.hearthpwn.com/forums/hearthstone-general/general-discussion/200484-frozen-throne-friends-list-bug

**Comment by troggnostupidhs** [comment]
There are also issues with friends stacking

https://us.battle.net/forums/en/hearthstone/topic/20758527515

https://us.battle.net/forums/en/hearthstone/topic/20758577885

https://us.battle.net/forums/en/hearthstone/topic/20758637040

>Hey after latest patch i have this bug almost every time i play HS. For while it is okey but after 20 min of play my friend list look like this.
http://imgur.com/a/umUez

>Yup. I just posted the same thing. If you scroll, you should see all of your friends stacked.
Below is my friends list:
http://imgur.com/a/Ydlc9

**Comment by troggnostupidhs** [comment]
I think these issues are fixed. There haven't been any reports.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21098848

> Fixed a visual error that could appear when scrolling down and up on a populated friends list.

**Comment by troggnostupidhs** [comment]
I'm closing this one. It can be re-opened if needed.
