### ISSUE TITLE
Prince Taldaram copies of Enrage minions gain no Attack when Enraged

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#791]
* https://www.reddit.com/r/hearthstone/comments/6u2dyq/dont_try_to_enrage_taldaram_copies/

![image](https://user-images.githubusercontent.com/666597/29391206-105b8366-8339-11e7-9c84-e7dbce349c48.png)

**Comment by VoidMayonnaise** [comment]
Already fixed.
![_20180228_203159](https://user-images.githubusercontent.com/28046803/36788990-0546a498-1ccb-11e8-8381-1af2b497b4a4.jpg)
![_20180228_203202](https://user-images.githubusercontent.com/28046803/36788992-0653836a-1ccb-11e8-8815-5181988c7371.jpg)
![_20180228_203204](https://user-images.githubusercontent.com/28046803/36788997-09413bf8-1ccb-11e8-9516-a943c53bbbeb.jpg)
