### ISSUE TITLE
Skeleton summoned by Rattling Rascal may invisible

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#792]
They still on board, but you cannot see them or select them.

Seems only happen when both player got the Skeletion

http://imgur.com/a/yUgCN

![image](https://user-images.githubusercontent.com/22508641/29416651-cfa11f06-8334-11e7-8441-90d97b764b32.png)

![image](https://user-images.githubusercontent.com/22508641/29416665-da597d4e-8334-11e7-9654-f1729266fc88.png)

![image](https://user-images.githubusercontent.com/22508641/29416669-de1f65f6-8334-11e7-923e-56bea91c55ef.png)

**Comment by troggnostupidhs** [comment]
![image](https://user-images.githubusercontent.com/22508641/29416639-c1cdd874-8334-11e7-8869-09e71c5eb04d.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6vxa3z/game_breaking_bug_lich_king_encounter_with/

Happens 100% of the time. The second time played, evolved, devolved, and also with the spawned Skeletal Enforcer for opponent.
Evolve my board with 2 of them on it, and it completely broke the game. Some minions didn't evolve and the Lich King didn't make anymore actions (however he does emote, classic Hearthstone). I restarted the game to recreate it for the video, but it won't let you concede.
I had to quit the game, and of course it crashed too :)
Disguised Toast, is Blizzard Jail nice this time of year?
Here's some video footage; sorry for bad quality, threw it together for an example. Also, sorry for so much footage, had to include context: no bamboozles https://www.youtube.com/watch?v=tQgOylSR6YQ

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20758946417

>This happened to me 3 or 4 times now on both mobile and Desktop versions of the game. I run a shaman evolve deck and when I reach the Frostmure stage, I cast rattling Rascal and evolve everything after also casting Doppelgangster. The 5/5 that the rascal summons is invisible and so are most of the evolved minions and I cannot use them. Here is a screenshot after I evolved.
https://imgur.com/gallery/6cjoD

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/71acqf/bug_monster_not_appearing_in_board/

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20759166932

**Comment by troggnostupidhs** [comment]
I believe this is fixed. I haven't seen reports on it for a while.
