### ISSUE TITLE
Bolvar, Fireblood does not trigger if a Divine Shield minion loses its Divine Shield and goes to 0 Health in the same Phase

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#793]
https://www.youtube.com/watch?v=OLLqOIvol1o

**Comment by troggnostupidhs** [comment]
Starts at 0:18

**Comment by Kybxd** [comment]
Bolvar seems to check the loss of Divine Shield at a very late timing:

https://youtu.be/dF7YItKogug

**Comment by Patashu** [comment]
Maybe if a minion loses Divine Shield and gains it again in the following Death Phase, Bolvar won't trigger. (He seems to wait until after Death Phases to trigger, which seems odd.)
Can be done with Selfless Hero or Cobalt Guardian.

**Comment by Kybxd** [comment]
Not that late. I guess the interaction in Toast's video is just because Bolvar mistakenly ignores mortally wounded minions.

https://youtu.be/Ec9UzIg7Njs
https://youtu.be/YIxXBJS7dGo

**Comment by Patashu** [comment]
Ok, good points.

But I think you could do it with Rotface summoning a mech legendary at the same time as a Cobalt Guardian loses its Divine Shield. Assuming Cobalt Guardian is still a presummon trigger, it will get its divine shield back before Bolvar, Fireblood triggers.

(I understand if you don't want to do this test though as it contains RNG. Unless you can think of a non-RNG way to do the same thing.)

**Comment by Kybxd** [comment]
I find Cobalt Guardian and Murloc Tidecaller are changed to SRS triggers through testing this. ( #35 ) And Bolvar will always gain attack before Cobalt regains Divine Shield.

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

>Bolvar, Fireblood now correctly gains attack when minions with Divine Shield die to Despicable Dreadlord’s end of turn effect.

**Comment by troggnostupidhs** [comment]
Is that a new bug?
