### ISSUE TITLE
Using Shadowform on Shadowreaper Anduin chooses Mind Shatter

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#794]
Using Shadowform on Shadowreaper Anduin should choose Mind Spike, but it chooses Mind Shatter.

Starts at 5:35

https://youtu.be/OLLqOIvol1o?t=335

**Comment by Patashu** [comment]
Unclear to me if this is a bug or an easter egg (like Sac Pact/Secrets vs Jaraxxus)

**Comment by troggnostupidhs** [comment]
Wording is tough.

> Your Hero Power becomes 'Deal 2 damage'. 

Voidform and Mind Spike both are 'Deal 2 damage'.

> If already in Shadowform: 3 damage.

This part isn't clear. Shadowform wasn't played, but does Shadowreaper also count as being in Shadowform? It could make sense, I just think it isn't clear.

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

>Shadowform will no longer incorrectly grant an upgraded Hero Power if played while Voidform is active.

**Comment by troggnostupidhs** [comment]
![img000](https://user-images.githubusercontent.com/22508641/31695190-12137074-b377-11e7-95fd-8b8e73bb9b43.png)
![img001](https://user-images.githubusercontent.com/22508641/31695191-121f4390-b377-11e7-9f67-dbffeeff9c31.png)
