### ISSUE TITLE
Alexstrasza or Amara cannot work on Repentance Jaraxxus

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#795]
http://www.bilibili.com/video/av13474746/

Jaraxxus would always stay at 1 health.

**Comment by troggnostupidhs** [comment]
YouTube mirror. Interaction at 2:22 and 5:39.

https://www.youtube.com/watch?v=RT7fJzhAivk

**Comment by troggnostupidhs** [comment]
Possibly mitigated

https://playhearthstone.com/en-us/blog/21098848

> Lord Jaraxxus no longer triggers Repentance, Sacred Trial, and Snipe.

**Comment by troggnostupidhs** [comment]
Closing this issue because the reproduction case was removed
