### ISSUE TITLE
Anomalous with Lifesteal from Frost Lich Jaina doesn't heal correctly

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#798]
* https://www.reddit.com/r/hearthstone/comments/6wurdu/anomalus_not_healing_in_elemental_mage_day9tv/

**Comment by 10925** [comment]
My personal guess, there was a deathrattle with minion summon triggers first, the Aura of DK Jaina is updated, so that Anomalous lose it Lifesteal.

**Comment by troggnostupidhs** [comment]
Same clip at 0:40
https://youtu.be/-wKAa9SELTA?t=40

**Comment by troggnostupidhs** [comment]
This seems inconsistent with the poisonous change.

https://hearthstone.gamepedia.com/Patch_9.0.0.20457

> Any Minion or Weapon that has a Deathrattle that deals damage to minions and that has become Poisonous now kills every affected minion.

**Comment by ThePlayer14** [comment]
Well, they did fixed it for Poisonous, but they missed on the new Lifesteal effect.

**Comment by 10925** [comment]
Anomalous with Lifesteal from Frost Lich Jaina could heal.

This is a bug because multi deathrattle triggers together and one of them is summon minions( before Anomalous's trigger).

Which make the Aura of Jaina's lifesteal update, such that Anomalous in the graveyard lose the lifesteal.

You can test normal deathrattle of Anomalous(without other deathrattle that would summon minions), it would heal normally.

**Comment by troggnostupidhs** [comment]
https://tempostorm.com/articles/interview-hearthstone-mike-donais-kotft

> 
> Shaun: I did see a bug reported on Reddit. Apparently there are cases where Anomalus won’t give health with his Deathrattle. Can you comment on this?
> 
> Mike: The bug is, “if a Deathrattle triggers before Anomalus, he won’t get his lifesteal ability.” The engineers have fixed the bug. I do not know when the patch will be delivered, or if it can be hotfixed, but it is fixed and will go live.

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

>Anomalus’ Deathrattle now correctly gains Lifesteal after Frost Lich Jaina has been played

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7cy2a0/are_hunter_spells_not_actually_spells/
![image](https://user-images.githubusercontent.com/22508641/32816858-d70aeba6-c988-11e7-8c4f-f872ae5c8cb1.png)
