### ISSUE TITLE
The interaction between Grim Patron and 'pending destroy' effects is inconsistent 

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#799]
The order of Grim Patron and Poisonous used to be affected by DP bug. Tested in 8.4:
https://www.bilibili.com/video/av12183926/

But in 9.0 Poisonous can stop Grim Patron from spawning regardless of DP. I also tested Lifesteal & Grim Patron, and they are still affected by DP bug. I guess Poisonous may resolve in a prior queue now. 

Then I tested Acidmaw and Grim Patron. The order is correct, but Acidmaw can never stop Grim Patron from spawning:
https://youtu.be/yqjowL0OwIs

Finally I tested Grim Patron attacking into Imp Gang Boss (with Knife Juggler). Grim Patron is still unable to spawn when killed by KJ.

My conclusion:
Grim Patron's queuing conditions: This minion is not mortally wounded or pending destroy.
Grim Patron's trigger conditions: This minion is not mortally wounded.

**Comment by Kybxd** [comment]
I met a bug in Dungeon. I attacked enemy Rotface with my 2/1/4 Mega-windfury + Poisonous weapon. Rotface summoned another Legendary before it was poisoned.

Then I tested and found minion's poisonous and weapon's poisonous worked differently.

Poisonous minion still kills Grim Patron and stops it from summoning another.
However, poisonous weapon can never stop Grim Patron from summoning another, although the order is decided by Dominant Player order. This is very similar to Acidmaw's interaction with Grim Patron I mentioned above.

https://youtu.be/lkk6sltthJA

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7m8t0a/dungeon_run_bug_reverberating_ooze_summons_copy/

> [Dungeon Run BUG] Reverberating Ooze summons copy when attacked with poisonous weapon
The card text reads: "Whenever this minion survives damage, summon a copy of this minion."

**Comment by Kybxd** [comment]
https://playhearthstone.com/en-us/blog/21507224/hearthstone-update-10-2-february-6-ranked-play-update

> Ice Breaker now correctly destroys Rotface without activating his effect if he is Frozen.

Poisonous weapon and Acidmaw also prevent Grim Patron from summoning another correctly now.
