### ISSUE TITLE
'Elementary My Dear' quest does not count all Elementals

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#800]
https://www.reddit.com/r/hearthstone/comments/6xt4nb/elemental_shaman_is_literally_unplayable_bug/

> I got the "elementary, my dear" quest today and since token shaman is a pretty good top tier meta tournament deck i decided to build an elemental shaman. You know what's elementary?? Elementals counting as such for the quest. Through careful experimentation and surgical level research I found the issue that limited the amount of fun I have playing this godly deck: Playing Jade Spirit does not count as an elemental for the quest.
> 
> TL;DR:Playing Jade Spirit does not count as an elemental for the quest.

**Comment by Patashu** [comment]
Might be https://github.com/HearthSim/hs-bugs/issues/261 , since one guy in the comments said they completed the quest with Jade Spirit

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6xt4nb/elemental_shaman_is_literally_unplayable_bug/dmies5z/

> Are you sure, I beat that quest playing exclusively druid with jade spirit as my only elemental the other day.

**Comment by troggnostupidhs** [comment]
I put unconfirmed until I can get the quest to test it. It's possible the report is an error or another bug as you mentioned.

**Comment by troggnostupidhs** [comment]
Deck
AAECAZICAsGrAovAAg5AX/sB/gGcAqICtAL3A7QFxAaKB8+8AqTCAvDCAgA=

![hearthstone screenshot 09-17-17 12 39 12](https://user-images.githubusercontent.com/22508641/30522920-d700b35e-9ba5-11e7-9612-f85f93811750.png)

![hearthstone screenshot 09-17-17 12 53 31](https://user-images.githubusercontent.com/22508641/30523005-3b308cea-9ba7-11e7-8ff4-4083e501f083.png)
