### ISSUE TITLE
Naga Sea Witch stops Dragon's Breath from cost reducing itself

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#802]
It appears that with the recent changes to how Naga Sea Witch (and Aviana) interact with cost reduction mechanics, a bug was introduced where the effect of Dragon's Breath to cost reduce itself when a minion dies is disabled/overridden if Naga Sea Witch is on the board.

[Reddit thread w/video](https://www.reddit.com/r/hearthstone/comments/6yj2o9/new_bug_with_naga_sea_witch_and_dragons_breath/)

[Hearthstone Laboratory video](https://youtu.be/tw6ofcUFtVk)

**Comment by NightKev** [comment]
Todo: test Solemn Vigil (Paladin spell) interaction

**Comment by troggnostupidhs** [comment]
It stays at 5.

![hearthstone screenshot 09-07-17 08 11 20](https://user-images.githubusercontent.com/22508641/30162835-594e3a66-93a4-11e7-8b2a-5b42712ba337.png)
![hearthstone screenshot 09-07-17 08 11 42](https://user-images.githubusercontent.com/22508641/30162836-5951e09e-93a4-11e7-81e6-f817fba5753b.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/6zw2kp/nerfs_will_go_live_on_september_18th/dmyrzdg/?context=1

> It's a bug. Should be fixed in an upcoming patch (though the fix will miss 9.1.)

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

> Mana-cost reductions on cards such as Dragon’s Breath, Solemn Vigil, Everyfin is Awesome, and Obsidian Shard will now apply after all other mana cost changes, such as the effects from cards like Naga Sea Witch.

**Comment by troggnostupidhs** [comment]
![img000](https://user-images.githubusercontent.com/22508641/31696087-db27fd86-b37c-11e7-97af-d480b6c67981.png)
![img001](https://user-images.githubusercontent.com/22508641/31696088-db3906ee-b37c-11e7-91f6-7d9ca13b4368.png)
