### ISSUE TITLE
Replacing Valeera the Hollow with another Hero causes Auras to be applied twice

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#803]
https://clips.twitch.tv/BadExpensiveAardvarkHotPokket

**Comment by troggnostupidhs** [comment]
The DK seems to re-apply the buff. Probably should test other heroes.

![image](https://user-images.githubusercontent.com/22508641/30160176-580075f8-9399-11e7-927f-326ea7b89d37.png)

![image](https://user-images.githubusercontent.com/22508641/30160190-672fe6b2-9399-11e7-91b6-55e92da9dcb1.png)

**Comment by troggnostupidhs** [comment]
The attack doesn't go up to when just playing Shadowreaper Anduin

![hearthstone screenshot 09-08-17 16 55 26](https://user-images.githubusercontent.com/22508641/30231034-0f97810c-94b7-11e7-8a5e-3e0a5d5a6d43.png)

![hearthstone screenshot 09-08-17 16 55 41](https://user-images.githubusercontent.com/22508641/30231035-0f997016-94b7-11e7-8fa5-56acfa4a3522.png)

**Comment by troggnostupidhs** [comment]
I wasn't able to reproduce this as Priest. I'm not sure if this needs to be with Rouge or Valeera the Hollow.

![hearthstone screenshot 09-08-17 23 04 44](https://user-images.githubusercontent.com/22508641/30236565-578e2672-94ea-11e7-9450-2732d9e0f8bb.png)

![hearthstone screenshot 09-08-17 23 04 54](https://user-images.githubusercontent.com/22508641/30236568-5a22b4fc-94ea-11e7-81d7-da9bfce1b94a.png)

**Comment by troggnostupidhs** [comment]
Priest Deck

AAEBAZ/HAgLgrAKQ0wIOHvsBnALlBNMK1wrsrgL6sALwuwLRwQLVwQLYwQLZwQLGzAIA

**Comment by troggnostupidhs** [comment]
Also tested playing Tar Creeper before and after transforming the opponent hero into a DK. Still didn't reproduce this issue.

![hearthstone screenshot 09-08-17 23 29 06](https://user-images.githubusercontent.com/22508641/30236713-c9120478-94ed-11e7-9144-ca2d5e1f089b.png)

**Comment by troggnostupidhs** [comment]
It must be Dk Valeera to DK Anduin

https://www.reddit.com/r/hearthstone/comments/712v2m/4_bugs_persisting_after_patch_91/

https://www.youtube.com/watch?v=Oaj3fMb1Zoc

**Comment by PattuX** [comment]
https://news.blizzard.com/en-gb/hearthstone/21507224/hearthstone-update-10-2-february-6-ranked-play-update

"Switching from Valeera the Hollow to Deathstalker Rexxar will now correctly allow Rexxar’s Battlecry to destroy minions buffed to 2 health by Stormwind Champion or similar effects."

Probably fixed the general bug that replacing Valeera ran Auras twice.

**Comment by VoidMayonnaise** [comment]
Confimed to be fixed.
![dk1](https://user-images.githubusercontent.com/28046803/36788934-c8c0b0e0-1cca-11e8-9821-18f2c6b7fb26.png)
![dk2](https://user-images.githubusercontent.com/28046803/36788931-c7053c80-1cca-11e8-8dc1-8e7c5cf0b2a9.png)
