### ISSUE TITLE
Brann + Corpsetaker could give you double lifesteal

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#804]
https://www.bilibili.com/video/av14267849
you can see lifesteal triggers twice at 0:18

But you cannot gain double lifesteal if you use 2 Leeching poison on your weapon.

**Comment by troggnostupidhs** [comment]
https://youtu.be/xxmD2r3FSCM?t=378

**Comment by troggnostupidhs** [comment]
I tested Brann + Prince Valanar. Lifesteal did not stack.

Deck
AAEBAf0GBO0FhRf2rgKe4gIN+wGcArkGkgf7B8QIzAjwEc8WtKwC58sCos0C980CAA==

![img001](https://user-images.githubusercontent.com/22508641/32995615-074394fc-cd45-11e7-9824-557ac4337503.png)

![img002](https://user-images.githubusercontent.com/22508641/32995616-074e1206-cd45-11e7-975a-b380e7694a77.png)

**Comment by troggnostupidhs** [comment]
Deck
AAEBAaToAgTtBfoGhRe8vQIN+wG0ArkG/gePCd0K6w/JFrPBAqfNAvfQApHiApboAgA=


![hearthstone screenshot 12-06-17 21 23 55](https://user-images.githubusercontent.com/22508641/33695541-d921b5f6-dacb-11e7-9401-e5c8bfa35f0a.png)
