### ISSUE TITLE
Auto Discard Clutchmother Zavas

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#807]
If Clutchmother is returned to hand with PO, she will be auto discarded each time that player ends their turn. It seems like the PO stays attached and triggers each time. 

https://www.reddit.com/r/hearthstone/comments/6xlycc/bug_auto_discard_clutchmother_zavas/

https://www.youtube.com/watch?v=Q3M2JWorfUM

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/712v2m/4_bugs_persisting_after_patch_91/

https://www.youtube.com/watch?v=Oaj3fMb1Zoc

**Comment by thoughthouse** [comment]
To clarify, this only works if PO is cast on Clutchmother while Clutchmother is in the hand, which is only possible with Illidan/Anubar shenanigans.

**Comment by troggnostupidhs** [comment]
https://youtu.be/xxmD2r3FSCM?t=319

**Comment by troggnostupidhs** [comment]
I think it's fixed

https://www.youtube.com/watch?v=VWhKK_wwaQ4

**Comment by troggnostupidhs** [comment]
Deck
AAEBAR8AD40B+wGcArQCtwK1A8kEuQbtCfcNzq4C180C3dIC39IC4eMCAA==

https://www.youtube.com/watch?v=U02HgCnrEfs

**Comment by Kybxd** [comment]
This bug still happens (replaceing Power Overwhelming with Corruption)
![qq 20181106153729](https://user-images.githubusercontent.com/18246091/48049527-ede28b80-e1d9-11e8-9f52-4ee013cbb795.png)
![qq 20181106153734](https://user-images.githubusercontent.com/18246091/48049525-ede28b80-e1d9-11e8-96fb-f27be0b61562.png)

BTW, this doesn't fit Peter Whalen's intended interaction between Corruption and Immortal Prelate.
![bqq5-5mxkzzt3csku-1f2](https://user-images.githubusercontent.com/18246091/48049586-18ccdf80-e1da-11e8-9a7c-804e23e08f28.jpg)

**Comment by Jetz72** [comment]
Does Corruption on Prelate actually work the way he says? 

I've heard reports of Corrupting Mist and Reckless Experimenter destroying Immortal Prelate while it's in the deck, and I'm wondering if it's a good idea to refactor this into an "enchantments triggering when attached card is outside the battlefield" post.

**Comment by Kybxd** [comment]
Corruption & Prelate bug is hotfixed immediately after patch 13.0. Power Overwhelming & Nightmare also work correctly now. But Corrupting Mist still mills Prelate from deck/discards Prelate from hand :( 

This video shows Corruption, Nightmare and Corrupting mist (3:00 to 4:35): https://www.bilibili.com/video/av38715045

**Comment by troggnostupidhs** [comment]
Fixes for Prelate

https://news.blizzard.com/en-us/hearthstone/22882146/hearthstone-update-february-5

>Corrupting Mist and Reckless Experimenter can no longer incorrectly cause Immortal Prelate to be removed from the hand or deck.

**Comment by Jetz72** [comment]
If I haven't misread anything, I think all the specific cases mentioned here were resolved? Opened a more general report in #1293 in case any more are found.
