### ISSUE TITLE
Build-A-Beast doesn't discover King of Beasts

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#810]
https://www.reddit.com/r/hearthstone/comments/71z6o6/why_deathstalker_rexxar_never_gets_king_of_beasts/

> I have tested with friend frequency of discovered beasts. We spent couple hours, but "King of Beasts" count is still 0. Is it banned or what?

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/71z6o6/why_deathstalker_rexxar_never_gets_king_of_beasts/dneq1yt/

> I've got it a couple of times.

**Comment by troggnostupidhs** [comment]
Played 2 games, probably ~50 build attempts. Did not get King of Beasts.

**Comment by troggnostupidhs** [comment]
Tried another innkeeper match, didn't see King of Beasts.

**Comment by troggnostupidhs** [comment]
This is intentional

https://us.battle.net/forums/en/hearthstone/topic/20760345889

**Comment by NightKev** [comment]
I'm pretty sure this was confirmed a while ago, though by now that post/tweet/whatever is lost to time I guess.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/83wi2w/it_is_here/dvleso6/?context=3
