### ISSUE TITLE
If a deathrattle/end of turn effect summons Rivendare/Drakkari, it will resolve twice

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#818]
> Kel’Thuzad will no longer trigger a second time if his first activation revives Drakkari Enchanter.

![1](https://user-images.githubusercontent.com/18246091/31699591-4e102098-b3f6-11e7-8900-c5e0270fa1d3.jpg)
![2](https://user-images.githubusercontent.com/18246091/31699594-506c5230-b3f6-11e7-9f84-f1a3708bfbf8.jpg)
![3](https://user-images.githubusercontent.com/18246091/31699596-50de0b8c-b3f6-11e7-8520-618990206425.jpg)
![4](https://user-images.githubusercontent.com/18246091/31699597-51402538-b3f6-11e7-9b4f-3ecff571280d.jpg)
![5](https://user-images.githubusercontent.com/18246091/31699599-51f344ec-b3f6-11e7-98a1-1d41ad0f7aea.jpg)

**Comment by troggnostupidhs** [comment]
I don't think we track issues that were untracked, but fixed in a release. Either way, it's fixed now.
