### ISSUE TITLE
If one of your minions is killed when you have a full board, Redemption will not work

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#820]
No screenshot or video, but I tested and confirmed this bug.

**Comment by troggnostupidhs** [comment]
Confirmed

![img000](https://user-images.githubusercontent.com/22508641/31750618-2a9d3390-b44f-11e7-86d1-9ddc82c5873a.png)
![img001](https://user-images.githubusercontent.com/22508641/31750619-2aaa58c2-b44f-11e7-87aa-ed1b05d02170.png)
![img002](https://user-images.githubusercontent.com/22508641/31750620-2ab97a1e-b44f-11e7-866f-8af91c31adf9.png)
![img003](https://user-images.githubusercontent.com/22508641/31750621-2acf6284-b44f-11e7-9212-bf470648bafc.png)
![img004](https://user-images.githubusercontent.com/22508641/31750622-2afc96c8-b44f-11e7-9b20-186ae6a5502c.png)

**Comment by Kybxd** [comment]
This has been fixed. Triggers in death phase seem not to be checked earlier now.

**Comment by Kybxd** [comment]
This seems to be only a hard fix - this bug still happens in Effigy. 

We used to say all on-death secrets have both queuing conditions and trigger conditions. And in my view the 9.2 mechanical change is that 'queuing conditions' is replaced by 'pre-check conditions'. And the pre-check timing for Death Phase is before Death Creation Step starts. Here is a table about conditions of all on-death secrets:

Secret | Pre-check conditions | Trigger conditions
-- | -- | --
Redemption | in play | in play, your board is not full
Avenge | in play, your board is not empty | in play, your board is not empty
Gateway Kodo | in play, your hand is not full | in play, your hand is not full
Cheat Death | in play, your hand is not full | in play, your hand is not full
Effigy | in play, your board is not full | in play, your board is not full
Duplicate | in play, your hand is not full | in play, your hand is not full

This results:
1. Avenge triggers as long as you have a minion now. (Your board can never be empty if one or more of your minions die to trigger Avenge!) For example, you only have a Haunted Creeper and play Avenge, opponent kills your creeper and Avenge give one spider +3/+2.
2. Gateway Kodo/Cheat Death/Duplicate never trigger when your hand is full at pre-check timing, but discard or force play one before the secret.

**Comment by troggnostupidhs** [comment]
Should this be reopened?
