### ISSUE TITLE
Temporary mind control effect can trigger end of turn effects twice 

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#821]
![1](https://user-images.githubusercontent.com/18246091/31770970-d7c60304-b50c-11e7-9f4e-dc77ab5e63c6.jpg)

Ragnaros first shoots a fireball for me, then returns to enemy and shoots again.
Kel'Thuzad and Y'Shaarj also have the same interaction.

**Comment by Patashu** [comment]
New Dominant Player bug lol. Surprising :o

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/77nge3/potion_of_madness_now_triggers_end_of_turn/

https://www.youtube.com/watch?v=jYtmS5v1jkw

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/77nge3/potion_of_madness_now_triggers_end_of_turn/donce39/

> mdonais 
We are going to fix this, not sure exactly when yet.

**Comment by troggnostupidhs** [comment]
Related to #29

**Comment by Kybxd** [comment]
This is fixed now.
