### ISSUE TITLE
Spellbender still works even if the spell is countered

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#822]
* https://twitter.com/YNisemono/status/921198736818294785 
It summons an 1/3 and does nothing else.

**Comment by Roxor9999** [comment]
Looks to me like this actually fixes the bug that spellbender always triggered after counterspell. Reading the card texts this seems like the logical outcome.

**Comment by Kybxd** [comment]
This is fixed. Counterspell works and Spellbender remains hidden.
