### ISSUE TITLE
Wind-up Burglebot ignores the survival requirement and always draws a card

### ISSUE THREAD

**Issue by Roxor9999** [HearthSim/hs-bugs#823]
When attacking a minion Wind-up Burglebot now always draws a card. Probably because of the new rule changes and since it was alive at the time it attacked.

![before](https://i.imgur.com/NMmGMML.jpg)

![after](https://i.imgur.com/Dbu4bXp.jpg)

**Comment by Kybxd** [comment]
Confirmed. Burglebot now works as 'Whenever this attacks and kills a minion' rather than surviving.

**Comment by troggnostupidhs** [comment]
Fixed

Deck
AAEBAf0GAu0F58ECDvsBnAK0ArkGkgfECMwIrRDwEc8WtKwCkbsC58sC980CAA==

![hearthstone screenshot 11-07-17 09 48 30](https://user-images.githubusercontent.com/22508641/32499599-0458451a-c3a1-11e7-8ceb-804b562affb9.png)

![hearthstone screenshot 11-07-17 09 48 58](https://user-images.githubusercontent.com/22508641/32499600-0463eab4-c3a1-11e7-9f6f-868c96093345.png)

**Comment by troggnostupidhs** [comment]
This is fixed.

Deck
AAEBAf0GAu0F58ECDvsBnAK0ArkGkgfECMwIrRDwEc8WtKwCkbsC58sC980CAA==

![hearthstone screenshot 11-07-17 09 48 30](https://user-images.githubusercontent.com/22508641/32499768-7a78042e-c3a1-11e7-94ba-c48d3593f599.png)

![hearthstone screenshot 11-07-17 09 48 58](https://user-images.githubusercontent.com/22508641/32499769-7abe9e66-c3a1-11e7-81ba-ab289bd901a4.png)
