### ISSUE TITLE
Justicar Trueheart's mana cost is not increased by Nerub'ar Weblord

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#832]
![qq 20171108180610](https://user-images.githubusercontent.com/18246091/32543091-9cc46eb4-c4af-11e7-8673-163210099d03.jpg)

**Comment by troggnostupidhs** [comment]
Confirmed. And it's not just visual, because Justicar is playable.

Deck
AAEBAf0EAu0FsBUOTfsBnAK0ArsCyQOWBbkG+wyIDomsAvSvAqO2ApjEAgA=


![img000](https://user-images.githubusercontent.com/22508641/32957478-c9cfd0ca-cb89-11e7-9ae2-3be1b18985b0.png)

**Comment by troggnostupidhs** [comment]
https://youtu.be/xxmD2r3FSCM?t=597

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=jArfMxDLl0U

**Comment by Kybxd** [comment]
Fixed.

![111](https://user-images.githubusercontent.com/18246091/36894862-ccba551a-1e47-11e8-9e49-797e664a5d25.jpg)
