### ISSUE TITLE
Stolen Nat Pagle visually fishes from wrong deck

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#84]
If a Cabal Shadow Priest takes control of an enemy Nat Pagle, the fishing animation incorrectly plays on the opponent's deck when triggered.

http://us.battle.net/hearthstone/en/forum/topic/15700254845
http://us.battle.net/hearthstone/en/forum/topic/17085018379

**Comment by Patashu** [comment]
This bug has not been confirmed since April 2015.

**Comment by jleclanche** [comment]
Confirmed fixed.
