### ISSUE TITLE
Attacking with a Lifesteal minion when you have Bolf and Auchenai on board will trigger the Lifesteal several times

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#840]
Edit: See update below

Even if Bolf should die, it shouldn't continue after he has <= 0 health.

https://hearthstone.gamepedia.com/Patch_9.0.0.20457
> Auchenai Soulpriest and similar effects will only trigger once when combined with Lifesteal.

It's also inconsistent with that change.

https://youtu.be/xxmD2r3FSCM?t=699

![image](https://user-images.githubusercontent.com/22508641/32993461-646bdf32-cd26-11e7-939b-53d18b42e94f.png)

**Comment by troggnostupidhs** [comment]
They removed the loop. But the behavior seems odd now. Bolf and your hero take the damage.

![hearthstone screenshot 10-28-18 12 48 22](https://user-images.githubusercontent.com/22508641/47619022-39958680-dab0-11e8-9588-b71c1686ad55.png)
![hearthstone screenshot 10-28-18 12 48 43](https://user-images.githubusercontent.com/22508641/47619023-39958680-dab0-11e8-9e8f-d6e884b6dd65.png)
![hearthstone screenshot 10-28-18 12 49 21](https://user-images.githubusercontent.com/22508641/47619024-3a2e1d00-dab0-11e8-93ff-ff4c2c328fcb.png)
![hearthstone screenshot 10-28-18 12 48 36](https://user-images.githubusercontent.com/22508641/47619025-3a2e1d00-dab0-11e8-9983-b3e51f46a8aa.png)


AAEBAa0GAqMUoIADDu0B+wGQAuUEuQbTCtcK+rACtbsC5MwC5swC8M8CkeICpvACAA==

**Comment by Jetz72** [comment]
It does seem inconsistent that it also damages your hero. Seems like it should only damage Bolf once, and not trigger a second time.

**Comment by troggnostupidhs** [comment]
Should be fixed in next release

https://www.reddit.com/r/hearthstone/comments/a0mc0j/new_card_snapjaw_shellfighter/eaius3f/?context=2

**Comment by troggnostupidhs** [comment]
Closing this because the loop is fixed.

See #918 for the Bolf + hero damage part

**Comment by troggnostupidhs** [comment]
Should be fixed in next release

https://www.reddit.com/r/hearthstone/comments/a0mc0j/new_card_snapjaw_shellfighter/eaius3f/?context=2

**Comment by troggnostupidhs** [comment]
See #918 for the Bolf + Auchenai + Lifesteal problem
