### ISSUE TITLE
In Arena, unable to discover Death Knights with Kabal Courier

### ISSUE THREAD

**Issue by ZonisX** [HearthSim/hs-bugs#841]
Death Knight cards are undiscoverable with Kabal Courier in Arena. They remain discoverable with Lotus Agents and Grimestreet Informant.

**Comment by thoughthouse** [comment]
false?
https://youtu.be/iLb3_Nbikek?t=1337

**Comment by PattuX** [comment]
Is that video from the most recent patch? If so, I'll close this.

**Comment by troggnostupidhs** [comment]
I'm assuming it is from the upload date.
