### ISSUE TITLE
Acquiring a Shadow Reflection by means other than Valeera the Hollow's hero power makes it unplayable

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#845]
Original Title: "Decks Assemble: Using Valeera the Hollow may result in an unusable Shadow Reflection in hand"

https://www.reddit.com/r/hearthstone/comments/7f3fb8/using_valeera_the_hollow_in_this_week_brawl/

Even though an Edwin was played that turn, the Shadow refection in hand turned into Edwin and has a yellow border, it's not playable.

![image](https://user-images.githubusercontent.com/15743638/33224982-ea53392c-d16f-11e7-9994-aaa147cebdd9.png)

**Comment by troggnostupidhs** [comment]
I can confirm this happens.

**Comment by troggnostupidhs** [comment]
![img005](https://user-images.githubusercontent.com/22508641/47954948-347c7f80-df67-11e8-8e00-04e0579fdc41.png)

**Comment by Jetz72** [comment]
Seems Shadow Reflection in general doesn't function without its enchantment. 
https://www.reddit.com/r/hearthstone/comments/bpg3wt/discarded_shadow_reflection_glitch_in_dalaran/
> https://www.gfycat.com/MintyValuableLark

Clip shows the card being added by Soulwarden after presumably being discarded earlier. Seems like a viable way to test non-enchanted Reflections outside of a Brawl.

**Comment by Jetz72** [comment]
https://playhearthstone.com/en-us/blog/23239986/hearthstone-update-december-5-descent-of-dragons
>Shadow Reflections generated by Valeera the Hollow now function properly if discarded and then created by Soulwarden.

Generalized this issue since it originally couldn't happen outside the Brawl, but it's presumably the same root cause.
