### ISSUE TITLE
Flamewaker triggers when being pulled by a Deathlord killed with a spell

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#846]
https://youtu.be/LlP9kzdZMR0?t=6m12s

With the new changes to the mechanics (https://www.youtube.com/watch?v=3nJDHtyh7PU) this is not supposed to happen anymore.

I'm sure this is more broad than that, let's see whether we can find any other similar reports.

**Comment by VoidMayonnaise** [comment]
Already fixed.
Deathlord was killed by Arcane Blast and it pulled the Flamewaker out. However the Flamewaker didn't trigger at all.
![hearthstone screenshot 03-02-18 23 48 41](https://user-images.githubusercontent.com/28046803/36907928-d003515e-1e74-11e8-8a09-a19b9264bba0.png)
![hearthstone screenshot 03-02-18 23 48 22](https://user-images.githubusercontent.com/28046803/36907931-d1f0b7cc-1e74-11e8-9ea1-21e6f5671c77.png)
