### ISSUE TITLE
The Void Singularity: Deathrattles that summon minions are not handeled consistently

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#847]
If you play a Deathrattle minion that summons another minion on an empty board, the end of turn effect triggers twice and absorb the summoned minion.

https://www.reddit.com/r/hearthstone/comments/7gg1es/void_singularity_brawl_bug/

> Im sure many others have noticed this, but I haven’t seen a post and wanted to bring some attention to the phenomenon.
> 
> If you play a deathrattle that summons another minion onto an empty board, the brawl end of turn effect (which i shall call “event horizon” for flavor) will trigger twice. First it will kill the deathrattle minion, summoning a void creature of the same stats and whatever minion is dropped by the deathrattle. Second, it will trigger again combining all the minions together.
> 
> This does not work when there is already a void creature in play. The event horizon effect will cause the deathrattle minion to combine with the void creature and then leave the summoned minion in play next to the void creature.
> 
> The bug goes one level further, however. For one reason of another, if you trigger the double event horizon effect on certain minions (such as [[rat pack]]), it gains extra stats out of nowhere, as if the first event horizon effect accounted for the summoned rats. This does not appear to be intentional, and is certainly unbalance.
> 
> [[rat pack]] is a 3 mana 2/2 that summons 2 1/1 rats the turn it’s played (in this brawl). Even accounting for the double event horizon bug, you should end up with a single 4/4 (2/2 + 1/1 + 1/1), but you don’t. Instead you end up with a 6/6.
> 
> Blizzard halp!

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7gfsyz/bug_with_deathrattles_summoning_tokens_in_this/

https://www.reddit.com/r/hearthstone/comments/7gfgvo/gamebreaking_tavernbrawl_bug/

https://www.reddit.com/r/hearthstone/comments/7gfcpx/tavern_brawl_inconsistencies/

https://www.reddit.com/r/hearthstone/comments/7gf76q/tavern_brawl_big_bad_wolf_bug/

https://www.reddit.com/r/hearthstone/comments/7gezjr/tavern_brawl_inconsistency/

https://www.reddit.com/r/hearthstone/comments/7geyhk/bug_in_tavern_brawl/

**Comment by troggnostupidhs** [comment]
https://youtu.be/Zi9dYMKvyLk

**Comment by Jetz72** [comment]
Fixed in this week's rerun.
![hearthstone screenshot 01-30-19 17 42 00](https://user-images.githubusercontent.com/8607832/52018134-6befbf00-24b7-11e9-96d3-8c85b23851ea.png)
![hearthstone screenshot 01-30-19 17 42 09](https://user-images.githubusercontent.com/8607832/52018140-6eeaaf80-24b7-11e9-94da-57b6ed249449.png)
