### ISSUE TITLE
The Void Singularity: 0 attack Void Singularity minion displays 1 attack when hovering over it

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#848]
![image](https://user-images.githubusercontent.com/15743638/33405269-eede74c4-d567-11e7-9833-9355f0c3cf2f.png)

**Comment by Jetz72** [comment]
Fixed in this week's rerun.
![hearthstone screenshot 01-30-19 17 42 09](https://user-images.githubusercontent.com/8607832/52018058-2e8b3180-24b7-11e9-9c1f-ab7aa1f56b98.png)
