### ISSUE TITLE
Siege Engine does not trigger when you play a Death Knight card

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#849]
https://www.bilibili.com/video/av16851830/
(Starting from 7:55)

**Comment by troggnostupidhs** [comment]
Confirmed. 

This is probably a more general issue. Playing a Death Knight probably doesn't count as armor gain. As far as I know, Siege Engine is the only way to test it.

**Comment by Kybxd** [comment]
Fixed in this patch. Both Siege Engine and Druid's spellstone are tested.
