### ISSUE TITLE
Explosive Rune could deal more than 6 damage since it does not ignore mortally wounded minions

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#853]
![bqq5-hduaz2lt3cs112-ku jpg medium](https://user-images.githubusercontent.com/15797857/33760224-eb2599aa-dc3f-11e7-96c8-95d41e143975.jpg)
![bqq5-l0mhxbz32t3cs112-ku jpg medium](https://user-images.githubusercontent.com/15797857/33760225-eb5d4346-dc3f-11e7-951b-74f23c423e25.jpg)
image may failed.
But it's a 2/1 murloc first trigger snipe, then trigger Explosive Runes, and deal 9 damage to enemy hero.

Normally these after play phase should ignore mortally wounded minion, and Explosive does not, which make this bug.

Even if it's intended for explosive rune deal damage to mortally wounded minion, they should still set the maximum damage to 6(+ spell damage).

**Comment by Patashu** [comment]
LOL

**Comment by troggnostupidhs** [comment]
Hunter Deck
AAEBAR8E+wGSBe0F7wgNswGcArQChQP+A/UFrga5BrdsubQC6rsC4soCp80CAA==

Mage Deck
AAEBAf0EAoUD7QUOswH7AZwCtAKrBPUFuQaYDbdswcEC4soCj9MC1eECluQCAA==

**Comment by 10925** [comment]
Seems being hotfixed.

**Comment by troggnostupidhs** [comment]
Confirmed, this is fixed.
