### ISSUE TITLE
The order of the spells Lynessa Sunsorrow casts is always consistent with the order you casted them in

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#854]
It should be random according to Peter Whalen's twitter.

https://twitter.com/khell18/status/935177298147401728

**Comment by Kybxd** [comment]
Besides, Lynessa works very similar to Yogg-Saron. A Forced Death Phase is run between each spell (KJ + Silvermoon Portal), and the battlecry stops immediately she leaves board (Shadowstep or Fireball).

The only difference is that she doesn't check whether she is a valid target. She Shatters herself despite not being frozen.

**Comment by troggnostupidhs** [comment]
https://youtu.be/kW_3BUZoJ2c?t=195

**Comment by VoidMayonnaise** [comment]
Peter Whalen admitted that he made a mistake in that twitter. This order should be intended.
https://mobile.twitter.com/LegendaryFerret/status/982492186041176064

> Yep, you're right - my bad.  Double checked and Lynessa is in order.  Double-checked Tess and she is in a random order.
