### ISSUE TITLE
Dungeon Run: When a boss evolves one minion to Garrison Commander or Coldarra Drake, his hero power is not refreshed

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#857]
![1](https://user-images.githubusercontent.com/18246091/33797089-9c4b552e-dd3c-11e7-8d82-bca290e0d213.jpg)
<img width="360" alt="2" src="https://user-images.githubusercontent.com/18246091/33797090-9cd49b5e-dd3c-11e7-8634-45ee6d4d85a9.png">

Thrall, Deathseer‘s hero power may also have this bug.

**Comment by Kybxd** [comment]
This may only happen to bosses.
![1112](https://user-images.githubusercontent.com/18246091/33801152-85b92ff2-dd8c-11e7-92c9-56c32f4c2c46.png)
![11119](https://user-images.githubusercontent.com/18246091/33801153-867dd26c-dd8c-11e7-8872-70b571d56076.png)

**Comment by Dragas** [comment]
![coldarra](https://i.imgur.com/p6wi06F.png)

**Comment by troggnostupidhs** [comment]
Probably intended, just like Mindbreaker and Sideshow Spelleater don't work in Adventures

**Comment by troggnostupidhs** [comment]
Rafaam playing Garrison Commander doesn't have the Hero Power refresh. I think this is intentional behavior.

![img001](https://user-images.githubusercontent.com/22508641/47958757-7a0d6c80-dfa8-11e8-8127-890fb14c8483.png)

```
### Custom Priest
# Class: Priest
# Format: Wild
#
# 2x (0) Circle of Healing
# 2x (0) Silence
# 2x (0) Target Dummy
# 2x (1) Binding Heal
# 2x (1) Flash Heal
# 2x (1) Holy Smite
# 2x (1) Power Word: Glory
# 2x (1) Power Word: Shield
# 2x (1) Test Subject
# 2x (2) Garrison Commander
# 2x (2) Lightwell
# 2x (2) Shadow Visions
# 2x (2) Spirit Lash
# 2x (3) Twilight's Call
# 2x (4) Greater Healing Potion
# 
AAEBAa0GAA+XAuUEnQalCdIKjRDVE4gUlhS3uwLRwQLSwQLwzwKp4gLxgAMA
# 
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
```
