### ISSUE TITLE
Rummaging Kobold can give you the weapon returned to hand by Doomerang

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#859]
![qq 20171211003102](https://user-images.githubusercontent.com/18246091/33806964-a5c5b332-de0a-11e7-9455-d786637fd00b.gif)

(This is not because Kingsbane is special. Test with another weapon and you can result the same. )

**Comment by troggnostupidhs** [comment]
Doomerang probably shouldn't destroy the weapon, which makes this seem like a bug. It's possible that this is intended.

Doomerang
> Throw your weapon at a minion. It deals its damage, then returns to your hand.

Rummaging Kobold
> Battlecry: Return one of your destroyed weapons to your hand.

**Comment by ceceita** [comment]
used doomerang
![](https://i.imgur.com/tj5hlBx.jpg)
played Rummaging Kobold later and no 2nd weapon
![](https://i.imgur.com/w2L7I0P.jpg)
