### ISSUE TITLE
Skull erroneously shown on combat with Poisonous minion that will not cause death

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#86]
If minion with the Poison ability such as Emperor Cobra is reduced to 0 attack by Shrinkmeister, when attacking with it or into it, a Skull symbol incorrectly shows that the target will be killed by Poison. If the target has Divine Shield or is Immune, causing the Poisonous minion to do 0 damage and thus not trigger, the Skull symbol is also incorrectly shown.
- http://us.battle.net/hearthstone/en/forum/topic/15537715051
- http://www.twitch.tv/adwcta/v/19308607?t=2h44m30s
- https://www.reddit.com/r/hearthstone/comments/3regc1/emperor_cobra_vs_divine_shield_skull_bug/
- http://imgur.com/LJBwYGh

**Comment by Patashu** [comment]
Confirmed in 3.1:

<Aprel> Just saw a visual bug on adwcta's stream. Divine-shielded silent knight attacking into a cobra: the skull tooltip appeared on the silent knight even tho it wouldn't die

**Comment by Patashu** [comment]
Confirmed in 3.2:

https://www.reddit.com/r/hearthstone/comments/3regc1/emperor_cobra_vs_divine_shield_skull_bug/

**Comment by culinko** [comment]
Also happens with Immune minions: http://imgur.com/LJBwYGh. Edited the first post.

**Comment by Patashu** [comment]
Confirmed in 4.0:

http://us.battle.net/hearthstone/en/forum/topic/20043314709

**Comment by troggnostupidhs** [comment]
This still happens

![hearthstone screenshot 03-02-17 23 14 31](https://cloud.githubusercontent.com/assets/22508641/23538120/d0f5c7d6-ff9e-11e6-8ff1-e65b170a0d4e.png)

**Comment by troggnostupidhs** [comment]
Fixed

![hearthstone screenshot 06-03-17 18 33 06](https://cloud.githubusercontent.com/assets/22508641/26757507/796f3c5a-488b-11e7-9ddf-e814359e4a3d.png)
