### ISSUE TITLE
Divine Shield from Unidentified Elixir is not removed by silence effect

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#860]
https://youtu.be/7zyp5-leYXI
If you Faceless this minion, the copier's Divine Shield also cannot be silenced.

Update: The minion needn't to be already silenced.

**Comment by troggnostupidhs** [comment]
Attacking is shown in the video, it's not a display issue

![image](https://user-images.githubusercontent.com/22508641/33910801-f72a7560-df5d-11e7-8050-c1ec31dd5c96.png)

**Comment by troggnostupidhs** [comment]
Deck
AAEBAZ/HAgAP+wGiArQC5QTyBbkGpQnTCtcK+rAC8LsC4b8C0cEC1cECv+UCAA==

**Comment by riQQ** [comment]
Video: https://clips.twitch.tv/AdventurousRudeBurritoKappaClaus

**Comment by Otbdave** [comment]
Another example in arena https://www.twitch.tv/videos/215234032

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20760585875

> Thanks for the reports folks. We are aware of this one and working on getting it fixed :)

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21507224/hearthstone-update-10-2-february-6-ranked-play-update

> Fixed a bug where the Divine Shield provided by Elixir of Purity could not be silenced.

**Comment by troggnostupidhs** [comment]
Deck
AAEBAZ/HAgAP+wGcAqICtALlBPIFuQalCdMK1wryDPqwAvC7AtHBAr/lAgA=
