### ISSUE TITLE
Uncollectible cards can have a rarity gem

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#865]
Currently only Nerubian

https://www.reddit.com/r/hearthstone/comments/7j91he/bug_the_nerubian_that_comes_out_of_the_nerubian/

> ![image](https://user-images.githubusercontent.com/22508641/33965729-09c2720e-e02b-11e7-9d84-765e6c3c8efa.png)

From bbrode, this shouldn't happen

https://www.reddit.com/r/hearthstone/comments/7b7e4o/marins_chest_is_not_technically_a_legendary/dpg1lkz/

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21507224/hearthstone-update-10-2-february-6-ranked-play-update

> Removed rarity gems from several summoned minions.

**Comment by troggnostupidhs** [comment]
Checked Nerubian Egg and Beneath the Grounds

Deck
AAEBAYO6AgAPtAHyAfsBjALcAuAE+wX6DZsUkrYC+MECgcIClc4ClNAC3NECAA==

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/ajnrve/2_years_of_hearthstone_and_i_never_saw_this_card/

![image](https://user-images.githubusercontent.com/22508641/51776466-4f264680-20c7-11e9-842c-5aa64ef1646d.png)

Shadow of Nothing has this problem

**Comment by Jetz72** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/spellbender-minion-bug/4446
>The minion summoned by Spellbender still has a rarity gem, which it isn’t supposed to have.

Don't have a screenshot handy but the tags check out:
>[Spellbender][tt_010a][1086]
[1 Mana, 1/3 Epic Minion]
HEALTH=3, ATK=1, COST=1, CARD_SET=3, CLASS=4, CARDTYPE=4, RARITY=4, AttackVisualType=2

**Comment by Jetz72** [comment]
Golemagg in the Showdown at Blackrock Mountain brawl has a gem as well.

>[Golemagg][BRMC_95][2690]
[50 Mana, 20/20 Legendary Minion]
Costs (1) less for each damage your hero has taken.
HEALTH=20, ATK=20, COST=50, ELITE=1, CARD_SET=18, CLASS=12, CARDTYPE=4, RARITY=5

https://youtube.com/watch?v=DueDU1Dto5M&t=3m52s

**Comment by troggnostupidhs** [comment]
Shadow of Nothing was fixed

![image](https://user-images.githubusercontent.com/22508641/60459123-4570b400-9c0e-11e9-9c4e-2595d652f85b.png)

Spellbender too

![image](https://user-images.githubusercontent.com/22508641/60459217-8799f580-9c0e-11e9-97f1-74c3f1e7fd55.png)

**Comment by troggnostupidhs** [comment]
Golemagg is currently the only one left, I believe

**Comment by troggnostupidhs** [comment]
Golemagg was fixed. I think we can close this for now.

![image](https://user-images.githubusercontent.com/22508641/64892139-9d318f80-d641-11e9-848b-33b625be0598.png)
