### ISSUE TITLE
The summoned copies of Doppelgangster do not have their deathrattle triggered by Spiritsinger Umbra when they are buffed with Val'anyr

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#868]
(Starting from 20:52) https://www.bilibili.com/video/av17299153/

However, if you play Saronite Chain Gang, both minions' Deathrattles work.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761696219

> 
> It seems this is a bug. Let me describe below :-
> 
> I have Umbra, Chain Gang, and Doppel. Chain Gang and Doppel both have Valanyr's deathrattle on them.
> 
> Case 1: I put Umbra on field, then Doppel. I expect 3 Valanyrs come into my hand. But I just saw 1 Valanyr.
> 
> Case 2: I put Umbra on field, then Chain Gang. I expect 2 Valanyrs. It actually does have 2.
> 
> I think the first case is a bug. :P~~~

---

> We are aware of this issue and working on it :)

**Comment by Kybxd** [comment]
Still happening in Patch 10.4.
