### ISSUE TITLE
Rank image incorrectly shows as Rank 15 for a single frame while shrinking

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#87]
During a ranked match's victory/defeat animation where your Rank image is shrinking, you can observe a Rank 15 image for a brief moment.

http://www.reddit.com/r/hearthstone/comments/2undie/this_bug_that_everyone_experiences_yet_nobody/
https://www.youtube.com/watch?v=UWs-XyUw4Pc&t=2m30s

**Comment by culinko** [comment]
Confirmed in 6.0: https://www.reddit.com/r/hearthstone/comments/4yxg6o/can_we_please_fix_that_stupid_rank_15_icon_bug/.

**Comment by troggnostupidhs** [comment]
Confirmed 8.0

https://www.reddit.com/r/hearthstone/comments/690pfa/is_it_just_me_or_am_i_seeing_the_rank_15_logo_pop/

**Comment by troggnostupidhs** [comment]
I think this is fixed

https://www.youtube.com/watch?v=PZ1d6DXWPNs&t=9
