### ISSUE TITLE
Ixlid (controlled by Dominant Player) summons both original minion and sheep when the minion is transformed by Potion of Polymorph

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#872]
* https://youtu.be/hgV2v1KI8g8
Animated Berserker (Dominant) and Dred (first played) also act in this way. If they don't kill the played minion and then it's polymorphed, they can damage the sheep again. I'm not sure whether these are also bugs, because they look rational to me.

My thoughts:
In #727 , _Inserted Phase_ is introduced to explain how self-transform minions work. In fact, this also applies to Potion of Polymorph.
> So what I think is that there is an After Play Phase and an After Summon Phase for the transformed minion within the Battlecry Phase.

As to the fix of bug 727, I used to believe that all after-play triggers are classified to work in the inserted phase, or in the original timing. But this is not completely correct. In fact, it's just that these triggers - Hidden Cache, Rumbling Elemental, Sherazin, Seed, Patches the Pirate, The Marsh Queen, The Caverns Below and Voidform's refreshing effect are commanded not to work in the inserted phase. Other triggers don't work in the original timing for a very simple reason - the subject has been removed.

This makes no sense to self-transform minions, but not to Potion of Polymorph. If a trigger not in the above list works before Potion of Polymorph and is not removed (i.e. excluding secrets), it can also work in the inserted phase. Only 3 triggers meet this condition - Ixlid, Animated Berserker and Dred.

To fix this, one possible idea is to use a tag. When Ixlid triggers ,his tag is switched to 1. And Ixlid cannot trigger when his tag is 1. Reset the tag to 0 at the end of the sequence. If Animated Berserker and Dred are considered to be bugs, they can also use similar tags.

**Comment by troggnostupidhs** [comment]
Also see #29

**Comment by Kybxd** [comment]
![qq 20180606233108](https://user-images.githubusercontent.com/18246091/41048692-e4ab00d0-69e1-11e8-9669-a2ca14b48fc1.jpg)
This is fixed. Dominant Ixlid: a copy of original minion + sheep. Secondary Ixlid: sheep ×2.
