### ISSUE TITLE
Upgrading Spellstones detatches Mana Cost enchantments

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#874]
https://youtu.be/IEBoD3FXS6o?t=1m45s

Imo inconsistent with Zerus/Molten Blade, but I guess may be intended.

**Comment by Kybxd** [comment]
This is fixed now.

https://www.youtube.com/watch?v=h_NeNhte6oE

**Comment by Kybxd** [comment]
Seems that it is not completely fixed. Some Mana Cost enchantments are still not preserved, such as Mana Bind.

**Comment by PattuX** [comment]
If it's inconsistent then it's definetely not intended. Peopened already, but still any proof would be nice.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7rcs7h/an_interesting_mana_bind_interaction_i_found/

![image](https://user-images.githubusercontent.com/22508641/35484530-08da1f46-041f-11e8-8e32-98e0cb331c13.png)

**Comment by troggnostupidhs** [comment]
Possibly related?

https://us.battle.net/forums/en/hearthstone/topic/20762036308

> The Hunter aka Hex in the current Tavern Brawl gave me a card, see screenshot. The card said (0) "unidentified armor" for a split second before it identified the armor, and now it costs 6 instead of 0.

---

> Thanks for the report. It's kind of an odd case because it did give you a 0 cost card. The card transforms into another card when it enters your hand though. Transforming cards typically don't maintain buffs or cost reductions, because they are technically not the same card anymore.
> 
> I agree that it's a bit confusing :^/

**Comment by Kybxd** [comment]
Still happending in this week's brawl (Nefarian's Hero Power).
![qq 20180310143311](https://user-images.githubusercontent.com/18246091/37239109-59deb084-2470-11e8-8237-24db19089c17.jpg)

**Comment by Kybxd** [comment]
Still happening in Patch 10.4. Tested with Mana Bind + Ruby Spellstone.

**Comment by Kybxd** [comment]
Still happening in this week's brawl (Skelesaurus Hex's Hero Power).

**Comment by Jetz72** [comment]
Worth pointing out that the behavior originally described is no longer inconsistent, as Zerus and friends also detach mana cost enchantments when they shift as of 12.0. Instead, the opposite behavior could be considered inconsistent. Cards that were considered "fixed" in this regard may be worth retesting.

**Comment by Jetz72** [comment]
Tested with Thaurissan. The discount was retained across an upgrade for the Rogue's spellstone. So if Mana Bind and Hex's hero power discount isn't preserved, then that is inconsistent.

**Comment by troggnostupidhs** [comment]
It now stays at 0 mana

![Hearthstone Screenshot 03-19-19 21 02 37](https://user-images.githubusercontent.com/22508641/54651811-cefadc80-4a8a-11e9-9691-29c3182438ac.png)
![Hearthstone Screenshot 03-19-19 21 02 50](https://user-images.githubusercontent.com/22508641/54651812-cefadc80-4a8a-11e9-894c-baa718dcfb55.png)
