### ISSUE TITLE
Reconnecting after fatigue shows your deck as full

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#88]
f you reconnect to a game after you enter Fatigue, the Deck image will be shown again.
http://imgur.com/ZDDItu8,tgKVPaT

**Comment by culinko** [comment]
https://www.youtube.com/watch?v=XhZusEJswSA&t=8m53s

**Comment by jleclanche** [comment]
This affects spectator mode as well, experienced it the other day.

**Comment by Xinhuan** [comment]
Tested with culinko, on both PC and iPads. Appears to be fixed.
