### ISSUE TITLE
Silence working partially against Unidentified Elixir

### ISSUE THREAD

**Issue by TTCrackers** [HearthSim/hs-bugs#884]
My opponent played Unidentified Elixir, Elixir of Purity: +2/+2 and divine shield and when I silenced it with Spellbreaker kept his divine shield. I don't know why?
![hearthstone screenshot 01-05-18 15 47 01](https://user-images.githubusercontent.com/28037684/34628145-58edc1c2-f231-11e7-8eca-2b156977dfb7.png)

**Comment by riQQ** [comment]
Duplicate of #860
