### ISSUE TITLE
Opponent playing Choose One cards after King Togwaggle has swapped decks causes an animation hang

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#890]
https://www.reddit.com/r/hearthstone/comments/7r01qn/annoying_bug_with_king_togwaggle/

> When playing Druid and when you swap decks with your opponent whenever they play one of your choose one cards you get the card back displayed right in front of you like your playing the card and normally it doesn't go away

![image](https://user-images.githubusercontent.com/22508641/35074532-62cf412c-fbbc-11e7-9dc8-b7ffd18b1bc0.png)

**Comment by troggnostupidhs** [comment]
Confirmed this. You can't play cards once the card is being displayed.

**Comment by troggnostupidhs** [comment]
Reproduction Steps:
1. Player A plays a Druid deck containing King Togwaggle and Choose One cards.
1. Player A plays King Togwaggle to swap decks.
1. Player B does not play King's Ransom.
1. Player B plays a Choose One card that is from Player A's deck and chooses an option.
1. Player A will have the hovering card displayed and it will not go away. They will not be able to play cards on their turn.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086687

**Comment by troggnostupidhs** [comment]
https://youtu.be/IAJ-Zp13W-k?t=112

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=oLmggfghmlM

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761007500

> Hi so I found a bug that causes your game to freeze and you're unable to click and interact with your cards all you can do is hero power. I played King Togwaggle and stole my opponents deck while his hand was full so he could not switch back. Then he played Moonfire a card he had stolen from Curious Glimmerroot which caused a giant card back to be stuck on my screen and on my turn I was unable to click my cards but I found that I could in fact hero power and interact with the hero power option. https://imgur.com/a/1pIns is a screenshot of how the image appeared.

**Comment by PattuX** [comment]
Can this be reproduced with Death Grip?

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761087409?page=2#post-33

> Yeah the fix was for the Tavern Brawl only. The fix for Togwaggle is still being worked on.

**Comment by troggnostupidhs** [comment]
https://youtu.be/UkJDLYrXcns?t=13m33s

https://youtu.be/UkJDLYrXcns?t=20m24s

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21943493/hearthstone-update-11-4-july-10-the-boomsday-project-pre-purchase

> Resolved an issue where Choose One choices would persist on the board if a player used King Togwaggle to swap decks with the opponent.
