### ISSUE TITLE
Bolvar, Fireblood does not trigger if a Divine Shield minion is summoned and loses its Divine Shield in the same Phase

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#893]
* https://youtu.be/2qBUomJjruk

The first Sheep's DR breaks 3 Divine Shields, but Bolvar and Light's Sorrow only trigger once (for Bolvar). The newly-summoned Argent Squires are ignored.

In #793 I mentioned if Rotface summons Bolvar during Volcano and then its Divine Shield is broken, Bolvar doesn't gain +2 Attack. Actually it belongs to this bug.

**Comment by troggnostupidhs** [comment]
Is this bug different than #793?

**Comment by Kybxd** [comment]
Yes, #793 has already been fixed in Patch 9.2 but this bug still exists now.

**Comment by Kybxd** [comment]
![qq 20180818131012](https://user-images.githubusercontent.com/18246091/44296030-1e580f00-a2e8-11e8-940f-22852965ca94.png)
This bug is fixed. In the picture above I exchange Moat Lurker with Explosive Sheep. Moat Lurker summons a Shielded Minibot then Sheep breaks Divine Shield. 3/7 Bolvar triggers and becomes 5/5.
