### ISSUE TITLE
Nefarian Rises: Playing Shadow or Light can cause the card to block view of the board

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#894]
https://us.battle.net/forums/en/hearthstone/topic/20761087409

---

 Was in tavern brawl as priest. Other player played a choose one card. The card backs in my view did not disappear from my view after he chose so had to play the game with cards blocking view of board.

---

The bug looks like this:

https://i.imgur.com/VljqFjs.png

I couldn't play cards in my hand. However, after clicking my hero power, it then let me play cards from my hand.

![image](https://user-images.githubusercontent.com/22508641/35363023-fd77bef6-0135-11e8-8a77-be6a57514a14.png)

---

Thanks for these reports. Looking into it. Based on the reports I have seen on the forums so far I am thinking this might be coming from the Shadow or Light? card in the Priest deck.

If you run into this issue, please update this with more details :)

---

I also got this bug just now, and yes it was the Shadow or Light card. My mouse was hovered over one of the card backs. The one I wasn't hovered on disappeared, the other stayed on the screen. I then couldn't play any of my cards and had to concede.

---

Thanks for all the information. We have got the cause nailed down now and are working on a fix. As usual, no timeframe on that fix happening.

Restarting your client does make the big card go away, so that can be used as a workaround for now :)

**Comment by troggnostupidhs** [comment]
Seems to happen when your opponent plays Shadow or Light

**Comment by PattuX** [comment]
I think this should be merged with #890

**Comment by troggnostupidhs** [comment]
Oh, possibly. If it only happens Shadow or Light is played after Nefarian swaps decks.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790#post-2

> Fix for cards getting stuck on screen during the Nefarian Rises Tavern Brawl.

https://www.reddit.com/r/hearthstone/comments/7t4iep/i_think_removed_shadow_or_light_from_the_tavern/

>I noticed that there seem to be two new cards for priest in the tavern brawl, well not new but they werent in his deck before, they are Greater healing potion and Eternal Servitude. And i think they replaced "Shadow or Light?" probably because of the visual bug. Great hot fix

Allegedly, it's not really fixed. They just replaced the problem cards.

Closing this because the reproduction case was removed.
