### ISSUE TITLE
Sir Finley cannot discover Shapeshift

### ISSUE THREAD

**Issue by thoughthouse** [HearthSim/hs-bugs#898]
https://www.reddit.com/r/hearthstone/comments/7ukfh9/finley_bugged_in_rogue_no_shapeshift_offered_over/
https://us.battle.net/forums/en/hearthstone/topic/20760967340

hsreplay stats: https://hsreplay.net/cards/2948/sir-finley-mrrgglton/#gameType=RANKED_WILD&tab=discover

**Comment by riQQ** [comment]
![2018-02-01 22_10_31-sir finley mrrgglton - hearthstone card statistics - hsreplay net](https://user-images.githubusercontent.com/3404787/35703569-ca380362-079c-11e8-99d8-fdd24b634725.png)

**Comment by PattuX** [comment]
https://www.reddit.com/r/hearthstone/comments/7v2d4q/renounce_darkness_doesnt_turn_you_into_druid/

Possibly also bugged with Renounce?

**Comment by troggnostupidhs** [comment]
> I play Renounce Darkness quite a bit. Last season I played it 62 times and here are the stats (from hsreplays):
> 
> * Rogue: 13
> * Paladin: 12
> * Priest: 11
> * Mage: 9
> * Warrior: 8
> * Shaman: 6
> * Hunter: 3
> * Druid: 0
> 
> So yeah you might be right. Druid for sure was possible to get before, but in some of the newest patches something has changed. 
> 
> I also checked some of my older replays and at least 6 months ago I was able to renounce into druid.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790#post-3

> Resolved issue where Sir Finley was not giving the option to be a Druid

**Comment by troggnostupidhs** [comment]
Renounce is also fixed

![image](https://user-images.githubusercontent.com/22508641/36009464-322ee9e0-0d1a-11e8-87f7-50f3edb4a360.png)
