### ISSUE TITLE
Crafting/disenchanting ignores volume slider

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#9]
Crafting and disenchanting sound effects do not respect the volume slider when rapidly crafting/disenchanting cards.

* https://www.reddit.com/r/hearthstone/comments/39z0io/warning_disenchant_sound_bug_still_exists/
* https://www.reddit.com/r/hearthstone/comments/3a41pp/sound_bug_when_disenchanting_cards/

**Comment by culinko** [comment]
https://www.reddit.com/r/hearthstone/comments/3saz1v/wooah_they_fixed_the_disenchant_maximum_sound_bug/

Need to be verified, people have claimed this being fixed many times before and it wasn't.
