### ISSUE TITLE
Minions returned to hand display incorrect mana costs when replayed

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#90]
Returning to hand and replaying minions that have their mana cost actively reduced or increased (by Mana Wraith or similar effects) will display their original cost (only for the opponent) on the card when it enters the play.
- https://www.youtube.com/watch?v=J8mM0S4OT88

The same bug can be observed by returning and replaying a Mountain Giant/Molten Giant/Sea Giant/Clockwork Giant. It will display its original cost on the card (only for the opponent) when it enters the play.
- https://www.youtube.com/watch?v=jRB4Rla805s

This can also be observed by replaying a minion that has been affected by Freezing Trap.

![zosyvig](https://cloud.githubusercontent.com/assets/11700272/12077011/6a13b5a2-b1c8-11e5-871b-ffbfef22f8b2.jpg)

**The same bug happens also in sidebar. Only the opponent sees the bug.**

Returning to hand and replaying minions that have had their mana cost actively reduced or increased by Mana Wraith or similar effects or cards like Molten Giant will display their original cost in your sidebar. Same happens when the minion got returned to hand by Freezing trap and then replayed.

![d261j9r](https://cloud.githubusercontent.com/assets/11700272/12077013/9a087874-b1c8-11e5-9857-00a02817bfe7.png)

Your opponent's sidebar will show this correctly.

![taseknx](https://cloud.githubusercontent.com/assets/11700272/12077016/b288147c-b1c8-11e5-9463-68ef399d9905.png)

**Comment by culinko** [comment]
This can be observed by effects and auras that enchant the minion when in hand. This does **not** happen to minions buffed on board and then returned to the hand and replayed.

**Comment by Patashu** [comment]
Is this related? If you sap an enemy Shadowcastered Sylvanas and they replay it, it will display as a 1 mana 5/5.

https://www.reddit.com/r/hearthstone/comments/4hndum/bug_with_shadowcaster_and_sap/

http://imgur.com/yMatS9i

**Comment by jleclanche** [comment]
Yes definitely.

**Comment by culinko** [comment]
This bug has been fixed in the meantime.
