### ISSUE TITLE
Serrated Shield (Unidentified Shield) card text doesn't scale with Spell Damage

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#901]
https://us.battle.net/forums/en/hearthstone/topic/20761786134

> 
> While playing the most recent brawl, I noticed that the card text for the damage version of Unidentified Shield, Serrated Shield, wasn't updating for spell damage. I tested it further and I found out that the spell still did the 5 damage plus the spell damage added. The spell still works properly, but the card text doesn't update to tell you that it works.
> 
> This can be easily reproduced by having spell damage on board when you play Serrated Shield.
> 
> This gallery of images explains what the player sees:
> https://imgur.com/a/QX7Gg

---

> Thanks for the report, looking into it :)

**Comment by troggnostupidhs** [comment]
![image](https://user-images.githubusercontent.com/22508641/35710059-673a05c6-0783-11e8-9be1-ec05b53480ef.png)

![image](https://user-images.githubusercontent.com/22508641/35710062-70384584-0783-11e8-9006-cef732fb8261.png)

**Comment by troggnostupidhs** [comment]
Deck
AAEBAQcC7QXlDw77AZ0CogSgBZEGuQb/B7IIzhaCrQLKzQLMzQKXzgLP5QIA

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=WbwB4599i6w

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21694420

> Serrated Shield now correctly displays bonuses from Spell Damage.

**Comment by ceceita** [comment]
no spell damage
![](https://i.imgur.com/shMbLJ7.jpg)
spell damage
![](https://i.imgur.com/ZSAQ0rR.jpg)
damage to face
![](https://i.imgur.com/SJSFviF.jpg)
