### ISSUE TITLE
Deck of Wonders shuffles 5 Decks of Wonder instead of 5 Scrolls into your deck

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#903]
https://www.reddit.com/r/hearthstone/comments/7hoaf8/so_why_does_the_deck_of_wonders_shuffle_5_decks/

![image](https://user-images.githubusercontent.com/22508641/35763437-570f99d4-087a-11e8-9af5-8c6e7b5a3fa9.png)

**Comment by troggnostupidhs** [comment]
Deck
AAEBAf0EAu0F9uoCDk37AZwCtAKrBLQE5gSWBbkG4xGYxALHxwKg0wLV4QIA

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=WbwB4599i6w

**Comment by PattuX** [comment]
https://www.reddit.com/r/hearthstone/comments/7vxdwj/deck_of_wonders_now_shuffles_scrolls_of_wonder/
