### ISSUE TITLE
Stealing and return to hand effects can fail to show summoning sickness when replaying

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#91]
If you steal a minion that has been on the board for multiple turns with Cabal Shadow Priest or Shadow Madness, return the stolen minion to your hand and replay it again, it will not have the "Zzz" summoning sickness animation indicating that it cannot attack.

Frostwolf Grunt:

![1](https://cloud.githubusercontent.com/assets/235410/9612260/e45bbb56-50e4-11e5-894f-369cb38f88a1.jpg)

**Comment by culinko** [comment]
I simplified the issue and found out it doesn't matter if you keep the stolen minion in your hand for a turn (at least not for Shadow Madness). With Cabal the results varied, sometimes you got the sickness and sometimes don't, but I don't think there is a need to list all the examples.

**Comment by jleclanche** [comment]
Worth mentioning that the "Zzz" is tracked entirely clientside.

**Comment by culinko** [comment]
I can confirm it being fixed in 4.0, it was most likely fixed in the same Patch that fixed #213, but not sure which Patch was that.
