### ISSUE TITLE
Sacrificial Pact + Auchenai Soulpriest + Floating Watcher plays animation twice

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#92]
If you use Sacrificial Pact while having Auchenai Soulpriest and Floating Watcher on the board, its animation will play twice.
https://www.youtube.com/watch?v=OLslvNKyHEk&t=2m

**Comment by NightKev** [comment]
https://github.com/HearthSim/hs-bugs/issues/96#issuecomment-134770553?

**Comment by culinko** [comment]
Duplicate issue, merged into #11.
