### ISSUE TITLE
Molten Blade transforming into a Legendary weapon keeps the dragon border in hand

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#921]
https://www.reddit.com/r/hearthstone/comments/8b0a8q/my_molten_blade_turned_into_a_legendary_weapon/

![image](https://user-images.githubusercontent.com/22508641/38531304-2db87046-3c3d-11e8-8092-e137b0e5403f.png)

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8b0a8q/my_molten_blade_turned_into_a_legendary_weapon/dx3houj/

> This is a known issue that should be resolved along with a number of other relatively minor visual bugs in the upcoming patch.

**Comment by Jetz72** [comment]
Is now fixed:
![hearthstone screenshot 01-25-19 01 43 54](https://user-images.githubusercontent.com/8607832/51735341-31b89480-2055-11e9-8828-edc047b7aa4f.png)
![hearthstone screenshot 01-25-19 01 44 01](https://user-images.githubusercontent.com/8607832/51735345-341aee80-2055-11e9-94fb-5076aa2beb54.png)

With no reports of this afterwards, just going to take their word for it and assume it was included in this bit from the [11.0 patch](https://playhearthstone.com/en-us/blog/21694420/).:
>Fixed various minor UI and Animation issues.
