### ISSUE TITLE
Death Knights copied by Chameleos can have a permanent attack value

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#923]
https://us.battle.net/forums/en/hearthstone/topic/20762127315

> Hi,
> so i was trying this cool card from the new expension (Witchwood) called Chameleos, and i've encountered a bug :
> 
> I was playing against a guldan who had DK Guldan in hand, my chameleos transformed into it, and i played it , but out of no where i had 1atk on my hero( like when malfurion hero powers, he has 1 atk and 1 armor) and this 1atk was staying even the next turn and the one after
> 
> here's an image to show you guys :
> https://ibb.co/b2S3CS
> 
> i guess its a bug, and even if i lost the game, it was a bit annoying and unfair for the enemy so i hope it gets nerfed ASAP,
> 
> Thank you :)
> 
> PS: sorry for the possible mistakes, english is not my first language

> We are aware of this issue, it happens with any Hero Card that Chameleos copies. Thanks for the report anyhow :)

![image](https://user-images.githubusercontent.com/22508641/38707246-9f82f64a-3e7e-11e8-81c2-82509f972615.png)

**Comment by Kybxd** [comment]
Other buffs can also be preserved such as Pumpkin Peasant. 

Enemy Chameleos first transforms into 4/2 peasant and at the end of turn it becomes a 2/4. Next turn Chameleos transforms into Paladin DK and opponnent plays it. (His hero is at 30 health.) Now we can see his hero becomes a 2/4. (7 = 2 hero attack + 5 weapon attack)
![img_9662](https://user-images.githubusercontent.com/18246091/38716852-8c414d24-3f15-11e8-8d3c-97da043403bd.JPG)

2 attack is permanent, even in opponent's turn.
![img_9663](https://user-images.githubusercontent.com/18246091/38716860-952914ee-3f15-11e8-941f-8851548309f2.JPG)

Note that playing a hero card doesn't reset your hero's damage to 0. So if enemy hero was at 26 or less health when he played that DK card, he would die immediately.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8bszm2/so_when_you_play_the_chameleon_on_a_deathknight/dx9fa9p/

A report on Reddit mentioned that

> I am guessing this also works with weapons, 1/3 skull for instance. When I had a Doomsayer he had a green 1 for attack.
> 
> Now we need to know if you have a weapon/DK and smuggler crate will the crate buff the beastly weapon?
> 
> Edit: this was likely due to an interaction with lady in white. She was played while Lil' Chamil was in my deck.

**Comment by troggnostupidhs** [comment]
>Apr 13, 2018
> * Fixed an issue where Chameleos retained the buff from Lady in White when transformed into a Hero Card, giving the hero permanent 1 attack
> * Fixed an issue where Chameleos retained the buff from Prince Keleseth when transformed into a Hero Card, giving the hero permanent 2 attack
> * Fixed an issue where Chameleos retained the buff from hand buff cards like Grimstreet Enforcer or Don Han'cho when transformed into a Hero Card, giving that hero permanent attack equal to the buffed attack of Chameleos
so much for my Chameleos  bug video

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20762247315

> We fixed many of the instances where this happens. There are still a couple we are working on.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790#post-11

> Fixed an issue where Chameleos retained the stats after copying a transforming Worgen card that would make all future cards copied maintain those stats(including Hero Cards and Weapons)

**Comment by troggnostupidhs** [comment]
This is possibly fixed?

**Comment by ceceita** [comment]
do we have to test something specific ?  mb we can close and reopen if something came out

**Comment by troggnostupidhs** [comment]
Have Chameleos copy a Death Knight and then play it. The hero should not have an attack value after you play the card.

**Comment by troggnostupidhs** [comment]
> Lady in White when transformed into a Hero Card, giving the hero permanent 1 attack

I forgot that part
