### ISSUE TITLE
Tess Greymane with Psychic Scream bug

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#924]
https://us.battle.net/forums/en/hearthstone/topic/20762197287

> I just played a game with Tess, I had gotten a Psychic scream from a priest. When I played Tess the Psychic Scream triggered as normal but then every card onward was played by the other player rather than my hero, so they got the minions I played from the priest class during the game instead of me. Should that happen? The card text doesn't say that the cards are played by a random player just targets are random.

> Thanks for the report. Investigating :)

**Comment by Patashu** [comment]
Good ol' Yogg + Sylvanas combo

**Comment by PattuX** [comment]
Same principle as #886 

Not sure whether to merge, I'd vote yes.

**Comment by troggnostupidhs** [comment]
I agree, but can you think of a good title?

**Comment by Patashu** [comment]
Minions with Batttlecries that repeat an action (Yogg, Tess) perform it for their current controller even if it changes mid-Battlecry

**Comment by troggnostupidhs** [comment]
Done. Thanks!

**Comment by troggnostupidhs** [comment]
Un-merged from #886

This behavior is intended, so ticket changed to invalid
