### ISSUE TITLE
Chameleos copying a Worgen card will always keep the Worgen Attack and Health stats

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#925]
https://us.battle.net/forums/en/hearthstone/topic/20762137329

> I noticed something strange with Chamelos.
> 
> He copied a minion with mechanic "each turn this is in your hand swap its attack and health" (a 2/4 - 4/2).
> 
> Then, when Chamelos copied other minions during the game, he was always 2/4 or 4/2... I thought he was only a graphic bug but when I played a copied "Splintergraft" (legendary druid minion 8/8), he was just a 2/4.. big value :D
> 
> Sorry for my English :) anyone noticed it?

> Thanks for the report. Investigating :)

> Same problem with Swift messenger and Chameleos

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790#post-11

**Comment by Kybxd** [comment]
Chameleos never keeps any hand buff now, including transformations that don't change card type (minion to minion).

**Comment by Patashu** [comment]
I wouldn't be surprised if Shifting Scroll, Shifter Zerus and Molten Blade were also changed.

**Comment by troggnostupidhs** [comment]
I think them not keeping buffs makes sense. As long as they are consistent, it's probably intended.

**Comment by troggnostupidhs** [comment]
Shifter Zerus keeps the buffs
