### ISSUE TITLE
Drakkari makes your Worgen 0/0 at the end of your turn

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#928]
It will keep 0/0 and never get its stats back. It dies immediately when you play it.

![qq 20180414102420](https://user-images.githubusercontent.com/18246091/38763471-26e29784-3fcf-11e8-8e21-0145b99c2a2c.jpg)

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790#post-11

> Drakkari Enchanter will no longer cause transforming Worgen cards to have stats of 0/0

**Comment by troggnostupidhs** [comment]
Technically, I would argue the Worgen effect isn't an 'End of turn' effect (even though the effect happens at the end of the turn).
