### ISSUE TITLE
Rat Trap can be triggered by Spellbender

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#933]
https://us.battle.net/forums/en/hearthstone/topic/20762317640

> during my last game , i played Rexard vs jayna , and jayna copy my "rat trap" with "mana bind" before the "buged turn". during this turn i played a "vicious scalehide" with the boost of "dire frenezy" , just after , i play an other dire frenezy on this scalehide, but an ennemie spellbender proc , and my spell go to the ennemie spellbender ( and 3 copy of it go in my deck) BUT , just after , the ennemie rat trap proc ( i actualy play only 2 card , scalehide / dire frenezy) ... can i say Wtf ?

> Thanks for the well detailed report. Investigating.

> 
> Hi,
> I also noticed this bug. Also with spell bender and rat trap. However it proc'd with earthen scales.
> 
> Btw it happend in a dungeon run with the 3 secrets treasure. Not sure how to upload a screenshot, so here a link: https://imgur.com/a/00sBddv
> 
> Edit: To make it more understandable. The enemy played just 2 cards in his turn, however my spellbender triggered and apparently counts towards the "cards played" of rat trap.

**Comment by Kybxd** [comment]
This also happens on Hidden Wisdom (instead of Rat Trap) and Mayor Noggenfogger (instead of Spellbender) , but not on Sherazin, Seed. 

Both Mayor and Spellbender (or multiple Mayors) triggering is not counted as 3 cards played for Rat Trap/Hidden Wisdom.

**Comment by Kybxd** [comment]
I also tested:
1. If Noggenfogger triggers but doesn't change the target, this is not counted twice for Rat Trap/Hidden Wisdom.
2. Opponent has HW and Repentance (in this order). Noggenfogger is in play. You play first the Coin then Elven Archer (target changed). Repentance triggers first, then HW.
3. You have Animated Berserker and opponent has Rat Trap. Noggenfogger is in play. You play first the Coin then Elven Archer (target changed). Berserker triggers first regardless of Dominant Player.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21802981
>Spellbender will no longer trigger Rat Trap or Hidden Wisdom when it triggers.
