### ISSUE TITLE
If you freeze a Rush minion entering play this turn, it's not unfrozen at the end of turn

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#936]
Starting from 11:00 https://www.bilibili.com/video/av22368508/

**Comment by Patashu** [comment]
Hmm, no clue if this counts as a bug or not, since Rush isn't quite a real attack, but nicely catched.

**Comment by zombie** [comment]
https://youtu.be/yk5aglaRej8?t=350

Rush should totally count as a "real attack" (just limited targets).

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21943493/hearthstone-update-11-4-july-10-the-boomsday-project-pre-purchase

> Resolved an issue where freezing a Rush minion the turn it was played would cause it to skip two attacks.

**Comment by ceceita** [comment]
the zombie report of kripp video i think dont shows the bug , becouse if you copy an already freezed minion with rush , he cant attack that turn using the rush , so it stay freeze the next turn.  it's like when you copy the frozen minions , original ones unfreeze the next turn , copied ones stay freeze.

btw tested and rush minion unfreeze the turn they are played if they miss the rush attack

played the spark with rush , no attack
![](https://i.imgur.com/qPXOJTj.jpg)
freeze the board
![](https://i.imgur.com/eaVd9fV.jpg)
on enemy turn the spark unfreezes
![](https://i.imgur.com/fQbOMec.jpg)

**Comment by troggnostupidhs** [comment]
this is fixed?
