### ISSUE TITLE
The Darkness cannot get Echo from Glinda Crowskin

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#938]
Starting from 15:15 https://www.bilibili.com/video/av22368508/

Besides, Glinda works correctly on Jaraxxus and Brann+ Injured Blademaster.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8imylu/glinda_darkness_bug_hasnt_been_fixed_yet/

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22546493
> The Darkness now gains Echo from Glinda Crowskin!
