### ISSUE TITLE
Shudderwock, Saronite Chain Gang and Golden Kobold bug

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#939]
Starting from 17:20 https://www.bilibili.com/video/av22368508/

1. You play Shudderwock and it copies himself from Saronite Chain Gang's (or Doppelgangster‘s) battlecry
2. The copies are returned to hand by Grumble’s battlecry (or just Shadowstep, as shown in this video)
3. The copies are transformed by Golden Kobold
4. Play the post-transformed minion and it summons a copy of itself (it summons two if created by Doppelgangster‘s battlecry).

Here're some logs about this bug:
![qq 20180421125115](https://user-images.githubusercontent.com/18246091/39080515-c224ff00-4562-11e8-9b1d-ba0f58b6400c.png)
Golden Kobold transforms Shudderwock into the Beast. We can see its 'BATTLECRY' tag is somehow set to 1.

![qq 20180421125600](https://user-images.githubusercontent.com/18246091/39080546-6360a7ac-4563-11e8-8121-a1541c8853e2.png)
Play Sequence of the Beast. We can see the first battlecry is empty, and the second battlecry is Saronite Chain Gang's battlecry, and the Beast copies itself.

If the post-transformed minion already has a battlecry such as Malkorok, its first battlecry gives you a random weapon, and second battlecry copies itself.

**Comment by troggnostupidhs** [comment]
#834 #837 and this issue are probably all related

**Comment by Kybxd** [comment]
> Leyline Manipulator now correctly reduces the cost of cards created by Golden Kobold.
It seems that the fix of this bug also affects other bugs relevant to Golden Kobold. The Shudderwock bug is fixed. Here are some logs:

![qq 20180607215200](https://user-images.githubusercontent.com/18246091/41103998-07bc1526-6a9d-11e8-82cf-1808fe504d82.png)
Golden Kobold transforms Shudderwock into Dreadscale. The BATTLECRY tag is no longer 1 now.

![qq 20180607215306](https://user-images.githubusercontent.com/18246091/41104081-307279ec-6a9d-11e8-8624-944247813126.png)
When I play it, BlockType=POWER is only one and empty.
