### ISSUE TITLE
Rapid Shadowstepping can make the minion visually smaller

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#94]
If you play a minion and Shadowstep it quickly multiple times before it goes visually into the hand, the minion's final image on the board may appear smaller.

![](https://cloud.githubusercontent.com/assets/235410/11167482/573e6fb8-8b6b-11e5-8aab-d803073dc230.jpg)

**Comment by ZeroRin** [comment]
tested in 3.1, i can no longer re-play a minion before it turn to a card and move into the hand.

**Comment by culinko** [comment]
You can still replay the minion mid-animation if you spam click it and sometimes it appears smaller, I just tested it in 3.1. Also you can move the minion a bit if you drag it during the animation when it goes to hand.

**Comment by troggnostupidhs** [comment]
Can this be considered fixed? 

2:48
https://youtu.be/zx1ifafdu50?t=168
