### ISSUE TITLE
Monster Hunt: Infinite Toki's Alternate Timeline behaves incorrectly when used by the player.

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#944]
This has been posted in a few places, but it's worth documenting here.

https://www.reddit.com/r/hearthstone/comments/8ghb3x/i_managed_to_steal_infinite_tokis_alternate/
https://www.reddit.com/r/hearthstone/comments/8fdeir/alternate_timeline_doesnt_work_against_infinite/
https://www.reddit.com/r/hearthstone/comments/8fz0vr/when_stealing_the_opposing_tokis_alternate/
https://us.battle.net/forums/en/hearthstone/topic/20763256165

Alternate Timeline reads "Start a new game, but your opponent's Health stays the same." However, when used by the player, Infinite Toki's health will be reset, while her old health value will be applied to the player's hero. It correctly stores the opposite hero's health value, but does not apply it correctly.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20762786113

> The infinite toki bossfight contains a 10 mana card: alternate timeline.
> I understand that she automatically plays it at 10 mana but I happened to draw my 3 mana 5/5 minion with battlecry: swap both player's hands.
> So i swapped hands and got to play alternate timeline for myself.
> 
> The card reads: start a comepletely new game, but you're OPPONENT'S health remains the same.
> 
> I played alternate timeline with both heroes's health at 1.
> and when i did, my opponent's health went back up to 60 whilst mine remained 1.
> 
> If any of you guys at blizzard reads this, fix this bug and make the OPPONENT remain at it's current health whilst mine goes back to starting health if the player plays alternate timeline.
> 
> I feel like you did a very poor job on fixing this before release, since you even got a special voiceline for infinite toki when the player plays alternate timeline, so you must have noticed this bug before already.
 

> We are aware of this issue. Thanks for the report. :)

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21802981
> Alternate Timeline no longer resets Infinite Toki’s Health to full when played by a player.
