### ISSUE TITLE
Forced Death Phases do not have a Death Creation Step after them, postponing the consequences of damage/destroy Deathrattles

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#947]
https://hearthstone.gamepedia.com/Advanced_rulebook#Forced_Death_Phase

> If you remember how Phases work, then you know that normally a Death Phase cannot start inside of a Phase - and indeed, once the Forced Death Phase ends, no follow-up Death Phases can be scheduled until the outer Phase ends, so additional Deaths remain un-processed until then.

Example:

https://us.battle.net/forums/en/hearthstone/topic/20762148100

In this scenario there is a Voodoo Doll targeting a Voidlord. The player plays Defile, expecting the Voidlord to die after the 1st Defile cast (as a consequence of the Voodoo Doll's deathrattle), but instead the Voidlord dies after the 2nd Defile cast, since the 'pending destroy' state is not checked until a new Forced Death Phase is started.

A QA member (Grizzle) chimes in:

> We are aware of this issue. It is inconsistent as most deathrattles trigger between the repeat Defile casts. Thanks for the report!

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21802981
>Voodoo Doll and other Deathrattles now correctly trigger during a Defile.

**Comment by Kybxd** [comment]
Now Defile works just like Yogg - the next AoE doesn't continue until no death occurs. Other Forced Death cards are not tested yet, but it's possible that they are all changed.

**Comment by Kybxd** [comment]
This is completely fixed for all 6 cards (Mimiron's Head, Poison Seeds, Reincarnate, Blood of The Ancient One, Ravenous Pterrordax and Defile). Here are some screenshots:
![qq 20181106094054](https://user-images.githubusercontent.com/18246091/48037642-2ec1ac80-e1a8-11e8-8bd5-6a76b4d0a46a.png)
Two Blood merges, one is with Ancestral Spirit, KJ shoots Explosive Sheep.
![qq 20181106094135](https://user-images.githubusercontent.com/18246091/48037661-4b5de480-e1a8-11e8-89a8-12e6d50a0788.png)
The newly summoned 30/30 doesn't take any damage.

![qq 20181106094135](https://user-images.githubusercontent.com/18246091/48037707-9841bb00-e1a8-11e8-8670-12007b6a1068.png)
Two Tentacles with Ancestral Spirit, Poisonous Seeds.
![qq 20181106094436](https://user-images.githubusercontent.com/18246091/48037742-be675b00-e1a8-11e8-8265-e4d4bcf2e2f9.png)
All Treants survive.
