### ISSUE TITLE
Tess Greymane continues casting after leaving the board, unlike every other cast-sequencing minion

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#961]
This anomaly has been known for a while, most commonly shown when Tess casts Psychic Scream:

https://us.battle.net/forums/en/hearthstone/topic/20762197287

Unlike other "cast-sequencing" battlecries (is there a better term for this? this is just what I call them; feel free to rename it), namely Yogg, Shudderwock, and Lynessa, Tess will continue casting even after being killed, silenced, or leaving the battlefield. Tess's card has nothing that would indicate a different behavior.

**Comment by troggnostupidhs** [comment]
Shudderwock continues casting, doesn't it? And it wouldn't make sense for Lynessa to continue casting, since she casts the spells on herself.

I'm not sure this is a bug, it's more of a design decision.

**Comment by Jetz72** [comment]
> Shudderwock continues casting, doesn't it? 

Don't think so. If it does, I suspect the resulting oddities would have been noticed long ago. I imagine we'd have more reports of Saronite Chain Gang duplicating a dead Shudderwock if it was allowed to cast from the graveyard or hand.

> I'm not sure this is a bug, it's more of a design decision

Possible, but I can't imagine why this would be done deliberately. Whether or not a cast-sequence minion continues after dying can wildly affect their power level (see Yogg), and someone suggested that this behavior varies on a per-card basis specifically for balance purposes. But it's not documented in the card text, and there are more obvious ways to tune a card's power, so having this behavior vary from card to card just seems inconsistent. I think it's more likely an oversight.

**Comment by troggnostupidhs** [comment]
> I imagine we'd have more reports of Saronite Chain Gang duplicating a dead Shudderwock if it was allowed to cast from the graveyard or hand.

Targeting the minion and continuing to cast spells / battlecries are two different things.  Saronite Chain Gang needs to copy the minion, but something like Lifedrinker's battlecry can still be cast.

>  But it's not documented in the card text

There's a lot of behaviors that are not documented in the card text in Hearthstone. Antonidas, what is 'Fireball'. Animal Companion, what is a beast companion? etc.

> so having this behavior vary from card to card just seems inconsistent

Legendaries have generally been able to have exceptions. Skycap'n Kragg has 'Charrrrrge'. Not that it is a huge inconsistency, just that Legendaries get to have their own rules that can be inconsistent with other cards.

> I think it's more likely an oversight.

That is not impossible, but we do not have anything to say that is the case. That is why this should be 'may be intended' until we have some feedback on the desired behavior.

**Comment by Jetz72** [comment]
> Targeting the minion and continuing to cast spells / battlecries are two different things. Saronite Chain Gang needs to copy the minion, but something like Lifedrinker's battlecry can still be cast.

Chain Gang isn't a targeted Battlecry, and even battlecries that are targeted rarely check the state of the target before activating (wrong zone battlecries and all that). If someone wants to try a wrong-zone battlecry with Chain Gang while it's in the graveyard or hand, I imagine they'll get a 2/3 regardless, but that's neither here nor there. 

More to the point: [here's someone reporting](https://us.battle.net/forums/en/hearthstone/topic/20762227195#post-5) that a Shadowreaper Anduin battlecry killed their Shudderwock and stopped the sequence prematurely. Grizzle later [replies](https://us.battle.net/forums/en/hearthstone/topic/20762227195#post-14), stating:
> Being destroyed ends the Battlecries.

> Legendaries get to have their own rules that can be inconsistent with other cards.

They have been known to introduce new mechanics, but older mechanics that get recycled generally behave comparably if not identically. When they don't, there's almost always a discernable reason for it. Finley and Rafaam bend the rules for discover because the set of hero powers/artifacts has no overlap with the normal discover pool. Kragg is worded differently for the same reason Blingtron gives golden weapons: it's an intentional quirk to add to their flavor without affecting gameplay. Genn and Baku perform their checks differently to avoid interference from other Start of Game effects (current implementation is still bugged or flawed, but their reason for not using the normal deck-check logic is understandable).

There doesn't seem to be any reason for Tess to be an exception to the logic established by the other 3 minions with cast-sequence battlecries. When there's no indication that a difference like that is intended, and no good reason for the different behavior can be discerned, I think it's fair to call it a bug.

**Comment by troggnostupidhs** [comment]
> Grizzle later replies, stating:
> 
> > Being destroyed ends the Battlecries.

That is fair. I was thinking of return to hand with Grumble, which I don't think ends the battlecries. 

My assumption with post-nerf Yogg is that it stops casting spells if it leaves the battlefield (Vanish, for example). Do you know if that is true?

> There doesn't seem to be any reason for Tess to be an exception to the logic established by the other 3 minions with cast-sequence battlecries. When there's no indication that a difference like that is intended, and no good reason for the different behavior can be discerned, I think it's fair to call it a bug.

I agree that being consistent is the ideal. And, in my opinion, it should be that way. And I agree that in general, the inconsistency would be a bug. 

When it comes to legendaries, I believe it has been stated that they do not have to be consistent (I am not sure if I will be able to find the source). I hear you on there are 'reasons' for the inconsistencies with the other legendaries. But for this, I'm not convinced it's a bug until there is a comment on it.

**Comment by troggnostupidhs** [comment]
> When cast by Shudderwock, the one doing the casting won't be returned.

Yes, makes sense.

> As far as I'm aware.

I just did a test with Faceless Manipulator and Shudderwock. Shudderwock stops casting when it transforms, which makes sense.

It makes sense for them all to be consistent. But, in my opinion, it's a design decision for the legendaries.

AAEBAfe5AgLtBe/3Ag7uAfsBkwT1BP4FsgbZDfUP8RHSE/uqAqC2ApHBAtjlAgA=

**Comment by troggnostupidhs** [comment]
I forgot about this comment.

https://old.reddit.com/r/hearthstone/comments/8aeax2/new_rouge_card_tess_graymane/dwy17fb/?context=3

> u/mdonais , does Tess Greymane work like pre-nerf Yogg or post-nerf ?

> /u/mdonais could we Have a confirmation about this ? Because if she Works like post nerf yog saron and the first thing she does she dies and it gets shut down would be disapointing (shadow Word death, twisting nether, polymorph etc)

> pre-nerf

As I said in the last post, I agree that it makes sense to be consistent. However, this seems like it is a design decision and not a bug.

**Comment by troggnostupidhs** [comment]
Even though it seems intended previously, they made a change to the card in the recent patch.

@Jetz72 do you want to test this?

https://playhearthstone.com/en-us/blog/21802981

> Tess Greymane’s Battlecry is now limited to 30 cards, and will stop if she is silenced, killed, transformed, leaves the battlefield, or if any hero dies.

**Comment by Jetz72** [comment]
You had me convinced it was intended, too!

Much as I like testing interactions, I don't actually own Tess. :|

**Comment by troggnostupidhs** [comment]
No worries, I will find out the new interaction at some point.

**Comment by Jetz72** [comment]
If the angry reddit mob manages to beat a dust refund out of Blizzard for this change, we could test it for no cost!

**Comment by troggnostupidhs** [comment]
Yogg got full dust when it was nerfed? Shouldn't Tess?

https://www.reddit.com/r/hearthstone/comments/8osjci/new_update_112/e05r0t2/

**Comment by troggnostupidhs** [comment]
Going back to intended. Also this implies / shows that legendaries do not need to be consistent. 

https://us.battle.net/forums/en/hearthstone/topic/20765117580

>Update 11.2 brought with it some changes as part of our ongoing, overall goal to make card interactions moreq intuitive across the board. The intention of some of those changes was to align four similar cards (Tess Greymane, Lynessa, Shudderwock, and Yogg-Saron). If you’re familiar with the way that one of these minions works, you should be able to guess how the others work. We added a cap to the maximum number of effects that can be generated by these Battlecries, and made Tess’ Battlecry end if she was destroyed, silenced, or otherwise removed, just like Yogg-Saron.

>After hearing your feedback to that change, we initially considered offering a full Arcane Dust refund for Tess. We also read feedback from players who use Tess in their decks asking for her to be reverted to her old functionality. In this case, we agree that it’s worthwhile to sacrifice some consistency so Tess is more fun to play, especially since our priority wasn’t to decrease Tess’ power level. With that in mind, instead of offering an Arcane Dust refund and encouraging players to disenchant the card, we’re reverting one of the changes to Tess Greymane so that her Battlecry will continue even if she’s destroyed, silenced, or otherwise removed from the board.

**Comment by troggnostupidhs** [comment]
https://youtu.be/x131hBZvCfU?t=573

Shudderwock stops casting here when it dies
