### ISSUE TITLE
Tess Greymane does not cast Hero cards

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#965]
https://www.reddit.com/r/hearthstone/comments/8op8fd/another_tess_greymane_bug_ft_kibler/

**Comment by Jetz72** [comment]
I could have sworn this was already on here, but apparently not. In the linked post I posted a link back to this bug, having found it via search thinking there was more information here.

Anyway, for future reference, here's the confirmation that this is a known issue:
https://us.battle.net/forums/en/hearthstone/topic/20763906356#post-4

**Comment by troggnostupidhs** [comment]
Should be fixed

https://playhearthstone.com/en-us/blog/21802981 

> Tess Greymane will now replay hero cards with her Battlecry.
