### ISSUE TITLE
Adaptations cannot be applied to minions with the "Can't be targeted by spells or hero powers" effect

### ISSUE THREAD

**Issue by Jetz72** [HearthSim/hs-bugs#966]
Perhaps the rules for specifically-targeted force-cast spells have changed and now enforce usual targeting restrictions? It may be worth re-testing Lynessa with Sacrificial Pact or some other spell with a target restriction. She was able to cast them on herself before - https://www.youtube.com/watch?v=HQferouGG7U

http://gall.dcinside.com/mgallery/board/view/?id=pebble&no=2099125&page=1

https://www.reddit.com/r/hearthstone/comments/8otixb/bug_in_new_patch_cannot_adapt_minions_with_cant/

> You cannot adapt any minion that has the "Cannot be targeted by spells or hero powers" keyword. (The OP in the source tested with Crackling Razormaw, Lightfused Stegodon, Volcanosaur on the second adapt and even Vicious Fledgling's unique ability)

![image](https://user-images.githubusercontent.com/22508641/41006529-eaf9a3ee-68ef-11e8-81f9-2df3ebf2a46e.png)

![image](https://user-images.githubusercontent.com/22508641/41006535-eded283c-68ef-11e8-9cb7-fb8246e1c1dc.png)

![image](https://user-images.githubusercontent.com/22508641/41006539-f24ed254-68ef-11e8-960f-6a69eb4bb572.png)

![image](https://user-images.githubusercontent.com/22508641/41006543-f6cea6ce-68ef-11e8-8658-95c3663fede8.png)

**Comment by Jetz72** [comment]
Official acknowledgement, for all your "Blizzard is aware" needs: https://us.battle.net/forums/en/hearthstone/topic/20763956467#post-2

>We are aware of an issue with Adapt not affecting minions with the "Can't be targeted by spells of Hero Powers." We are currently investigating.

**Comment by Jetz72** [comment]
https://www.reddit.com/r/hearthstone/comments/8otnk3/galvodon_is_now_glitched/e067di9/?context=3

> Just a quick update: there's already a hotfix in the works for this issue, and we're hoping to roll it out today.
I'll update this post once it goes live.
Edit: This hotfix is now live in all regions.

Anyone got a confirmation handy?

**Comment by troggnostupidhs** [comment]
Should be hotfixed

https://www.reddit.com/r/hearthstone/comments/8otnk3/galvodon_is_now_glitched/e067di9/?st=JI26JYH6&sh=c694585f

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8ot9h7/volcanosaur_only_adapted_once/

https://www.reddit.com/r/hearthstone/comments/8otap8/crackling_razormaw_is_not_working_on_bearshark/

https://www.reddit.com/r/hearthstone/comments/8otixb/bug_in_new_patch_cannot_adapt_minions_with_cant/

https://www.reddit.com/r/hearthstone/comments/8otnk3/galvodon_is_now_glitched/

**Comment by ceceita** [comment]
tested first 3 cases and no bugs , i dont have galvodon for last test

**Comment by troggnostupidhs** [comment]
I'll assume it is all fixed
