### ISSUE TITLE
Power Overwhelming kills Dreadsteed permanently

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#968]
https://www.reddit.com/r/hearthstone/comments/8ouz8m/new_bug_power_overwhelming_now_kills_dreadsteed/

> Everyone stop freaking out about Tess, this stealth nerf is literally a million times worse.
> 
> Before, a Dreadsteed targetted by Power Overwhelming didn't come back that turn but would reappear at the end of the following turn. I guess cause both effects had the same "end of turn" trigger. Now though, it dies and stays dead turn after turn after turn.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8ouz8m/new_bug_power_overwhelming_now_kills_dreadsteed/e06f59a/

> Thanks for the report. I'll ask the team to look into it!

**Comment by Kybxd** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790?page=2
> Dreadsteed is no longer killed permanently by effects that destroy it at the end of turn.
