### ISSUE TITLE
'If you played an Elemental last turn' conditions do not trigger if the Elemental was transformed

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#969]
https://old.reddit.com/r/hearthstone/comments/8oukte/is_this_because_of_the_new_patch_i_played_the/

https://www.youtube.com/watch?v=mbm-BHo9VVU

![image](https://user-images.githubusercontent.com/22508641/41011203-c1514258-6909-11e8-8eaa-b1fff99c8a74.png)

![image](https://user-images.githubusercontent.com/22508641/41011222-d16c9ed0-6909-11e8-8b77-ae87638a7f9c.png)

![image](https://user-images.githubusercontent.com/22508641/41011242-e8e6fe20-6909-11e8-9081-20a00cda2df4.png)

**Comment by troggnostupidhs** [comment]
One comment speculates Dire Wolf Alpha could affect it.

**Comment by PattuX** [comment]
This is caused by transformations now changing the cardID, not the entity ID. Whether you played an elemental last turn is not checked via tags but via going through all entities that were played last turn. Those two things combined yield this bug. Log for polymorph transform: https://gist.github.com/PattuX/04dc64c6ede94aa43cc4b692ec92ce4b

**Comment by PattuX** [comment]
This should also work the other way around with Tanglefur Mossbinder, and it partially does:

https://www.reddit.com/r/hearthstone/comments/8p1hq1/overview_over_partially_undocumented_game/e07qj9s/

> Case A: I play a non-Elemental on Turn 8. On Turn 9, I hit it with Furbolg Mossbinder. All of my Elemental cards become active.
Case B: I play a non-Elemental on Turn 10. In the same turn, I hit it with Furbolg Mossbinder. None of my Elemental cards are active on Turn 11.

However I have no explanation for case B.

**Comment by PattuX** [comment]
Possible explanation for case B: https://www.reddit.com/r/hearthstone/comments/8p1hq1/overview_over_partially_undocumented_game/e07vyhm/

When playing a minion:

```TAG_CHANGE Entity=[entityName=Zombie Chow id=21 zone=HAND zonePos=8 cardId=FP1_001 player=1] tag=JUST_PLAYED value=1```

When transforming it:

```
CHANGE_ENTITY - Updating Entity=[entityName=Zombie Chow id=21 zone=PLAY zonePos=5 cardId=FP1_001 player=1] CardID=LOOT_150t1
    ...
    tag=JUST_PLAYED value=0```

**Comment by PattuX** [comment]
If you transform your own elemental with Hex, the next turn your elemental synergies will work.

![image](https://user-images.githubusercontent.com/15743638/41058071-22823b1c-69c9-11e8-8b57-b013bce56f65.png)
![image](https://user-images.githubusercontent.com/15743638/41058085-27354c1c-69c9-11e8-8930-05a9950cf193.png)

I don't have any reasonable explanation for how this elemental check works anymore...

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8p0wir/bug_generated_cards_now_show_that_they_were/

**Comment by Kybxd** [comment]
It seems that all transformations don't change EntityID now (previously it uses 'replacing' which changes EntityID). And 'Created by' uses EntityID to record its creator, causing this bug.
![qq 20180607224325](https://user-images.githubusercontent.com/18246091/41107339-c076cdd4-6aa4-11e8-908d-c381a78bc7b9.jpg)

**Comment by PattuX** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790?page=2#post-21

> Elementals that have been Transformed will now properly trigger the "played an Elemental last turn" effect.
