### ISSUE TITLE
Playing spells rapidly causes a temporary gap to form in your hand

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#97]
If you quickly play a spell after you played another card, a gap will form in your hand for a brief moment. If there are any minions that trigger while you cast your spell, e.g. Lorewalker Cho, the gap stays there for a longer period of time.

![5yijvxm](https://cloud.githubusercontent.com/assets/11700272/12409583/c69cfda6-be6b-11e5-820c-f05c041eab82.jpg)

If you draw an extremely large number of cards, and continue to queue up more played cards from your hand while doing this, the gap in your hand increases with no upper limit. This could cause a card to be all the way off-screen and be impossible to select until animations finished.
- https://www.youtube.com/watch?v=rAn54JsR7UE

Causing 'gap in hand' while drawing cards may cause two cards in your hand to visually overlap.
- https://www.youtube.com/watch?v=a5ZcwXku7L4&t=8m41s

**Comment by Patashu** [comment]
If you draw an extremely large number of cards, and continue to queue up more played cards from your hand while doing this, the gap in your hand increases with no upper limit. This could cause a card to be all the way off-screen and be impossible to select until animations finished.

* https://www.youtube.com/watch?v=rAn54JsR7UE

**Comment by Patashu** [comment]
Causing 'gap in hand' while drawing cards may cause two cards in your hand to visually overlap.

https://www.youtube.com/watch?v=a5ZcwXku7L4&t=8m41s

**Comment by Patashu** [comment]
Still true in 5.0

**Comment by Patashu** [comment]
https://www.youtube.com/watch?v=RHm7a_XHooU

Another video of cards visually overlapping in hand in 5.0

**Comment by Patashu** [comment]
Potentially fixed according to http://us.battle.net/forums/en/hearthstone/topic/20749867298

**Comment by troggnostupidhs** [comment]
https://github.com/HearthSim/hs-bugs/issues/377

I think this is a duplicate issue. This issue should also be closed.

**Comment by culinko** [comment]
It is not a duplicate issue. #377 talks about a **permanent** gap and afaik it only happened with Preparation and Coin. This issue happened with all spells and once the animations finished, the cards returned to their correct positions, unlike in #377.

**Comment by troggnostupidhs** [comment]
(should the "potentially fixed" tag be removed?)

**Comment by culinko** [comment]
Yeah, you're right!
