### ISSUE TITLE
Shudderwock does not cast silenced battlecries, while the battlecry minion is still alive

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#971]
https://mobile.twitter.com/Thumai_hs/status/1004130224840364032

> Hey, I have encountered a weird bug playing Shudderwock Shaman. I've played Grumble but when I played my Shudderwock Grumble's battlecry didnt trigger. I guess it got silenced on board ? Shouldnt work like that.

**Comment by troggnostupidhs** [comment]
Transform does not cause this.

https://twitter.com/SeikuLoL/status/1004157280349286400?s=20

>I just used sheep on a Grumble and it still worked on Shudderwock

> PattuX 
> yea, i transformed grumble and it still was cast by shudderwock

**Comment by PattuX** [comment]
![image](https://user-images.githubusercontent.com/15743638/41039520-f6668d28-6999-11e8-8ac8-98e2fb587d1c.png)
![image](https://user-images.githubusercontent.com/15743638/41039533-ff022230-6999-11e8-938f-9e7aa87e8ab8.png)

Confirmed. I'll try again but this time kill the silenced Grumble.

**Comment by PattuX** [comment]
![image](https://user-images.githubusercontent.com/15743638/41040559-0f43de42-699d-11e8-8667-ed2b9ab5a89b.png)
![image](https://user-images.githubusercontent.com/15743638/41040591-236b5bfc-699d-11e8-824c-4319b3d78bad.png)

If you kill the silenced Grumble it works fine

**Comment by PattuX** [comment]
For completeness:

If you transform Grumble and leave the transformed minion alive, Shudderwock will still replay Grumble battlecry.

![image](https://user-images.githubusercontent.com/15743638/41056405-5d73a6e8-69c4-11e8-9dc5-2651cc92f768.png)
![image](https://user-images.githubusercontent.com/15743638/41056416-63962708-69c4-11e8-978c-62bec6925d34.png)

**Comment by troggnostupidhs** [comment]
@PattuX can you test another battlecry with the silencer alive? Just to check if it is only related to Grumble or not.

**Comment by PattuX** [comment]
Sure. Would surprise me if it's only Grumble tho.

**Comment by troggnostupidhs** [comment]
Would have surprised me too, but who really knows at this point with all the 🍝

**Comment by PattuX** [comment]
If a battlecry is played multiple times (by bouncing), all its appearences are ignored by Shudderwock.

> It was captured on Cifka's stream where he played 3 Saronites but only received 1 battlecry trigger on resolution of Shudderwock. A quick recap of the relevant turns would be; Turn 4 Cifka plays Saronite1 generating 1A/1B, opponent kills 1A with flanking strike. Turn 5 Cifka plays the 2nd natural Saronite2 generating 2A/2B. Opponent plays MC Tech which steals 2B and also attacks his beast into 1B. Going into turn 6 Cifka's only remaining copy of Saronite (2A) is returned to his hand with Grumble's battlecry reducing its cmc to 1. This copy remains in his hand until turn 9 when he casts Saronite3 to generate 3A/3B, on this same turn the MC Tech'd Saronite (2B) was killed by Lightning Storm. Opponent proceeds to kill 3B with flanking strike and silence 3A with spellbreaker and that copy is left in play (the only copy still left in play is the silenced 3A). Turn 10 Cifka casts Shudderwock and only receives 1 Saronite battlecry trigger but has played 3 copies in total, only 1 of which was silenced.

https://www.reddit.com/r/hearthstone/comments/8p1hq1/overview_over_partially_undocumented_game/e08kjva/

https://www.twitch.tv/videos/269970258?t=01h46m05s

Worth noting that a minion played multiple times is still cast once for every time played by Shudderwock in the normal case (2:35:00 and 2:41:00 shows this with MCT bounced by Grumble)

**Comment by PattuX** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790?page=2#post-22

> Fixed an issue where silencing a Battlecry minion would prevent its ability from being recast from Shudderwock.
