### ISSUE TITLE
Aura Updates are missing after a spell is countered 

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#973]
https://us.battle.net/forums/en/hearthstone/topic/20765196798
> I was playing burn mage just now and I played a Kirin Tor Mage which states "The next secret you play this turn costs (0)."
My opponent was also a mage and had a secret on the board.
I had 3 secrets in my hand, I played the first for (0) and my opponent's secret was activated, it was a counterspell.
Then, I noticed the other secrets in hand had a mana cost of (0) even though I already played one. Thinking this was a graphical bug I tested to see if another secret was playable.
I was able to play 2 secrets for (0) mana that turn. The first secret which was counter spelled and the second secret which remained on the board until my opponent activated it the next turn.

The detachment of Kirin Tor Mage's enchantment is an On Play trigger. Before Patch 11.2 it has same priority with Counterspell so it works fine. But now Counterspell stops all On Play triggers. So this is mechanically correct but irrational.

**Comment by Patashu** [comment]
One way to look at this - Does a counterspelled spell count as playing a card for any purpose (Arcane Tyrant, Edwin, Sherazin, Arcane Giant, etc)? If it doesn't, then this is consistent and therefore probably intended.

**Comment by Kybxd** [comment]
Doesn't count for Arcane Tyrant, Sherazin, Arcane Giant.
Counts for Edwin (and other Combo cards).

**Comment by 10925** [comment]
Another thing about counterspell.
If a spell being countered, the mana cost of Mountain Giant would not changed(though you lost one card)

**Comment by Kybxd** [comment]
Here are some screenshots:
![qq 20180607220944](https://user-images.githubusercontent.com/18246091/41105221-c79fd2a4-6a9f-11e8-8d8b-cab0c11c87f2.png)
Play Dragon's Fury
![qq 20180607221004](https://user-images.githubusercontent.com/18246091/41105294-f239ce5c-6a9f-11e8-9a9b-430d70a6b51f.png)
Countered
![qq 20180607221025](https://user-images.githubusercontent.com/18246091/41105408-4168fc00-6aa0-11e8-90bb-d481dc36ae77.png)
Mountain Giant still costs 3
![qq 20180607221119](https://user-images.githubusercontent.com/18246091/41105350-1d93a186-6aa0-11e8-82cb-a8a3b8a7c2b1.png)
Use the remaining 2 mana to play Explosive Sheep

(If you don't play Mountain Giant immediately but another card, it will turn to 5 cost correctly.)

**Comment by Patashu** [comment]
Fascinating - this is to my knowledge the first time the timing (specifically absence of) mana cost aura update step has made a mechanical difference.

**Comment by PattuX** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790?page=2#post-22

> Spells countered by Counterspell will no longer apply “next spell” discounts as if they were successfully cast.

**Comment by Kybxd** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20761086790?page=2
> Spells countered by Counterspell will no longer apply “next spell” discounts as if they were successfully cast.

**Comment by Kybxd** [comment]
![qq 20180608184211](https://user-images.githubusercontent.com/18246091/41154184-ebb24dc8-6b4b-11e8-82f7-7574627db69d.png)

**Comment by Kybxd** [comment]
This is not completely fixed. In the screenshot above Mountain is correctly 9-cost because Aura Update is run when Kirin Tor enchantment is detached. If there is not Kirin Tor enchantment, the mana cost of Mountain is still not updated. 
![img_0064](https://user-images.githubusercontent.com/18246091/41391987-725ce242-6fd0-11e8-9ae7-7c5ed33f58fc.PNG)
(Coldlight is on board. Its dislocation is only a visual bug in spectator mode.)

**Comment by Kybxd** [comment]
@PattuX Reopen this?

**Comment by PattuX** [comment]
Sorry, somehow missed this one

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8wy4fi/bug_giant_3_mana_instead_of_4_only_9_cards_in_hand/

https://twitter.com/neon31HS/status/1015770588122701825

**Comment by Pikamander2** [comment]
It happens with Goblin Sapper and in Tavern Brawl as well

https://i.imgur.com/LuVkBSo.jpg

**Comment by troggnostupidhs** [comment]
(Current Brawl is Valeera's Bag of Burgled Spells)
