### ISSUE TITLE
iOS: Dreadscale killing Skelemancer during end of turn causes a crash

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#976]
https://www.reddit.com/r/hearthstone/comments/8p2b82/yet_another_bug_from_this_patch/

> My [[Dreadscale]] killed my opponent’s [[Skelemancer]] with its end of turn effect. This instantly crashed the game. Every time I tried to reconnect, it reconnected, then crashed to desktop. I lost because of this bullshit. Test your patches Blizzard.

---

> anyone want to try replicate this for science? i wish innkeeper could use custom deck so we can see interaction like this..

> edit: confirmed with /u/maskdmann , i played the dreadscale while my opponent play the skelemancer ,he crashed and i didn't. got a video but don't know how to censor name https://www.youtube.com/watch?v=arh7TjSzHCU
, around 6:55

**Comment by PattuX** [comment]
Probably nothing special about Dreadscale and Skelemancer. Should work with all "When this dies on your opponent's turn" DRs.

I wonder whether this is somehow connected to the Dreadsteed fix.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8ubiyp/chess_tavern_brawl_crashes/e1e2pj1/

> Every time my Skelemancer is about to die it crashes

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21943493/hearthstone-update-11-4-july-10-the-boomsday-project-pre-purchase

> Resolved an issue where Skelemancers killed by an end of turn effect would crash iOS devices.

**Comment by Jetz72** [comment]
This one was widely reported prior to the date it was supposedly fixed, and I can't find any reports from after that point. Just gonna go ahead and close this one.
