### ISSUE TITLE
Enemy attacks with Truesilver Champion repeats the 'lifting up' animation

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#98]
When an opponent attacks with Truesilver Champion, his portrait visibly lifts off the board twice, once before the healing trigger and once after it.
https://www.youtube.com/watch?v=ClJfdopzsU8

**Comment by jleclanche** [comment]
Didn't we say this was #11?

**Comment by culinko** [comment]
It only happens for one player, though.

**Comment by jleclanche** [comment]
We decided this was a dupe of #11.
