### ISSUE TITLE
If you Faceless a Zombeast, its trigger/mana cost aura/deathrattle will work twice

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#983]
Starting from 11m30s: https://www.bilibili.com/video/av24938852

Examples include: Dreadscale, Emerald Hive Queen, Bittertide Hydra, Scavenging Hyena, Plated Beetle, Knuckles, Vicious Fledgling. But not Timber Wolf.

(1) From Knuckles we see Lifesteal is not doubled.
(2) Vicious Fledgling's second adaption is chosen randomly, not by you.
(3) This bug doesn't happen on normal minions.

**Comment by Jetz72** [comment]
Tested this one:
![hearthstone screenshot 01-25-19 00 49 30](https://user-images.githubusercontent.com/8607832/51734917-f1a4e200-2053-11e9-9692-d255747fed7a.png)
Note the two Hive Queens on the right. Also tried it with Dreadscale and Haunted Creeper. Seemed fine across the board. Any special cases in particular that should be tested, or is it safe to close this one?
