### ISSUE TITLE
If the minion targeted by Voodoo Doll is transformed, it can still be killed by the deathrattle

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#984]
Starting from 5m20s: https://www.bilibili.com/video/av24938852

**Comment by Kybxd** [comment]
Also mentioned in #975.

https://www.reddit.com/r/hearthstone/comments/8qrle4/bug_when_using_unstable_evolution_on_a_minion/

> 
Had Primordial Drake on the field, opponent plays Voodoo doll and ends their turn, I play Unstable Evolution on the drake, it turns into a Ysera, I then attack with Acolyte of Pain killing Voodoo Doll, Ysera dies.
To me, that makes no sense. I'm sure I've evaded other cards effect by evolving, cards like Power Overwhelming and Corruption. So why does Voodoo Doll work.
If this turns out to be intended and I've missed an interview where it's said to be intended, I apologize.

> 
This has probably something to do with the changes lady patch - you know, the Lich king card "created by frog" and such. The same way the game sees that the frog was the Lich king before, the voodoo doll sees that the evolved minion was the target before

**Comment by Jetz72** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20765048053

Also seems to affect Stasis Elemental in the Taverns of Time arena event.

**Comment by troggnostupidhs** [comment]
https://news.blizzard.com/en-us/hearthstone/21964710/update-12-0-august-2-the-boomsday-project

> Whenever a card transforms it loses its enchantments.
> This change primarily affects the following 4 cards: Shifter Zerus, Molten Blade, Shifting Scroll, and Voodoo Doll. If the target of a Voodoo Doll is transformed or silenced, it is no longer destroyed by the Voodoo Doll’s Deathrattle.
