### ISSUE TITLE
Holding Doomguard while Voidcaller dies causes it to be placed visually incorrectly

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#99]
If you are holding a Doomguard card above the Battlefield while a Voidcaller dies, if the Deathrattle causes that Doomguard to be selected to enter the Battlefield, the Doomguard will get put into play slightly below where the mouse cursor is instead of the correct position in the Battlefield. Depending on where the position of that Doomguard is, it may become uninteractable with.
http://us.battle.net/hearthstone/en/forum/topic/17347675181
http://www.reddit.com/r/hearthstone/comments/34y734/doomguard_didnt_want_to_fight/
https://www.youtube.com/watch?v=Imm5x8yp3us&t=4m22s

**Comment by Patashu** [comment]
I've seen reports of this in 3.0. Adding 'gameplay' tag as it can cause you to be unable to make a play, like other visual bugs that obscure parts of the board.

**Comment by ZeroRin** [comment]
tested in 3.1, cannot choose doomguard after sending the attacking commend even though it shows green

**Comment by culinko** [comment]
I can confirm it being fixed.
